### ISSUE TITLE
[Feature] 公式引用的单元格被删除应该报 #REF! 错误

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1005]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

1. E1 单元格输入公式 `=SUM(A1+B1)`
2. 删除 A 列
3. univer 内容为 `=SUM(A1+A1)`

### 解决方案

1. D1 位置内容应该变成 `=SUM(#REF!+A1)` ,并且单元格展示 `#REF!`
2. 注意：univer 即使内容为 `=SUM(#REF!+A1)` ，展示也和 excel 不匹配，univer 为 `#ERROR!`

**Comment by DR-Univer** [comment]
需要ggg支持 @Gggpound 

todo:
- [ ] Narrow range on remove row/column 
- [ ] Support split range

**Comment by Gggpound** [comment]
> * split range

split range 应该不需要支持，没有场景啊。
