### ISSUE TITLE
[Feature] add more API to Facade

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#1009]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Missing API on Facade

### Solution

Features

- [x] bold @hexf00 
- [x] italic @hexf00 
- [x] underline @hexf00 
- [x] strike-through @hexf00 
- [x] font family @hexf00 
- [x] font size @hexf00 
- [x] font color @hexf00 
- [ ] border style 
- [x] wrap 
- [x] align 
- [x] number format

Common

- [x] Undo redo @wzhudev (this feature is missing in AppsScript)

Callbacks

- [x] Selection changed @wzhudev 
- [x] Command executed @wzhudev

**Comment by NadaaFarook** [comment]
@wzhudev @hexf00 why is this closed ? the setBorder feature is not added yet.
