### ISSUE TITLE
[Feature] 文档能不能再完善一下

### ISSUE THREAD

**Issue by liyangyangi** [dream-num/univer#1014]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

vue3项目想做一些配置修改，比如监听鼠标事件，找不到api

### Solution

希望能完善一下文档

**Comment by jikkai** [comment]
After we finish the work on the facade layer, we will improve the relevant documentation. Please follow this repo: https://github.com/dream-num/docs
