### ISSUE TITLE
[Bug] 删除隐藏行/列，撤销后隐藏行/列未恢复

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1021]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、删除隐藏行/列
2、然后undo，恢复删除的行/列

### 预期行为

撤销后隐藏行/列恢复

### 实际行为

隐藏状态未保持
[2024_1_5 19_39_27 video.webm](https://github.com/dream-num/univer/assets/154207126/5a2d9296-3554-445e-ae0b-b8ab91f4dbe2)

**Comment by wzhudev** [comment]
![](https://github.com/dream-num/univer/assets/12122021/a3174d85-cc07-4ea8-b4d4-3d27a2d93153)

cc @Gggpound

**Comment by wzhudev** [comment]
Duplicated #1030
