### ISSUE TITLE
[Feature]获取sheet的json数据

### ISSUE THREAD

**Issue by Monster1020** [dream-num/univer#1027]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

想通过方法获取到整张表的json数据

### 解决方案

希望有实例在api文档可以查看

**Comment by Gggpound** [comment]
examples/src/plugins/local-save/services/local-snapshot.service.ts:51 可以看看这段代码。

**Comment by jikkai** [comment]
Duplicate of #1014
