### ISSUE TITLE
[Bug] 删除单元格所在的行列后，无法移动单元格

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1037]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

case1
 1、选中部分单元格如A1
2、右键菜单删除（删除行列都可以）
3、移动A1单元格

### 预期行为

case1可以移动

### 实际行为
case1需要再次选中单元格才可以移动A1单元格

[2024_1_6 16_51_17 video.webm](https://github.com/dream-num/univer/assets/154207126/e9d7fdb2-3fba-43a3-9ed9-7fc3c0d16f3e)

**Comment by DR-Univer** [comment]
![image](https://github.com/dream-num/univer/assets/68851825/d9b7decc-1e91-4d9e-9582-1f70d676fc92)
删除单元格后，重新绑定选区，但是选区没有绑定selectionMoved$事件，需要处理一下。 @Gggpound
