### ISSUE TITLE
ref-range 支持行列拖拽。

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1038]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、选中有数字格式的行列，选中截图A列移动到其他位置
![image](https://github.com/dream-num/univer/assets/154207126/83f60399-3676-48ec-9a7a-7abb308ef99f)

### 预期行为

位置移动后仍保留数字格式
![image](https://github.com/dream-num/univer/assets/154207126/25310e60-1b85-4721-9b78-40bd457cc659)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/812ee9a2-4360-40f2-86be-8da5ece8bfc6)

**Comment by Gggpound** [comment]
不只是数据格式，涉及range引用的 都需要迭代。
