### ISSUE TITLE
[Bug粘贴到合并单元格时，预期显示弹窗禁止粘贴

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1082]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

1、复制没有合并单元格的列粘贴到有合并单元格的列
2、复制有合并单元格的单列粘贴到没有合并单元格的列

### 预期行为

粘贴时提示禁止粘贴

### 实际行为

[2024_1_10 16_01_35 video.webm](https://github.com/dream-num/univer/assets/154207126/4338f8b2-773b-4ae2-84a7-157498de5a8f)

**Comment by yuhongz** [comment]
@Ella1117 maybe we should think about this sutiation
