### ISSUE TITLE
[Bug] univer实例在执行univer.dispose()销毁后重新执行创建，表格不显然

### ISSUE THREAD

**Issue by Is-Your-LGG** [dream-num/univer#1083]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

我使用延时操作模拟了业务场景打开表格与关闭表格的操作，使用如下代码进行模拟
// create univer sheet instance
univer.createUniverSheet(UNISCRIT_WORKBOOK_DATA_DEMO);
setTimeout(() => {
  univer.dispose();
}, 10000);

setTimeout(() => {
  console.log("1111111111");
  univer.createUniverSheet(UNISCRIT_WORKBOOK_DATA_DEMO);
}, 20000);

### 预期行为

当我销毁以后重新打开，应该能够打开新的表格

### 实际行为

销毁后重新打开的时候,容器内是空白的，表格并没有重新打开，将univer置空重新new一个univer实力也是空的

**Comment by wzhudev** [comment]
Duplicate #1077. This issue has been resolved.

**Comment by zifeiyuSun** [comment]
Is this issue really resolved? 
I diposed univer instance, and reinstance ,not show sheet. But if I delay reinstance by 2s, sheet shows. 
Is dipose function a sync function?
