### ISSUE TITLE
[Bug] 插入单元格右移，公式未更新

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1084]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1. A5 输入公式 =SUM(A1:A3)
2. 框选 A1:A3， 插入单元格 右移

### 预期行为

A5 应该更新为 =SUM(B1:B3)

**插入行列，删除行列，也有同样的问题：**
比如选择第二行，插入行或者删除行，A5的公式也需要变化。

### 实际行为

A5 没有更新
[1_10_2024, 4_18_54 PM video.webm](https://github.com/dream-num/univer/assets/26371161/b0162c42-ab34-4ea3-b15c-dcf21001f9a1)

**Comment by Dushusir** [comment]
cc @Gggpound

**Comment by Gggpound** [comment]
> cc @Gggpound 本地已修复。下一个PR后复测下即可。

不是的。。。
<img width="512" alt="image" src="https://github.com/dream-num/univer/assets/141617023/a8e1d006-7095-4103-aa4e-19e1d1d05c3f">
公式这里直接return了，都没走到求range变化的函数。
