### ISSUE TITLE
作为普通开发人员，最需要的在线预览Word和Excel

### ISSUE THREAD

**Issue by mqingqing123** [dream-num/univer#11]
Univer很惊艳，能把Office三大利器制作成在线编辑这个难度极高。
但是，我们目前遇到的最大问题其实是：在线预览Word和Excel

这个需求极大，或者说这个是刚需，至于在线编辑Word和Excel，反而并不那么大。
因为，更多用户还是喜欢用Office软件本地编辑。

所以，希望能最先开发这个功能：在线预览Word和Excel。 
 
（1）比如 https://officeweb365.com?src=Word_Online_URL
（2）微软的 https://view.officeapps.live.com/op/view.aspx?src=URL
（3）葡萄城的开发组件 https://www.grapecity.com.cn/ 等
都是通过云服务收费，提供在线预览。

你这个如果做成这种最好，通过URL传递远程word或者exel， 然后在线预览。
https://dream-num.github.io/doc?url=http://xx.com/test.docx
https://dream-num.github.io/xls?url=http://xx.com/test.xls

**Comment by Dushusir** [comment]
Thanks for the suggestion, please follow our import plugin for updates
感谢建议，请关注我们导入插件的更新

**Comment by isyunketu** [comment]
不同意，市面上能预览的开源产品很多，能编辑的开源产品不多，我们协同办公最需要的就是编辑功能，希望能先开发出基础版本的Excel编辑功能作为第一优先级。

**Comment by kosuke-zhang** [comment]
需要在线预览+1（手机，WEB）
