### ISSUE TITLE
[Bug] 删除子表时，激活的下一个子表可能为隐藏的

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1111]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1. 设置第二个 sheet tab 为隐藏
2. 删除第一个 sheet tab

### 预期行为

激活到第三个 sheet tab

### 实际行为

激活到了第二个隐藏的 tab
[1_11_2024, 9_06_40 PM video.webm](https://github.com/dream-num/univer/assets/26371161/142493c9-c12c-4296-9ea9-cb4854477f29)

**Comment by wzhudev** [comment]
@Dushusir 和其他 sheet tab 的问题一起处理吧，reassign 给你
