### ISSUE TITLE
如何导出excel文件（下载）[Feature] 

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1121]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

查看api没找到导出的方法

### 解决方案

导出excel文件（下载）

**Comment by jikkai** [comment]
Duplicate of #80 #248

Please follow #248 for the latest news
