### ISSUE TITLE
[Bug] 公式结果下拉填充后，计算结果错误

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1127]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、单元格A1=SUM(C:C+D:D)
2、选中A1单元格下拉填充

### 预期行为

下拉填充后单元格中的公式显示结果显示为=SUM(C:C+D:D)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/96dec281-3543-4462-97fc-1ac7d85d5634)
[2024_1_13 15_11_13 video.webm](https://github.com/dream-num/univer/assets/154207126/6d926447-c6e9-4b9a-8c6e-42367e8a805a)

**Comment by Dushusir** [comment]
fixed in other PR, just close
