### ISSUE TITLE
[Bug] 公式等于行/列，删除或插入行/列后公式结果错误

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1128]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

case1、单元格A1=sum(d列+e 列)，删除任意一行
case2、单元格A1=sum(2:2),选中第2行任意单元格插入（列、右移）

### 预期行为

case1、删除行后，单元格A1=sum(d列+e 列)
case2、插入行或移动都，A1=sum(2:2）

### 实际行为
![image](https://github.com/dream-num/univer/assets/154207126/208cb31c-b956-4973-93b9-e9c42febd462)

**Comment by Dushusir** [comment]
_getFormulaReferenceMoveInfo 偏移出错
![image](https://github.com/dream-num/univer/assets/26371161/93f9e6a7-98e0-4b76-aab9-bab03386b072)
