### ISSUE TITLE
[Bug] 使用表格外的按钮，保存数据（）光标被保存下来

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1149]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

使用表格外的按钮保存数据，再点击表格外的更新按钮，用保存下来的数据重新加载表格；因为点击表格外面的按钮，单元格标记状态的光标没有失去焦点，导致重新加载数据时保存旧的光标，重新编辑单元格，会出现多个光标

### 预期行为

点击表格外面，表格单元格自动失去焦点

### 实际行为

点击表格外面，表格单元格没有失去焦点，导致重新加载会出现多个光标

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Vite

**Comment by yyyyffqqqq** [comment]
bug复现视频

https://github.com/dream-num/univer/assets/19225441/4f3c6b31-206e-43c3-a02c-67780f8e7452

**Comment by Jocs** [comment]
@yyyyffqqqq 最新版这个问题还存在吗？

**Comment by yyyyffqqqq** [comment]
> @yyyyffqqqq 最新版这个问题还存在吗？

已经解决好了

**Comment by hibehero** [comment]
@yyyyffqqqq 请问更新表格数据是如何实现的
