### ISSUE TITLE
Basic UI components & services

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#117]
Implements basic components and services to improve code reuse and provide consistent behavior across different plugins and platforms.

> Deadline Oct 14, 2023

## Components

- [x] `Message`
- [x] `Button`
- [x] `Icon`: integrate `@univerjs/icon`
- [x] `Input` @Dushusir 
- [x] `InputNumber` @Dushusir 
- [x] `Container`
- [x] `Layout`
- [x] `Slider`
- [x] `Tooltip`

## Docs

- [x] Design Token / Palette
- [x] Deploying storybook

## Services

Services should be platform-agnostic.

- [x] ThemeService (manages themes and dark mode)
- [x] `IMessageService`

---

> Deadline Oct 27, 2023

## Components

- [x] `Dropdown`
- [x] `CanvasIcon`: rename `CanvasIcon` to `BorderLine`
- [x] `Menu`
  - [x] ~~`Item`~~
  - [x] `NeoCustomLabel`
  - [x] `CustomLabel`: completely deprecate the`CustomLabel` component
  - [x] ~~`Select`~~
- [x] `ColorPicker`
- [x] `ColorPickerCircleButton`

---

> Deadline Nov 4, 2023

## Components

- [x] ~~`Tabs`~~
- [x] `Dialog`: rename `Modal` to `Dialog`
- [x] `Notification` @Dushusir 
- [x] `Confirm`

## Services

- [x] `INotificationService` @Dushusir 
- [x] `IDialogService`
- [x] `IConfirmService`

---

> Deadline Nov 11, 2023

## Components

- [x] ~~`CellRange`~~
- [x] ~~`Collapse`~~
- [x] ~~`Separator`~~
- [x] ~~`ResizeDialog`~~
- [x] ~~`SiderModal`~~
- [x] `Avatar`
- [x] `Checkbox`
  - [x] `CheckboxGroup`
- [x] `Radio`
  - [x] `RadioGroup`
- [x] ~~`Drag`~~
- [x] ~~`Slot`~~
- [x] ~~`Modal`~~

---

> Not in plan

## Components

- [x] ~~`DatePicker`~~ move to #378

**Comment by wzhudev** [comment]
@jikkai Please schedule components development plan

**Comment by ryanwwest** [comment]
I see 'dark mode' mentioned here - but is dark mode itself not actually implemented yet, there's just a manager ready for themes like dark mode?

**Comment by jikkai** [comment]
> I see 'dark mode' mentioned here - but is dark mode itself not actually implemented yet, there's just a manager ready for themes like dark mode?

Due to limited manpower, we have not yet scheduled the implementation of dark mode.

**Comment by lingchuL** [comment]
> > I see 'dark mode' mentioned here - but is dark mode itself not actually implemented yet, there's just a manager ready for themes like dark mode?
> 
> Due to limited manpower, we have not yet scheduled the implementation of dark mode.

very needed feature, may it come sooner~ Or are there any trick ways to implement dark mode for now?
