### ISSUE TITLE
[Feature] 提供鼠标拖拽到sheet内部的结束事件

### ISSUE THREAD

**Issue by Thingfxj** [dream-num/univer#1176]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

需要退拽元素内容到sheet中指定的单元格

### 解决方案

提供类似luckysheet的cellDragStop方法
![Uploading 928019ad464e8498112bfa0d3713284.png…]()

**Comment by HaiYangHuX** [comment]
请问这个功能近期会上吗

**Comment by Dushusir** [comment]
关注下一个版本的Facade更新，通过onCellPointerMove拿到单元格信息之后就可以进行自定义操作

```ts
univerAPI.getSheetHooks().onCellPointerMove((cell) => {
  // 拿到当前鼠标指向的单元格
  console.log(cell);
})
```
