### ISSUE TITLE
[Bug] some skeleton lines are not cleared if set scale

### ISSUE THREAD

**Issue by weird94** [dream-num/univer#1178]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.0

### Steps to reproduce

![WeChatWorkScreenshot_86819216-c1ce-45ed-862e-73d3381a7cd1](https://github.com/dream-num/univer/assets/16274199/8184b567-3234-428a-b103-9db6059cc8b8)

### Expected behavior

-

### Actual behavior

-

**Comment by DR-Univer** [comment]
@weird94 这是在非缓存的场景下？

**Comment by weird94** [comment]
can't reproduce
