### ISSUE TITLE
[Bug] 公式支持 =">"&A1:A3

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1186]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1. 任意单元格输入 `=">"&A1:A3`

### 预期行为

![image](https://github.com/dream-num/univer/assets/26371161/54b30bc3-51b6-4bbe-bb0d-781caaf07ef1)

### 实际行为

![image](https://github.com/dream-num/univer/assets/26371161/d40cb9a5-db10-41a4-a248-882bda9fcf8d)

**Comment by DR-Univer** [comment]
& CONCATENATE  还没实现，等我周末弄个
