### ISSUE TITLE
[Bug] 表格卡死后白屏（偶现）

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1220]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

无必现路径；有必现路径后补充

### 预期行为

表格正常使用

### 实际行为

[2024_1_22 20_06_38 video.webm](https://github.com/dream-num/univer/assets/154207126/21d8c788-3d26-41ca-a595-3ae63cdafdde)

**Comment by DR-Univer** [comment]
https://staging.univer.plus/?type=2&unit=1750847004398087003&subunit=uni2 
导入遇到了一个白屏case，以下是单元格数据
`{"6": {"4": {"p": {"body": {"textRuns": [{"ed": 5, "st": 0, "ts": {"cl": {"th": 0, "rgb": "#000000"}, "ff": "等线", "fs": 12}}, {"ed": 6, "st": 6, "ts": {"cl": {"th": 0, "rgb": "#000000"}, "ff": "等线", "fs": 12}}, {"ed": 7, "st": 7, "ts": {"cl": {"th": 0, "rgb": "#000000"}, "ff": "等线", "fs": 12}}, {"ed": 8, "st": 8, "ts": {"cl": {"th": 0, "rgb": "#000000"}, "ff": "等线", "fs": 12}}, {"ed": 14, "st": 9, "ts": {"cl": {"th": 0, "rgb": "#000000"}, "ff": "等线", "fs": 12}}], "dataStream": "我在马路边\r\r\r\r捡到一块钱\r\n", "paragraphs": [{"startIndex": 5}, {"startIndex": 6}, {"startIndex": 7}, {"startIndex": 8}, {"startIndex": 14}], "sectionBreaks": [{"startIndex": 15}]}, "lists": {}, "footers": {}, "headers": {}, "drawings": {}, "settings": {}, "documentStyle": {}}, "s": "HSC_-P", "t": 1}}}`
