### ISSUE TITLE
[Bug] 隐藏行列在切换子表时icon没有消失

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#1221]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

![image](https://github.com/dream-num/univer/assets/68851825/a98f6417-6254-49e8-b785-ebb93d808ff1)
隐藏行列或者列，然后切换子表

### 预期行为

隐藏行列的icon需要与当前子表的行为一致

### 实际行为

切换子表后，隐藏行列的icon没有消失

### 运行环境

Chrome

### 操作系统

Windows

### 构建工具

Webpack

**Comment by zhaolixin7** [comment]
#1185 这2个issue应该时一个问题
