### ISSUE TITLE
调整行高 粗线不隐藏 越调越多[Bug] 

### ISSUE THREAD

**Issue by mayiyahei1992** [dream-num/univer#1233]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

![image](https://github.com/dream-num/univer/assets/48984649/c1fcd680-567d-4752-b89a-136dc64e95d5)

### 预期行为

调整行高 粗线消失

### 实际行为

粗线没有消失 每调整一次就多一条粗线 

### 运行环境

Chrome

### 操作系统

Windows

### 构建工具

Vite

**Comment by jikkai** [comment]
Likely resolved in this PR: #1165. We plan to release this updated version on this Friday.
Close this issue for now, feel free to reopen again if the new version reproduces the problem.
