### ISSUE TITLE
[Bug] 编辑单元格时修改行高或列宽，编辑框大小不对

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1240]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、A编辑单元格，B修改行高列框

### 预期行为

单元格大小随修改宽高改变

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/b9891c68-c0fc-44f3-ad2e-05b85f99cad1)

**Comment by Jocs** [comment]
@zhaolixin7 这是协同过来导致的吗？

**Comment by jikkai** [comment]
It appears to be a collaborative resizing. If that's the case, the editor should indeed maintain its original size and not participate in the collaboration.
