### ISSUE TITLE
[Bug] 打印- 缩放选择适合，修改对齐方式表格内容错位

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1279]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

场景一1、缩放选择适合（除正常以外的选项），对齐方式选择右对齐

场景二1、缩放选择适合（除正常以外的选项），对齐方式左、中、右加底部对齐
### 预期行为

表格右对齐方式显示

### 实际行为

https://github.com/dream-num/univer/assets/154207126/ced8876a-4a59-45ee-9e10-3afc828fd21a
![image](https://github.com/dream-num/univer/assets/154207126/1b46684a-52bb-44d6-9a3e-42492141a254)

**Comment by weird94** [comment]
fixed
