### ISSUE TITLE
[Bug] 打印-打印预览时边框线显示不全

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1281]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤
window

![image](https://github.com/dream-num/univer/assets/154207126/df16fc55-eae9-4336-bc64-14b1943fd397)
1、设置如截图，电脑缩放比例为125%，表格id:unit=1749416146125266361&type=2&subunit=MMt5bSEhbQ4A7OGR50XW8

![image](https://github.com/dream-num/univer/assets/154207126/ff274f19-5396-4fb2-8cee-cee5a1b2af93)
![image](https://github.com/dream-num/univer/assets/154207126/61951f41-8eb6-486f-b243-8ceaafa821fa)
2、设置如上2个截图，电脑比例为100%，表格是1月31日志

### 预期行为

边框线正常显示

### 实际行为
边框线显示不全
![image](https://github.com/dream-num/univer/assets/154207126/2821887d-be6a-4cc3-bcb6-746ec80969f4)

**Comment by weird94** [comment]
can't reproduce now.
