### ISSUE TITLE
[Bug] 打印-刷新后直接打印，打印预览时表格不显示内容

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1286]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

unit=1749416146125266361&type=2&subunit=stcyrbJD1malDrIokwv4m
1、刷新后直接点击打印，打印范围默认当前工作表

### 预期行为

当前工作表可以正常显示内容

### 实际行为

子表内容![image](https://github.com/dream-num/univer/assets/154207126/c99ecd7e-4ee2-4b3c-86f0-7f90e4d31927)
打印是显示的内容![image](https://github.com/dream-num/univer/assets/154207126/4699e1e7-dc93-4a9a-b88d-974c63aa6354)

**Comment by weird94** [comment]
fixed
