### ISSUE TITLE
[Bug] 使用cdn的方式引入facde,在使用window.UniverFacade.FUniver.newAPI(univer)的时候报错，导致无法使用

### ISSUE THREAD

**Issue by Is-Your-LGG** [dream-num/univer#1298]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

使用cdn的方式引入facade
    <script src="https://unpkg.com/@univerjs/facade/lib/umd/index.js"></script>
在执行  const univerAPI = window.UniverFacade.FUniver.newAPI(univer)的时候报错

### 预期行为

能过获取到这个univerAPI，然后执行后续的赋值等操作

### 实际行为

<img width="674" alt="截屏2024-01-30 13 34 29" src="https://github.com/dream-num/univer/assets/78673160/b7dc9dff-7226-48bb-bc9e-47fecf493526">

**Comment by feige-2011** [comment]
我碰到同样的问题，不知道这位老师是怎么解决的
