### ISSUE TITLE
[Feature] 如何更改主题？

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1299]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

const univerTmp: any = new window.UniverCore.Univer({
      theme: window.UniverDesign.defaultTheme,
      locale: window.UniverCore.LocaleType.ZH_CN,
      logLevel: window.UniverCore.LogLevel.VERBOSE,
    });

查看api文档，没有找到其他内置的主题名称，api文档很多都查不到，只有一个空名称

### Solution

修改这个主题为黑色主题 theme: window.UniverDesign.defaultTheme

**Comment by jikkai** [comment]
We've refreshed the [documentation](https://univer.ai/guides/extend/theme/) on custom themes, aiming to provide more assistance.
