### ISSUE TITLE
什么时候有最新的发行版

### ISSUE THREAD

**Issue by shuaibibaba** [dream-num/univer#13]
用了lucksheet2.0感觉功能很好，就是没有导出，用了别人的导出的方法都不太好。在这里蹲一个最新的包

**Comment by Dushusir** [comment]
Thanks for your support, please pay attention to the development progress of our import and export plug-in.
感谢支持，请关注我们导入导出插件的开发进度。

**Comment by HengCC** [comment]
2.0的协同功能太弱了. 没有合并模型. 在实际应用过程中基本避免不了数据覆盖的问题. 还会各种错乱. 我现在虽然用了. 但是也基本不敢大规模推广.  在调研其他的替代物... 不过话说回来. 导出还是很好做的.  你读下api的数据格式. 自己用poi就能导出了. 另外看现在3.0好像是有规划基于crdt模型做协同.还是比较期待的

**Comment by icoco** [comment]
small question,  if possible use some data source plugin that can pull data from database ?

**Comment by Dushusir** [comment]
> small question, if possible use some data source plugin that can pull data from database ?

Yes. Just like importing plug-ins, before obtaining data that conforms to the Univer parameter format, there are many ways to organize the data, such as writing a data source plug-in yourself.
