### ISSUE TITLE
[Bug]  通过 setValue 设置单元格的值，页面不会更新

### ISSUE THREAD

**Issue by ZenoHu** [dream-num/univer#1307]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

sheet.getActiveSheet().getCellMatrix().setValue(0,0,{v:11})

### 预期行为

单元格显示 11

### 实际行为

单元格显示空白，双击编辑时才显示值，鼠标离开了又显示为空白

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Vite

**Comment by ZenoHu** [comment]
其他 API 也有类似问题，比如使用 addWorksheet API 添加一个 sheet,页面不会更新，再手动点击底部添加 sheet,会把之前通过 API 添加的 sheet  展示出来。调用了 flush API 也是一样的效果

**Comment by hexf00** [comment]
- [getCellMatrix](https://univer.work/api/core/classes/Worksheet.html#getCellMatrix) 是model层的api，不应该直接在你说的常见使用，你可以改为使用 facade API [FRange.setValues](https://univer.work/api/facade/classes/FRange.html#setValues)
- 创建sheet也可以改为使用facade API [FWorkbook.create](https://univer.work/api/facade/classes/FWorkbook.html#create)
