### ISSUE TITLE
[Feature] 如何设置表格只读（禁用编辑）？

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1312]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

想根据用户权限设置表格是否可编辑，找不到相关配置和api进行配置

### 解决方案

设置表格不可编辑

**Comment by Dushusir** [comment]
关注我们的路线图：https://univer.ai/guides/roadmap/
保护区域（子表和范围权限控制）

**Comment by linfaithjuntong** [comment]
请问解决了吗，我也遇到这个问题了

**Comment by wzhudev** [comment]
@Gggpound Can we provide a temp solution at the current moment?

**Comment by semmywong** [comment]
这个特性实现了吗，或者有临时办法处理吗？

**Comment by semmywong** [comment]
Has this feature been implemented, or is there a workaround?

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/features/permission
