### ISSUE TITLE
[Bug] 表格单元格输入值，光标没有失去焦点，点击外部的按钮导出表格数据，导出的数据没有当前输入的值

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1314]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

https://github.com/dream-num/univer/assets/19225441/935e883e-f7e4-4fdf-949e-43d106c8a5bf

### 预期行为

点击导出数据按钮能够取得光标所在的输入的数据

### 实际行为

点击导出按钮，不能够取得光标所在的输入的数据，要失去焦点过后导出才会有这个数据

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Vite

**Comment by Dushusir** [comment]
@Jocs  考虑如果用户点击到表格外部，是否需要失焦

**Comment by iamyunsin** [comment]
@Dushusir 我觉得点击外部按钮或其它区域时主动触发失焦，因为那样可能会导致我们在通过外部按钮做某些需要获取当前选区的功能时遇到困难。 
我觉得这个场景，应该在用户点击“导出表格数据”按钮时，由开发人员编码调用Univer提供的API来失焦或存储当前用户正在输入的值，然后再执行导出的代码。

**Comment by jikkai** [comment]
> @Dushusir 我觉得点击外部按钮或其它区域时不应该主动触发失焦，因为那样可能会导致我们在通过外部按钮做某些需要获取当前选区的功能时遇到困难。
> 我觉得这个场景，应该在用户点击“导出表格数据”按钮时，由开发人员编码调用Univer提供的API来失焦或存储当前用户正在输入的值，然后再执行导出的代码。

The **defocusing** here doesn't mean that the cell itself becomes unfocused, but rather that it exits the editing mode. However, the user can still obtain the cell that is currently in focus.

**Comment by iamyunsin** [comment]
> > @Dushusir 我觉得点击外部按钮或其它区域时不应该主动触发失焦，因为那样可能会导致我们在通过外部按钮做某些需要获取当前选区的功能时遇到困难。
> > 我觉得这个场景，应该在用户点击“导出表格数据”按钮时，由开发人员编码调用Univer提供的API来失焦或存储当前用户正在输入的值，然后再执行导出的代码。
> 
> The **defocusing** here doesn't mean that the cell itself becomes unfocused, but rather that it exits the editing mode. However, the user can still obtain the cell that is currently in focus.

Got it, thank you

**Comment by iamyunsin** [comment]
> > @Dushusir 我觉得点击外部按钮或其它区域时不应该主动触发失焦，因为那样可能会导致我们在通过外部按钮做某些需要获取当前选区的功能时遇到困难。
> > 我觉得这个场景，应该在用户点击“导出表格数据”按钮时，由开发人员编码调用Univer提供的API来失焦或存储当前用户正在输入的值，然后再执行导出的代码。
> 
> The **defocusing** here doesn't mean that the cell itself becomes unfocused, but rather that it exits the editing mode. However, the user can still obtain the cell that is currently in focus.

但是，如果用户想通过选中单元格中一部分类容，来实现类似下图中，对单元格中部分内容做操作，那么一旦点击外部按钮就主动失焦，这个单元格内被选中的文本是否还能获取到选中状态呢？
<img width="606" alt="image" src="https://github.com/dream-num/univer/assets/121468590/112fe9db-e236-413f-b221-59be1f388f82">

**Comment by linfaithjuntong** [comment]
请教一下，导出功能怎么做，文档里面没有这个导出功能介绍

**Comment by jikkai** [comment]
In order to deal with more complex scenarios, we don't intend to implement this feature internally.

Fortunately, your can implement this feature via the Facade API.

```typescript
import { DeviceInputEventType } from '@univerjs/engine-render';
import { FUniver } from '@univerjs/facade';

const univerAPI = FUniver.newAPI(univer);

$btn.addEventListener('click', () => {
    univerAPI.executeCommand('sheet.operation.set-cell-edit-visible', {
        visible: false,
        _eventType: DeviceInputEventType.PointerUp,
    });
});
```

**Comment by 2234839** [comment]
@jikkai  有让他恢复焦点的办法吗

**Comment by Xue-Eric** [comment]
其他单元格通过这个单元格计算的，失去焦点能获取到这个单元格的值，但是获取到的值公式单元格计算后的值还是之前的值，能看到UI重新计算了，但是获取到的值还是失焦之前的
