### ISSUE TITLE
[Bug] Workbook.getSnapshot() doesn't reflect changes in Worksheet

### ISSUE THREAD

**Issue by Sahil333** [dream-num/univer#1332]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Steps to reproduce

1. Use pnpm dev:demo
2. Change one of the sheet name
3. Use debugger.operation.saveSnapshot operation to create the snapshot.
4. Check the name of the sheet you changed in the snapshot.

### Expected behavior

Snapshot data should reflect the latest state in the UI.

### Actual behavior

Snapshot data retains the name of the sheet given at the initialization of the sheet.
What I could understand after running debug is that sheet mutations changes the data in the _worksheets._snapshot which is not reflected in the _workbook._snapshot as both are using different instances of the IWorksheetData (upto one level deep). Refering to this line of code [worksheet.ts](https://github.com/dream-num/univer/blob/492f0e14c0e34d81b85d1bc20db1eece90241006/packages/core/src/sheets/worksheet.ts#L48)

https://medium.com/@kevinlai76/the-spread-operator-deep-and-shallow-copies-d193ac9b58bf

Is there a sync operation I am missing that needs to happen between the Workbook and Worksheet snapshots?

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Vite

**Comment by wzhudev** [comment]
Thanks for reporting this. We will fix it soon!
