### ISSUE TITLE
[Bug] 每次初始化表格渲染时，会调用四次Sum函数，每次选择单元格会执行两次Sum函数

### ISSUE THREAD

**Issue by iamyunsin** [dream-num/univer#1333]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1. 修改`examples/src/sheets/main.ts`文件，初始化空白sheet，变更代码如下：  
```ts
// univer.createUniverSheet(DEFAULT_WORKBOOK_DATA_DEMO);
univer.createUniverSheet({});
```
2. 运行`pnpm dev:demo`命令启动开发服务
3. 打开浏览器，访问`http://localhost:3002`，并在`packages/engine-formula/src/functions/math/sum/index.ts`文件中的第24行打上断点
4. 刷新当前页面，发现执行了四次sum函数
5. 当单击单元格切换选区或新增工作表，或修改任意单元格的样式（不是值），都会触发执行两次Sum函数

* 额外说明：
我通过查看调用堆栈，发现是在`packages/sheets-ui/src/controllers/status-bar.controller.ts`文件的第145行触发的。

### 预期行为

1. 初始化时候只执行`1`次Sum函数
2. 切换worksheet时执行`1`次Sum函数
3. 仅仅改变选区和单元格样式时，`不执行`Sum函数
4. 修改单元格值时候执行`1`次Sum函数`

### 实际行为

1. 初始化时执行了`4`次Sum函数
2. 切换worksheet时执行了`2`次Sum函数
3. 修改选区和修改单元格样式的时候，执行了`2`次Sum函数
4. 修改单元格值时，执行了`2`次Sum函数

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

esbuild, Vite

**Comment by yuhongz** [comment]
发现不必要的计算，已在这个 PR #1353 优化掉了。
修改样式会导致重新计算是在预期中的行为，因为修改样式和修改值都是使用 SetRangeValueMutation，要区分开来需要用更细粒度的比较，也会带来性能负担

**Comment by iamyunsin** [comment]
> 发现不必要的计算，已在这个 PR #1353 优化掉了。 修改样式会导致重新计算是在预期中的行为，因为修改样式和修改值都是使用 SetRangeValueMutation，要区分开来需要用更细粒度的比较，也会带来性能负担

但是status bar是公共能力，如果表格数据特别多的情况下，应该会产生CPU资源浪费和性能问题（即使计算都放到Web Worker中，也可能产生性能问题，看看是否需要构造一个大数据量的表格来做性能测试吧）。
