### ISSUE TITLE
[Feature] 单元格附加数据字段

### ISSUE THREAD

**Issue by fmwww** [dream-num/univer#1334]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

单元格没有地方可以存储一些和单元格关联的数据，虽然可以通过在外部实现一个二维数组存放相关数据，但是当表格的形态发生变化时，如新增行列，移动单元格之后，需要对很多事件进行监听和处理，因此希望单元格内部可以提供一个存储额外数据的字段

### 解决方案

希望可以提供一个字段用于存储单元格的额外数据，例如meta字段

**Comment by guowb1997** [comment]
是关于表格下拉选项的问题吗?表格怎么设置下拉选项呀

**Comment by fmwww** [comment]
> 是关于表格下拉选项的问题吗?表格怎么设置下拉选项呀

不是，下拉选项是条件格式，官方说一季度会推出，这个是单元格存储自定义数据，比如可以给单元格设置id等等

**Comment by ChuanfengZhang** [comment]
need it too.

**Comment by Superman-wc** [comment]
现在的单元格就只有value与style两个属性， 楼主是想要附加自定义的属性上去， 并且这些属性一样支持下拉填充、复制粘贴等操作，只是可能不直接做为value显示在单元格上， 可以在选中单元格的时候，显示属性时才显示出来！

不知道楼主我这样理解是否符合你想要的

**Comment by Superman-wc** [comment]
luckysheet的时候，cell 对象可以添加自定义属性的，而且可以被复制到其他单元格， 不知道这边行不行得通，

**Comment by fmwww** [comment]
> luckysheet的时候，cell 对象可以添加自定义属性的，而且可以被复制到其他单元格， 不知道这边行不行得通，

目前不行，不过官方说未来会添加这个功能

**Comment by JackieCheung** [comment]
目前有其他方法吗

**Comment by chenkeguo1** [comment]
就像spreadjs 的tag属性，点击了单元格也不会显示，导入excel会丢失。我主要用它把数据记录的id值、代码值（v属性显示的是代码内容）放入到这个属性中，在crud时很方便
