### ISSUE TITLE
[Feature] custom setting for context menu

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1343]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![image](https://github.com/dream-num/univer/assets/26371161/46b1dd43-6b9b-483f-b521-a14d560cf828)

### Solution

1. Selective initialization of menu service and shortcut keys
2. Facade API to hide some menu item, disable function

**Comment by young-tree** [comment]
只能进行禁用和隐藏某个菜单吗？我想增加一个菜单项怎么办？还是得改源码吗？如果可以通过配置就能增加菜单项，我就继续查看文档
Selective initialization of menu service and shortcut keys，翻译后依然有点云里雾里
