### ISSUE TITLE
[Bug] 使用http协议发布网页，window.navigator.clipboard.readText == "function" 会报错

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1368]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

UMD版本

### 复现链接

UMD方式引入包，正常初始化，就会报错，导致无法输入表格内容

### 预期行为

能够兼容http协议的网页

### 实际行为

http发布的网页无法正常输入表格内容
<img width="1434" alt="截屏2024-02-06 14 11 43" src="https://github.com/dream-num/univer/assets/19225441/fca9f404-59f8-4852-878e-9383270cf207">
<img width="809" alt="截屏2024-02-19 09 26 59" src="https://github.com/dream-num/univer/assets/19225441/ccde0a4f-e881-456d-b300-f9e507f80900">

### 运行环境

Chrome

**Comment by jikkai** [comment]
We have already fixed the issue at #1345, please wait for the next release.
