### ISSUE TITLE
[Bug] 数组公式范围赋值粘贴仅对左上角生效

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#1379]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、通过填充功能建立一个范围数据
2、使用=A1:B10，展开一个数组公式
3、对数组公式使用赋值
4、在空白单元格进行粘贴

### 预期行为

粘贴数据公式所有的数据到空白单元格

### 实际行为

仅粘贴了数据公式范围中的左上单元格数据

### 运行环境

Chrome

**Comment by Dushusir** [comment]
目前与 excel 表现一致
