### ISSUE TITLE
[Bug]公式引用值是字符串计算结果错误

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1390]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、公式=day("7/20/1969")
2、公式=sum("1")  、=ACOS("1")

### 预期行为

1、Excel、google会报#value
2、Excel可以计算出结果
![image](https://github.com/dream-num/univer/assets/154207126/ebaa8e8e-836f-48f5-a494-faa39bdd7348)

### 实际行为

1、结果显示为空
2、报#value
![image](https://github.com/dream-num/univer/assets/154207126/64951b82-defb-478f-8c20-335c5505a3a1)
![image](https://github.com/dream-num/univer/assets/154207126/69631251-bf60-4075-9606-5b632e301ad3)

**Comment by Dushusir** [comment]
类似 =SUM("1") =ACOS("1")，应该是所有的计算类型的函数都需要默认转化字符串数字和布尔值，比如 =SUM("1",TRUE) 为 2。
但是引用中的字符串数字和布尔值一般不转化，比如=SUM(A2,B2) 其中A2为强制字符串1,B2为TRUE，结果为 0。

如下Excel
![image](https://github.com/dream-num/univer/assets/26371161/4ce4214c-5fa2-4573-8eb1-60ee1aead939)

目前已实现的函数中，数学与三角函数、统计这两个分类中的函数有此特性。
