### ISSUE TITLE
[Feature] acot公式计算逻辑

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1393]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

1、单元格公式acot(-2)
![image](https://github.com/dream-num/univer/assets/154207126/790ed94e-9196-4e4b-90a2-4441051df01a)

### 解决方案

对齐google还是Excel?

**Comment by Dushusir** [comment]
对齐Excel
