### ISSUE TITLE
下拉填充或者拖动选中区域之后选中框线不消失

### ISSUE THREAD

**Issue by guowb1997** [dream-num/univer#1410]
### 在您提交此问题之前，您是否检查了以下内容？

- [x] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

![1708586386696](https://github.com/dream-num/univer/assets/118286188/556df9e0-583c-4ffc-a8f9-f73f6663cbc2)

### 预期行为

拖动选中区域之后内容跟随移动但再点击其他单元格应该取消选中

### 实际行为

下拉填充或者拖动选中区域之后选中框线不消失

**Comment by yuhongz** [comment]
复现描述有些模糊，这个问题仍存在吗？如还有，可提供录屏：顶部->其他->snapshot->record  @guowb1997

**Comment by yuhongz** [comment]
现网表现为：多选区时，执行下拉填充后会取消其他的多余选区。因此本 issue 视为已解决。
