### ISSUE TITLE
[Feature]公式中输入中文符号时转为英文符号计算

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1414]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

1、输入法为中文时输入公式，如=sum（1+1）括号是中文的

### 解决方案

可以转为英文符号计算
目前表现报#name

**Comment by Dushusir** [comment]
全角符号会统一转成半角符号
