### ISSUE TITLE
[Bug]公式只输入符号无参数时预期报错，控制台有报错

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1415]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

###复现链接

case1、单元中直接输入=（）
case2、单元格中输入=-或(<>等)，然后选择单元格A1（A1单元格有内容如：数字2）

### 预期行为

case1、对齐google报错？
case2、可以计算出结果，等于-2

### 实际行为

1、显示为空且控制台有报错
2、单元格显示=A1-
![image](https://github.com/dream-num/univer/assets/154207126/ee2ea568-b5aa-4bfa-a637-21c415793558)
[2024_2_22 16_55_17 commands.json](https://github.com/dream-num/univer/files/14371383/2024_2_22.16_55_17.commands.json)
[2024_2_22 16_55_17 video.webm](https://github.com/dream-num/univer/assets/154207126/3656cc6b-ca7a-4e0d-a9c8-feec0e2a2411)

**Comment by Dushusir** [comment]
公式输入：=INDEX((A6:B6,C6:D7),1,1,2)，解析错误，一组范围用()包围起来

Excel 也支持 =SUM((A6:B6,C6:D7),1,1,2)

**Comment by zhaolixin7** [comment]
@DR-Univer 1、公式括号和计算符号组合计算错误
![image](https://github.com/dream-num/univer/assets/154207126/18a574e6-e8d6-42cc-bc99-df47cfe49c13)
2、评论这个也未修复
![image](https://github.com/dream-num/univer/assets/154207126/e39f0a8a-900f-473a-807d-0871499efeb2)
