### ISSUE TITLE
[Feature] Get the row and column of the cells directly under the mouse based on the coordinates on the screen where the current mouse is located

### ISSUE THREAD

**Issue by iamyunsin** [dream-num/univer#1425]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I hope to be able to set the corresponding selection based on the currently obtained rows and columns directly below the mouse, plus my own calculations. It may be multiple rows and columns, following the movement of the mouse.

### Solution

step 1: Get the row and column of the cells directly under the mouse based on the coordinates on the screen where the current mouse is located.
step2: Calculate the selection range based on the cell row and column information obtained in the first step, and set the selection range to be displayed in the sheet.

**Comment by Dushusir** [comment]
Pay attention to the next version of Facade update. After getting the cell information through onCellPointerMove, you can perform customized operations.

```ts
univerAPI.getSheetHooks().onCellPointerMove((cell) => {
  // Get the cell currently pointed by the mouse
  console.log(cell);
})
```
