### ISSUE TITLE
[Bug]文档编辑显示保存中

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1427]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、文档显示保存https://staging.univer.plus/doc/?unit=1762480784173420570&type=1

### 预期行为

可以正常编辑

### 实际行为

显示保存中
![image](https://github.com/dream-num/univer/assets/154207126/dcf1313a-6b83-4ae1-996b-077afb2f1d0f)
traceId:f91009900fa41f31e61c3968f904de8f
routeKey "1762480784173420570"

**Comment by Jocs** [comment]
先 pending，需要可以稳定复现的步骤

**Comment by Jocs** [comment]
因为没法复现，最近也没有在遇到，先暂时关闭
