### ISSUE TITLE
[Bug] docker-compose部署后无法编辑

### ISSUE THREAD

**Issue by kurosakisora** [dream-num/univer#1430]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

univer-demo-client@0.1.0-beta.3

### 复现链接

https://univer.ai/enterprises/trial-version/
使用的是docker-compose（社区完整版）部署方式，部署过程中，没有任何报错，日志正常

### 预期行为

能正常编辑

### 实际行为

点击无法编辑，点击无反应，但是可以创建sheet，换任何浏览器都不行，无痕也不行

### 运行环境

Chrome, Safari, Firefox

### 系统信息

Linux version 5.15.0-46-generic (buildd@lcy02-amd64-007) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022

**Comment by kurosakisora** [comment]
![image](https://github.com/dream-num/univer/assets/13403496/1a809630-b185-4329-813f-9e4a3001725e)

**Comment by kurosakisora** [comment]
![image](https://github.com/dream-num/univer/assets/13403496/6232bb58-b247-4059-a9e9-9e3f30533f89)

**Comment by jikkai** [comment]
The issue has been fixed in the latest version.
If you still encounter this problem, please feel free to reopen this issue at any time.

**Comment by kokojacket** [comment]
请问如何使用docker部署，似乎没有看到相关文档

**Comment by kokojacket** [comment]
@kurosakisora
