### ISSUE TITLE
[Feature] 前端表格编辑的时候可以对当前单元格内容进行格式校验

### ISSUE THREAD

**Issue by linfaithjuntong** [dream-num/univer#1466]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

前端表格编辑的时候可以对当前单元格内容进行格式校验，目前文档里面没找到对应的api

### Solution

希望前端表格编辑的时候可以对当前单元格内容进行格式校验

**Comment by jikkai** [comment]
The conditional formatting feature is under development.
https://github.com/dream-num/univer/pull/1323

**Comment by weird94** [comment]
Data validation is supported. https://univer.ai/api/sheets-data-validation/
