### ISSUE TITLE
[Bug] 底部sheet无法更改颜色

### ISSUE THREAD

**Issue by river666** [dream-num/univer#1470]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

  "dependencies": {     "@univerjs/core": "^0.1.1",     "@univerjs/design": "^0.1.1",     "@univerjs/docs": "^0.1.1",     "@univerjs/docs-ui": "^0.1.1",     "@univerjs/engine-formula": "^0.1.1",     "@univerjs/engine-render": "^0.1.1",     "@univerjs/sheets": "^0.1.1",     "@univerjs/sheets-formula": "^0.1.1",     "@univerjs/sheets-ui": "^0.1.1",     "@univerjs/ui": "^0.1.1",     "element-plus": "^2.6.0",     "pinia": "^2.1.7",     "sas": "^3.0.4",     "vue": "^3.4.15",     "vue-router": "^4.2.5"   },

### Reproduction link

![image](https://github.com/dream-num/univer/assets/35917804/0fc37ddf-e1fa-4e99-bf73-86d8a9a8b836)

### Expected behavior

能改颜色

### Actual behavior

鼠标移动到改颜色区域时，颜色面板自动消失

### System information

mac

**Comment by jikkai** [comment]
This is a known issue that has been fixed in #1440, we will release it in `0.1.2`.
