### ISSUE TITLE
[Bug] VLOOKUP公式计算不出结果

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1472]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格=VLOOKUP("john",A1:E4,1,0)
![image](https://github.com/dream-num/univer/assets/154207126/4550c632-0fd1-448d-b256-2e2034ee1416)

### 预期行为

计算出结果
![image](https://github.com/dream-num/univer/assets/154207126/166219be-1e8f-4dd2-9475-1d967727a21f)

### 实际行为

计算不出结果报#n/a
![image](https://github.com/dream-num/univer/assets/154207126/79d485c2-2a79-484f-8d10-fe4358f93112)

**Comment by DR-Univer** [comment]
底层全等匹配需要加一个配置，是否大小写敏感。
<img width="844" alt="企业微信截图_17098861288444" src="https://github.com/dream-num/univer/assets/68851825/78fd4018-e6aa-4db5-bac2-25f6e97b4d70">  除了上面这些，其他匹配函数都是大小写不敏感得
