### ISSUE TITLE
[Bug] 按照文档中的使用 UMD方式使用，报错，显示不了表格，之前版本是正常的

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1474]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

UMD版本

### 复现链接

<img width="1175" alt="截屏2024-03-05 10 16 38" src="https://github.com/dream-num/univer/assets/19225441/b3cce70f-5624-4344-b005-14eb04d6a892">

### 预期行为

无报错，能正常显示表格

### 实际行为

报错，没法显示表格

### 运行环境

Chrome

**Comment by jikkai** [comment]
The list of plugins required to minimize the demo has changed a bit, you can make some adjustments by referring to the example below, or refer to our [online demo](https://univer.ai/playground/?title=UMD) to troubleshoot the issue.

Example:

```diff
<script crossorigin="anonymous" src="https://unpkg.com/@univerjs/docs/lib/umd/index.js"></script>
+ <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/docs-ui/lib/umd/index.js"></script>
<script crossorigin="anonymous" src="https://unpkg.com/@univerjs/sheets-ui/lib/umd/index.js"></script>

<script>
univer.registerPlugin(window.UniverDocs.UniverDocsPlugin, {
  hasScroll: false,
});
+ univer.registerPlugin(window.UniverDocsUi.UniverDocsUIPlugin);
</script>
```
