### ISSUE TITLE
[Bug] 使用UMD在线demo，输入表格数据，失焦后输入的数据消失

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1479]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

UMD版本

### 复现链接

https://github.com/dream-num/univer/assets/19225441/d2dbd785-2ed2-496e-b244-cacc06b83070

<img width="1440" alt="截屏2024-03-05 15 07 34" src="https://github.com/dream-num/univer/assets/19225441/09aa5afc-ecf8-47a4-8f0b-2c6bb6b0686c">

### 预期行为

失焦后数据能正常显示

### 实际行为

失焦后数据不能正常显示

### 运行环境

Chrome

**Comment by jikkai** [comment]
Thank you for bringing this issue to our attention.

Upon reviewing the details, we realized that our demo was indeed lacking a necessary dependency. We have now addressed this oversight.

To resolve the issue, we have added the missing dependency package `@univerjs/engine-numfmt`. You can incorporate this change into your setup by including the following line in your HTML file, as shown in the diff below:

```diff
    <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/core/lib/umd/index.js"></script>
    <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/design/lib/umd/index.js"></script>
    <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/engine-render/lib/umd/index.js"></script>
+    <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/engine-numfmt/lib/umd/index.js"></script>
    <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/engine-formula/lib/umd/index.js"></script>
```
