### ISSUE TITLE
[Bug] 复制链接粘贴到文档中未显示url

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1494]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

前提：edge浏览器
1、复制浏览器搜索栏中的链接粘贴到文档中（文档链接或新闻链接）

### 预期行为

![image](https://github.com/dream-num/univer/assets/154207126/d6f91b93-884e-402f-98d4-98c5afec8f0c)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/1850e727-bbe0-4515-a2f5-2223f3124843)

**Comment by Jocs** [comment]
目前复制到 word 也是这样的，应该是预期行为
