### ISSUE TITLE
[Bug]表格白屏

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1496]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、表格为导入表格，导入后白屏报错
[项目管理模板（实战版）.xlsx](https://github.com/dream-num/univer/files/14509335/default.xlsx)

### 预期行为

表格正常显示

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/9d585b39-f089-49cb-806a-2b4aecbaeb6b)

**Comment by DR-Univer** [comment]
已经在pro修复了
