### ISSUE TITLE
[Bug] 不支持的公式会报#SPILL!  ,预期报#n/a或#value

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1505]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格公式=weekday(A1)

### 预期行为

预期报#n/a或#value

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/9c010550-f169-4b0f-9078-b48bbe681744)

**Comment by DR-Univer** [comment]
Follow google sheet,  show #NAME?
