### ISSUE TITLE
Cell editor (doc) enhancements

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#152]
- [x] 中文输入
- [ ] 回车换行
- [x] update更新输入
- [ ] 上下快捷键支持
- [x] 排版文字太紧密
- [x] 鼠标点击空白处体验
- [x] 光标体验
- [x] doc重构
- [x] editor接入sheet
- [x] ime input bugfix
- [x] show scroll bar
- [x] shortcut
- [ ] 网格调试
- [x] indent不生效
- [ ] 排版问题优化：中英文间隔、
- [x] 快捷键
- [ ] 复制粘贴
- [x] 范围选择器开发及优化（抽象及开发优化选择器）
- [ ] 导入
- [x] editor样式编辑重构
- [x] editor最后一个段落不能被删除

**Comment by DR-Univer** [comment]
需要考虑freeze、group、等情况，延期3天，28日进入

**Comment by DR-Univer** [comment]
formula selection、临时样式设计（支持内存态的文本高亮：公式、语法着色）、语法高亮设计（针对sheet公式）；这几个我移到公式的任务里了。其他 @Jocs 看看要不要重新建单跟进。

**Comment by Jocs** [comment]
@wzhudev @DR-Univer 我们是否可以 close 这个 issue？这个 issue 中未完成部分已经拆分成 task issue 了
