### ISSUE TITLE
[bug]切换到第二个子表滑动后表格公式不显示结果

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1530]
https://www.univer.ai/univer-examples/sheets/ 打开后切换到第2个子表，然后滑动
![image](https://github.com/dream-num/univer-examples/assets/154207126/c861bc80-ec4b-4841-b98e-f95a3f17b6fa)
[2024_3_7 20_38_09 video.webm](https://github.com/dream-num/univer-examples/assets/154207126/34f4a0ce-2f65-4895-81c0-14ef81e41aa2)

**Comment by Dushusir** [comment]
@DR-Univer @Jocs 富文本渲染问题 
复现DEMO https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-ubzk6z?file=src%2Fdata.ts

**Comment by DR-Univer** [comment]
> @DR-Univer @Jocs 富文本渲染问题 复现DEMO https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-ubzk6z?file=src%2Fdata.ts

这里是不是先用常规文本替换一下  @Dushusir

**Comment by Dushusir** [comment]
> > @DR-Univer @Jocs 富文本渲染问题 复现DEMO https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-ubzk6z?file=src%2Fdata.ts
> 
> 这里是不是先用常规文本替换一下 @Dushusir

Demo 已经替换成常规文本（即 cell.v）

**Comment by Dushusir** [comment]
目前 Demo 相关问题先 Close。后续如果再测出问题再新开 issue。 @zhaolixin7
