### ISSUE TITLE
[Bug] 合并单元格提示文案

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1531]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、选中2个以上有内容的单元格合并

### 预期行为

弹出toast加提示文案

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/0aa20d63-0798-4d35-a91e-bdf65dd49066)

**Comment by wzhudev** [comment]
This issue is already resolved by a previous fix.
