### ISSUE TITLE
[Bug] 编辑单元格内容时，使用左右键移动光标，直接失焦了

### ISSUE THREAD

**Issue by codebabydxj** [dream-num/univer#1549]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.2

### 复现链接

https://sheetsvitedemo-s2r2--5173--dc33e3af.local-credentialless.webcontainer.io

### 预期行为

已经获取焦点，键入值的时候可以使用键盘左右键移动光标

### 实际行为

输入值之后，左右移动光标修改值时， 光标失焦；

**Comment by jikkai** [comment]
The behavior is intentional and matches the expected functionality as seen in Excel.

https://github.com/dream-num/univer/assets/14025786/f1d64df3-3f87-4660-9b02-8868ca681158

**Comment by Yang-yibu** [comment]
不是吧，或者是有什么设置吧。我用 wps 测试是未失焦状态。我觉得不失焦更合理，不然还需好用鼠标确定光标位置，用户如果想失焦退出编辑状态，可以按Esc等退出键。

**Comment by Yang-yibu** [comment]
![动画1](https://github.com/dream-num/univer/assets/23130670/b90b9abf-3215-469d-9c1f-52b80be1caf0)
