### ISSUE TITLE
[Bug] Border Operation

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1552]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

Use demo https://univer.ai/playground/?title=Vite

1. select A1:C3
2. set border all
3. set merge all
4. cancel merge

### Expected behavior

cancel inner border
![image](https://github.com/dream-num/univer/assets/26371161/c82f9fb5-48b4-45b7-8dde-25fb6a289b5f)

### Actual behavior

restore all border
![image](https://github.com/dream-num/univer/assets/26371161/13b59261-dd72-483b-a34a-6df58c56b984)

**Comment by jikkai** [comment]
It seems like it has already been fixed.
