### ISSUE TITLE
[Bug] 特定表格刷新后控制台报错

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1553]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

刷新该表格https://staging.univer.plus/?unit=1767058890313147079&type=2&subunit=uni13

### 预期行为

不报错

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/c51b11a7-3549-4d9c-b053-83530c473303)

**Comment by Dushusir** [comment]
`=SUMIF(Transactions!A:A,$A8,Transactions!J:J)-SUMIF(Transactions!A:A,$A8,Transactions!I:I)` 公式报错，原因是解析 Transactions!A:A 变成了 TRANSACTIONS!A ColumnReferenceObject  中sheet name大写，匹配不到 sheet id  @DR-Univer
