### ISSUE TITLE
[Bug] PS D:\project\information-system-web> npm install --save @univerjs/docs-ui                                                                                           npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR!  npm ERR! While resolving: vue-admin-template@4.4.0 npm ERR! Found: @univerjs/core@0.1.0-beta.5 npm ERR! node_modules/@univerjs/core npm ERR!   peer @univerjs/core@"0.1.0-beta.5" from @univerjs/docs@0.1.0-beta.5 npm ERR!   node_modules/@univerjs/docs npm ERR!     peer @univerjs/docs@"0.1.0-beta.5" from @univerjs/sheets-formula@0.1.0-beta.5 npm ERR!     node_modules/@univerjs/sheets-formula npm ERR!       peer @univerjs/sheets-formula@"0.1.0-beta.5" from @univerjs/facade@0.1.0-beta.5 npm ERR!       node_modules/@univerjs/facade npm ERR!         @univerjs/facade@"^0.1.0-beta.5" from the root project npm ERR!       1 more (the root project) npm ERR!     peer @univerjs/docs@"0.1.0-beta.5" from @univerjs/sheets-ui@0.1.0-beta.5 npm ERR!     node_modules/@univerjs/sheets-ui npm ERR

### ISSUE THREAD

**Issue by linfaithjuntong** [dream-num/univer#1595]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

^0.1.2 更新到 0.1.3版本之后

### 预期行为

项目启动成功

### 实际行为

项目启动报错

### 系统信息

These dependencies were not found:

* @univerjs/engine-numfmt in ./node_modules/@univerjs/sheets-ui/lib/es/index.js
* @univerjs/protocol in ./node_modules/@univerjs/core/lib/es/index.js
* @univerjs/sheets-numfmt in ./node_modules/@univerjs/sheets-formula/lib/es/index.js
* @wendellhu/redi in ./node_modules/@univerjs/core/lib/es/index.js, ./node_modules/@univerjs/docs-ui/lib/es/index.js and 7 others
* @wendellhu/redi/react-bindings in ./node_modules/@univerjs/docs-ui/lib/es/index.js, ./node_modules/@univerjs/sheets-formula/lib/es/index.js and 2 others
* react in ./node_modules/@univerjs/design/lib/es/index.js, ./node_modules/@univerjs/docs-ui/lib/es/index.js and 3 others
* react-dom in ./node_modules/@univerjs/design/lib/es/index.js, ./node_modules/@univerjs/ui/lib/es/index.js

To install them, you can run: npm install --save @univerjs/engine-numfmt @univerjs/protocol @univerjs/sheets-numfmt @wendellhu/redi @wendellhu/redi/react-bindings react react-dom

**Comment by jikkai** [comment]
Please use npm@7+ or pnpm to install dependencies, and DO NOT abuse github issues.

**Comment by linfaithjuntong** [comment]
我npm版本是8.15.0
