### ISSUE TITLE
编辑时候转义一下

### ISSUE THREAD

**Issue by zhaorui2000** [dream-num/univer#16]
![image](https://github.com/dream-num/univer/assets/49807887/d5fa3820-ada7-484d-b420-2a3352f49c3d)
![image](https://github.com/dream-num/univer/assets/49807887/111aa218-cd81-4a61-be15-58668b14453b)
demo里看的，编辑时候转义一下，要不又出现奇怪的东西了。

**Comment by jikkai** [comment]
Already fixed in the previous pull request, we will update the demo before the official release.
