### ISSUE TITLE
[perf] mutations could be merged when executing `_pasteUSM` and other methods

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#1650]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

Not necessary.

### Expected behavior

There should be a `SetRangeValues` mutation.

### Actual behavior

There are 3 `SetRangeValues` mutations.

**Comment by yuhongz** [comment]
This issue was completed in #1665
