### ISSUE TITLE
[Bug] When copying and pasting local Excel into Univer’s Excel, the style is wrong

### ISSUE THREAD

**Issue by chenjing0823** [dream-num/univer#1660]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.3

### 复现链接

https://univer.ai/playground/?title=Vue%203

### 预期行为

回显样式正常

### 实际行为

1. 仅设置背景色，复制粘贴后出现黑色边框，没有背景色
2. 仅设置字体颜色，复制粘贴后出现同颜色边框，字体没有颜色
<img width="1753" alt="image" src="https://github.com/dream-num/univer/assets/34295555/f2bb35c5-bc7d-4f31-b617-6aea77b81b49">

**Comment by yuhongz** [comment]
Thank you for the feedback, this bug has been fixed! @chenjing0823
