### ISSUE TITLE
Switching to EN_US local does stop rendering

### ISSUE THREAD

**Issue by jan-source** [dream-num/univer#1671]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.3

### Reproduction link

https://univer.ai/playground/?title=UMD

 // univer --> index.html
      var univer = new UniverCore.Univer({
        theme: UniverDesign.defaultTheme,
        locale: UniverCore.LocaleType.EN_US,
        logLevel: UniverCore.LogLevel.VERBOSE,
      });
      
      
<img width="2421" alt="image" src="https://github.com/dream-num/univer/assets/77538739/78c77589-120a-4af0-a976-fb7c3c9ecb36">

### Expected behavior

Local swith to EN_US

### Actual behavior

rendering fails

**Comment by jikkai** [comment]
You forgot to add `locales` for it.
https://univer.ai/guides/quick-start/i18n/
