### ISSUE TITLE
[Bug] 3-25 facade document, nginx returns 404

### ISSUE THREAD

**Issue by raintoway** [dream-num/univer#1689]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

1

### 复现链接

1

### 预期行为

1

### 实际行为

1

**Comment by jikkai** [comment]
Please do not abuse GitHub issues.
