### ISSUE TITLE
[Bug] The operation control of frozen rows and columns will disappear when zoomed out

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#1718]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

![image](https://github.com/dream-num/univer/assets/68851825/034913aa-21d4-4098-8ea9-e5f7fbaa964d)
100%缩放下可以捡到，缩小为80%后消失
![image](https://github.com/dream-num/univer/assets/68851825/2cb40f00-fe0f-4152-bea9-44f6133bfbe9)

### 预期行为

缩小的情况下也可以展示

### 实际行为

消失了

**Comment by lumixraku** [comment]
https://github.com/dream-num/univer/pull/1724
