### ISSUE TITLE
Data is populated with previous sheet data when another spreadsheet is created on the same page[Bug] 

### ISSUE THREAD

**Issue by ktjh123** [dream-num/univer#1723]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.4

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

The new spreadsheet should not have any data

### Actual behavior

The new spreadsheet has data of the previous spreadsheet on the page

**Comment by jikkai** [comment]
```
const obj = {}

univer.createUniverSheet(obj);
```
