### ISSUE TITLE
[Bug] When the style "tb" = WrapStrategy.WRAP and use “\r" for line breaks, only the alignment of the last line will take effect

### ISSUE THREAD

**Issue by XY5** [dream-num/univer#1738]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.4|0.1.5

### Reproduction link

The Data Demo:
```JSON
{
	"id": "TEST",
	"sheetOrder": [
		"sheet-01"
	],
	"styles": {
		"TESTSTYLE": {
			"ht": 2,
			"tb": 3
		}
	},
	"sheets": {
		"sheet-01": {
			"id": "sheet-01",
			"rowData": [
				{
					"h": 50
				}
			],
			"cellData": [
				[
					{
						"s": "TESTSTYLE",
						"t": 1,
						"v": "aaa\rbbb\rccc"
					}
				]
			]
		}
	}
}
```

### Expected behavior

When using "\r" for line wrapping, all lines except the last line remain aligned to the left.
![1](https://github.com/dream-num/univer/assets/1542756/dd46f719-33f1-4c27-9786-9ccc98ddaab0)

### Actual behavior

All lines are aligned according to configuration. There is no such bug in 0.1.3.

**Comment by Jocs** [comment]
@XY5 How did this demo data come from? Currently, cell.v does not support line breaks, please use cell.p.
