### ISSUE TITLE
[Bug] The format of a specific table is wrong

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1763]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

导入该样张
[企业工作项导入样例 (5).xlsx](https://github.com/dream-num/univer/files/14832724/5.xlsx)

### 预期行为

与样张一致

### 实际行为

导入后变成上标，字体颜色不对
![image](https://github.com/dream-num/univer/assets/154207126/4c83d472-dc8c-4648-9365-119126ba0130)

**Comment by DR-Univer** [comment]
https://github.com/dream-num/univer-exchange/pull/73  fix
