### ISSUE TITLE
[Bug] New selection in conditional format does not display

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1776]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

staging

### 复现链接

1、选择选区，新建条件格式

### 预期行为

新建后应用范围显示选区

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/41f94fa8-914a-4126-975e-3e3b8c211e02)

**Comment by Gggpound** [comment]
无法复现
