### ISSUE TITLE
[Bug]  Undo after deleting rows. The original value is lost

### ISSUE THREAD

**Issue by HengCC** [dream-num/univer#1789]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

https://univer.ai/pro-examples/sheets-collaboration/?unit=1775354053916651555&type=2&subunit=sheet-1

### Reproduction link

https://univer.ai/pro-examples/sheets-collaboration/?unit=1775354053916651555&type=2&subunit=sheet-1

### Expected behavior

Values are not lost after undo is performed

### Actual behavior

Values are lost after undo is performed

### System information

https://github.com/dream-num/univer/assets/6167532/ff1c5ab2-b229-434b-9983-685b0017a966

**Comment by yuhongz** [comment]
Thank you for the feedback, this bug has been fixed.
