### ISSUE TITLE
[Feature] Change Default Currency Symbol

### ISSUE THREAD

**Issue by joanengenhoff** [dream-num/univer#1803]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I want to use multiple currency symbols. And make Euro as default (in the toolbar and inside the sheets rows), but I haven't found a way to do that in the docs or in the settings object.

How can I achive that? If it's possible.

### Solution

Be able to change the currency icon in the UI config object.

**Comment by Gggpound** [comment]
Certainly, if you need to add shortcut currency buttons, you can modify the code in univer/packages/sheets-numfmt/src/menu/menu.ts. This file is responsible for handling the menu functionality related to number formatting in the application.

**Comment by Matt-Jensen** [comment]
> Certainly, if you need to add shortcut currency buttons, you can modify the code in univer/packages/sheets-numfmt/src/menu/menu.ts. This file is responsible for handling the menu functionality related to number formatting in the application.

Is this the currently supported route for changing the default currency?
[Extending UI](https://univer.ai/guides/sheet/customization/ui.en-US#how-to-register-custom-menu-in-third-party-plugin).  Then we'd need to implement our own plugin, controller(s), command handler(s), and icon registration?  However we'd also need to disable the default RMB currency menu items and replace them first?
