### ISSUE TITLE
[Bug] Paste data from NotePad doesn't work as pasting from Excel!!

### ISSUE THREAD

**Issue by KiddoV** [dream-num/univer#1806]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.6

### Reproduction link

Explain the bug:
When I copy the whole worksheet from ``Excel`` and paste it to the ``UniverSheet``, data present correctly.
Then I tried to copy data from ``Excel`` again and paste it to ``NotePad`` then copy all data from ``NotePad`` and paste it to ``UniverSheet``, data only paste **in a single cell**.

### Expected behavior

``UniverSheet`` should treat pasting data as normal from different sources.

### Actual behavior

Only work with ``Excel`` for now!

### System information

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 8.85 GB / 31.89 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636

**Comment by yuhongz** [comment]
Which notepad are you using? It's highly possible that the reason for the data being pasted into a single cell is that the clipboard data is not saved in the <table> tag format by the Notepad. @KiddoV

**Comment by KiddoV** [comment]
I am using Notepad version 21H2 (OS Build 19044.4291) on Windows 10.
