### ISSUE TITLE
[Feature] Math Formulas

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#1809]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Math formula

### Solution

- [x] ASIN
- [x] ASINH
- [x] ATAN
- [x] ATAN2
- [x] ATANH
- [x] COS
- [x] TAN
- [x] TANH
- [x] ROUND
- [x] ROUNDDOWN
- [x] ROUNDUP
- [x] MROUND
- [x] CEILING.MATH
- [x] CEILING
- [x] CEILING.PRECISE
- [x] EXP
- [x] SIN
- [x] SINH
- [x] LOG
- [x] LOG10
- [x] FLOOR
- [x] FLOOR.MATH
- [x] FLOOR.PRECISE
- [x] DECIMAL
- [x] DEGREES
- [x] EVEN
- [x] ODD
- [x] LN
- [x] PI
- [x] RADIANS
- [x] RAND
- [x] RANDARRAY
- [x] RANDBETWEEN
- [x] SEC
- [x] SECH
- [x] SQRT
- [x] SQRTPI
- [x] SUMSQ
- [x] SUMX2MY2
- [x] SUMX2PY2
- [x] SUMXMY2

**Comment by oumomomo** [comment]
SUMX2MY2函数：
输入=SUMX2MY2({2,0,0},{2,ceshi,0})／=SUMX2MY2({},{})，预期应该报错
![企业微信截图_17213795444039](https://github.com/user-attachments/assets/0b722962-7268-4687-85ba-9d1c8d690839)
