### ISSUE TITLE
[Bug] Merging cells to paste into Excel will appear misaligned

### ISSUE THREAD

**Issue by karlsbeard** [dream-num/univer#1810]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.6

### Reproduction link

![bug](https://github.com/dream-num/univer/assets/50100424/49d183b3-a76c-4dde-863a-01019f971d39)

### Expected behavior

Copy the data from the Univer sheet and paste it into Excel the format could be the same.

### Actual behavior

When meeting the merge cell the paste format is not correct.

**Comment by ybzky** [comment]
fixed
