### ISSUE TITLE
[Bug] The formula refers to a selection, and the selection in the cell is not fully displayed.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1828]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格中输入公式如=sum(,然后鼠标选择选区

### 预期行为

单元格结果中显示选择的选区

### 实际行为

[2024_4_8 19_34_56 video.webm](https://github.com/dream-num/univer/assets/154207126/9eccb394-56fe-4f78-a59a-d12562d494c5)
1、有时需要等1-2s才显示选区、有时显示部分
![image](https://github.com/dream-num/univer/assets/154207126/87aa913b-4a1e-449d-843b-0e02142784aa)

**Comment by DR-Univer** [comment]
@zhaolixin7 能稳定复现？我这里没有遇到

**Comment by Dushusir** [comment]
暂无复现，如有问题再reopen
