### ISSUE TITLE
[Bug] When formatting drop-down options, the red mark is not displayed in the upper right corner of the cell and the capsule color is wrong.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1829]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格中下拉选项为数字，设置格式（货币、时间等）
2、显示样式条件改为箭头

### 预期行为

1、右上角有红标、错误文案提示
2、修改格式胶囊颜色不改变
3、改为箭头时，背景的默认灰色显示（google显示灰色）

### 实际行为

1、无不符合提示，右上角无红标
2、修改格式胶囊颜色变为默认的灰色
3、改为箭头单元格无背景色（google显示灰色）
[2024_4_8 11_12_51 video.webm](https://github.com/dream-num/univer/assets/154207126/4e6724da-27b1-4e99-b145-e73685246e12)

**Comment by weird94** [comment]
1. 我认为是正确的
2. 3应该没问题了
