### ISSUE TITLE
[Bug] The formula is equal to DefinedName, delete the row or column in the selection, and the formula result displays incorrectly

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1831]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、公式等于DefinedName，DefinedName1的选区为A1:A4，删除第2行

### 预期行为

公式显示正确结果

### 实际行为

公式结果等于#name?
[2024_4_8 20_29_48 video.webm](https://github.com/dream-num/univer/assets/154207126/25705fde-335b-4ac8-8748-b636cb687153)

**Comment by raintoway** [comment]
same bug i had found today, it is a deadly bug!

**Comment by DR-Univer** [comment]
https://github.com/dream-num/univer/pull/1888   resolved  @zhaolixin7
