### ISSUE TITLE
[Bug] copy the default text to Excel can not get the correct font size

### ISSUE THREAD

**Issue by karlsbeard** [dream-num/univer#1841]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.6

### Reproduction link

![bug](https://github.com/dream-num/univer/assets/50100424/b5ee6caa-f5ed-4099-a13c-072bde0f8b41)

### Expected behavior

copy the cell value from univer and paste it into Excel, the font size should be 11, not 10

### Actual behavior

the font size is 10 not 11

**Comment by ybzky** [comment]
fixed
