### ISSUE TITLE
[Feature request] When setting conditional format, the corresponding data cannot be obtained through the save method.

### ISSUE THREAD

**Issue by hibehero** [dream-num/univer#1880]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.6

### 复现链接

demo链接：https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-wx9rzq?file=src%2Fcomponents%2FUniverSheet.vue
通过条件格式设置色阶，点击get-data按钮获取execl数据
![screenshots](https://github.com/dream-num/univer/assets/23311404/6af70b2e-edbc-4ffb-9cd9-8b0d1ebb7345)

### 预期行为

期望能获取到色阶对应的json数据

### 实际行为

未获取到色阶对应的数据
`{
  "id": "workbook-01",
  "sheetOrder": [
    "sheet-01",
    "sheet-02",
    "sheet-03"
  ],
  "name": "universheet",
  "appVersion": "3.0.0-alpha",
  "locale": "zhCN",
  "styles": {},
  "sheets": {
    "sheet-01": {
      "type": 0,
      "id": "sheet-01",
      "cellData": {
        "0": {
          "0": {
            "v": "Hello World"
          },
          "1": {
            "v": 1,
            "t": 2
          }
        },
        "1": {
          "1": {
            "v": 2,
            "t": 2
          }
        },
        "2": {
          "1": {
            "v": 3,
            "t": 2
          }
        }
      },
      "name": "sheet1",
      "tabColor": "red",
      "hidden": 0,
      "rowCount": 1000,
      "columnCount": 20,
      "zoomRatio": 1,
      "scrollTop": 200,
      "scrollLeft": 100,
      "defaultColumnWidth": 93,
      "defaultRowHeight": 27,
      "status": 1,
      "showGridlines": 1,
      "hideRow": [],
      "hideColumn": [],
      "rowHeader": {
        "width": 46,
        "hidden": 0
      },
      "columnHeader": {
        "height": 20,
        "hidden": 0
      },
      "selections": [
        "A2"
      ],
      "rightToLeft": 0,
      "pluginMeta": {},
      "freeze": {
        "xSplit": 0,
        "ySplit": 0,
        "startRow": -1,
        "startColumn": -1
      },
      "mergeData": [],
      "rowData": {
        "0": {
          "hd": 0,
          "h": 27,
          "ah": 27
        },
        "1": {
          "hd": 0,
          "h": 27,
          "ah": 27
        },
        "2": {
          "hd": 0,
          "h": 27,
          "ah": 27
        }
      },
      "columnData": {}
    },
    "sheet-02": {
      "type": 0,
      "id": "sheet-02",
      "name": "sheet2",
      "cellData": {},
      "tabColor": "",
      "hidden": 0,
      "rowCount": 1000,
      "columnCount": 20,
      "zoomRatio": 1,
      "freeze": {
        "xSplit": 0,
        "ySplit": 0,
        "startRow": -1,
        "startColumn": -1
      },
      "scrollTop": 0,
      "scrollLeft": 0,
      "defaultColumnWidth": 73,
      "defaultRowHeight": 19,
      "mergeData": [],
      "rowData": {},
      "columnData": {},
      "showGridlines": 1,
      "rowHeader": {
        "width": 46,
        "hidden": 0
      },
      "columnHeader": {
        "height": 20,
        "hidden": 0
      },
      "selections": [
        "A1"
      ],
      "rightToLeft": 0
    },
    "sheet-03": {
      "type": 0,
      "id": "sheet-03",
      "name": "sheet3",
      "cellData": {},
      "tabColor": "",
      "hidden": 0,
      "rowCount": 1000,
      "columnCount": 20,
      "zoomRatio": 1,
      "freeze": {
        "xSplit": 0,
        "ySplit": 0,
        "startRow": -1,
        "startColumn": -1
      },
      "scrollTop": 0,
      "scrollLeft": 0,
      "defaultColumnWidth": 73,
      "defaultRowHeight": 19,
      "mergeData": [],
      "rowData": {},
      "columnData": {},
      "showGridlines": 1,
      "rowHeader": {
        "width": 46,
        "hidden": 0
      },
      "columnHeader": {
        "height": 20,
        "hidden": 0
      },
      "selections": [
        "A1"
      ],
      "rightToLeft": 0
    }
  },
  "resources": []
}`

### 运行环境

Chrome

**Comment by jikkai** [comment]
This is not a bug, the data you need is not the final drop data and therefore should not be available via `.save()`.

The way to do this is still under development, so track down #1853 for an update!

---

这并不是一个 bug，你所需要的数据并不是最终落盘数据，因此不应该通过 `.save()` 获取。

获取的方法尚在开发中，请追踪 #1853 来获取更新
