### ISSUE TITLE
[Feature] Math Formula ACOTH

### ISSUE THREAD

**Issue by lumixraku** [dream-num/univer#1906]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

Formula ACOTH is not implemented

### 解决方案

https://support.microsoft.com/zh-cn/office/acoth-%E5%87%BD%E6%95%B0-cc49480f-f684-4171-9fc5-73e4e852300f

**Comment by lumixraku** [comment]
@lumixraku solve it

**Comment by Dushusir** [comment]
Implemented in other issue
