### ISSUE TITLE
[Feature] Math Formula ARABIC

### ISSUE THREAD

**Issue by lumixraku** [dream-num/univer#1907]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

Math Formula ARABIC not implemented

### 解决方案

https://support.microsoft.com/zh-cn/office/arabic-%E5%87%BD%E6%95%B0-9a8da418-c17b-4ef9-a657-9370a30a674f

**Comment by lumixraku** [comment]
@lumixraku solve it

**Comment by Dushusir** [comment]
Implemented in other issue
