### ISSUE TITLE
[Feature] Math Formula ASIN

### ISSUE THREAD

**Issue by lumixraku** [dream-num/univer#1908]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Math formula ASIN not implemented

### Solution

https://support.microsoft.com/zh-cn/office/asin-%E5%87%BD%E6%95%B0-81fb95e5-6d6f-48c4-bc45-58f955c6d347

**Comment by lumixraku** [comment]
@lumixraku  solve it

**Comment by Dushusir** [comment]
Implemented in other issue
