### ISSUE TITLE
[Feature] Support removing gridlines

### ISSUE THREAD

**Issue by 18860852449** [dream-num/univer#1911]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Hope to support the same function as Excel to remove background gridlines

### Solution

As shown in the figure, after checking the grid line checkbox, the entire table will hide the background grid line.
![ca84f6d9dfb515b21023f0a4d6bac24](https://github.com/dream-num/univer/assets/48787019/8c616105-0ed3-487d-9be9-b0ceefea2539)

**Comment by jikkai** [comment]
It seems that we need to do some UI design on the toolbar first. @Eelson
