### ISSUE TITLE
[Feature] Be able to add line breaks on cell text. 

### ISSUE THREAD

**Issue by joanengenhoff** [dream-num/univer#1923]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

When input data we are unable to break lines.

### Solution

Add break lines with "Shift + Enter" or similar keys.

**Comment by Dushusir** [comment]
Use `Alt+Enter`

**Comment by joanengenhoff** [comment]
@Dushusir  Do you know if there is a way to customize this hotkey?
