### ISSUE TITLE
[Bug] New Lines Break the Application

### ISSUE THREAD

**Issue by joanengenhoff** [dream-num/univer#1924]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

Facade API

### Reproduction link

https://stackblitz.com/edit/github-aayzou-pwwuzf?file=src%2FApp.jsx

### Expected behavior

When providing text with break lines the application might not break.

### Actual behavior

Application breaks and disappear from the screen when we set a value or an enriched text with new lines.

### System information

  System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.7 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.2.1

**Comment by jikkai** [comment]
https://stackblitz.com/edit/github-aayzou-w7wzvv?file=src%2FApp.jsx

**Comment by joanengenhoff** [comment]
@jikkai replacing `\n` to `\r` is more a workaround than a fix. I would say the bug still exists, and on cases that data arrives from servers or other places, the developer will need to clean and replace the `\n` everytime.
