### ISSUE TITLE
[Bug] After entering content in the search box, click Confirm to not filter.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1939]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接
#1450 
1、筛选面板搜索框中输入内容，点击确认

### 预期行为

1、可以筛选

### 实际行为

点击确认后无反应
[2024_4_17 14_34_30 video.webm](https://github.com/dream-num/univer/assets/154207126/6004bb10-5465-418c-9be2-e41c43f15786)

**Comment by wzhudev** [comment]
@zhaolixin7 The screen capture seems irrelevant.
