### ISSUE TITLE
[Bug] Rich text cannot be filtered

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1946]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、筛选区域有富文本
2、仅筛选富文本

### 预期行为

支持筛选

### 实际行为

筛选结果不对

**Comment by wzhudev** [comment]
Fixed boolean values as well.
