### ISSUE TITLE
[Bug] Data validation capsule and filter icon overlap

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1947]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

#1450 
1、在有数据验证选项区域新增筛选区域
2、在有条件格式区域新增筛选

### 预期行为

![image](https://github.com/dream-num/univer/assets/154207126/b4261aa3-2242-4b8f-bde4-eca5329a71f2)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/ab57e4a2-b71e-4731-85ec-f63935648ab4)
![image](https://github.com/dream-num/univer/assets/154207126/80a6c4e4-4749-4d7a-b400-030da46dc3a4)
![image](https://github.com/dream-num/univer/assets/154207126/a4e0c635-6248-4eee-9edc-aa22a36bd438)

[2024_4_17 17_37_14 video.webm](https://github.com/dream-num/univer/assets/154207126/e39f03c5-0170-4116-aae5-02d125d694bb)

**Comment by wzhudev** [comment]
@lumixraku @weird94 @Gggpound data validation rendering should respect cell offset.

**Comment by oumomomo** [comment]
筛选范围内有失效数据，筛选过滤这条失效数据时，红色icon还是会展示在表内
![image](https://github.com/dream-num/univer/assets/167171356/579d5776-6ab6-4298-b5ab-7c5e08702c6d)
![image](https://github.com/dream-num/univer/assets/167171356/06c43ac4-53af-4f60-a8ab-e97142434224)

**Comment by oumomomo** [comment]
筛选掉包含条件格式-色阶的数据，色阶颜色还是会展示在表内
![image](https://github.com/dream-num/univer/assets/167171356/ab5b4331-5ea2-4946-ba20-5068c19a272f)
