### ISSUE TITLE
[Bug] The arrow in the drop-down option after filtering is not displayed as expected.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1949]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、筛选区域有下拉选项，过滤下拉选项所在行

### 预期行为

筛选后不显示箭头

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/658325f7-20ad-4051-bdee-c435f155ba8a)
[2024_4_17 17_18_06 video.webm](https://github.com/dream-num/univer/assets/154207126/bbf5113f-77b0-4f4e-8603-8e1d48caedf1)

**Comment by weird94** [comment]
fixed
