### ISSUE TITLE
[Bug] Plugin life cycle onRendred and onSteady callback methods are invalid

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#1963]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

![image](https://github.com/dream-num/univer/assets/68851825/d3e89412-5c12-4834-9d85-5386aae7f772)
在onRendred和 onSteady方法内实现的逻辑无法执行。

### 预期行为

正常执行回调

### 实际行为

无法执行

### 运行环境

Chrome

**Comment by DR-Univer** [comment]
重构后目前onReady也不执行了

**Comment by wzhudev** [comment]
This problem had been fixed in recent refactoring.
