### ISSUE TITLE
[Bug] Filtered rows cannot be deleted as expected

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1968]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、选中被筛选过滤掉的行删除
2、清除筛选

### 预期行为

1、被过滤掉的行无法删除（Excel是无法被删除的）
2、清除筛选后显示被筛选的内容

### 实际行为

被筛选的内容和选中行一同被删除
[2024_4_18 11_36_01 video.webm](https://github.com/dream-num/univer/assets/154207126/fd528a1e-75ce-47d6-8356-1568345e0e6b)

**Comment by wzhudev** [comment]
@yuhongz Please take a look into Filter's command interceptor.

**Comment by zhaolixin7** [comment]
@yuhongz 删除被删选的行后清除筛选，然后undo 3次，筛选区域内容、范围都不对（录屏中多出“5”）[2024_4_25 14_43_52 video.webm](https://github.com/dream-num/univer/assets/154207126/0ab9ad76-51cd-4536-9201-8755b39a1f07)
