### ISSUE TITLE
[Bug] When modifying the filtered value, the newly modified value is not checked in the filter panel.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#1976]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、设置筛选条件
2、将筛选出来的值进行修改

### Expected behavior

修改筛选出来的值，筛选面板会对应勾选该值

### Actual behavior

修改筛选出来的值，筛选面板不会对应勾选该值

[2024_4_19 10_46_40 video.webm](https://github.com/dream-num/univer/assets/167171356/2407fb54-24fb-4e97-a280-6ebd751c2229)

**Comment by wzhudev** [comment]
We refer to Excel here. This won't be fixed.
