### ISSUE TITLE
[Feature] Text Formula UPPER

### ISSUE THREAD

**Issue by jackpk235** [dream-num/univer#1977]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Formula UPPER is not implemented

### Solution

Implement formula UPPER 
Reference https://support.microsoft.com/zh-cn/office/upper-%E5%87%BD%E6%95%B0-c11f29b3-d1a3-4537-8df6-04d0049963d6
@jackpk235 : I can solve it

**Comment by dharmik3504** [comment]
hi @jackpk235 
can you correct me m i reproducing  the  correctly ?

[screen-capture (1).webm](https://github.com/dream-num/univer/assets/77182459/c642655c-ffd9-4efe-97d5-4f47d291f74a)

**Comment by Dushusir** [comment]
Assign to https://github.com/dream-num/univer/issues/1812
