### ISSUE TITLE
[Bug] When the data in the cell is a date, using conditional filtering to select text that contains a number within the date cannot be filtered out.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#1980]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

操作步骤：
1、单元格内输入日期
2、筛选使用按条件筛选，设置文本包含日期内某数字
3、保存筛选

### 预期行为

预期应该可以筛选出包含日期的单元格？

### 实际行为

无法筛选出包含日期的单元格
[2024_4_18 16_15_53 video.webm](https://github.com/dream-num/univer/assets/167171356/d77ee6c6-9f66-4c52-82b2-bc993f93f0aa)

**Comment by wzhudev** [comment]
This is not a bug. Please refer to Excel.
