### ISSUE TITLE
[Bug] If you click General first and then click Add Rule to select the condition type, it will automatically jump back to General.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#1983]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、点击常规-更多格式
2、再点击数据验证-更多规则选择条件类型

### Expected behavior

正常打开条件规则下拉框

### Actual behavior

未打开条件规则下拉框，跳转到了最开始点击的更多格式
[2024_4_18 17_14_53 video.webm](https://github.com/dream-num/univer/assets/167171356/827b05d8-cef2-4b19-89fe-fa29e0802947)

**Comment by Gggpound** [comment]
<img width="509" alt="image" src="https://github.com/dream-num/univer/assets/141617023/9b2ef7c5-6311-4cbe-973d-b80192d319f6">
转给 @weird94 看看

**Comment by weird94** [comment]
问题已经无法复现
