### ISSUE TITLE
[Bug] Large filter form freezes

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1992]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、大表格筛选（1000行）

### 预期行为

筛选时间和feishu差不多

### 实际行为

相比feishu会慢些

**Comment by wzhudev** [comment]
![image](https://github.com/dream-num/univer/assets/12122021/4a7c36dd-0268-4a7a-b1b8-aee6796069fe)

The rendering layer used a lot of time to update cache. Any idea?

**Comment by viditrastogi11** [comment]
Hey @zhaolixin7 is this issue resolved? i m still facing this issue in v0.2.9. because of this issue filter are not usable any idea how to fix this? @wzhudev

**Comment by jikkai** [comment]
> Hey @zhaolixin7 is this issue resolved? i m still facing this issue in v0.2.9. because of this issue filter are not usable any idea how to fix this? @wzhudev

If the issue persists, please submit a new issue with a minimal reproduction link.

**Comment by viditrastogi11** [comment]
@jikkai  https://github.com/dream-num/univer/issues/3313
