### ISSUE TITLE
[Bug] When filtering cells containing font colors within the filter range, the cell border line in the filter header row is incompletely displayed.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#1994]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、框选筛选范围（包含字体颜色单元格）
2、设置筛选条件为有字体颜色的数据后点击确认

### Expected behavior

筛选头那一行单元格边框线展示完整

### Actual behavior

筛选头那一行单元格边框线展示不完整
[2024_4_19 11_50_46 video.webm](https://github.com/dream-num/univer/assets/167171356/052a85a4-d178-4b56-98db-1af2f3eb6908)

**Comment by wzhudev** [comment]
This is what we've talked before. @DR-Univer Please take a look into this. It won't block our launch of filter.
