### ISSUE TITLE
how to edit old excel?

### ISSUE THREAD

**Issue by itmeicn** [dream-num/univer#1997]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

//保存到数据库
const saveSheet = () => {
    const result = univerRef.value?.getData();
    form.content = JSON.stringify(result);
};
save mysql.
edit data 
form.content=api return data  这样excel没有反应

### Solution

同上，能否出个接口返回数据 ，然后编辑的教程或者文档？

**Comment by jikkai** [comment]
It seems that this issue might be related to usage. Please consider reviewing the official documentation carefully.

We will temporarily close this issue for now. If you believe there is indeed a problem with Univer, please describe your issue in detail and provide sufficient information. You are welcome to reopen this issue at any time.

---

看起来只是使用方面的问题，可以考虑先仔细查看官网文档。
这里暂时先关闭这个 issue，如果你觉得确实 univer 存在问题，请详细描述你的问题并提供足够的信息，欢迎你随时再打开这个 issue
