### ISSUE TITLE
[Bug] Copy the number format in excel and paste it into univer without retaining the format

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#1998]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、复制表格中的格式粘贴到univer
[样张.xlsx](https://github.com/dream-num/univer/files/15036154/default.xlsx)

### 预期行为

保留数字格式

### 实际行为

显示为数值
![image](https://github.com/dream-num/univer/assets/154207126/44e7576f-cadc-4de0-80ba-6de7ffc503f3)

**Comment by zhongxu-Sun** [comment]
我的也是，当我从Excel中粘贴日期格式的数据的时候，所有的日期都丢失，变成了最原始的数值。

**Comment by Allisam-c** [comment]
我也遇到了相同的问题，现在还没有修复吗

**Comment by ybzky** [comment]
> 我也遇到了相同的问题，现在还没有修复吗

会在这个版本修复
