### ISSUE TITLE
[Bug] When there is no space at the bottom of the filter range, there is a problem with data display when clicking Insert-Move Down

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2004]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：（筛选范围内新增列也会使筛选区域内的列外移）
1、框选筛选范围
2、设置筛选条件使底部没有空格
3、点击插入-下移

### Expected behavior

筛选范围对应向下扩展？
![image](https://github.com/dream-num/univer/assets/167171356/c701fbb1-64d5-4df1-a8c5-431e0c011a90)

### Actual behavior

点击下移后，数据往下移消失不见，另外被筛选掉的数据也会出现
[2024_4_19 17_53_04 video.webm](https://github.com/dream-num/univer/assets/167171356/b4bae952-f908-400f-a7c9-e195c679e335)

**Comment by yuhongz** [comment]
FIlter result at local will not refresh untill manual trigger reCalc
