### ISSUE TITLE
[Bug] The calculation result of the formula imported into a specific sample is incorrect.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2008]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、导入甘特图
[项目甘特图.xlsx](https://github.com/dream-num/univer/files/15040413/default.xlsx)

### 预期行为

可以计算出结果

### 实际行为

截图中的公式计算不出来![image](https://github.com/dream-num/univer/assets/154207126/dad04d4c-3332-4bc3-a990-bbbe95c54921)
![image](https://github.com/dream-num/univer/assets/154207126/05bf20b2-dae9-4053-a275-de3704c837a3)

**Comment by DR-Univer** [comment]
@Dushusir  formulaDataModel初始化不正确

**Comment by Dushusir** [comment]
@zhaolixin7  待 https://github.com/dream-num/univer/pull/1876 合入后复测下
