### ISSUE TITLE
[Bug] Select the formula and then perform the table cutting operation and select the selection. The formula does not take effect after pressing Enter.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2011]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、选择公式后进行切表操作
2、在某个表内选区
3、点击回车键

### Expected behavior

回到最开始选择公式的表，公式未生效

### Actual behavior

赋值到第一个工作表
[2024_4_20 10_44_46 video.webm](https://github.com/dream-num/univer/assets/167171356/e5e2d90b-9fd8-48c0-a6d3-3105513d7b87)

**Comment by Dushusir** [comment]
Has been fixed, please test
