### ISSUE TITLE
[Bug] The style is not displayed in the custom formula conditional formatting area

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2015]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、表格设置条件格式--自定义公式
https://staging.univer.plus/?unit=1780691569014383147&type=2&subunit=uni2
[2024_4_20 12_04_19 snapshot.json](https://github.com/dream-num/univer/files/15046838/2024_4_20.12_04_19.snapshot.json)

### 预期行为

符合条件显示格式样式

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/1d04c8a2-1295-4604-9a54-3a689260954b)

**Comment by Gggpound** [comment]
无法复现
