### ISSUE TITLE
[Bug] JavaScript errors using the UMD Package Generation Tool code

### ISSUE THREAD

**Issue by thdoan** [dream-num/univer#2027]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

@univerjs

### Reproduction link

I tried to use the UMD Package Generation Tool to create a minimal demo. Even though the demo loaded, it produced errors in the console. Steps to reproduce:

1. Go to https://univer.ai/guides/quick-start/umd/ and download the generated `univer.umd.css` and `univer.umd.js` files.
2. Save the boilerplate code to `index.html`.
3. Add the CDN links as well (copy code exactly as shown). The final `index.html` is attached: [index.zip](https://github.com/dream-num/univer/files/15053160/index.zip)
4. Load this `index.html`.

### Expected behavior

A basic spreadsheet component with no JavaScript errors.

### Actual behavior

These errors showed up in the console:

![image](https://github.com/dream-num/univer/assets/4110567/f9af0061-be4e-43cc-9156-f42f4d8982df)

### System information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 14.94 GB / 31.95 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636

**Comment by jikkai** [comment]
It seems that these two packages are missing.

```diff
+ <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/network/lib/umd/index.js"></script>
<script crossorigin="anonymous" src="https://unpkg.com/@univerjs/facade/lib/umd/index.js"></script>
+ <script crossorigin="anonymous" src="https://unpkg.com/@univerjs/uniscript/lib/umd/index.js"></script>
```

https://stackblitz.com/~/github.com/awesome-univer/sheets-umd-demo
