### ISSUE TITLE
[Bug] The ISERR function returns an error code when selecting an entire column or row.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2029]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、使用ISERR/ISERROR/ISNA/ISTEXT函数(使用lsref参数选择行的时候返回#value)
2、value选择整行

### Expected behavior

选择整行时返回#value！
![image](https://github.com/dream-num/univer/assets/167171356/3e69cef3-ddd8-4849-8579-9823550b2dcf)

### Actual behavior

excel均返回为false
![image](https://github.com/dream-num/univer/assets/167171356/f2da3c69-884a-44ce-b149-fb3d5796f638)

**Comment by Dushusir** [comment]
1. 整列在最新版Excel中显示 溢出（#SPILL!），无需修复 =ISERR(J:J) @oumomomo 
2. 整行在解析=ISERR(1:1)时，_generateAstNode 对整行解析错误 @DR-Univer 
![image](https://github.com/dream-num/univer/assets/26371161/7eb263c0-ba98-4024-931c-6f55ae819478)
