### ISSUE TITLE
[Bug] When the SUBTLTAL function uses a number of 4, the calculation is incorrect when there is a value that is too long in the range.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2031]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤
1、使用power函数
2、框选范围内有超长的数值
3、使用函数编号4

### Expected behavior

有超长数值时不展示最大的值

### Actual behavior

有超长数值时也会展示最大的值
![image](https://github.com/dream-num/univer/assets/167171356/bf0bd9de-2d63-4fd6-880c-4bc8ac10440b)

**Comment by Dushusir** [comment]
google 认为 16 位数字及以上是字符串
![image](https://github.com/dream-num/univer/assets/26371161/04581f3c-eb09-4435-90d8-9c5c13727422)

所以字符串不统计在内
![image](https://github.com/dream-num/univer/assets/26371161/b5fd9a3c-944f-4b0f-b202-1f6c1aeaf2f4)

我们认为 17 位以上数字是字符串，不做统计
