### ISSUE TITLE
[Bug] After dragging the unit, there is a very thick line

### ISSUE THREAD

**Issue by itmeicn** [dream-num/univer#2032]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.7

### 复现链接

none

### 预期行为

none line

### 实际行为

![image](https://github.com/dream-num/univer/assets/31679124/ddd403f1-0663-4baf-888c-6c7cb8a90c91)

### 系统信息

edge,win11 64

**Comment by jikkai** [comment]
Based on standard community guidelines, we typically close issues that do not provide detailed steps to reproduce or links to replicate the problem.
If you are able to provide this information, please feel free to reopen this issue at any time.
