### ISSUE TITLE
[Bug] The formula does not stop calculating after deleting the table

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2037]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

子表中公式计算时，删除子表

### 预期行为
![image](https://github.com/dream-num/univer/assets/154207126/41b91c47-3bfa-48db-ba2b-2851dcecc891)

### 实际行为

删除表格后不会公式停止计算

**Comment by Dushusir** [comment]
需要有一个引擎提供一个停止计算的方法 @DR-Univer

**Comment by DR-Univer** [comment]
> 需要有一个引擎提供一个停止计算的方法 @DR-Univer
可以用SetFormulaCalculationStopMutation
