### ISSUE TITLE
[Bug] When pulling down to fill formulas, some cells in the snapshot do not display formulas

### ISSUE THREAD

**Issue by fmwww** [dream-num/univer#2040]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.7

### 复现链接

[Screen-Recording-2024-04-23-at-09.41.51.webm](https://github.com/dream-num/univer/assets/11371523/bb08a6d1-de74-4bc3-8292-615247afee93)

### 预期行为

snapshot中应该所有格子都有公式，和格式化插件一起使用的时候，应该可以照常编辑公式

### 实际行为

1. 下拉填充公式的时候，snapshot中只有第一个填充的会有公式（也就是f字段），之后的都没有，不确定是这么设计的还是bug
2. 和格式化插件一起使用的时候，比如添加两位小数，会直接导致除了第一个以外的填充格子无法编辑公式，但是公式依然可以计算

**Comment by Dushusir** [comment]
1. 公式si是特别的设计，参考 https://univer.ai/zh-cn/guides/configuration/cell-data/#%E5%85%AC%E5%BC%8F-id
2. 0.1.8 版本对数字格式进行了改造，我们会关注下

**Comment by fmwww** [comment]
好的，了解👌
