### ISSUE TITLE
[Bug] When dragging a cell to a formula, the formula calculation result is incorrect.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2043]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、A1=sum(B1+c1),拖拽有内容（“测试”）的单元格到A1,

### 预期行为

拖拽后单元格显示为“测试”

### 实际行为

单元格内容未改变
[2024_4_23 11_26_03 video.webm](https://github.com/dream-num/univer/assets/154207126/186d74c6-fa4a-46e6-a5fd-f4c3cf53b797)

**Comment by Dushusir** [comment]
已恢复正常，如有问题再 reopen
