### ISSUE TITLE
[Feature] How to reinitialize or optimize initialization

### ISSUE THREAD

**Issue by dawudyang** [dream-num/univer#2046]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

目前我已新建了univer 我会保存当前的模板，会做切换模板 ，当切换模板的时候就需要重新初始化unvier和里面的数据，数据是已经组装好了 直接能用的json 我想重新create我对应的模板json 发现目前没有很好的方法，就去用unvier.dispose()进行销毁，但是发现我所有的已经注册的插件和监听的命令都不能用了 需要销毁后 在create前又重新注册一次插件，和监听命令和newApi等一系列操作，感觉这样就太麻烦了。

### 解决方案

看看能不能有一个什么方法调用后就直接能重新create,或者用一个update来重新更新unvier及unvier里面的sheets对应的数据 这样就能在保持插件和监听命令的情况下重新初始化里面的sheet内容

**Comment by HengCC** [comment]
Is it possible to minimize updates. Let's say I know for sure that the formula has changed. I just need to update the formula. If the cell value changes, only the cell is updated. Is there such an api

**Comment by xiaosongxiaosong** [comment]
使用下面的代码可以重置的功能，但是开发环境会抛出 `permissionPoint does not exist!` 异常
```jsx
const reset = useMemoizedFn(() => {
    const { instance, api } = univer.peek();
    if (!instance) {
      return;
    }
    const id = api.getActiveWorkbook()?.getId();
    if (id) {
      api.disposeUnit(id);
    }
    setTimeout(() => {
      instance.createUnit(UniverInstanceType.UNIVER_SHEET, {});
    }, 1000);
  });
```

![image](https://github.com/dream-num/univer/assets/2703455/7351073f-27df-41eb-86c5-ac6e6831b1b5)

**Comment by hexf00** [comment]
This feature has been implemented in #2091. For the API documentation, please refer to https://univer.ai/typedoc/@univerjs/facade/classes/FUniver#disposeunit . Therefore, this feature is closed. If there are any issues, please open a new bug issue.
