### ISSUE TITLE
[Feature] If the cell is selected, the column and column information is returned. For example, if the cell 'A3' is selected, the 'A3' is returned in onBeforeCommandExecute. It is difficult to handle this by yourself.

### ISSUE THREAD

**Issue by webhaohao** [dream-num/univer#2064]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

If the cell is selected, the column and column information is returned. For example, if the cell 'A3' is selected, the 'A3' is returned in onBeforeCommandExecute. It is difficult to handle this by yourself.

### 解决方案

onBeforeCommandExecute  command  return info

**Comment by jikkai** [comment]
I'm not very sure whether you mean this facade api or not.
https://univer.ai/zh-cn/guides/facade/sheet/#%E7%9B%91%E5%90%AC%E9%80%89%E5%8C%BA%E5%8F%98%E5%8C%96

The current version (v0.1.7) may throw an error. Although it DOES NOT affect usage, we have fixed it here. https://github.com/dream-num/univer/pull/2066
