### ISSUE TITLE
[Feature] When will floating charts be supported

### ISSUE THREAD

**Issue by alindas** [dream-num/univer#2069]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

now version dont support render img

### Solution

support render img

**Comment by jikkai** [comment]
We will start this work in this quarter.

**Comment by Mr-Glin** [comment]
> We will start this work in this quarter.

Hello, could you tell me the progress of this project?

**Comment by jikkai** [comment]
The floating charts feature is provided by VCharts through the [univer-vchart-plugin](https://github.com/VisActor/univer-vchart-plugin).
