### ISSUE TITLE
[Bug] When multiple univer instances are initialized, the behavior data is confusing.

### ISSUE THREAD

**Issue by Qsh-yh** [dream-num/univer#2085]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.7

### 复现链接

https://univer.ai/playground/?title=Multi%20Instance

### 预期行为

多实例的行为、数据不应该相互影响。例：在nuive1中A1=123，B1=A1=123。在nuive2中A1=234，B1=A1=234

### 实际行为

多实例的行为、数据相互影响了。例：在nuive1中A1=123，B1=A1=123。在nuive2中A1=234，B1=A1=123。这里的nuive2中B1单元格中=A1，取的是nuiver1中A1的值。
![微信图片_20240426105640](https://github.com/dream-num/univer/assets/56424404/18b2f2a7-ff5d-420c-8cfc-8758b9a4446f)

### 运行环境

Chrome

**Comment by wzhudev** [comment]
`UnitId`s of the snapshots should not be the same.

**Comment by Dushusir** [comment]
The problem with multiple instances has been solved. Please retest. If the problem still exists, please submit an issue or reopen it.
