### ISSUE TITLE
[Bug] The value in the formula is not highlighted

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2096]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、公式等于=AND($H8>$E8,K$5>$E8,K$5<=$H8)
2、公式等于=IFS(C2:C13>=20,"b2",C2:C13>60,"c",C2:C13>80,"a")

### 预期行为

![image](https://github.com/dream-num/univer/assets/154207126/29e84015-9e71-4c7c-a527-61b234216e05)

### 实际行为

1、$H8没有显示颜色
![image](https://github.com/dream-num/univer/assets/154207126/1a0ef0b3-a78d-47ed-b94e-4712230a8cbd)

2、引号未高亮
![image](https://github.com/dream-num/univer/assets/154207126/ab9960f1-8665-4fc4-9383-824a296bc513)

**Comment by Dushusir** [comment]
_nodeMaker 中 跳过了 "<=" 中的 "=" @DR-Univer 
![image](https://github.com/dream-num/univer/assets/26371161/f59912e1-9d01-4f01-afc3-a7680ed9613d)
