### ISSUE TITLE
[Bug]  WARN  Issues with peer dependencies found

### ISSUE THREAD

**Issue by JackieCheung** [dream-num/univer#2102]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.8

### Reproduction link

update 0.1.8

### Expected behavior

no warning

### Actual behavior

 WARN  Issues with peer dependencies found
.
├─┬ @univerjs/core 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/data-validation 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/docs 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/docs-ui 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/engine-formula 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/engine-render 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/facade 0.1.8
│ ├── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
│ └── ✕ unmet peer @univerjs/network@0.1.8: found 0.1.7
├─┬ @univerjs/find-replace 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/sheets 0.1.8
│ ├── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
│ └── ✕ unmet peer @univerjs/engine-numfmt@0.1.8: found 0.1.7
├─┬ @univerjs/sheets-conditional-formatting-ui 0.1.8
│ ├── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
│ └── ✕ unmet peer @univerjs/sheets-conditional-formatting@0.1.8: found 0.1.7
├─┬ @univerjs/sheets-data-validation 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/sheets-find-replace 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/sheets-formula 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/sheets-numfmt 0.1.8
│ ├── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
│ └── ✕ unmet peer @univerjs/engine-numfmt@0.1.8: found 0.1.7
├─┬ @univerjs/sheets-ui 0.1.8
│ ├── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
│ └── ✕ unmet peer @univerjs/engine-numfmt@0.1.8: found 0.1.7
├─┬ @univerjs/ui 0.1.8
│ └── ✕ unmet peer @wendellhu/redi@^0.13.3: found 0.13.0
├─┬ @univerjs/network 0.1.7
│ └── ✕ unmet peer @univerjs/core@0.1.7: found 0.1.8
└─┬ @univerjs/sheets-conditional-formatting 0.1.7
  ├── ✕ unmet peer @univerjs/core@0.1.7: found 0.1.8
  ├── ✕ unmet peer @univerjs/engine-formula@0.1.7: found 0.1.8
  ├── ✕ unmet peer @univerjs/engine-render@0.1.7: found 0.1.8
  └── ✕ unmet peer @univerjs/sheets@0.1.7: found 0.1.8

**Comment by jikkai** [comment]
It seems that some of your dependencies have not been updated to 0.1.8. Please check it yourself.
