### ISSUE TITLE
[Bug] Quickstart link 404

### ISSUE THREAD

**Issue by tino** [dream-num/univer#2105]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

Website

### Reproduction link

See the QuickStart link under “What’s Next” on [this page](https://univer.ai/guides/introduction/), it leads to https://univer.ai/guides/quickstart, which shows an nginx 404. 

### Expected behavior

-

### Actual behavior

-

**Comment by jikkai** [comment]
Thank you for your feedback and for bringing this issue to our attention. The correct link should indeed be https://univer.ai/guides/quick-start/. This is a known issue, and we apologize for any inconvenience caused.

As we are currently in the process of restructuring our official website and documentation, we have decided to temporarily postpone fixing this issue. We expect the new documentation pages to be released **within the next two weeks**.

We appreciate your understanding and patience during this transition period. Rest assured that we are working diligently to provide you with an improved and seamless experience :)
