### ISSUE TITLE
[Bug] why does the @univerjs/engine-render npm bundle have node.js api?

### ISSUE THREAD

**Issue by LogikMeister** [dream-num/univer#2122]
### Before you submit this issue, have you checked the following

- [x] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.8

### Reproduction link

Occurs when building with Rspack resources. 
使用Rspack打包构建时发生.
![image](https://github.com/dream-num/univer/assets/59829345/fc7647f6-cc31-4fa1-9d19-29311f4a1247)

### Expected behavior

Can someone explain why there are node-related APIs in packaged products? Although it does not affect the use, there will be a page error prompt box every time it is refreshed.
有人能解释一下，打包产物中为什么会有node相关的api呢。虽然不影响使用，但是每次刷新，会有页面错误提示框。

### Actual behavior

```
File: ./node_modules/.pnpm/@univerjs+engine-render@0.1.8_@univerjs+core@0.1.8_@wendellhu+redi@0.13.3_rxjs@7.8.1/node_modules/@univerjs/engine-render/lib/es/index.js
  × Resolve error: Can't resolve 'fs' in '/**/node_modules/.pnpm/@univerjs+engine-render@0.1.8_@univerjs+core@0.1.8_@wendellhu+redi@0.13.3_rxjs@7.8.1/node_modules/
  │ @univerjs/engine-render/lib/es'
        ╭─[102877:1]
 102877 │         } else console.warn("Font file could not be downloaded. Try using a different browser.");
 102878 │     } else {
 102879 │         var u = require("fs"), l = Iv(n);
        ·                 ─────────────
 102880 │         u.writeFileSync(r, l);
 102881 │     }
        ╰────
```

**Comment by jikkai** [comment]
https://github.com/dream-num/univer/discussions/2033

**Comment by jikkai** [comment]
Fixed in https://github.com/dream-num/univer/pull/2278
