### ISSUE TITLE
[Bug] When importing a document with data validation set but not edited, and adding rows and columns, the selection within the data validation will change accordingly.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2132]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、框选B1单元格新增数据验证
2、不在单元格内输入内容直接导出
3、导入该表后在B1单元格插入列
4、观察数据验证内的应用范围

### Expected behavior
预期是新增列到B1时应用范围不变嘛？

### Actual behavior

新增B1列时，应用范围显示为C1
样张：https://staging.univer.plus/?unit=zE36he-kR6O41AUPpcJNQw&type=2&subunit=uni1
![image](https://github.com/dream-num/univer/assets/167171356/9324bba8-ee3d-4b27-ad25-94207241f45e)

**Comment by DR-Univer** [comment]
这个问题应该是ref的变更文本，与导入导出无关
