### ISSUE TITLE
[Bug] The table freezes after importing

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2140]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、样张：
[项目甘特图.xlsx](https://github.com/dream-num/univer/files/15161012/default.xlsx)

### 预期行为

导入后不卡？加载时间短一点？

### 实际行为

子表显示如截图，加载时间很久
![image](https://github.com/dream-num/univer/assets/154207126/71fecc5d-3970-4a7e-8627-0a8bc3d86bd5)
[2024_4_30 16_50_07 commands.json](https://github.com/dream-num/univer/files/15160841/2024_4_30.16_50_07.commands.json)
[2024_4_30 16_50_07 video.webm](https://github.com/dream-num/univer/assets/154207126/0677c4c9-ee68-4a5c-a4f0-cb11c0450d7b)

**Comment by DR-Univer** [comment]
@Dushusir 条件格式中的公式太多导致卡顿，可以看看

**Comment by Dushusir** [comment]
由于公式插件 UniverFormulaEnginePlugin 注册时没有配置  notExecuteFormula:  true 导致主线程也在计算增加了耗时

出问题的链接：https://staging.univer.plus/sheet/?type=2&unit=RVrqpGv2TaC96afVS4SdxQ&subunit=uni2


类似的问题：https://staging.univer.plus/sheet/?type=2&unit=9xzzYbBmQ1qb04jpTTTIow&subunit=uni1
条件格式设定了两个 L4:DA198 公式格式，等于有 36660 个公式需要计算，属于正常的计算过程
