### ISSUE TITLE
[Bug] When filtering is set to condition = not empty, the filtering results are displayed incorrectly.

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2142]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

staging

### Reproduction link

特定样张特定选区范围问题，无复现路径

### Expected behavior

筛选后结果正常

### Actual behavior

筛选后结果有误
样张：https://staging.univer.plus/?unit=T0wjUPp3QmOrnrTwmVmXPg&type=2&subunit=sheet-1

**Comment by wzhudev** [comment]
@oumomomo Please provide screen cast with this issue.

**Comment by QinHang-Git** [comment]
你好  我想问下 我的UI面板中没有筛选功能，请问您是如何开启筛选功能的呢？
Hello, I would like to ask if there is no filtering function in my UI panel. How did you enable the filtering function?

**Comment by jikkai** [comment]
The issue seems to have expired, temporarily closing for now.
