### ISSUE TITLE
[Bug] The table content displays incorrectly after deleting a subtable

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2145]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

staging

### 复现链接

1、表格中有sheet1、sheet2
2、删除sheet1

### 预期行为

删除后显示下一个子表sheet2的内容

### 实际行为

仍显示sheet1

https://github.com/dream-num/univer/assets/154207126/500b9a9e-5440-4ee3-b04f-c104e2255513

**Comment by Dushusir** [comment]
fixed

**Comment by Dushusir** [comment]
已经修复，如有问题再 reopen
