### ISSUE TITLE
[Bug] Failed to unhide table

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2146]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

取消已经隐藏的子表

### 预期行为

可以取消隐藏

### 实际行为

取消隐藏失败

**Comment by Dushusir** [comment]
已经修复，如有问题再 reopen
