### ISSUE TITLE
[Bug] After exporting and then importing the conditional formatting data bar, the color color changes.

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2149]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

样张：https://dev.univer.plus/sheet/?unit=3k-KKwDGRmKubG98d9hfBg&type=2&subunit=yVg31OA238Taky-MpUl-b
1、导出样张后再导入

### 预期行为

数据条配色一致
![image](https://github.com/dream-num/univer/assets/154207126/78cea110-09f8-485f-b6bb-a640b1ed516c)

### 实际行为

导入后的表格：https://dev.univer.plus/sheet/?unit=KvR9TaTrTsa73KaGAKjkVA&type=2&subunit=uni1
1、导入后数据条配色如截图、导出是黄绿配色，导入后是白绿配色
![image](https://github.com/dream-num/univer/assets/154207126/97b4f570-2526-4839-8567-48ecc1530e63)

2、导出后再导入，规则的顺序反了（这个是否处理？）
![image](https://github.com/dream-num/univer/assets/154207126/d73b33dc-12a3-4798-a49e-ee962ca3894a)

**Comment by DR-Univer** [comment]
https://staging.univer.plus/sheet/?unit=lYDE7lt0Tdu_f4ErIJO6zQ&type=2&subunit=S34gwbZJNxgOXAuo3BEXN  

我用这个链接无法复现，是否还有其他步骤

**Comment by zhaolixin7** [comment]
> https://staging.univer.plus/sheet/?unit=lYDE7lt0Tdu_f4ErIJO6zQ&type=2&subunit=S34gwbZJNxgOXAuo3BEXN
> 
> 我用这个链接无法复现，是否还有其他步骤
 @DR-Univer  可以用新的链接复现（上面的链接已更新），之前的表格无权限打开了

**Comment by zhaolixin7** [comment]
@DR-Univer 1、导出后再导入数据条颜色不对2、全部规则顺序与原表相反https://dev.univer.plus/sheet/?unit=3k-KKwDGRmKubG98d9hfBg&type=2&subunit=yVg31OA238Taky-MpUl-b
![image](https://github.com/user-attachments/assets/57ce9b8d-812f-4c75-89f6-7d6cb32003fb)

**Comment by zhaolixin7** [comment]
在pro仓库提给新的模块onwer
