### ISSUE TITLE
[Bug] Conditional Formatting - The checkbox for reversing the order of the icons in the icon set does not show the checked state

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2157]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、选择条件格式-图标集
2、勾选按反转次序

### Expected behavior

点击复选框实际会生效，但不会展示勾选状态
![image](https://github.com/dream-num/univer/assets/167171356/8a204538-2a09-4030-bf0f-81e4742f33b7)

### Actual behavior

点击复选框实际会生效，会展示勾选状态

**Comment by Gggpound** [comment]
这个不会持久化，只是个临时的工具函数，帮你反转图例顺序
