### ISSUE TITLE
[Bug] Data validation-check box problem collection

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2162]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

staging

### Reproduction link

问题1、设置了未选中值后再删除未选中值保存时会有报错提示
操作步骤：
1、新增数据验证，条件类型选择复选框
2、勾选在单元格内使用自定义值
3、填写选中值，不填写未选中值点击确认
4、再次点击刚刚保存的数据验证
5、删除选中值的内容点击确认

问题2、勾选在单元格内使用自定义值，当选中值=未选中值时，复选框无法取消勾选
操作步骤：
1、数据验证内选择复选框，勾选在单元格内使用自定义值
2、设置选中值=未选中值点击确定
3、点击复选框

### Expected behavior

问题1：
预期是不会报错？还是报错？ 新建时不输入值也可以正常保存

问题2：
有错误码提示选中值与未选中值分别对应不同的值

### Actual behavior

问题1、
新建时不输入值可以正常保存，新建时输入值保存后再次删掉会有错误提示
[2024_5_6 16_36_08 video.webm](https://github.com/dream-num/univer/assets/167171356/03dc9ebe-738e-4381-a820-b7e84bcab37b)

问题2、
无错误提示，当选中值=未选中值时复选框无法取消勾选
[2024_5_6 16_42_19 video.webm](https://github.com/dream-num/univer/assets/167171356/7b9c8dec-5bc2-47fd-aeb2-8a7cecc60380)

**Comment by oumomomo** [comment]
保存自定义值再删除值，复选框会自动勾选上

预期：自定义值被删除后会报错
[2024_5_14 11_47_25 video.webm](https://github.com/dream-num/univer/assets/167171356/739e66d0-9e2f-4377-b65f-713a8bdd5c48)

**Comment by weird94** [comment]
> 保存自定义值再删除值，复选框会自动勾选上
> 
> 预期：自定义值被删除后会报错 实际：自定义值被删除后还是可以被保存，并且自动勾选复选框 [2024_5_14 11_47_25 video.webm](https://github.com/dream-num/univer/assets/167171356/739e66d0-9e2f-4377-b65f-713a8bdd5c48)

这个是符合预期的
