### ISSUE TITLE
[Bug] When setting the background color of the frame selection range, the background color of the cell is missing when clicking repeatedly

### ISSUE THREAD

**Issue by oumomomo** [dream-num/univer#2165]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

dev

### Reproduction link

操作步骤：
1、框选范围设置背景色
2、在框选范围内多次点击单元格

### Expected behavior

背景色不会缺失，会完整展示

### Actual behavior

背景色会在多次点击中缺失
[2024_5_6 20_21_43 video.webm](https://github.com/dream-num/univer/assets/167171356/1298b3e8-94b5-4cd5-b0e3-0975f5f0aca9)

**Comment by lumixraku** [comment]
Both Chrome and Edge on windows can not reproduce this issue
