### ISSUE TITLE
[Bug] When copying web page content and pasting it into a document, the font displays "apple-system"

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#2179]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

staging

### 复现链接

外部链接：github、Google中的内容
1、复制外部网页中的内容粘贴到文档

### 预期行为

确认是否符合？google粘贴后字体显示arial
365 word
![image](https://github.com/dream-num/univer/assets/154207126/3ea5dee3-d5df-489a-a35a-e5c21bc2ffcf)

### 实际行为

显示apple- system”
<img width="1336" alt="image" src="https://github.com/dream-num/univer/assets/154207126/54cd206f-5efa-4e9b-be7d-2bd74c347c75">

**Comment by ybzky** [comment]
符合预期 解析出来的字体就是apple默认字体
