### ISSUE TITLE
[Bug] When copying a cell and pasting it into another blank cell, the font style is abnormal.

### ISSUE THREAD

**Issue by chenjing0823** [dream-num/univer#2184]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.9

### 复现链接

https://univer.work/playground/?title=Vue%203

### 预期行为

数据应该正常

### 实际行为

实际上，默认情况下，仅给单元格输入文本内容。复制该单元格粘贴到其他空白格，字体大小从11变到了10，同时出现了边框。再复制粘贴后的单元格，粘贴到另一处，字体大小从10变成了5。
![image](https://github.com/dream-num/univer/assets/34295555/f76521cf-df1d-488d-8912-1808ca4af42a)

**Comment by chenjing0823** [comment]
0.1.7是正常的

**Comment by ybzky** [comment]
已经修复
