### ISSUE TITLE
[Bug] After activating a cell, the page changes to the end when the left key of the keyboard direction key is pressed.

### ISSUE THREAD

**Issue by chenjing0823** [dream-num/univer#2187]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.9

### 复现链接

https://univer.work/playground/?title=Vue%203

### 预期行为

实际应该是单元格内光标的左移动

### 实际行为

![image](https://github.com/dream-num/univer/assets/34295555/9097fec6-8f2e-42c6-9df2-37fa4b47058a)

![image](https://github.com/dream-num/univer/assets/34295555/f6f94085-f2b9-47f3-b6d7-ea6aec301664)

如果在激活后，通过鼠标将光标移动到非最后位置，键盘方向键又不会又上述问题

**Comment by jikkai** [comment]
This is an intentional design choice for the user interaction and not a bug.
