### ISSUE TITLE
[Bug] The umd case of the univer.ai website cannot be run

### ISSUE THREAD

**Issue by wanghaiyang1221** [dream-num/univer#2205]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

最新版

### 复现链接

![image](https://github.com/dream-num/univer/assets/37435363/de8430be-fac0-4303-abc8-674dcfc64a56)

### 预期行为

正常展示

### 实际行为

无法渲染

### 运行环境

Chrome

**Comment by jikkai** [comment]
Thanks for your feedback. The demo has been fixed.
https://stackblitz.com/~/github.com/awesome-univer/sheets-umd-demo
