### ISSUE TITLE
[Bug]When editing data pasted into UniverSheet from Excel, the saved result prints an error, changing from a normal number to undefined.

### ISSUE THREAD

**Issue by zhongxu-Sun** [dream-num/univer#2207]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.7

### Reproduction link

[五一旅游.xlsx](https://github.com/dream-num/univer/files/15260848/default.xlsx)
This is the Excel data I want to paste into UniverSheet。

### Expected behavior

Edit the data imported from Excel to UniverSheet and produce a properly updated CellData.

### Actual behavior

Paste data from Excel to UniverSheet, the printed data cellData is correct, but after editing one of the data items, print cellData data again, and the changed data becomes undefined.

**Comment by FHamster** [comment]
我也遇到了，升级到v0.17版本了。但是粘贴进Univer之后，一些数值编辑之后就变成富文本了，我需要里面数值进行编辑并且获取它。

**Comment by ybzky** [comment]
https://github.com/dream-num/univer/pull/2957. This has been fixed in this PR
