### ISSUE TITLE
[Feature] Related to conditional format

### ISSUE THREAD

**Issue by xlchan6** [dream-num/univer#2211]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

I have encountered a problem. office-excel judges the application of icon set in conditional format, but it does not take effect in univer. I do not expect users to control it through the browser, but I need to conditionally format the data so that users can read it directly

### 解决方案

Conditional formatting can be configured using ts source data or through the api provided by univer

**Comment by jikkai** [comment]
Please provide more details of your requirements.
For now, we will close this issue, but feel free to reopen it at any time.

---

你可以用中文详细描述一下你的需求，我们暂时会关闭这个 issue，欢迎你随时再次打开
