### ISSUE TITLE
[Bug] low node version depends error "export 'bufferTime' (imported as 'Ei') was not found in 'rxjs'

### ISSUE THREAD

**Issue by yooyea** [dream-num/univer#2220]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.10

### Reproduction link

An error is reported for dependency installation
![image](https://github.com/dream-num/univer/assets/66212485/4332fc1e-ad0a-48b2-b539-893f5d4a4214)

Node: v8.17 (this version only, this version of NPM can only be up to v6)

Self-installation error message:
![image](https://github.com/dream-num/univer/assets/66212485/e068a1c8-320d-4ae6-a897-410d8b91aa13)

OK, then don't install '@wendellhuredireact-bindings'

Then when starting rxjs-related errors:

![image](https://github.com/dream-num/univer/assets/66212485/02e6a71b-4219-4fd9-9017-092a09a6accf)

However, the project was able to start normally

However, after starting, the console gives an error:

![image](https://github.com/dream-num/univer/assets/66212485/0d19b711-2006-4912-a79f-40f231e10a0b)

![image](https://github.com/dream-num/univer/assets/66212485/6a1bb1c6-8800-4ec1-9cb2-e26089e0e9db)

### Expected behavior

use fine

### Actual behavior

log error, it's bad

### System information

Node: v8.17.0
NPM: v6.13.4

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/troubleshooting#why-do-i-get-an-error-outputting-that-could-not-resolve-dependencies-when-i-use-npm-or-yarn-to-install

**Comment by jikkai** [comment]
duplicate of #2152

**Comment by yooyea** [comment]
> https://univer.ai/guides/sheet/troubleshooting#why-do-i-get-an-error-outputting-that-could-not-resolve-dependencies-when-i-use-npm-or-yarn-to-install

When I submitted this issue, I already installed the dependencies and configured webpack according to the scheme mentioned in this article

**Comment by yooyea** [comment]
I suspect it's the rxjs version is wrong, I see that univer depends on rxjs@7, but I found that the dependencies after npm i univer are rxjs@6 in package-lock.json, so I installed rxjs@7 in the main project, and now it works, I think maybe univer needs to force a declaration to use version rxjs@7

**Comment by jikkai** [comment]
Based on the system information you provided, your npm version is 6.13.4. If your npm version is below 7, you need to ensure manually that the versions of peer dependencies you install are correct.

**Comment by yooyea** [comment]
> Based on the system information you provided, your npm version is 6.13.4. If your npm version is below 7, you need to ensure manually that the versions of peer dependencies you install are correct.

I may not have made it clear, I have installed the dependencies manually, but I still get an error (last image), so I tried upgrading the version of rxjs and it works

**Comment by jikkai** [comment]
> > Based on the system information you provided, your npm version is 6.13.4. If your npm version is below 7, you need to ensure manually that the versions of peer dependencies you install are correct.
> 
> I may not have made it clear, I have installed the dependencies manually, but I still get an error (last image), so I tried upgrading the version of rxjs and it works

What I mean is that if you manually instal dependencies and later versions of Univer update the peer dependencies, you might face the same issue again. Please ensure that your npm version is above 7 as much as possible.

**Comment by yooyea** [comment]
> > > Based on the system information you provided, your npm version is 6.13.4. If your npm version is below 7, you need to ensure manually that the versions of peer dependencies you install are correct.根据您提供的系统信息，您的 npm 版本为 6.13.4。如果您的 npm 版本低于 7，则需要手动确保安装的对等依赖项版本正确无误。
> > 
> > 
> > I may not have made it clear, I have installed the dependencies manually, but I still get an error (last image), so I tried upgrading the version of rxjs and it works我可能没有说清楚，我已经手动安装了依赖项，但我仍然收到错误（最后一张图像），所以我尝试升级 rxjs 的版本并且它可以工作
> 
> What I mean is that if you manually instal dependencies and later versions of Univer update the peer dependencies, you might face the same issue again. Please ensure that your npm version is above 7 as much as possible.我的意思是，如果您手动安装依赖项，并且 Univer 的更高版本更新了对等依赖项，您可能会再次遇到同样的问题。请确保您的 npm 版本尽可能高于 7。

Okay I see, thanks a lot
