### ISSUE TITLE
[Feature] Existing tool methods can support dynamic configuration.

### ISSUE THREAD

**Issue by chenjing0823** [dream-num/univer#2222]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

默认目前的工具栏为官方提供的工具栏，无法选择配置哪些操作或者不配置哪些操作

### 解决方案

例如下图，我可以选择加载除了文字旋转以外的所有功能，或者我可以选择不加载文字旋转功能
![image](https://github.com/dream-num/univer/assets/34295555/0a1e6c7e-5da4-4aa6-afad-375001a0253a)

**Comment by jikkai** [comment]
Duplicate of #1343
