### ISSUE TITLE
[Bug] pnpm run dev:sheet 运行无法编辑

### ISSUE THREAD

**Issue by fulus06** [dream-num/univer#224]
### 初始清单

- [x] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev分支

### 复现步骤

```shell
git clone https://github.com/dream-num/univer.git 
pnpm i
pnpm run dev:sheet
```

### 预期行为

可展示、可编辑

### 实际行为

表格可点击，可更改样式，但不可输入内容

![image](https://github.com/dream-num/univer/assets/12890684/a0df48ff-518c-4fc6-9ea5-09168aced974)

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

esbuild

**Comment by jikkai** [comment]
related to #92
