### ISSUE TITLE
[Bug] InsertRowCommand not work, cellValue not showing

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2243]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.7

### Reproduction link

![image](https://github.com/dream-num/univer/assets/67748948/48996216-41ac-4647-85cf-dc599f27e8d4)

### Expected behavior

To execute InsertRowCommand that can be work. Just insert row but not insert cellValue.

### Actual behavior

execute InsertRowCommand can not work.

**Comment by Dushusir** [comment]
Thank you for your question, we will fix it as soon as possible
