### ISSUE TITLE
[Bug] When copying formula data to another sheet, an error occurs.

### ISSUE THREAD

**Issue by ljcoder2015** [dream-num/univer#2297]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.11

### Reproduction link

https://univer.ai/examples/sheets

### Expected behavior

![copy_bug](https://github.com/dream-num/univer/assets/15226918/e6f0bb96-74de-498f-bf5e-219112d7892e)

1. copy the data
2. When pasting data into another sheet, the data is incorrect. Alice's total is 0, but it should be 207.

1. copy the data
2. When pasting data into current sheet, it is working.
3. copy the new data.
4. When pasting data into another sheet, an error occurs.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getChildren')
```

### Actual behavior

![copy_bug](https://github.com/dream-num/univer/assets/15226918/e6f0bb96-74de-498f-bf5e-219112d7892e)

1. copy the data
2. When pasting data into another sheet, the data is incorrect. Alice's total is 0, but it should be 207.

1. copy the data
2. When pasting data into current sheet, it is working.
3. copy the new data.
4. When pasting data into another sheet, an error occurs.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getChildren')
```

**Comment by ybzky** [comment]
The absolute position is used in the formula, so is as expected
