### ISSUE TITLE
[Bug]  Formula entry remains stuck when clicking another cell 

### ISSUE THREAD

**Issue by IsabellaSampaio** [dream-num/univer#2327]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [x] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.12

### Reproduction link

https://univer.ai/examples/sheets

https://github.com/dream-num/univer/assets/71940799/8d727a8c-10fc-48a7-ad00-4bb853996d3f

In the video, I attempt to delete the formula, but it doesn't work unless I select the cell that actually contains it. Additionally, I try clicking on a different cell to see if the formula will disappear, but it doesn't. This issue was initially encountered while using the playground feature.

### Expected behavior

After selecting a cell and typing a formula the same should not appear on other empty cells, only on the cell selected previously. 

### Actual behavior

When clicking a cell and typing a formula, if the user clicks on an empty cell the formula stays there, even tho it was typed on a different cell. 

### System information

Tried on both Windows 10 and MacOS Sonoma 14.5, in both cases I got the same problem.

**Comment by Dushusir** [comment]
The cells can be saved normally when switching cells. If there are still problems, reopen the issue
![selection-save](https://github.com/dream-num/univer/assets/26371161/5c919a7d-a2c7-47d6-b510-c0003f7de47d)
