### ISSUE TITLE
[Feature] Custom formula supports asynchronous requests

### ISSUE THREAD

**Issue by guinanlin** [dream-num/univer#2331]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

问题1: 关于自定义函数的话, 在处理自定义函数的过程中 , 是要通过接口读取数据的, 但是这个是一个异步的请求. 我尝试改为 同步的, 
改了很多种方式, 在univer这边都没法接收. 或者就是报 promise的Uncaught (in promise) TypeError: s.isReferenceObject is not a function,

建议2:  对于自定义函数, 数据请求之后, 一般为数组, 这个数组的封装过程现在过于复杂.  

在微信群做了沟通, 润泽建议提交一个feature. 

感谢你们为univer做的贡献和付出, 感谢.

![cb5676a2321909624009eee52da983f](https://github.com/dream-num/univer/assets/44794953/4eab0b9d-5afc-435d-93aa-0387c5d28b91)

### 解决方案

1, 建议对于override calculate 能支持 同步和异步.  override calculate(docname: StringValueObject): ArrayValueObject { 

2,  数组的封装过程过于复杂, 希望能提供函数, 输入为 二维数组, 输出为univer的格式. 现在的封装过程为:

```
 console.log("转换后的数据",data);
                let result: BaseValueObject[][] = data.map(fieldRow => 
                        fieldRow.map(field => new StringValueObject(field))
                    ); 

                // 构建 ArrayValueObject 的数据结构
                const arrayValueObjectData: IArrayValueObject = {
                    calculateValueList: result,
                    rowCount: data.length,
                    columnCount: data[0].length,
                    unitId: '',
                    sheetId: '',
                    row: -1,
                    column: -1,
                };                    
                console.log('封装后的数据',arrayValueObjectData);                 
                o = ArrayValueObjectClass.create(arrayValueObjectData);
```

**Comment by Dushusir** [comment]
Thank you for your suggestion, we will give you a solution as soon as possible

**Comment by Dushusir** [comment]
@guinanlin  内部已经有 AsyncArrayObject 支持异步，可以尝试下，参考这里 https://github.com/dream-num/univer/blob/a6761dda2cd39e11de594b1935f2847f94283ec5/packages/engine-formula/src/functions/logical/makearray/index.ts#L62C22-L62C23

**Comment by Dushusir** [comment]
1. 已有 AsyncArrayObject 支持异步，参考Makearray的写法 https://github.com/dream-num/univer/blob/a6761dda2cd39e11de594b1935f2847f94283ec5/packages/engine-formula/src/functions/logical/makearray/index.ts#L62C22-L62C23

2. ArrayValueObject 新增静态方法 createByArray来支持从数组创建

以上修复关注 PR https://github.com/dream-num/univer/pull/2342
