### ISSUE TITLE
Is it possible to provide a global monitoring function to transmit the latest overall table data when the table data changes? [Feature]

### ISSUE THREAD

**Issue by mindsfsdfwe** [dream-num/univer#2337]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

onCommandExecuted 这个是所有的动作监听，而无法知道哪些会变动数据

当动作能改变表格的时候 才触发这个监听，而不是选中表格 或者其他无关表格数据变动的。

例如，样式变动，值变动等 给个全局的监听方法，能告知表格数据变动了

### 解决方案

        univerAPI.addDataChangeListeners((command,data)=>{
            console.log('最新表格数据',data)
        }}

**Comment by jikkai** [comment]
The `onCommandExecuted` listens for all commands, including those that modify data. You will need to determine the type of command based on the command's id by yourself.
