### ISSUE TITLE
[Bug] sheet page have out of memory issue

### ISSUE THREAD

**Issue by fantasy-zeng** [dream-num/univer#2344]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

all versions

### Reproduction link

url: https://univer.ai/examples/sheets
reproduce: continue to zoom in and out

### Expected behavior

memory keeps rising and falling by a certain amount

### Actual behavior

memory keeps going up and it doesn't come down
<img width="1209" alt="image" src="https://github.com/dream-num/univer/assets/11945569/7a8c6f44-92f8-4f7b-bcb8-325827da3d4b">
<img width="1202" alt="image" src="https://github.com/dream-num/univer/assets/11945569/ec0b7b6c-7a60-4f80-ab13-a65cfe6ac224">

**Comment by fantasy-zeng** [comment]
the memory growth is obvious in safari
<img width="1660" alt="image" src="https://github.com/dream-num/univer/assets/11945569/5c7a17a8-2fb5-4fa1-9137-4467aa959f65">

**Comment by fantasy-zeng** [comment]
> the memory growth is obvious in safari <img alt="image" width="1660" src="https://private-user-images.githubusercontent.com/11945569/335033696-5c7a17a8-2fb5-4fa1-9137-4467aa959f65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTg1ODksIm5iZiI6MTcxNzA1ODI4OSwicGF0aCI6Ii8xMTk0NTU2OS8zMzUwMzM2OTYtNWM3YTE3YTgtMmZiNS00ZmExLTkxMzctNDQ2N2FhOTU5ZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODIxMTk1Njk1YTMwODA1MWZjODFmZGZkMWZkOGE4ZGFlZDkzODg0ZjA4NDNkNTI4OTFkZjFmMTI4Yjg0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9rmz-DPHWpQ388Pk2HnaEecFyYqSDKWd3jidxad_rKw">



I found that accumulating too many Message Channels caused memory to keep increasing in Safari. Manually releasing them solved the issue, which alleviated the rapid memory increase and helped reduce interaction lag and crashes in Safari. However, this doesn't completely eliminate the risk of memory leaks. Interacting with the page continuously adds objects, causing memory to keep increasing. This needs to be handled separately.

<img width="682" alt="image" src="https://github.com/dream-num/univer/assets/11945569/f69e7553-dfd5-4407-a56c-971c275a769a">

**Comment by DR-Univer** [comment]
We have recently undertaken a refactor of our rendering layer, which has resulted in numerous improvements. Please try it out after the release of version 0.1.13.

**Comment by Dushusir** [comment]
> > the memory growth is obvious in safari <img alt="image" width="1660" src="https://private-user-images.githubusercontent.com/11945569/335033696-5c7a17a8-2fb5-4fa1-9137-4467aa959f65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTg1ODksIm5iZiI6MTcxNzA1ODI4OSwicGF0aCI6Ii8xMTk0NTU2OS8zMzUwMzM2OTYtNWM3YTE3YTgtMmZiNS00ZmExLTkxMzctNDQ2N2FhOTU5ZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODIxMTk1Njk1YTMwODA1MWZjODFmZGZkMWZkOGE4ZGFlZDkzODg0ZjA4NDNkNTI4OTFkZjFmMTI4Yjg0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9rmz-DPHWpQ388Pk2HnaEecFyYqSDKWd3jidxad_rKw">
> 
> I found that accumulating too many Message Channels caused memory to keep increasing in Safari. Manually releasing them solved the issue, which alleviated the rapid memory increase and helped reduce interaction lag and crashes in Safari. However, this doesn't completely eliminate the risk of memory leaks. Interacting with the page continuously adds objects, causing memory to keep increasing. This needs to be handled separately.
> 
> <img alt="image" width="682" src="https://private-user-images.githubusercontent.com/11945569/335111572-f69e7553-dfd5-4407-a56c-971c275a769a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTc5NTEsIm5iZiI6MTcxNzE1NzY1MSwicGF0aCI6Ii8xMTk0NTU2OS8zMzUxMTE1NzItZjY5ZTc1NTMtZGZkNS00NDA3LWE1NmMtOTcxYzI3NWE3NjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDEyMTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjkwODQwMzNhNTQ1MThkOGM0NDc2ZDZiZDYxMzhkMWI1YjU1MWI0MGMxZTI1ZTc2MDY2MzkwM2QyYmQ0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tsGmZb9qEdrwhJx-0bwexsWRY6MguCetTHCEiaDddPg">

We noticed the issue of the release of Message Channel resource, and will be fixed as soon as possible
