### ISSUE TITLE
[Bug] Site does not work

### ISSUE THREAD

**Issue by FoxyFoxRed** [dream-num/univer#2407]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

-

### Reproduction link

https://univer.ai/guides/sheet/getting-started/quickstart

### Expected behavior

Link is open without 404 error

### Actual behavior

I click to link and get 404 error

**Comment by jikkai** [comment]
Duplicate of #2400
