### ISSUE TITLE
Using UMD to introduce univer, there is a display problem in the last row of the editing table[Bug] 

### ISSUE THREAD

**Issue by Robert-Du0001** [dream-num/univer#2409]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.13

### Reproduction link

There is a full example:  https://codesandbox.io/p/sandbox/dreamy-violet-9wwz7p

### Expected behavior

The last line should also display normally when editing.

### Actual behavior

An error occurs on the last line.

![image](https://github.com/dream-num/univer/assets/29976859/3c620e42-36f8-45e2-9858-acd3a3f7d440)

### System information

Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527

I tried to use Firefox  (version 126.0.1), but the result is the same.

**Comment by Jocs** [comment]
This issue can't be reproduced, I closed it first, if there are still problems, please comment, reopen this issue
