### ISSUE TITLE
[Bug] range api setValue

### ISSUE THREAD

**Issue by chenyuan4x7** [dream-num/univer#2411]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.13

### 复现链接

`univerAPI.value = FUniver.newAPI(univer);
  /*const range = {
    startRow: 1,
    startColumn: 1,
    endRow: 1,
    endColumn: 1,
  };
  univerAPI.value.executeCommand('sheet.command.set-range-values', {
    value: 'Test Univer',
    range
  });*/
  const activeWorkbook = univerAPI.value.getActiveWorkbook();
  const activeSheet = activeWorkbook.getActiveSheet();
  const range = activeSheet.getRange(0, 0, 2, 2);
  range.setValue('Test Univer');
`
[https://sheetsvitedemo-s2r2--5173--12d46890.local-credentialless.webcontainer.io](url)

### 预期行为

setValue the console has no error message [Cannot destructure property 'skeleton' of 'n.getCurrent(...)' as it is undefined.]
setValue 可以正常赋值, 控制台无报错提示  [Cannot destructure property 'skeleton' of 'n.getCurrent(...)' as it is undefined.] 

### 实际行为

setValue  the console prompts an error; [Cannot destructure property 'skeleton' of 'n.getCurrent(...)' as it is undefined.]
setValue 可以正常赋值, 控制台提示报错; [Cannot destructure property 'skeleton' of 'n.getCurrent(...)' as it is undefined.]``
![5d4a09679c62504573bcf65da35d3b8](https://github.com/dream-num/univer/assets/57245313/b224abf7-c675-444d-b88d-679fc3fdaf5d)

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please provide a valid link.

**Comment by chenyuan-tanzhuang** [comment]
> 请提供有效链接。

https://stackblitz.com/edit/github-i8z5an?file=src%2Fcomponents%2FUniverSheet.vue

**Comment by hexf00** [comment]
@chenyuan-tanzhuang  I found that calling `setValue` within `setTimeout` does not trigger an error message. If this helps you, I will further investigate the issue.

**Comment by chenyuan-tanzhuang** [comment]
> @chenyuan-tanzhuang 我发现`setValue`在内部调用`setTimeout`不会触发错误消息。如果这对您有帮助，我会进一步调查该问题。
`setTimeout` usable, but each used once `setValue`  needs to be wrapped `setTimeout`?
`setTimeout`是可以的, 但是每个地方使用 `setValue` 都需要 `setTimeout`进行包裹吗

**Comment by hexf00** [comment]
> `setTimeout` usable, but each used once `setValue`  needs to be wrapped `setTimeout`?
Immediately calling setValue after instance creation requires wrapping it in `setTimeout(() => {}, 0)`. This is just a temporary measure, and I am investigating the cause. After the instance is created, if it is an asynchronous operation (such as responding to a user click event), there is no need to add `setTimeout`.

**Comment by chenyuan4x7** [comment]
> > `setTimeout` usable, but each used once `setValue`  needs to be wrapped `setTimeout`?
> 
> Immediately calling setValue after instance creation requires wrapping it in `setTimeout(() => {}, 0)`. This is just a temporary measure, and I am investigating the cause. After the instance is created, if it is an asynchronous operation (such as responding to a user click event), there is no need to add `setTimeout`.

thank you !
