### ISSUE TITLE
[Bug] Failing To Hide Menu Items

### ISSUE THREAD

**Issue by tannerTurba** [dream-num/univer#2419]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.13

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

I am interested in hiding a couple of the menu items, so I have followed the advice that is given on the [Extending UI](https://univer.ai/guides/sheet/customization/ui#customizing-menu-items-hiding-menu-items) page of the documentation, which I have included a screenshot of below. 

![image](https://github.com/dream-num/univer.ai/assets/95774198/a6481e86-87c4-4d86-9035-a31f58b0a2eb)

![image](https://github.com/dream-num/univer.ai/assets/95774198/805353b7-22b3-4d31-b27e-e5393e9cbe87)
(A snippet of my code)

I expected the format painter, text color, and bold menu icons to be hidden.

### Actual behavior

The rendered table still includes the icons that I have set to 'hidden' in the config data.

![image](https://github.com/dream-num/univer.ai/assets/95774198/927e6cff-e361-41f5-840c-dba633e8e930)

### System information

I am using vite, react, and typescript in my project. 

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1245U
    Memory: 4.61 GB / 15.69 GB
  Binaries:
    Node: 21.7.3 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.19041.4355

**Comment by jikkai** [comment]
Apologize for the inconvenience. I have already resolved this problem, and the fix will be released in version 0.1.14. 🙏

**Comment by tannerTurba** [comment]
Thank you!
