### ISSUE TITLE
[Feature] Supplement Math Formulas for Formula Engine

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#2425]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

How to contribute formulas: https://univer.ai/guides/sheet/customization/formula#how-to-add-formulas-in-formula-engine

It is highly recommended that you refer to the algorithms of similar formulas that have been implemented

https://github.com/dream-num/univer/blob/dev/packages/engine-formula/src/functions/math/function-map.ts

Especially for

ASIN
ASINH
ATAN
ATAN2
ATANH
COS

These, like Acos, already have corresponding underlying implementations in ArrayValueObject

### Solution

Formulas List:
- [ ] ACOTH
- [ ] ASIN
- [ ] ASINH
- [ ] ATAN
- [ ] ATAN2
- [ ] ATANH
- [ ] COS
- [ ] COSH
- [ ] COT
- [ ] COTH
- [ ] CSC
- [ ] CSCH

**Comment by abdelrahman830a** [comment]
@: I can solve it
