### ISSUE TITLE
[Bug] After dragging frozen rows and columns, cannot drag them back to A1

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2450]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.14

### Reproduction link

1. drag frozen rows and columns
2. cannot drag them back to A1

you can try this link, it very easy to reproduce https://univer.ai/examples/sheets

### Expected behavior

can drag them back to A1

### Actual behavior

cannot drag them back to A1

**Comment by jikkai** [comment]
https://github.com/dream-num/univer/assets/14025786/224ea84f-4235-4282-95d0-2f8bd86e87d6

Please provide a demo that reproduces the issue. In the meantime, we will close this issue. 
However, feel free to reopen it at any time once you have prepared the requested demo. We appreciate your cooperation and look forward to working with you to resolve this matter.
