### ISSUE TITLE
[Bug] When scrolling, the main extension canvas style is disordered

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2451]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.14

### Reproduction link

1. merge some cells
2. apply main  extension canvas, I drew some slashes and rect, try to hide the value
4. scroll page
5. the extension canvas is disordered, and the value is shown again.

Please see the video

https://github.com/dream-num/univer/assets/51111411/c74d7720-61b9-4c71-ac97-a9353165f31c

### Expected behavior

the extension canvas looks fine, and cover the value

### Actual behavior

the extension canvas is disordered, and the value is shown again

**Comment by jikkai** [comment]
Please update the video or provide a demo that reproduces the issue. In the meantime, we will close this issue. 
However, feel free to reopen it at any time once you have prepared the requested demo.

**Comment by huazhuwang** [comment]
https://github.com/dream-num/univer/assets/51111411/f4ba3747-1969-433d-b5dc-54ae8b8b57fc

**Comment by huazhuwang** [comment]
https://github.com/dream-num/univer/assets/51111411/4b7b3056-86a4-4eb6-beeb-0478c3b71df2

**Comment by huazhuwang** [comment]
@jikkai hi, please review the updated video
