### ISSUE TITLE
[Feature] COS Math Formula

### ISSUE THREAD

**Issue by abdelrahman830a** [dream-num/univer#2458]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Formula `Cos` is not implemented

### Solution

Implement formula COS
Reference https://support.google.com/docs/answer/3093476?sjid=13634280715965448689-EU
@abdelrahman830a: I can solve it

**Comment by Dushusir** [comment]
duplicate of https://github.com/dream-num/univer/issues/2425
