### ISSUE TITLE
[Feature] ACOTH Math Formula

### ISSUE THREAD

**Issue by abdelrahman830a** [dream-num/univer#2459]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

`ACOTH `is not implemented

### Solution

@abdelrahmanzaitoun830a: I can solve it
reference: https://support.google.com/docs/answer/9084097

**Comment by Dushusir** [comment]
duplicate of https://github.com/dream-num/univer/issues/2425
