### ISSUE TITLE
Named range

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#246]

**Comment by HeetVekariya** [comment]
Can you please elaborate that what the issues asks to perform ?

**Comment by wzhudev** [comment]
> Can you please elaborate that what the issues asks to perform ?

Named range is a feature of Microsoft Office Excel. It enables users to assign names to ranges. 
![image](https://github.com/dream-num/univer/assets/12122021/b40d2188-f565-444d-8881-71fe070d4e38)

**Comment by Dushusir** [comment]
Closed by https://github.com/dream-num/univer/pull/1737
