### ISSUE TITLE
[Feature] ASINH Formula

### ISSUE THREAD

**Issue by abdelrahman830a** [dream-num/univer#2461]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

`ASINH` Formula

### Solution

@abdelrahmanzaitoun830a: I can solve it. 
Ref: https://support.google.com/docs/answer/3093393

**Comment by Dushusir** [comment]
duplicate of https://github.com/dream-num/univer/issues/2425
