### ISSUE TITLE
[Bug] The result displayed by the custom formula is #SPILL

### ISSUE THREAD

**Issue by guinanlin** [dream-num/univer#2470]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.14

### 复现链接

1. 定义了一个自定义的函数:
```
async function asyncArrayFunction(value: BaseValueObject) {
  return new Promise((resolve: (value: ArrayValueObject) => void) => {
          getFrappeDbAll({ doctype: value.getValue(),fields1: "['valuation_method','item_code']" })  // 调用API获取所有文档
          .then(res => {
            console.info("原始数据:",res);
            return res.message.data.records;
          })
          .then(result => transformData(result))
          .then(data => {
              console.log("转换后的数据", data);
              resolve(ArrayValueObject.createByArray(data));
          })
          .catch(error => {
              console.error('Error fetching or transforming data:', error);
              throw error;  // Rethrow error to propagate it
          });
  });
}
```

2, 转换出来的data的格式在这里: https://gist.githubusercontent.com/guinanlin/c782a7cafaeb5d7f76693faa9dd0eefb/raw/405cce530ea2f750dac81714c3790e0542fdb277/custom-function-array
进行 resolve(ArrayValueObject.createByArray(data)); 的时候会报 #SPILL

3, 我已经尝试做了如下的检测:
1) 对字段里头的 null,空列, 特殊字段定义 做了 特别测试, 这些显示都没有问题.
2) 如果只是取其中的2列, 3列 也都是好的. 
是什么场景导致会取不了的呢? 

### 预期行为

需要能正常返回数据

### 实际行为

返回了 #SPILL
![image](https://github.com/dream-num/univer/assets/44794953/bd79daf1-c604-4c4c-95aa-5e0de43a2b39)

### 运行环境

Chrome

**Comment by Dushusir** [comment]
一个单元格赋值为数组公式，要求赋值范围内必须都是空单元格才能正常展示

**Comment by Dushusir** [comment]
有任何问题请再反馈，或者重开issue
