### ISSUE TITLE
[Bug] Print function is not working

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2475]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.13

### Reproduction link

1. apply print plugin， as this link https://univer.ai/zh-CN/pro/guides/sheet/features/print
2. click print icon
3. console show error, and print page is empty
 
![image](https://github.com/dream-num/univer/assets/51111411/d38ba3aa-5190-4242-95b3-e74056c3470d)
![image](https://github.com/dream-num/univer/assets/51111411/950423f2-69f6-44de-b11f-713a74bad5c4)

### Expected behavior

printer function works

### Actual behavior

console show error, and printer page is empty

**Comment by weird94** [comment]
Please upgrade `@univerjs-pro/sheets-print` to 0.1.15. For example, follow this demo https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-ivgjgd?file=package.json,src%2Fmain.ts

Notice: the plugin is changed from `SheetsPrintPlugin` to `UniverSheetsPrintPlugin`.
