### ISSUE TITLE
[Bug] freeze can not work

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2480]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.14

### Reproduction link

https://univer.ai/playground?title=React

### Expected behavior

freeze can work well.

### Actual behavior

freeze can not work. As shown in the picture
![240612 101355](https://github.com/dream-num/univer/assets/67748948/33910562-041c-4301-a8e9-f123caddd7b3)

**Comment by lumixraku** [comment]
https://github.com/dream-num/univer/pull/2833
