### ISSUE TITLE
[Bug] Abnormality occurs when introducing printing function using UMD method

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#2484]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.13

### 复现链接

![20240612145034](https://github.com/dream-num/univer/assets/170174083/67fae3b5-1d7d-4a95-8af8-cc0087fd185c)

### 预期行为

1

### 实际行为

![20240612145034](https://github.com/dream-num/univer/assets/170174083/7b1d8eee-871b-4063-8a04-2460a6967977)

### 运行环境

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
This is a known issue that will be addressed in v0.1.15. Stay tuned for the upcoming release.
