### ISSUE TITLE
[Bug] Copy the data from the page table to univerjs and display an exception

### ISSUE THREAD

**Issue by mansteinr** [dream-num/univer#2487]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.14

### 复现链接

no

### 预期行为

![image](https://github.com/dream-num/univer/assets/25771294/d5f6acdb-c4ab-4900-8fcb-cb04bb24a308)
**I copied five, but after pasting, it should show five including the header**

### 实际行为

![image](https://github.com/dream-num/univer/assets/25771294/0314bcbb-08c8-4faa-b0d8-ce046efcfa7b)
**Actually, only two were displayed**

### 运行环境

Chrome

### 系统信息

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.35 GB / 7.74 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.2.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.19041.1

**Comment by ybzky** [comment]
Can you provide a de-identified data source?

**Comment by jikkai** [comment]
Please provide a valid link to reproduce the issue. We will close this issue for now, but feel free to reopen it once you have the link ready.

**Comment by waterhydroxyl** [comment]
> Please provide a valid link to reproduce the issue. We will close this issue for now, but feel free to reopen it once you have the link ready.

我发现了[复制源](https://element-plus.org/en-US/component/table.html#striped-table)并且在univer sheet本地开发环境复现并定位根因。可以的话我打算解决该问题。
在此之外我发现使用getComputedStyle()这个DOM api在粘贴大量内容会非常耗时，我希望在PR中一并解决。
![a0d555c26a477d10a4d99b071cd5d97](https://github.com/dream-num/univer/assets/40552739/81131b0e-3157-437f-9c3c-0b86cd63a752)

**Comment by jikkai** [comment]
> > Please provide a valid link to reproduce the issue. We will close this issue for now, but feel free to reopen it once you have the link ready.
> 
> 我发现了[复制源](https://element-plus.org/en-US/component/table.html#striped-table)并且在univer sheet本地开发环境复现并定位根因。可以的话我打算解决该问题。 在此之外我发现使用getComputedStyle()这个DOM api在粘贴大量内容会非常耗时，我希望在PR中一并解决。 ![a0d555c26a477d10a4d99b071cd5d97](https://private-user-images.githubusercontent.com/40552739/339180946-81131b0e-3157-437f-9c3c-0b86cd63a752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDY3NjMsIm5iZiI6MTcxODI0NjQ2MywicGF0aCI6Ii80MDU1MjczOS8zMzkxODA5NDYtODExMzFiMGUtMzE1Ny00MzdmLTljM2MtMGI4NmNkNjNhNzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyNDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZDVhMGNlOGVmMGY5ZGU0ZmMyYzEwN2VkNzY1NWMzY2M5NzI3MmFkYTlmNDg4OThmMDExMGM3OTAzOGFiNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jz0_AltEvBTKbYAvzMV7D4TnEXxG2pJqkXi6ZFDLnTo)

PR welcome!
