### ISSUE TITLE
建议将计划中的研发任务都拆分新建issue，通过issue管理开发任务

### ISSUE THREAD

**Issue by bullub** [dream-num/univer#25]
很高兴能看到这么优秀的开源项目，通过架构介绍和源码结构，让我学到了很多。
我虽然看到了README中宏伟的开发计划，但是作为新人，想要参与开发，也很难找到切入点。
因此，斗胆建议管理员使用issue将研发任务拆分到issue中。

**Comment by Dushusir** [comment]
感谢建议，将会逐步建设

**Comment by Dushusir** [comment]
已经开始建设issue任务拆分https://github.com/dream-num/univer/issues/32
