### ISSUE TITLE
[Bug] the generated html does not include slash border style

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2502]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.14

### Reproduction link

1. apply slash border
![image](https://github.com/dream-num/univer/assets/51111411/4c9024e0-d62b-4e5f-ae34-76108b2fb89f)
2. execute `univerAPI.getActiveWorkBook().getActiveSheet().getRange(0,0,2,2).generateHTML()`  structure is incorrect
![image](https://github.com/dream-num/univer/assets/51111411/85fda181-2184-4116-a78f-63dd6192cb0f)

### Expected behavior

the generated html could include slash border style.

### Actual behavior

 the generated html does not include slash border style

**Comment by ybzky** [comment]
This line type is one of our features, but it is not one of the border types in HTML. Therefore, we do not provide replication for non-W3C standard attributes. If there is strong demand in the future, we will consider supporting it.
