### ISSUE TITLE
[Bug] Merged cell border line rendering problem

### ISSUE THREAD

**Issue by waterhydroxyl** [dream-num/univer#2509]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

https://univer.ai/zh-CN/examples/sheets

### 复现链接

1、对某块区域单元格进行合并操作（全部合并）。
2、对同区域设置边框（所有边框）。
3、在合并单元格的相邻区域设置边框（空边框）。

### 预期行为

excel对应场景的预期表现
![image](https://github.com/dream-num/univer/assets/40552739/53490450-af72-489e-9372-e10909b27a3a)

### 实际行为

合并单元格与区域相邻的列的边框线会被全部取消掉。
![image](https://github.com/dream-num/univer/assets/40552739/cdf4dc2c-8d09-4447-b591-7cd6fb1e5143)

### 运行环境

Chrome

### 系统信息

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F
    Memory: 7.76 GB / 31.82 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527

**Comment by ybzky** [comment]
@DR-Univer @lumixraku cc  数据应该是对的 应该是边框线的渲染规则不太一致

**Comment by waterhydroxyl** [comment]
还有这个操作场景，渲染结果也不符合预期
![image](https://github.com/dream-num/univer/assets/40552739/25036f31-e242-43cb-b5b9-1ffb7051033e)

**Comment by lumixraku** [comment]
Consistent with Google Sheets, but different from Excel.
<img width="342" alt="image" src="https://github.com/user-attachments/assets/67105ca5-4978-45c8-9960-1a7a6715c9bb">

**Comment by suave168** [comment]
If I perform the same operation in Google Sheets, the border lines do not change in any way. However, the expected scenario is to match Excel. I tried Tencent Docs, and it also allows clearing some border lines of merged cells.
![image](https://github.com/user-attachments/assets/1d05deb3-2759-4e32-b4f0-e171e9515168)

**Comment by waterhydroxyl** [comment]
If I perform the same operation in Google Sheets, the border lines do not change in any way. However, the expected scenario is to match Excel. I tried Tencent Docs, and it also allows clearing some border lines of merged cells.
![image](https://github.com/user-attachments/assets/f3d19005-75cc-4b25-b451-2957797dc283)
