### ISSUE TITLE
[Bug] Added CustomMenu, when registering plugin engine, LocaleService cannot be loaded.

### ISSUE THREAD

**Issue by Gocgo** [dream-num/univer#2511]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

univer-0.1.14

### 复现链接

可复现最小demo仓库地址：https://github.com/Gocgo/univer-demo.git
主页在pages/Home目录下，universheet组件在components/UniverSheet目录下，    univer.registerPlugin(UniverSheetsCustomMenuPlugin);注释掉，universheet可以正常展示
加载引擎会导致产生如图的报错，无法加载LocaleService
![Uploading image.png…]()

### 预期行为

应当可以加载引擎，展示自定义的custom-menu,zai

### 实际行为

实际产生了报错

### 运行环境

Chrome

**Comment by Gocgo** [comment]
![Snipaste_2024-06-13_19-12-13](https://github.com/dream-num/univer/assets/50833233/e3fbcf12-50c2-4c97-a416-04c73d7d0529)
报错截图

**Comment by jikkai** [comment]
This is a known issue. We are not sure what Umi has done that caused the TypeScript decorators to not execute as expected. The provided link (https://stackblitz.com/edit/vitejs-vite-exfdw3?file=src%2Fpages%2Fplugins%2FDataSourcePlugin.tsx) is a workaround for this problem.

If you are able to find a solution, we would greatly appreciate your help in resolving this issue.
