### ISSUE TITLE
[Bug] After deploying using Docker, the import cannot be used.

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#2519]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.13

### Reproduction link

https://univer.ai/zh-CN/pro/guides/sheet/features/exchange

### Expected behavior

导入成功

### Actual behavior

- S3_ENDPOINT_PUBLIC=http://univer-minio:9000
+ S3_ENDPOINT_PUBLIC=http://你的局域网IP:19000

根据官网文档修改无法另存为时出现
没改时导入可用，另存为出错，改完后就出现导入出错，另存为可用

### System information

![image](https://github.com/dream-num/univer/assets/170174083/f6a1f307-8595-41ce-820f-8fe2f1a63dc3)

**Comment by hexf00** [comment]
We are currently verifying this issue and will respond to you later today.
