### ISSUE TITLE
[Bug] After using UMD to introduce import and export, the export is successful after deploying Docker, but an export error occurs in the project.

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#2523]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.13

### Reproduction link

https://univer.ai/zh-CN/pro/guides/sheet/features/exchange

### Expected behavior

![image](https://github.com/dream-num/univer/assets/170174083/82ce43c7-848f-4578-94ca-1fb97570b65f)

### Actual behavior

![image](https://github.com/dream-num/univer/assets/170174083/be5157b0-0984-4e0a-a201-2c1fd63495c1)

### System information

无报错信息，只提示内部未知错误。

**Comment by hexf00** [comment]
Repeat with #2519
