### ISSUE TITLE
How to deploy using docker-compose?

### ISSUE THREAD

**Issue by kokojacket** [dream-num/univer#2533]
How to deploy using docker-compose?

**Comment by hexf00** [comment]
If you need to use advanced features like collaboration, you can refer to our backend Docker image and deployment guide: https://univer.ai/pro/guides/sheet/deployment/docker. However, please note that if you don't need these advanced features, Univer's basic plugins run entirely on the frontend and are open-source.

**Comment by rogerc66** [comment]
link is dead
