### ISSUE TITLE
[Bug] Data Rendering Issue After Switching Sheets and Deleting 'sheet-02' Tab

### ISSUE THREAD

**Issue by congxiaobai** [dream-num/univer#2534]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.14

### 复现链接

https://github.com/congxiaobai/ubiver-sheet-error

### 预期行为

1.切换到'sheet-02'页签
2. 删除'sheet-02'页签
3. 期望切换到'sheet-01'页签，并保证数据渲染正确

### 实际行为

切换到了'sheet-01'页签，但是数据渲染不正确。没有进行重绘。

### 系统信息

System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 126.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  Browsers:
    Edge: 126.0.2592.56
    Safari: 17.5

**Comment by jikkai** [comment]
Our DI library currently does not support React's strict mode.

```diff
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'

ReactDOM.createRoot(document.getElementById('root')!).render(
-  <React.StrictMode>
    <App />
-  </React.StrictMode>,
)
```

**Comment by congxiaobai** [comment]
https://github.com/congxiaobai/ubiver-sheet-error
I Delete  StrickMode code。 But it still happens。

**Comment by jikkai** [comment]
> https://github.com/congxiaobai/ubiver-sheet-error I Delete StrickMode code。 But it still happens。

The updated demo you provided DOES NOT reproduce the issue you mentioned.

![16d15ffe6107c4a73174247d6a606ffa](https://github.com/dream-num/univer/assets/14025786/53545f59-c81b-48fc-96a3-1bd97c9ed6fa)

**Comment by jikkai** [comment]
It seems we need to confirm this issue. @Dushusir

**Comment by Dushusir** [comment]
Thank you for your feedback. Version 0.1.16 has fixed this. If you still have problems, please reopen the issue
