### ISSUE TITLE
[Feature] Please tell me, are there any examples of cells in the time format in the official examples? I set the cell type to time, but I didn’t see any effect?

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2535]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

更改单元格数据为time格式的时候，没有看到单元格有任何变化，官网的例子里没有时间单元格的例子。

### Solution

设置单元格为time ，formula1和formula2，都没有设置

**Comment by Gggpound** [comment]
你是把什么样的数值改为 time格式？
【45638.883472222224】 这种数值在改为time格式的时候，会被序列化为 【下午 9:12:12】

**Comment by feige-2011** [comment]
我的意思是我在设置time格式时没有，输入框是不是应该弹出一个选择时间的弹窗，像日期组件那样方便输入？
