### ISSUE TITLE
[Feature] How to set cells in the WORKBOOK_DATA sheet to be read-only

### ISSUE THREAD

**Issue by ManderGao** [dream-num/univer#2549]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

在luckysheet中可以在init中设置保护单元格只读，
Univer中实现是使用权限管控（IPermissionService ），针对vue2使用不友好

### 解决方案

希望能够简化权限管控

**Comment by hexf00** [comment]
You can refer to it https://stackblitz.com/ ~/github.com/awesome-univer/sheets-permission-demo
