### ISSUE TITLE
[Feature] We have date and time, but no date and time format. We currently need such a function, and I think this is a very useful function.

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2554]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

增加日期时间格式的单元格类型

### 解决方案

增加日期时间格式的单元格类型

**Comment by Gggpound** [comment]
目前是支持的，可以试试设置 cell.s.n 属性，n是一段数字格式的规则，如果使用日期 可以设置为 yyyy/MM/dd ,其中 v 是一段日期数字
