### ISSUE TITLE
[Feature] Text Formula LEFT

### ISSUE THREAD

**Issue by sagarwal3005** [dream-num/univer#2558]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Formula LEFT is not implemented

### Solution

Implement formula LEFT
Reference https://support.microsoft.com/en-us/office/left-leftb-functions-9203d2d2-7960-479b-84c6-1ea52b99640c
@sagarwal3005 : I can solve it

**Comment by Dushusir** [comment]
Already implemented
