### ISSUE TITLE
[Bug] Cannot find "univer.doc.text-selection-render-manager" registered by any injector

### ISSUE THREAD

**Issue by chaopower-zhang** [dream-num/univer#2563]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.15

### Reproduction link

I followed the quick start guide to complete the deployment, but it prompted an error.
`import './App.css'
import "@univerjs/design/lib/index.css";
import "@univerjs/ui/lib/index.css";
import "@univerjs/docs-ui/lib/index.css";
import "@univerjs/sheets-ui/lib/index.css";
import "@univerjs/sheets-formula/lib/index.css";

import { LocaleType, Tools, Univer, UniverInstanceType } from "@univerjs/core";
import { defaultTheme } from "@univerjs/design";

import { UniverFormulaEnginePlugin } from "@univerjs/engine-formula";
import { UniverRenderEnginePlugin } from "@univerjs/engine-render";

import { UniverUIPlugin } from "@univerjs/ui";

import { UniverDocsPlugin } from "@univerjs/docs";
import { UniverDocsUIPlugin } from "@univerjs/docs-ui";

import { UniverSheetsPlugin } from "@univerjs/sheets";
import { UniverSheetsFormulaPlugin } from "@univerjs/sheets-formula";
import { UniverSheetsUIPlugin } from "@univerjs/sheets-ui";

import DesignZhCN from '@univerjs/design/locale/zh-CN';
import UIZhCN from '@univerjs/ui/locale/zh-CN';
import DocsUIZhCN from '@univerjs/docs-ui/locale/zh-CN';
import SheetsZhCN from '@univerjs/sheets/locale/zh-CN';
import SheetsUIZhCN from '@univerjs/sheets-ui/locale/zh-CN';

function App() {
  const univer = new Univer({
    theme: defaultTheme,
    locale: LocaleType.ZH_CN,
    locales: {
      [LocaleType.ZH_CN]: Tools.deepMerge(
        SheetsZhCN,
        DocsUIZhCN,
        SheetsUIZhCN,
        UIZhCN,
        DesignZhCN,
      ),
    },
  });

  univer.registerPlugin(UniverRenderEnginePlugin);
  univer.registerPlugin(UniverFormulaEnginePlugin);

  univer.registerPlugin(UniverUIPlugin, {
    container: 'univer',
  });

  univer.registerPlugin(UniverDocsPlugin, {
    hasScroll: false,
  });
  univer.registerPlugin(UniverDocsUIPlugin);

  univer.registerPlugin(UniverSheetsPlugin);
  univer.registerPlugin(UniverSheetsUIPlugin);
  univer.registerPlugin(UniverSheetsFormulaPlugin);

  univer.createUnit(UniverInstanceType.UNIVER_SHEET, {});
  return (
    <>
        <div id="univer" style={{ height: '600px', width: '100%' }}> </div>
    </>
  )
}

export default App`
this is my code 
![image](https://github.com/dream-num/univer/assets/41176704/2f6b00d6-0791-46fd-a352-403284827ce6)

### Expected behavior

How do I fix it?

### Actual behavior

How do I fix it?

**Comment by jikkai** [comment]
Are you using React? Please note that our DI library currently does not support React's strict mode.

```diff
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'

ReactDOM.createRoot(document.getElementById('root')!).render(
-  <React.StrictMode>
    <App />
-  </React.StrictMode>,
)
```

**Comment by chaopower-zhang** [comment]
> Are you using React? Please note that our DI library currently does not support React's strict mode.
> 
> ```diff
> import React from 'react'
> import ReactDOM from 'react-dom/client'
> import App from './App.tsx'
> 
> ReactDOM.createRoot(document.getElementById('root')!).render(
> -  <React.StrictMode>
>     <App />
> -  </React.StrictMode>,
> )
> ```

Thank you very much, it is indeed working now.
