### ISSUE TITLE
[Bug] If you request the backend interface multiple times to get the data and render it to generate a univer, the page will crash: out of memory

### ISSUE THREAD

**Issue by 352836670** [dream-num/univer#2565]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

跟版本没有关系

### 复现链接

[data.txt](https://github.com/user-attachments/files/15907485/data.txt)

### 预期行为

页面流畅，不会崩溃
[data.txt](https://github.com/user-attachments/files/15907497/data.txt)

### 实际行为

多次请求后端接口拿到data数据并渲染生成univer，页面会崩溃：out of memory

**Comment by jikkai** [comment]
![ae6f26b89a075e90e488429acaee7e7b](https://github.com/dream-num/univer/assets/14025786/0683f45c-b6a4-4476-a458-643add532ff1)

https://stackblitz.com/edit/github-aayzou-uwwdyg

unable to reproduce your issue. Please provide a demo that can reproduce the problem.
