### ISSUE TITLE
The function of Right Shift is not correct 

### ISSUE THREAD

**Issue by jaylpp** [dream-num/univer#2571]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.15

### Reproduction link

1. choose two cells, and right click and select insert option.
2. then，select right shift.

### Expected behavior

only right shift 2 cells, not 18.

### Actual behavior

right shift 18 cells

### System information

System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 61.96 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.62
    Edge: 126.0.2592.61
    Safari: 17.5

**Comment by wzhudev** [comment]
@yuhongz Something wrong with `InsertRangeMoveRightCommand`.
