### ISSUE TITLE
[Bug] After the user is set after calling the userManagerService.setCurrentUser method, after the protection is created, the creator displayed is not the set user.

### ISSUE THREAD

**Issue by LiuYuLu** [dream-num/univer#2582]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.15

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-permission-demo

<img width="1147" alt="image" src="https://github.com/dream-num/univer/assets/16041268/85c23225-b22e-46c4-9327-6c1d3fba7f3e">

### 预期行为

setCurrentUser方法调用后，操作记录的人应该是设置中的人

### 实际行为

调用userManagerService.setCurrentUser方法后设置的用户，创建保护后，显示的创建人不是设置的用户

### 运行环境

其他 (请在复现步骤中说明)

**Comment by Gggpound** [comment]
<img width="620" alt="image" src="https://github.com/dream-num/univer/assets/141617023/a913103c-3553-4919-a298-892ae3ceec43">
改造 2 个地方试试这样.
第一个地方，我们在mock权限体系的时候，通过在userID 中注入特别的字符来标明身份
<img width="652" alt="image" src="https://github.com/dream-num/univer/assets/141617023/66897f66-ba19-45ff-80eb-e2a7a45b1e88">
第二个地方，在mock权限io的时候,会设置用户身份，你得确保你设置的mockUser的时序在这个之后。
<img width="1127" alt="image" src="https://github.com/dream-num/univer/assets/141617023/a2b54ea3-974d-4d1c-a5ba-907ec2d6e456">
所以你需要提前injector.get，来触发 AuthzIoLocalService 的实例化（这部分实例化逻辑是交给di框架的，如果没有手动get,那么实例化的时机会在你创建区域保护规则的时候执行.）
