### ISSUE TITLE
[Feature] How to use permission to create a universalSheet in read-only mode?

### ISSUE THREAD

**Issue by Xiangzi529** [dream-num/univer#2585]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

看了官网的https://www.univer.ai/zh-CN/guides/sheet/features/permission 但是不太明白 不知道有没有demo可以参考一下 我就是希望全局禁用编辑 就是我的单元格的内容 我就是展示出来 不让改 也不用改 尝试过在onBeforeCommandExecute前面禁用一些id 但是控制台太难看了

### Solution

有没有全局制度摸索 不需要引入plugin的解决方案啊

**Comment by jikkai** [comment]
The key code is located here: https://stackblitz.com/~/github.com/awesome-univer/sheets-permission-demo?file=src/plugins/commands.ts:L34-L47.
Additionally, we will consider providing a read-only capability for the entire table through the facade API later on.
