### ISSUE TITLE
0.1.16 version new errors[Bug]

### ISSUE THREAD

**Issue by lyking90** [dream-num/univer#2597]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

https://univer.ai/examples/sheets

### 预期行为

1.vite启动项目运行univer，终端应没有错误警告
2.在单元格里输入一个数字，往下拉填充，应该会逐渐递增，而不是复制一样的数字，旧版本是可以的。
![image](https://github.com/dream-num/univer/assets/56106787/cf2e64b7-0656-4065-89a6-004168653c56)

### 实际行为

1.vite项目更新版本到0.1.16后，终端会报警告[vite:css] end value has mixed support, consider using flex-end instead
![image](https://github.com/dream-num/univer/assets/56106787/6d29f014-cd84-4bfe-b9aa-51590cdb31e1)
2.在单元格里输入一个数字，往下拉填充，没有逐渐递增
![image](https://github.com/dream-num/univer/assets/56106787/3be7b7d9-845a-412b-8ed9-fa950f976acf)

### 运行环境

Chrome

**Comment by lyking90** [comment]
我在最新版本0.2.2里测试，发现两个问题都依然存在。为什么issue就关闭了呢？

**Comment by lyking90** [comment]
![image](https://github.com/dream-num/univer/assets/56106787/ff2c9299-59bd-4026-b7af-407b8d33305f)
![image](https://github.com/dream-num/univer/assets/56106787/3e1d68bc-d380-4900-b7eb-ff1b8d292773)

**Comment by jikkai** [comment]
Should be fixed in #2638. If the issue persists, please create a new demo and reopen this issue.
