### ISSUE TITLE
[Feature] Does our table have a placeholder field that is similar to input? , can be used to prompt the user what to enter

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2599]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

需要一个类似于input的placeholder的提示，当用户编辑时隐藏，如果用户没有输入但退出编辑的时候显示。

### 解决方案

产品加个字段用于实现我所说的placeholder效果，或者有别的方式可以达到这种效果，麻烦告诉我一下

**Comment by jikkai** [comment]
There are currently no plans to implement this feature. You can implement it yourself by [Extending Canvas](https://univer.ai/guides/sheet/customization/canvas).
