### ISSUE TITLE
[Bug] Deleting a cell - moving left will cause all cells to the left of this cell to be deleted (moving up has the same problem)

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2622]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

复现在如下视频中：
https://github.com/dream-num/univer/assets/41188824/6049627b-a35e-4421-9370-06d4a9008749

### 预期行为

复现视频中有其他产品对照效果

### 实际行为

左移：要删除的单元格左侧的其他单元格全被删除了
上移：要删除的单元格上方的其他单元格全被删除了

### 运行环境

Chrome

### 系统信息

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.00 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.126
    Safari: 17.5

**Comment by Gggpound** [comment]
https://github.com/user-attachments/assets/98fa8474-0aec-4f4e-be19-93c1c973cf77

这个问题在最新版本已经无法复现
