### ISSUE TITLE
[Bug] After destroying the workbook instance and then creating a new instance, you will not be able to create a new sheet.

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2624]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

demo地址：https://github.com/qingnianz/univer-demo.git
复现视频：

https://github.com/dream-num/univer/assets/41188824/27bde0b5-6c90-435a-9ad2-445a1d79e3c5

### 预期行为

销毁sheet实例后新创建的实例应该正常切换左下角的sheet tab

### 实际行为

销毁sheet实例后新创建的实例无法正常切换左下角的sheet tab

### 运行环境

Chrome

### 系统信息

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.46 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.126
    Safari: 17.5

**Comment by jikkai** [comment]
> @zhaolixin7 Hi, this bug still exist on version 0.5.1, and when will it be fixed ?

reproduction plz
