### ISSUE TITLE
[Bug] Color rendering is incorrect

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2626]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

<img width="857" alt="image" src="https://github.com/dream-num/univer/assets/41188824/802c2784-280d-4369-b767-d8430be2ceb5">

### 预期行为

颜色与设置的实际效果保持一致

### 实际行为

颜色有偏差

### 运行环境

Chrome

**Comment by lumixraku** [comment]
please https://css.bqrdh.com/safety-color to see if color is match.

you can calibrate your sceen color settings here.  choose sRGB to see if match.
<img width="715" alt="image" src="https://github.com/user-attachments/assets/21b53634-2cbe-4ab7-bf8f-a5afaba8c476">
