### ISSUE TITLE
[Bug] generateHTML() the return property is invalid

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2627]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.16

### Reproduction link

1. A1 type a long sentence
2. Apply the intercept style
3. call the univerAPI.getActiveWorkBook().getActiveSheet().getRange(0,0,2,2).generateHTML()
4. the return property "white-space: clip" is invalid.

![001478f232023659411ba942f7de9177](https://github.com/dream-num/univer/assets/51111411/c9f1aae4-8533-42f1-b3d8-3cc6c396264e)

 

### Expected behavior

return the valid property

### Actual behavior

white-space: clip is not a valid property
![9442b6685a80ed4d1caf4987b93cced6](https://github.com/dream-num/univer/assets/51111411/8082b275-39a7-42f3-8919-f1d29248992a)

**Comment by waterhydroxyl** [comment]
I believe it should have these two CSS style properties. `white-space: nowrap; overflow-x: hidden;`

**Comment by ybzky** [comment]
> ### Before you submit this issue, have you checked the following
> 在提交此问题之前，您是否检查了以下内容
> * [x]  Is this really a problem?这真的是个问题吗？
> * [x]  I have searched the Github Issues for similar issues, but did not find anything. 我在 Github Issues 上搜索过类似的问题，但没有找到任何东西。
> 
> ### Affected packages and versions 受影响的软件包和版本
> 0.1.16
> 
> ### Reproduction link
> 1. A1 type a long sentence A1输入一个长句子
> 2. Apply the intercept style 应用拦截样式
> 3. call the univerAPI.getActiveWorkBook().getActiveSheet().getRange(0,0,2,2).generateHTML()调用 univerAPI.getActiveWorkBook().getActiveSheet().getRange(0,0,2,2).generateHTML()
> 4. the return property "white-space: clip" is invalid.返回属性“white-space:clip”无效。
> 
> ![001478f232023659411ba942f7de9177](https://private-user-images.githubusercontent.com/51111411/343665796-c9f1aae4-8533-42f1-b3d8-3cc6c396264e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjQ1NjcsIm5iZiI6MTcxOTU2NDI2NywicGF0aCI6Ii81MTExMTQxMS8zNDM2NjU3OTYtYzlmMWFhZTQtODUzMy00MmYxLWIzZDgtM2NjNmMzOTYyNjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzODQ0NjVkNzJlMWJmODdiMTM4MjEzZmVhZjAzNzc5MmQ0MzI2MzBhNGJmZmQ0MDIyNzE3Zjc5Nzc1MTZmYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbomP5e2lOPHlvYM1r879nGyvvIe4-NNKkpkuEDIs3A)
> 
> ### Expected behavior
> return the valid property 返回有效的属性
> 
> ### Actual behavior
> white-space: clip is not a valid property空白：剪辑不是有效的属性 ![9442b6685a80ed4d1caf4987b93cced6](https://private-user-images.githubusercontent.com/51111411/343665867-8082b275-39a7-42f3-8919-f1d29248992a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjQ1NjcsIm5iZiI6MTcxOTU2NDI2NywicGF0aCI6Ii81MTExMTQxMS8zNDM2NjU4NjctODA4MmIyNzUtMzlhNy00MmYzLTg5MTktZjFkMjkyNDg5OTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDA1Y2NlMTU1ZWMyN2MyMTE1YTE4NjE2MTMyZjgyYTM2NGMxMzBmYzQyNjBhYjY2OWY1OWNiNmRhZGRiN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cyI6elUTYxWLqXbxqOTfqv9P97vGFVvFzqLBtq6wjcU)
> 
> ### System information 系统信息
> _No response_

we will fix it in the next version

**Comment by Dushusir** [comment]
The problem has been fixed, please pay attention to the latest update. If there are still problems, please reopen the issue
