### ISSUE TITLE
[Bug] Calling DocumentDataModel.reset(snapshot: Partial<IDocumentData>) does not rerender visually

### ISSUE THREAD

**Issue by LeosPrograms** [dream-num/univer#2636]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.17

### Reproduction

1. generate a document using 
`document1 = univer.createUnit(UniverInstanceType.UNIVER_DOC, {});`
2. generate a second document using
``document2 = univer.createUnit(UniverInstanceType.UNIVER_DOC, {});``
3. make changes to document2
4. apply changes from document2 to document1 using
`document1.reset(document2.snapshot)`

### Expected behavior

The browser displaying document1 should reflect the data that is included in the snapshot passed to reset()

### Actual behavior

The document does not change visually. Once changes are applied via manual typing, both those changes, and the changes passed to reset() are suddenly applied.

### System information

Running in electron on Ubuntu 22.04.4

**Comment by Jocs** [comment]
```ts
// TODO: @JOCS do not use reset, please use apply to modify the snapshot.
    reset(snapshot: Partial<IDocumentData>) {
        if (snapshot.id && snapshot.id !== this._unitId) {
            throw new Error('Cannot reset a document model with a different unit id!');
        }

        this.snapshot = { ...DEFAULT_DOC, ...snapshot };
        this._initializeHeaderFooterModel();
    }
```

It is not recommended to use reset directly to modify the data model, please use apply, reset is only used internally, and reset will not automatically trigger re-rendering

**Comment by LeosPrograms** [comment]
@Jocs Could you please provide instruction on how to use "apply" to accomplish the desired behavior?
