### ISSUE TITLE
[Bug] react 16.8 compatibility issues

### ISSUE THREAD

**Issue by jay-xon** [dream-num/univer#2648]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.17

### Reproduction link

Using the demo example from: https://github.com/awesome-univer/sheets-react-facade-demo
Change the React version to 16.8.6
The issue is that changing the worksheet name is ineffective  after modification, the data still shows the previous name. Additionally, the event monitor for Command: sheet.command.set-worksheet-name Params was not found.

### Expected behavior

The worksheet name can be successfully modified.

### Actual behavior

The worksheet name can not be successfully modified.

**Comment by jikkai** [comment]
The lowest compatible version of React for univer is 16.9.0, which is defined in the `package.json`.

**Comment by jay-xon** [comment]
> The lowest compatible version of React for univer is 16.9.0, which is defined in the `package.json`.
Are you sure the minimum compatible version is 16.9.0? Even after upgrading to 16.9.0, I'm still encountering the same issue. After setting the worksheet name, the getActiveWorkbook().getSnapshot() data remains unchanged. I even upgraded to 16.14.0, but it still doesn't work. Could there be a bug here? Or is the minimum compatible version actually higher? 
Thank you for your response.

**Comment by jay-xon** [comment]
> The lowest compatible version of React for univer is 16.9.0, which is defined in the `package.json`.

> The lowest compatible version of React for univer is 16.9.0, which is defined in the `package.json`.
Are you sure the minimum compatible version is 16.9.0? Even after upgrading to 16.9.0, I'm still encountering the same issue. After setting the worksheet name, the getActiveWorkbook().getSnapshot() data remains unchanged. I even upgraded to 16.14.0, but it still doesn't work. Could there be a bug here? Or is the minimum compatible version actually higher? 
Thank you for your response.

**Comment by jikkai** [comment]
It seems like this issue is caused by a known bug in redi. Currently, redi does not support React's strict mode. You can temporarily remove React.StrictMode. We will update the demo repository later.

```diff
- <React.StrictMode>
  <App />
- </React.StrictMode>
```

**Comment by jay-xon** [comment]
> It seems like this issue is caused by a known bug in redi. Currently, redi does not support React's strict mode. You can temporarily remove React.StrictMode. We will update the demo repository later.
> 
> ```diff
> - <React.StrictMode>
>   <App />
> - </React.StrictMode>
> ```

It seems that's not the issue. Even after remove React.StrictMode, it still doesn't work in React versions 16.9.0 or 16.14.0.

**Comment by jikkai** [comment]
Here is a runable demo: https://stackblitz.com/edit/github-hnthoz

Please check if this is caused by caching or other factors.

**Comment by jay-xon** [comment]
> Here is a runable demo: https://stackblitz.com/edit/github-hnthoz
> 
> Please check if this is caused by caching or other factors.

![1719908253723](https://github.com/dream-num/univer/assets/40010547/600dae2a-9a42-440c-9ec9-61aaa37756d6)

**Comment by jikkai** [comment]
Thanks a lot for your patience and help 🙌. We have discovered and fixed two bugs related to compatibility with React versions prior to 18.0.

The fixes will be released with version 0.1.18.
