### ISSUE TITLE
[Feature] Add commands to the right-click menu of the worksheet in the sheets-ui plugin.

### ISSUE THREAD

**Issue by FrontToEnd** [dream-num/univer#2653]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I want to disable the pop-up of the right-click menu, currently the onBeforeCommandExecute cannot prevent the pop-up of the right-click menu.
![image](https://github.com/dream-num/univer/assets/17469925/38be7190-cd43-45a7-b80c-153b0f17dd9c)

### Solution

I can specify the right-click menu commands in onBeforeCommandExecute and prevent the menu from popping up by throwing an error.

**Comment by jikkai** [comment]
I think it is a bug 🐞.
When `contextMenu` is set to `false`, the context menu of the sheet bar should not be opened. Don't worry about it, I will fix it soon.
