### ISSUE TITLE
[Bug] Custom formulas in conditional formatting do not take effect

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2655]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

<img width="1434" alt="image" src="https://github.com/dream-num/univer/assets/41188824/8d6406fb-1eed-4e59-878d-319c657bf193">

### 预期行为

<img width="968" alt="image" src="https://github.com/dream-num/univer/assets/41188824/08e6c660-cfde-4bd3-9a1f-e9af0abe4769">

### 实际行为

没有正确渲染条件格式

### 运行环境

Chrome

**Comment by Dushusir** [comment]
SEARCH function is to be supported

**Comment by Dushusir** [comment]
SEARCH formula is already supported, please re-test with the latest version.
This issue will be closed, if you still have questions, feel free to reopen this issue.
