### ISSUE TITLE
[Bug] When I am editing a table unit and quickly switch to edit another table unit, a p field will appear in the table unit currently being edited, and the content being edited is in the dataStream, not in the field v.

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2659]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.15

### 复现链接

![WechatIMG1477](https://github.com/dream-num/univer/assets/19235739/ded2729c-c94d-4392-8a8c-3eae32ee9c6d)

### 预期行为

当单元格退出编辑状态时，编辑的字段应该存到v字段上

### 实际行为

当单元格退出编辑状态时，编辑的字段应该存到{p:{body:{dataStream:"编辑内容"}}}字段上

### 运行环境

Chrome

### 系统信息

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 93.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/node
    Yarn: 4.3.1 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/npm
    pnpm: 9.3.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 17.0

**Comment by jikkai** [comment]
Duplicate of #2207
