### ISSUE TITLE
[Bug] Sheet custom-ui contextmenu loading is slow.

### ISSUE THREAD

**Issue by mietl** [dream-num/univer#2664]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.17

### Reproduction link

Reproduction link:  https://univer.ai/zh-CN/playground?title=Custom+Menu
This example can be reproduced.

 Refresh the web page, or click  ➜  Local:   http://localhost:5173/  Can be reproduced

The custom menu is too slow to load, about 5 seconds. When entering for the first time, it cannot be loaded. After the view flashes, it works normally.

### Expected behavior

I hope it will be faster.

### Actual behavior

It is so slow that it doubts life and affects the use.

### System information

  System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M2
    Memory: 263.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    bun: 1.1.17 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 18.0

**Comment by jikkai** [comment]
```typescript
@OnLifecycle(LifecycleStages.Steady, CustomMenuController) 
```

https://github.com/awesome-univer/custom-menu/blob/3aa01d1f179d0dff240fe9aecfb0aa5e8918bd42/src/plugin/controllers/custom-menu.controller.ts#L15

Please read the documentation related to the plugin lifecycle.
https://univer.ai/guides/sheet/architecture/univer#plugin-life-cycle

**Comment by mietl** [comment]
> ```ts
> @OnLifecycle(LifecycleStages.Steady, CustomMenuController) 
> ```
> 
> https://github.com/awesome-univer/custom-menu/blob/3aa01d1f179d0dff240fe9aecfb0aa5e8918bd42/src/plugin/controllers/custom-menu.controller.ts#L15
> 
> 请阅读与插件生命周期相关的文档。https [://univer.ai/guides/sheet/architecture/univer#plugin-life-cycle](https://univer.ai/guides/sheet/architecture/univer#plugin-life-cycle)

Thanks for your reply.
