### ISSUE TITLE
[Bug] When react 17 version uses @univerjs/sheets-hyper-link-ui, the hyperlink cannot be displayed when the content area is suspended.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#2668]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.16

### 复现链接

以官方demo 为例子当我为18的时候就可以悬浮上去 并且可以跳转超链接功能，
当我为17的时候悬浮会失去效果。

### 预期行为

可以正常跳转超链接

### 实际行为

超链接的悬浮框没有出来

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please provide a minimal reproducible demo or link for the issue. 

We will close this issue for now, but feel free to reopen it once you have provided the necessary information.

**Comment by 840251442** [comment]
[link.zip](https://github.com/user-attachments/files/16104544/link.zip)
我把这个demo压缩了 你可以用pnpm 启动看一下 react版本 17.0.2

**Comment by 840251442** [comment]
@jikkai

**Comment by 840251442** [comment]
还有个问题 保护行列的菜单 为什么不能设置hidden
