### ISSUE TITLE
[Bug] Dragging numbers in versions after 0.1.15 will not automatically generate a sequence

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2670]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.17

### 复现链接

0.1.15版本在数字的右下角拖动数字，会自动生成自增的序列
0.1.15之后的版本：不会自动生成自增的序列，而是复制单元格的数字

### 预期行为

https://github.com/dream-num/univer/assets/41188824/fd81e952-9e2b-41d4-a83b-5fa483fcdd33

### 实际行为

https://github.com/dream-num/univer/assets/41188824/cebec5b4-9c05-497a-aff0-22d1a40f51f2

### 运行环境

Chrome

**Comment by jikkai** [comment]
Already fixed in a previous version. If the issue still appear, please provide a minimal reproducible demo link.
