### ISSUE TITLE
[Bug]We detected multiple package managers in your repository: pnpm, npm

### ISSUE THREAD

**Issue by sixgodIT** [dream-num/univer#271]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

node 16.18.1

### 复现步骤

按照文档，npm i -g pnpm ，pnpm install 后 使用npm run dev:sheet 时，报错：Error: We detected multiple package managers in your repository: pnpm, npm. Please remove one of them.
<img width="734" alt="image" src="https://github.com/dream-num/univer/assets/5539093/17159998-cb83-41a1-a8be-aafcfabf7eae">

### 预期行为

正常运行

### 实际行为

Error: We detected multiple package managers in your repository: pnpm, npm. Please remove one of them.

### 运行环境

其他 (请在复现步骤中说明)

### 操作系统

macOS

### 构建工具

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
这个问题多半是因为依赖不是通过 pnpm 安装的。

确认一下你本地项目中是否存在 `package-lock.json` 或者 `yarn-lock.json` 文件，如果存在的话请删除这些 lock 文件、 node_modules 和相关缓存（个人建议是删除本地项目，重新拉取一次），并重新通过 pnpm i 命令安装依赖，不要使用 npm 和 yarn。
