### ISSUE TITLE
[Bug] the cells of sheet don't support charactor '*' in version 0.2.1,but the online example import/export is ok

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2725]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.1

### Reproduction link

links: https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

I can input '*' in cells

### Actual behavior

I can't input '*' in cells

### System information

MacOS 14.5 (23F79) chrome 126.0.6478.127

**Comment by Picktarget** [comment]
maybe the online example import/export in version 0.1.17

**Comment by Picktarget** [comment]
Additionally  when the cellData's property v is "*BBBB", causing the sheet crash 
![image](https://github.com/dream-num/univer/assets/12743709/fec98269-39bd-43d5-81a4-1686aee0c3c5)

**Comment by jikkai** [comment]
Already fixed in https://github.com/dream-num/univer/pull/2720
