### ISSUE TITLE
[Bug] text underline display bug

### ISSUE THREAD

**Issue by lyking90** [dream-num/univer#2727]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.1

### 复现链接

https://univer.ai/zh-CN/examples/sheets

### 预期行为

像luckysheet一样，设置了下划线后，在外面就可以直接看到，而不是要点击进去。早期版本也已经存在该问题

### 实际行为

点击进去后才能看到效果
<img width="173" alt="bf23e702e9f910339a8b8d1ca49154c" src="https://github.com/dream-num/univer/assets/56106787/ce19ade5-cd1c-4c93-aa60-8ff30cd8a118">
<img width="580" alt="69e40a96441ea7b74f24cf5a7ad6e16" src="https://github.com/dream-num/univer/assets/56106787/673c918d-af6e-440f-8676-810df2b9ed52">

### 运行环境

Chrome

**Comment by jikkai** [comment]
![](https://github.com/dream-num/univer/assets/14025786/cc8770cb-eff5-4221-b945-8a0fd51fbc67)


This is not consistent with the behavior in Excel. Please assist in resolving this issue @Jocs @lumixraku

**Comment by Jocs** [comment]
This issue can't be reproduced, I tried to underline it in the sheet to display, I closed it first, if there are still problems, please comment, reopen this issue

**Comment by Jocs** [comment]
输入英文，在单元格比较矮的时候，会隐藏下划线，下划线位置偏低

**Comment by lumixraku** [comment]
https://github.com/dream-num/univer/pull/3139
