### ISSUE TITLE
[Feature] Provide a partially uneditable facade API

### ISSUE THREAD

**Issue by qingnianz** [dream-num/univer#2730]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

存在很多不区分权限只有部分单元格能编辑的场景，现在只能通过WorksheetEditPermission让整个工作表不能编辑或者通过保护区域控制（保护区域只能控制其他用户不能编辑）

### 解决方案

类似setEditable一样，提供一个局部不可编辑的facade api

**Comment by zifeiyuSun** [comment]
遇到同样问题，代码设置的权限应该优先级最高
