### ISSUE TITLE
[Feature] Can cells support multi-select fields?

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#2743]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

单元格能支持多选字段吗

### 解决方案

单元格能支持多选字段吗

**Comment by jikkai** [comment]
Please describe your requirements in detail.

We will close this issue temporarily, once you can add more information, feel free to open this issue at any time
