### ISSUE TITLE
[Bug] export Excel and open in iOS Number APP, the formula will missing

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#2744]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.2

### Reproduction link

this is my formula demo

![截圖 2024-07-11 10 27 11](https://github.com/dream-num/univer/assets/3794103/0241d864-cce3-41b8-802f-f054367eeeee)

.

I use `univerAPI.exportXLSXBySnapshot` to export my Excel file
here is `SUM` formula, but when I open xslx file in Number App, it show the formula is missing:

<img width="711" alt="截圖 2024-07-11 10 27 23" src="https://github.com/dream-num/univer/assets/3794103/cc6660ed-0fca-4da8-b4b8-d3ba08caa534">

### Expected behavior

Number App can read formula when I export excel

### Actual behavior

Number App can't read the formula

**Comment by Dushusir** [comment]
Thank you for your feedback, we will test this issue as soon as possible
