### ISSUE TITLE
[Feature] It is required to obtain cell data within a range, and the formula can control refresh[

### ISSUE THREAD

**Issue by dawudyang** [dream-num/univer#2745]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

需求获取范围内单元格数据提供一个api 如getValues获取范围内的值 getCellDatas获取范围内单元格所有属性，另外需求公式能控制刷新，初始化设置不自动刷新公式

### 解决方案

需求获取范围内单元格数据提供一个api 如getValues获取范围内的值 getCellDatas获取范围内单元格所有属性，另外需求公式能控制刷新，初始化设置不自动刷新公式

**Comment by jikkai** [comment]
Please use `forEach` instead.

@hexf00 could you add a `getValues` facade API?
