### ISSUE TITLE
[Feature] Pop-up windows without permission can be configured to close or customized.

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2746]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

无权限，双击单元格的时候，会弹出如下弹窗：
![da4e94e00bc53c1228ef86706e5de52](https://github.com/dream-num/univer/assets/67748948/4b6333f9-a4c7-4c87-9628-3ba04e1b1f3a)

### 解决方案

可以配置，不弹窗。或者弹窗可自定义

**Comment by jikkai** [comment]
Sometimes users don't need such strong prompts to know if a cell is protected, so this request is valuable. We will consider implementing it.

**Comment by Gggpound** [comment]
```ts
import { SheetPermissionInterceptorBaseController } from '@univerjs/sheets-ui'
export class YouService extends Disposable {
    constructor(
        @Inject(SheetPermissionInterceptorBaseController) private readonly _sheetPermissionInterceptorBaseController: SheetPermissionInterceptorBaseController,
    ) {
        super();
         this.sheetPermissionInterceptorBaseController.setDialogDisplayWithoutPermission(false)
    }
```
