### ISSUE TITLE
vite build error

### ISSUE THREAD

**Issue by likelikeit** [dream-num/univer#2750]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

"@univerjs/vite-plugin": "^0.4.4",

### Reproduction link

![image](https://github.com/user-attachments/assets/ac1f6383-cf8f-4398-9580-bc4a59740203)

### Expected behavior

Im looking forward to build success

### Actual behavior

TSERROR 7016
I sloved this problem by overriding the exports filed in package.josn file in node_modules
the following picture is my solution.
![image](https://github.com/user-attachments/assets/5352a6a5-f46a-47fa-890a-6f0a5f212f58)

### System information

system: windows10, 64-bit computing

chrome version: 126.0.6478.127

**Comment by jikkai** [comment]
```diff
/// <reference types="vite/client" />
+ /// <reference types="@univerjs/vite-plugin/types" />
```
