### ISSUE TITLE
I uploaded a table in the demo on the official website and then exported it, but only half of the table was obtained.

### ISSUE THREAD

**Issue by yang-xiao-xue** [dream-num/univer#2751]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.2

### 复现链接

https://univer.ai/pro/examples/sheets-exchange 
在官网的demo上传了一个表格,然后又执行了导出,但是只获得了半张表,文件大小未超限制,只有10kb
![Snipaste_2024-07-12_11-22-55](https://github.com/user-attachments/assets/302ed34a-5b3c-4931-af47-ee53ddef1e20)
[sheet.xlsx](https://github.com/user-attachments/files/16188091/sheet.xlsx)

### 预期行为

应该导出完整的表格,而非信息丢失

### 实际行为

导出的表格不完整,信息发生了丢失

### 运行环境

Chrome

### 系统信息

线上环境非本地

**Comment by jikkai** [comment]
The issue has been confirmed. There might be some problems with the import and export services. We will fix them later.

**Comment by DR-Univer** [comment]
![image](https://github.com/user-attachments/assets/887fb5ba-8444-4e1c-91b5-9d26e691ea89)
@yang-xiao-xue 可以试试看，已经修复了

**Comment by Dushusir** [comment]
This issue will be fixed in the next version
