### ISSUE TITLE
[Bug] props transfer of floating dom elements

### ISSUE THREAD

**Issue by hxguo** [dream-num/univer#2753]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.2

### 复现链接

在@univerjs/sheets-drawing-ui的SheetCanvasFloatDomManagerService类中向浮动dom传递props时，props值取自_domLayerMap。
但是_domLayerMap只有在经过addFloatDomToPosition方法时才有赋值过程。这就导致如果是手动添加图层，即有经过addFloatDomToPosition方法时_domLayerMap才有值；如果是从快照中加载的，是没有经过addFloatDomToPosition方法，_domLayerMap是没有值的，从快照加载的最终时进入_drawingAddListener()，如下图：
![image](https://github.com/user-attachments/assets/7cdcb5d5-2158-4c57-b660-fe2c5cdc538c)
图中_drawingAddListener()内只有直接从_domLayerMap取props，实际上是空的，此时props应当可从param中获取(param是来自SHEET_DRAWING_PLUGIN插件快照的数据)。

### 预期行为

在@univerjs/sheets-drawing-ui的SheetCanvasFloatDomManagerService类中浮动dom的props在从快照中加载时，应当可以传递之前的props。之前的props可以种param中获取

### 实际行为

在从快照中加载浮动dom时，props无法传递

### 运行环境

Chrome

### 系统信息

 System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 15.98 GB / 31.77 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22000.120

**Comment by jikkai** [comment]
Could you plz help confirm this issue @weird94

**Comment by weird94** [comment]
fixed on
https://github.com/dream-num/univer/pull/2791/files#diff-dd163e96ae5b499d0357cba6841497d7954d57f00ecb98df0231b1f24a8aee3eR515
In case we don't store props internally, please use `SheetCanvasFloatDomManagerService.addHook` to register a hook to get props from outside.
---
我们在内部无法持久话存储props, 所以需要用户自行注册`SheetCanvasFloatDomManagerService.addHook`以从外部获得float-dom的props

**Comment by hxguo** [comment]
好的，等版本发布后我试一下。
原本是想可以从param中获取，因为我有把props存进快照里，从快照加载时会带有props信息。

**Comment by hxguo** [comment]
另外有一个小建议，期望addFloatDomToPosition方法返回的drawingId可以由外部传进去，而不是内部直接生成一个随机ID，随机ID可以是外部没传的情况下生成。这个ID会用做悬浮层内容容器的id，在业务上有比较重要的意义。
![image](https://github.com/user-attachments/assets/87344cad-ac53-4fc9-8418-fbf977970976)

**Comment by jikkai** [comment]
> 另外有一个小建议，期望addFloatDomToPosition方法返回的drawingId可以由外部传进去，而不是内部直接生成一个随机ID，随机ID可以是外部没传的情况下生成。这个ID会用做悬浮层内容容器的id，在业务上有比较重要的意义。 ![image](https://private-user-images.githubusercontent.com/9603098/350319285-87344cad-ac53-4fc9-8418-fbf977970976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODAzOTksIm5iZiI6MTcyMTM4MDA5OSwicGF0aCI6Ii85NjAzMDk4LzM1MDMxOTI4NS04NzM0NGNhZC1hYzUzLTRmYzktODQxOC1mYmY5Nzc5NzA5NzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDkwODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZmNGZiYTlkNDZmNzNiMjA1MDBkMGVhOWMyZmM0ZDZhMTIxYjIzYzVmMjRlMGVjNWQ5YmY5ODMxMTZjMDEwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Jwj7z1eVyJp1bw18JF6vBfU6D2UvgPllMca77fQ_hfs)

good catch! Let me create a new issue for it.
