### ISSUE TITLE
[Bug] univer:locales doesn't has 'zhTW' module in univer v0.2.3

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#2771]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.3

### Reproduction link

I have updated univer to v0.2.3, will `@univerjs/vite-plugin` have to update for locale module ?
because I use Univer Plugins: `univer:locales` to import my language

```
import { zhCN, enUS } from 'univer:locales'
``` 

but something is error when I import `zhTW`

```
import { zhCN, enUS, zhTW } from 'univer:locales'
``` 

error:
```
The requested module '/@id/__x00__univer:locales' does not provide an export named 'zhTW' 
```

### Expected behavior

I can import zhTW by use `univer:locales`

### Actual behavior

has error
```
The requested module '/@id/__x00__univer:locales' does not provide an export named 'zhTW' 
```

**Comment by jikkai** [comment]
Please upgrade `@univerjs/vite-plugin` to version 0.5.0.
