### ISSUE TITLE
[Feature] Insert rows, columns and merge cells API

### ISSUE THREAD

**Issue by Gocgo** [dream-num/univer#2774]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

请问univer是否提供了插入行、列及合并单元格API，通过调用api就可以实现在某一行（列）下插入n行（列），以及合并指定区域的单元格，在univer官方文档及issue中均未查询到相关接口，劳烦解答，不胜感激。
![123](https://github.com/user-attachments/assets/68eb4343-eacd-4abb-8c1d-f7b19121b9fc)

### 解决方案

可以提供相应的api

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/facade/general-api#execute-commands

https://univer.ai/typedoc/@univerjs/sheets/variables/InsertRowCommand
https://univer.ai/typedoc/@univerjs/sheets/variables/AddWorksheetMergeAllCommand
