### ISSUE TITLE
[Bug] formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I) don't work!

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2778]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.2

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I)  work

### Actual behavior

The formula doesn't work

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Comment by Picktarget** [comment]
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts here is my reproduction

**Comment by Picktarget** [comment]
@jikkai there is no re-open button for me

**Comment by jikkai** [comment]
> https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts here is my reproduction

It's just an official demo, not your repro.

**Comment by Picktarget** [comment]
@jikkai https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue how about this? I just make a new repo to reproduce it

**Comment by jikkai** [comment]
> @jikkai https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue how about this? I just make a new repo to reproduce it

This is still an invalid repro.

**Comment by Picktarget** [comment]
@jikkai please try it again https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue I just commit my changes failed due to the network T.T

**Comment by jikkai** [comment]
@Dushusir Should have a look.

**Comment by Dushusir** [comment]
We will process it as soon as possible

**Comment by Picktarget** [comment]
@Dushusir hello Is there any progress?

**Comment by Dushusir** [comment]
fixed

**Comment by Picktarget** [comment]
@Dushusir maybe u should test with the link https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue . It happens if I render formula from workbook data
