### ISSUE TITLE
 [Bug] formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I) don't work! 

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2781]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.3

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts

### Expected behavior

the formula works good

### Actual behavior

the formula doesn't work

**Comment by jikkai** [comment]
Duplicate of #2778

Please do not abuse issues.

**Comment by Picktarget** [comment]
the link u can't see it?
