### ISSUE TITLE
[Bug] setWorkbookEditable does not exist

### ISSUE THREAD

**Issue by Colory** [dream-num/univer#2794]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.3

### 复现链接

无

### 预期行为

执行成功

### 实际行为

执行不到

### 运行环境

Chrome

### 系统信息

```
  System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 50.26 GB / 95.67 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22000.120
```

**Comment by Colory** [comment]
同时 `np.getActiveWorkbook()?.setEditable(false)` 不能即时执行。需要延时setTimeout才能生效。我想知道怎么挂到合适的声明周期上

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
