### ISSUE TITLE
[Bug] I used the facade's setEditable() method to change the workbook to read-only, but the workbook is still editable

### ISSUE THREAD

**Issue by ForSakuraLove** [dream-num/univer#2800]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.3

### Reproduction link

https://github.com/awesome-univer/sheets-react-demo.git
这是提供的react的demo，我只加了只读的代码
const unvierAPI = FUniver.newAPI(univer);
    const workbook = unvierAPI.getActiveWorkbook()
    if (!workbook) {
      console.log('workbook not found')
      return
    }
    workbook.setEditable(false)
![微信图片_20240717173411](https://github.com/user-attachments/assets/cf02c4ca-8798-4154-a6ae-7c9a89bfcb27)

### Expected behavior

工作簿只读

### Actual behavior

工作簿可查看和可编辑

### System information

System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
    Memory: 2.38 GB / 19.79 GB
  Binaries:
    Node: 18.20.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.19041.4355

**Comment by ruckyshao** [comment]
看之前帖子要放到setTimeout中执行才能有效，这玩意也困扰我好久

**Comment by jikkai** [comment]
@ybzky Should have a look 👀

**Comment by ForSakuraLove** [comment]
![image](https://github.com/user-attachments/assets/bf68a903-89f1-4f0c-ae95-fb23c3780425)
确实加个延时就好了
