### ISSUE TITLE
[Bug] When setting up a large amount of data verification (10,000 rows), the page for adding and deleting rows crashes. For 1,000 rows, the page will not crash but there will be a very obvious lag.

### ISSUE THREAD

**Issue by kiki1992** [dream-num/univer#2807]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

2.2.3

### Reproduction link

https://stackblitz.com/edit/github-hnthoz-qx1iyp

### Expected behavior

设置大量数据验证时也可以正常新增/删除行

### Actual behavior

新增删除行处理非常耗时，非常大概率崩溃，初步排查发现应该是data-validation.mutation.updateRule指令处理性能存在问题

**Comment by weird94** [comment]
Fixed on https://github.com/dream-num/univer/pull/2810
Please follow univer version 0.2.4, will published on this friday
