### ISSUE TITLE
[Feature] expected  the refresh functions or ways when the workbook or worksheet data changed

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2808]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

when I changed the workbook's data I don't find any ways to update my univer views? eg. when I push a new sheet in sheets property and sheetOrder

### Solution

maybe there is a refresh function that I can update univer views

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/getting-started/installation#modifying-data

**Comment by elia-ba** [comment]
@jikkai  The link provided doesn't exist anymore.
