### ISSUE TITLE
[Bug] When using vue3 components, many empty divs will be repeatedly created

### ISSUE THREAD

**Issue by hxguo** [dream-num/univer#2818]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.2

### 复现链接

在ComponentManager中注册一个vue3组件，如：
`this.disposeWithMe(this._componentManager.register(CHART_COMPONENT_KEY, Vue3Chart, {framework: 'vue3'}))`
使用SheetCanvasFloatDomManagerService类提供的addFloatDomToPosition方法添加一个悬浮图表，如图：
![image](https://github.com/user-attachments/assets/ca3a6f74-9981-4ce5-80ff-eb5bb00e6d15)
在这个悬浮图表拖拽过程中，会产生很多空div，如下图：
![image](https://github.com/user-attachments/assets/ad6dbab0-f19f-4718-afa7-e2f01dfda264)
产生的原因猜测是在FloatDom.tsx中，position发生变化，由于Component没有用useMemo包裹，也导致刷新从而变成从componentManager.get(layer.componentKey)重新获取，而componentManager.get方法中vue3组件会往document.body中添加div，最终导致悬浮图表的vue3组件会不停的往body添加空div。
![image](https://github.com/user-attachments/assets/2c866a50-ff80-4ba1-b727-3ffcbaad7637)
![image](https://github.com/user-attachments/assets/5210413e-0dda-4ac9-ab8a-55e6d3a5838b)

### 预期行为

悬浮层在使用vue3控件时，应当只要渲染一次组件，而不是在移动悬浮层时重复渲染vue3组件

### 实际行为

在悬浮层中的vue3组件，在移动悬浮层过程中会不断的重新渲染vue3组件，有时会导致移动过程中出现空白

### 运行环境

Chrome

### 系统信息

 System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 11.03 GB / 31.77 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22000.120

**Comment by jikkai** [comment]
We have confirmed the issue, but due to limited resources, it will not be fixed quickly and may require additional waiting time.
