### ISSUE TITLE
[Feature] When the input box type is a data field, I don’t want the user to be able to input by pressing the keyboard

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#2823]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

[Feature] 当我点击一个输入框的时候 我给这个输入框设置了不同的类型 假设有两个类型普通文本 数据字段 当是数据字段的时候我不想用户可以通过选中框 按下键盘之后输入。我看了源码没找到我能处理拦截的地方

### Solution

期望可以通过某种方式去屏蔽

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/facade/general-api#listening-commands-before-execution
