### ISSUE TITLE
[Bug] Create a new univer table, the scroll wheel does not dynamically change to adapt to the table content

### ISSUE THREAD

**Issue by ForSakuraLove** [dream-num/univer#2836]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.4

### Reproduction link

The import example on the official website, I used it to import Excel, the scroll wheel did not adapt, I needed to change the row height, then the scroll wheel would adapt. My own creation is the same, so I won't show it.
![image](https://github.com/user-attachments/assets/fb667c49-2474-4a7f-a6dd-da95684aa593)

### Expected behavior

Scroll wheel requires adaptive content

### Actual behavior

Scroll wheel has no adaptive content

### System information

System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
    Memory: 5.89 GB / 19.79 GB
  Binaries:
    Node: 18.20.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.19041.4355

**Comment by lumixraku** [comment]
@ForSakuraLove Is this issue still present? I was unable to reproduce it.

I am uploading this excel file.
[manycol.xlsx](https://github.com/user-attachments/files/16621365/manycol.xlsx)

**Comment by ForSakuraLove** [comment]
@lumixraku This problem still exists. I use the Excel file you uploaded, but it still doesn't show all
![image](https://github.com/user-attachments/assets/f0dcc4c6-8877-437e-aa43-d954d433ab75)

**Comment by MurphyHou123** [comment]
I have the same issue now. the maximum show rows are 42. actually the totall rows are 1000.
![image](https://github.com/user-attachments/assets/25668443-0821-4378-b0f2-267d93513ad3)
