### ISSUE TITLE
[Bug] data-validation plugin  dropdown change cellData custom be override.

### ISSUE THREAD

**Issue by mietl** [dream-num/univer#2846]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.4

### Reproduction link

![image](https://github.com/user-attachments/assets/0b43cc32-24c2-4599-b692-705b010ec30c)

### Expected behavior

the custom I saved is override.

### Actual behavior

custom : {
                            __link_url: '',
}

### System information

  System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M2
    Memory: 56.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 18.0

**Comment by jikkai** [comment]
Please describe your problem in detail. If you cannot describe it clearly in English, 你也可以使用中文。

**Comment by mietl** [comment]
> Please describe your problem in detail. 如果你无法使用英语清楚地描述，你也可以使用中文。
> 
> 由于缺乏足够的信息，我们暂时关闭了此问题。如果您可以提供最小限度的复现，请随时重新打开它。

非常抱歉，我没有描述清楚 以下是我的最小重现(https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-rgvdmj?file=src%2Fassets%2Fdefault-workbook-data.ts) 

### 重现步骤

步骤1 

![image](https://github.com/user-attachments/assets/0e12f650-af48-4387-9037-89bacef67c15)


步骤2

![image](https://github.com/user-attachments/assets/9dddbf2a-7514-4381-860c-199ca1af59b3)

步骤3 通过下拉选择修改值

![image](https://github.com/user-attachments/assets/6ac9a5f0-fdf7-4335-b611-e64e33adbe8f)



我不确定这是不是bug，  但我的自定义字段被覆盖了

**Comment by mietl** [comment]
> Please describe your problem in detail. 如果你无法使用英语清楚地描述，你也可以使用中文。
> 
> We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

I haven't found a way to reopen it. Do you mean to initiate a new issue?

**Comment by jikkai** [comment]
@Dushusir It might be a case that needs confirmation.

**Comment by mietl** [comment]
> @Dushusir It might be a case that needs confirmation.

This problem has always existed.

**Comment by mietl** [comment]
close  https://github.com/dream-num/univer/pull/3365
