### ISSUE TITLE
[Bug] Wide Worksheet Gets Cut Off

### ISSUE THREAD

**Issue by Matt-Jensen** [dream-num/univer#2856]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.4

### Reproduction link

https://github.com/Matt-Jensen/wide-sheets-bug-demo
[Source spreadsheet available here](https://docs.google.com/spreadsheets/d/128ecmUeMrqvSZk8gSQkDOr-yxqX3BMgPWiK4-f0PRDI/edit?usp=sharing).

### Expected behavior

When I input a Workbook with more columns beyond "T" I expect that they all be rendered in the UI.
When I reference columns beyond "T" they should not throw #NAME! errors.

### Actual behavior

The UI only render until column "T" and clips call columns after that.
Referencing columns beyond "T" causes #NAME! issues (for example `=AI1` should be "ZIP Code" however throws #NAME!)

### System information

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5

**Comment by hexf00** [comment]
This is not a bug. For optimal performance, you need to determine the maximum row and column count of your sheet by configuring `rowCount: 1000, columnCount: 20`. 

You can refer to the IWorksheetData definition at [https://univer.ai/typedoc/@univerjs/core/interfaces/IWorksheetData](https://univer.ai/typedoc/@univerjs/core/interfaces/IWorksheetData).

**Comment by Matt-Jensen** [comment]
Thank you!
