### ISSUE TITLE
[Bug] The table displays abnormally after updating to 0.2.5

### ISSUE THREAD

**Issue by corey77** [dream-num/univer#2860]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

你们的在线版本是0.2.3,
BUG操作步奏:
从0.2.4更新为0.2.5版本,代码使用的是官网最基础的核心功能:
import { Univer, UniverInstanceType } from '@univerjs/core'
import { defaultTheme } from '@univerjs/design'

import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula'
import { UniverRenderEnginePlugin } from '@univerjs/engine-render'

import { UniverUIPlugin } from '@univerjs/ui'

import { UniverDocsPlugin } from '@univerjs/docs'
import { UniverDocsUIPlugin } from '@univerjs/docs-ui'

import { UniverSheetsPlugin } from '@univerjs/sheets'
import { UniverSheetsFormulaPlugin } from '@univerjs/sheets-formula'
import { UniverSheetsUIPlugin } from '@univerjs/sheets-ui'
import { LocaleType, Tools } from '@univerjs/core'
import DesignZhCN from '@univerjs/design/locale/zh-CN'
import DocsUIZhCN from '@univerjs/docs-ui/locale/zh-CN'
import SheetsZhCN from '@univerjs/sheets/locale/zh-CN'
import SheetsUIZhCN from '@univerjs/sheets-ui/locale/zh-CN'
import SheetsFormulaZhCN from '@univerjs/sheets-formula/locale/zh-CN'
import UIZhCN from '@univerjs/ui/locale/zh-CN'

const univer = new Univer({
  theme: defaultTheme,
  locale: LocaleType.ZH_CN,
  locales: {
    [LocaleType.ZH_CN]: Tools.deepMerge(DesignZhCN, DocsUIZhCN, SheetsZhCN, SheetsUIZhCN, SheetsFormulaZhCN, UIZhCN)
  }
})
univer.registerPlugin(UniverRenderEnginePlugin)
univer.registerPlugin(UniverFormulaEnginePlugin)

univer.registerPlugin(UniverUIPlugin, {
  header: true,
  footer: true,
  container: 'corey'
})

univer.registerPlugin(UniverDocsPlugin, {
  hasScroll: false
})
univer.registerPlugin(UniverDocsUIPlugin)

univer.registerPlugin(UniverSheetsPlugin)
univer.registerPlugin(UniverSheetsUIPlugin)
univer.registerPlugin(UniverSheetsFormulaPlugin)

univer.createUnit(UniverInstanceType.UNIVER_SHEET, {})

html为:
<div id="corey" style="width: 1910px; height: 100%"></div>

### 预期行为

显示表格

### 实际行为

![1721984486084](https://github.com/user-attachments/assets/8b151814-6be2-47c4-9b42-d2fb57cae5ec)

### 运行环境

Chrome

### 系统信息

System:                                                     
    OS: Windows 10 10.0.19045                                 
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz    
    Memory: 1.04 GB / 47.74 GB                                
  Binaries:                                                   
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE          
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD              
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD            
  Browsers:                                                   
    Edge: Chromium (111.0.1661.62), ChromiumDev (113.0.1774.3)
    Internet Explorer: 11.0.19041.4355

**Comment by jikkai** [comment]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/a99acdfb-9619-400f-a4e7-ac83fef6d191">

We are unable to reproduce the issue you mentioned. Please provide a reproducible example.
