### ISSUE TITLE
[Feature] Can the function menu expose hidden ports?

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#2861]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

我们的系统不需要内置的函数 有自己实现的函数所以像屏蔽掉函数菜单

### Solution

根别的菜单一样 把hidden属性透出来

**Comment by jikkai** [comment]
You can hide it and implement the desired functions through a custom plugin. For details, please refer to the documentation.

https://univer.ai/guides/sheet/advanced/custom-ui#customizing-menu-items-hiding-menu-items
https://univer.ai/guides/sheet/advanced/custom-formula

**Comment by 840251442** [comment]
'formula-ui.operation.insert-function'  我用了这个id 没生效别的菜单都生效了

**Comment by 840251442** [comment]
@jikkai formula-ui.operation.insert-function 这个id写上去没有生效

**Comment by elonzh** [comment]
> You can hide it and implement the desired functions through a custom plugin. For details, please refer to the documentation.
> 
> [univer.ai/guides/sheet/advanced/custom-ui#customizing-menu-items-hiding-menu-items](https://univer.ai/guides/sheet/advanced/custom-ui#customizing-menu-items-hiding-menu-items) [univer.ai/guides/sheet/advanced/custom-formula](https://univer.ai/guides/sheet/advanced/custom-formula)

I couldn't find the command id for the insert function menu item either, if you think you can solve it, please provide it.
