### ISSUE TITLE
[Feature] More Engineering Formulas

### ISSUE THREAD

**Issue by wpxp123456** [dream-num/univer#2872]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

[How to contribute formulas](https://univer.ai/guides/sheet/advanced/custom-formula#how-to-add-formulas-in-formula-engine)

#### Engineering formulas
- [x] BESSELI
- [x] BESSELJ
- [x] BESSELK
- [x] BESSELY
- [x] BIN2DEC
- [x] BIN2HEX
- [x] BIN2OCT
- [x] BITAND
- [x] BITLSHIFT
- [x] BITOR
- [x] BITRSHIFT
- [x] BITXOR
- [x] COMPLEX
- [x] CONVERT
- [x] DEC2BIN
- [x] DEC2HEX
- [x] DEC2OCT
- [x] DELTA
- [x] ERF
- [x] ERF.PRECISE
- [x] ERFC
- [x] ERFC.PRECISE
- [x] HEX2BIN
- [x] HEX2DEC
- [x] HEX2OCT
- [x] OCT2BIN
- [x] OCT2DEC
- [x] OCT2HEX

**Comment by zhaolixin7** [comment]
@wpxp123456 贝塞尔函数
<img width="1537" alt="image" src="https://github.com/user-attachments/assets/5fb8d829-6b85-4522-bf2e-0d2570374ec4">

**Comment by zhaolixin7** [comment]
BIN2HEX  1、参数为（1000000，100000）时表格白屏
[2024_8_10 14_54_26 commands.json](https://github.com/user-attachments/files/16568763/2024_8_10.14_54_26.commands.json)
[2024_8_10 14_54_26 video.webm](https://github.com/user-attachments/assets/45b3661c-c6d3-4617-a85f-1ab6495fb548)

**Comment by zhaolixin7** [comment]
1、INDIRECT其他产品结果显示#num![image](https://github.com/user-attachments/assets/52301b08-c98f-4761-94e3-3a008aea0361)

**Comment by zhaolixin7** [comment]
BITLSHIFT  1、引用单元格，单元格为31时计算和及其他产品不一致
![image](https://github.com/user-attachments/assets/6109f431-e285-42dc-9593-418bebbf1f4f)

**Comment by zhaolixin7** [comment]
Bitor 1、参数超过10位时计算结果错误
![image](https://github.com/user-attachments/assets/b2da6aa6-4234-4b1a-8a61-53cd5d3be34e)

**Comment by zhaolixin7** [comment]
@wpxp123456 erf  1、ERF(-5,)，参数为-5或5时结果结果其他产品不一致，其他的等于1，我们显示小数
![image](https://github.com/user-attachments/assets/55daee23-a79d-4276-965c-90e2f4c724d5)

**Comment by zhaolixin7** [comment]
@wpxp123456  erfc不同参数和其他产品结果都不太一样（）
![image](https://github.com/user-attachments/assets/139c46f4-00bb-4c16-b344-1a1bdf2883af)

**Comment by zhaolixin7** [comment]
HEX2BIN  1、空参数报#num
![image](https://github.com/user-attachments/assets/73016669-c613-47b3-b904-201c0b5eb01d)

**Comment by zhaolixin7** [comment]
OCT2BIN 空参数报#num
![image](https://github.com/user-attachments/assets/f2cf44d5-2c77-4372-b58a-7c87c9d2b826)
