### ISSUE TITLE
[Bug] Enter special matches in cells! @#￥%……&*() will trigger websocket to disconnect

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#2874]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

在单元格内 输入特殊符合！@#￥%……&*（） 会触发websocket 断开连接

### 预期行为

不要断开连接

### 实际行为

会触发websocket断开连接

### 运行环境

Chrome

**Comment by jikkai** [comment]
We are unable to reproduce this issue. Please provide a reproduction.

We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
