### ISSUE TITLE
How to manually set the merge of cells

### ISSUE THREAD

**Issue by yanjiangao** [dream-num/univer#2875]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

如何手动设置单元格的合并

### 解决方案

提供一个方法可以实现单元格的合并，我查询了官方的文档没有发现类似的方法。

**Comment by jikkai** [comment]
I bet you haven't carefully read the document.

https://univer.ai/guides/sheet/facade/general-api#execute-commands

https://univer.ai/typedoc/@univerjs/sheets-ui/variables/AddWorksheetMergeAllCommand

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/facade/general-api#execute-commands

https://univer.ai/typedoc/@univerjs/sheets-ui/variables/AddWorksheetMergeAllCommand

**Comment by yanjiangao** [comment]
不好意思，我还是不太明白，可以给我一个示例吗？万分感谢

**Comment by dxj0211** [comment]
> 不好意思，我还是不太明白，可以给我一个示例吗？万分感谢

你好，可以借鉴一下吗
