### ISSUE TITLE
[Feature] Export `ISetFrozenCommandParams` interface

### ISSUE THREAD

**Issue by tifandotme** [dream-num/univer#2877]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

It's weird that `ISetFrozenMutationParams` is exported but `ISetFrozenCommandParams` does not. I've run into a use case where I need the interface but found that it doesn't export 

### Solution

Export it?

**Comment by jikkai** [comment]
`ISetFrozenMutationParams` is used by sheets-ui and sheets-drawing-ui, therefore it is exported. `ISetFrozenCommandParams`, on the other hand, is only used within sheets. If you really need it, you can try submitting a PR to export it.

**Comment by tifandotme** [comment]
Actually, my requirements have changed, and this is no longer needed. Nevertheless, Thank you for the response.
