### ISSUE TITLE
[Bug] Cannot find "univer.doc.text-selection-render-manager" registered by any injector

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2880]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.15

### Reproduction link

 "@univerjs/core": "0.1.15",
    "@univerjs/design": "0.1.15",
    "@univerjs/docs": "0.1.15",
    "@univerjs/docs-ui": "0.1.15",
    "@univerjs/engine-formula": "0.1.15",
    "@univerjs/engine-render": "0.1.15",
    "@univerjs/facade": "0.1.15",
    "@univerjs/sheets": "0.1.15",
    "@univerjs/sheets-drawing-ui": "0.1.15",
    "@univerjs/sheets-formula": "0.1.15",
    "@univerjs/sheets-ui": "0.1.15",
    "@univerjs/sheets-zen-editor": "0.1.15",
    "@univerjs/ui": "0.1.15",
    "@univerjs/webpack-plugin": "0.4.3",

import { Univer, UniverInstanceType, LocaleType, Tools } from "@univerjs/core";
import { defaultTheme } from "@univerjs/design";
import { UniverDocsPlugin } from "@univerjs/docs";
import { UniverDocsUIPlugin } from "@univerjs/docs-ui";
import { UniverFormulaEnginePlugin } from "@univerjs/engine-formula";
import { UniverRenderEnginePlugin } from "@univerjs/engine-render";
import { UniverSheetsPlugin } from "@univerjs/sheets";
import { UniverSheetsFormulaPlugin } from "@univerjs/sheets-formula";
import { UniverSheetsUIPlugin } from "@univerjs/sheets-ui";
import { UniverUIPlugin } from "@univerjs/ui";
import { UniverSheetsDrawingUIPlugin } from '@univerjs/sheets-drawing-ui';
import SheetsDrawingUIZhCN from '@univerjs/sheets-drawing-ui/locale/zh-CN';
import '@univerjs/sheets-zen-editor/lib/index.css';
import { UniverSheetsZenEditorPlugin } from '@univerjs/sheets-zen-editor';
import SheetsZenEditorZhCN from '@univerjs/sheets-zen-editor/locale/zh-CN';
import { FUniver } from "@univerjs/facade";

import { zhCN, enUS } from 'univer:locales'
// TODO:
import "@univerjs/sheets-ui/lib/index.css";

          let _this = this;
                        const univer = new Univer({
                                theme: defaultTheme,
                                locale: LocaleType.zhCN,
                                locales: {
                                        [LocaleType.ZH_CN]: Tools.deepMerge(
                                                zhCN,
                                                SheetsDrawingUIZhCN,
                                                SheetsZenEditorZhCN
                                        ),
                                        [LocaleType.EN_US]: enUS,
                                },
                        });
                        this.univer = univer;

                        // core plugins
                        univer.registerPlugin(UniverRenderEnginePlugin);
                        univer.registerPlugin(UniverFormulaEnginePlugin);
                        univer.registerPlugin(UniverUIPlugin, {
                                container: this.$refs.container,
                                header: false,
                        });

                        // doc plugins
                        univer.registerPlugin(UniverDocsPlugin, {
                                hasScroll: false,
                        });
                        univer.registerPlugin(UniverDocsUIPlugin);

                        // sheet plugins
                        univer.registerPlugin(UniverSheetsPlugin);
                        univer.registerPlugin(UniverSheetsUIPlugin);
                        univer.registerPlugin(UniverSheetsFormulaPlugin);

                        // drawing
                        univer.registerPlugin(UniverSheetsDrawingUIPlugin);
                        // 蝉编译器
                        univer.registerPlugin(UniverSheetsZenEditorPlugin);

                        // create workbook instance
                        this.workbook = univer.createUnit(UniverInstanceType.UNIVER_SHEET, this.excelData);

                        var univerAPI = FUniver.newAPI(univer);
                        this.univerAPI = univerAPI;

                        const activeWorkbook = univerAPI.getActiveWorkbook();
                        activeWorkbook.onSelectionChange((selection) => {
                                if (selection.length > 0) {
                                        const row = selection[0].startRow;
                                        const column = selection[0].startColumn;
                                        if (!_this.sheetLoading) {
                                                _this.getCurrenCellSelectedCell(row, column);
                                        }
                                }
                        });
                        univerAPI.onCommandExecuted((command) => {
                                if (command.id === "sheet.operation.set-cell-edit-visible" && command.params.visible) {
                                        console.log("Cell edit visible true");
                                        _this.isEditing = true;
                                }
                                if (command.id === "sheet.operation.set-cell-edit-visible" && !command.params.visible) {
                                        console.log("Cell edit invisible false");
                                        _this.isEditing = false;
                                }
                        });
<img width="1079" alt="截屏2024-07-30 09 25 49" src="https://github.com/user-attachments/assets/e44e2d79-9be1-4bd8-a0d1-8da0320c3543">

### Expected behavior

点击单元格的时候不要报错

### Actual behavior

报错

### System information

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 92.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/node
    Yarn: 4.3.1 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/npm
    pnpm: 9.3.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v20.14.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 17.0

**Comment by jikkai** [comment]
Please upgrade to the latest version.

**Comment by feige-2011** [comment]
我就是从最新版本退回来的，因为最新的版本也报同样的错误
