### ISSUE TITLE
[Feature]How to dynamically set rowCount?

### ISSUE THREAD

**Issue by GJDevil** [dream-num/univer#2881]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

怎么才能动态设置rowCount呢？

### Solution

111

**Comment by jikkai** [comment]
For such issues, please read the documentation first instead of seeking help through GitHub Issues.

**Comment by GJDevil** [comment]
> For such issues, please read the documentation first instead of seeking help through GitHub Issues.

要知道就说  不知道就说不知道，你怎么知道我没看文档呢
