### ISSUE TITLE
[Bug] Cannot find "univer.doc.text-selection-render-manager" registered by any injector

### ISSUE THREAD

**Issue by feige-2011** [dream-num/univer#2886]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.5

### Reproduction link

 "@univerjs/core": "0.2.5",
    "@univerjs/design": "0.2.5",
    "@univerjs/docs": "0.2.5",
    "@univerjs/docs-ui": "0.2.5",
    "@univerjs/engine-formula": "0.2.5",
    "@univerjs/engine-render": "0.2.5",
    "@univerjs/facade": "0.2.5",
    "@univerjs/sheets": "0.2.5",
    "@univerjs/sheets-drawing-ui": "0.2.5",
    "@univerjs/sheets-formula": "0.2.5",
    "@univerjs/sheets-ui": "0.2.5",
    "@univerjs/sheets-zen-editor": "0.2.5",
    "@univerjs/ui": "0.2.5", 
"@univerjs/webpack-plugin": "0.4.3",

import { Univer, UniverInstanceType, LocaleType, Tools } from "@univerjs/core";
import { defaultTheme } from "@univerjs/design";
import { UniverDocsPlugin } from "@univerjs/docs";
import { UniverDocsUIPlugin } from "@univerjs/docs-ui";
import { UniverFormulaEnginePlugin } from "@univerjs/engine-formula";
import { UniverRenderEnginePlugin } from "@univerjs/engine-render";
import { UniverSheetsPlugin } from "@univerjs/sheets";
import { UniverSheetsFormulaPlugin } from "@univerjs/sheets-formula";
import { UniverSheetsUIPlugin } from "@univerjs/sheets-ui";
import { UniverUIPlugin } from "@univerjs/ui";
import { UniverSheetsDrawingUIPlugin } from '@univerjs/sheets-drawing-ui';
import SheetsDrawingUIZhCN from '@univerjs/sheets-drawing-ui/locale/zh-CN';
import '@univerjs/sheets-zen-editor/lib/index.css';
import { UniverSheetsZenEditorPlugin } from '@univerjs/sheets-zen-editor';
import SheetsZenEditorZhCN from '@univerjs/sheets-zen-editor/locale/zh-CN';
import { FUniver } from "@univerjs/facade";

     let _this = this;
                        const univer = new Univer({
                                theme: defaultTheme,
                                locale: LocaleType.zhCN,
                                locales: {
                                        [LocaleType.ZH_CN]: Tools.deepMerge(
                                                zhCN,
                                                SheetsDrawingUIZhCN,
                                                SheetsZenEditorZhCN
                                        ),
                                        [LocaleType.EN_US]: enUS,
                                },
                        });
                        this.univer = univer;

                        // core plugins
                        univer.registerPlugin(UniverRenderEnginePlugin);
                        univer.registerPlugin(UniverFormulaEnginePlugin);
                        univer.registerPlugin(UniverUIPlugin, {
                                container: this.$refs.container,
                                header: false,
                        });

                        // doc plugins
                        univer.registerPlugin(UniverDocsPlugin, {
                                hasScroll: false,
                        });
                        univer.registerPlugin(UniverDocsUIPlugin);

                        // sheet plugins
                        univer.registerPlugin(UniverSheetsPlugin);
                        univer.registerPlugin(UniverSheetsUIPlugin);
                        univer.registerPlugin(UniverSheetsFormulaPlugin);

                        // drawing
                        univer.registerPlugin(UniverSheetsDrawingUIPlugin);
                        // 蝉编译器
                        univer.registerPlugin(UniverSheetsZenEditorPlugin);

                        // create workbook instance
                        this.workbook = univer.createUnit(UniverInstanceType.UNIVER_SHEET, this.excelData);

                        var univerAPI = FUniver.newAPI(univer);
                        this.univerAPI = univerAPI;

                        const activeWorkbook = univerAPI.getActiveWorkbook();
<img width="1079" alt="截屏2024-07-30 09 25 49" src="https://github.com/user-attachments/assets/ad0460ee-23f1-4952-96c6-0977930226c2">

### Expected behavior

点击表格不报错

### Actual behavior

点击表格报错
![Uploading 截屏2024-07-30 09.25.49.png…]()

### System information

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v18.6.0/bin/node
    npm: 8.13.2 - /opt/homebrew/Cellar/nvm/0.39.7/versions/node/v18.6.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 17.0

**Comment by feige-2011** [comment]
试了 0.1.15   0.2.1 和0.2.5 都是同样的问题，之前没有问题，更新过一次版本后，再怎么更新都会有问题

**Comment by jikkai** [comment]
请提供可复现问题的链接或者 demo，请不要重复提交同样类型的问题。

**Comment by zifeiyuSun** [comment]
I alse have meet this problem. Did you solve it ?

**Comment by Lime-song** [comment]
> I also have meet this problem. Did you solve it ?
> And I try delete package.lock.json and node_moudules, retry npm i , but still not work.

I also have meet this problem. Did you solve it ?
And I try delete package.lock.json and node_moudules, retry npm i , but still not work.
