### ISSUE TITLE
[Bug] when i use right click at sheet, edit protection of the sheet such as close copy, reopen the sheet setting the settings is empty.

### ISSUE THREAD

**Issue by keandfan** [dream-num/univer#2887]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

![image](https://github.com/user-attachments/assets/9fad5ec3-c574-4e4d-8a40-35744039286d)

### 预期行为

show the sheet setting as I open the sheet auth like first time.

### 实际行为

sheet auth setting is empty

### 运行环境

Chrome

### 系统信息

  System:
    OS: macOS 12.6.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 645.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 3.10.10 - ~/node_modules/.bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.72
    Safari: 15.6.1

**Comment by jikkai** [comment]
Please provide a reproduction.

**Comment by keandfan** [comment]
https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-ttnufu?file=src%2Fcomponents%2FUniverSheet.vue
![image](https://github.com/user-attachments/assets/d66d4dd3-6c04-452a-9692-6d9afb10b716)
first time change copy,second time open this will show

**Comment by jikkai** [comment]
This doesn't seem to be a bug. Some explanations should be provided for this feature, or some restrictions should be implemented at the code level. @ybzky.

**Comment by ybzky** [comment]
This has been fixed and will be released in the next version, but here is a mock data. We will not provide a server in the SDK, so if you want this function to work properly, you need to implement IoService yourself.
