### ISSUE TITLE
[Bug] DataValidation config ui bug

### ISSUE THREAD

**Issue by keandfan** [dream-num/univer#2889]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

![image](https://github.com/user-attachments/assets/e9cbe80c-8e2d-4d70-9b5d-fbc48707463c)
![image](https://github.com/user-attachments/assets/aa7f48fd-f08d-4c5b-a611-477172b35b8d)
![image](https://github.com/user-attachments/assets/07c67ec1-466b-42cf-b1ca-96e81fedf8c8)

### 预期行为

dropdown item show fine

### 实际行为

dropdown item offset

**Comment by keandfan** [comment]
https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-ttnufu

**Comment by weird94** [comment]
@jikkai 
![WeChatWorkScreenshot_4a9acc78-2df8-4d4f-b40d-30b0c311179f](https://github.com/user-attachments/assets/f07fdd6a-c245-4931-bc77-024df3a5e8c2)
gou jian chan wu构建产物内react-grid-layout相关的样式丢失了，麻烦看下
