### ISSUE TITLE
[Bug] After cell protection, the freeze button is grayed out. I hope cell protection and freeze will not interfere with each other.

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#2894]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

单元格保护后， 冻结按钮置灰了，希望单元格保护和 冻结 不互相干扰

### 预期行为

单元格保护后和 冻结 不互相干扰

### 实际行为

单元格保护后， 冻结按钮置灰了，无法进行冻结

### 运行环境

Chrome

**Comment by nanguaye** [comment]
补充链接：https://stackblitz.com/edit/github-hnthoz-qx1iyp?file=src%2Fcomponents%2FUniverSheet%2Findex.jsx
操作步骤： 选中第二行 然后 右键去冻结（冻结功能置灰 不可使用）

**Comment by nanguaye** [comment]
补充： univerAPI.getActiveWorkbook().setEditable(false); 设置整个需求表 不可编辑后， 冻结功能 也被被置灰了，期望可以进行冻结， 理由： 因为 需求表 第一行可能是一些表头 等等，那么 往下滚动后，用户可能也希望 第一行能被冻结在那，这样方便数据的查看。

**Comment by Gggpound** [comment]
你可以先冻结，再setEditable(false)
