### ISSUE TITLE
[Bug] Filtering does not take effect when range protection is enabled 

### ISSUE THREAD

**Issue by kiki1992** [dream-num/univer#2896]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.5

### Reproduction link

https://stackblitz.com/edit/github-hnthoz-ofclhp

### Expected behavior

Filtering take effect even when range protection is enabled because it's not kind of modification

### Actual behavior

<img width="444" alt="pic" src="https://github.com/user-attachments/assets/561b0865-01ba-4672-8011-66d0681ad47b">

**Comment by ybzky** [comment]
Filter is also a collaborative operation that will affect table rendering, so it needs to be controlled by permissions.
