### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'findNodePositionByCharIndex')

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#2904]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.3

### 复现链接

註冊以下任何一個 plugins ，都會產生 `Cannot read properties of undefined (reading 'findNodePositionByCharIndex')
    at uw (index.js:31406:103)` error，我更新到 v0.2.5 也是一樣的問題

![截圖 2024-08-01 13 44 50](https://github.com/user-attachments/assets/37990590-eb88-4e39-bf38-5b0fb112ba99)

目前測試過加入這些 plugins 都有問題：

```
  univer.registerPlugin(UniverSheetsNumfmtPlugin)

  univer.registerPlugin(UniverDataValidationPlugin)
  univer.registerPlugin(UniverSheetsDataValidationPlugin)

  univer.registerPlugin(UniverSheetsConditionalFormattingPlugin)
  univer.registerPlugin(UniverSheetsConditionalFormattingUIPlugin)
```

### 预期行为

正常使用，沒有錯誤訊息

### 实际行为

出現 `Cannot read properties of undefined (reading 'findNodePositionByCharIndex')`

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please provide a reproduction.

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Comment by luckyguanxin** [comment]
我也有这个报错，在调整插件导入顺序后报错消失。

**Comment by mukiwu** [comment]
@luckyguanxin 不好意思，方便的話能分享一下你調整的順序依據嗎？感謝

**Comment by zhanghui6666** [comment]
_univer.registerPlugin(UniverSheetsExchangeClientPlugin);
把这个放在最后注册就不报错了，可能插件不一样 但是你可以按照这个思路试试看
