### ISSUE TITLE
[Bug] After inserting a hover image, change the image again, such as rotate, zoom in, move, and refresh the page, then it reverts back to the original state, without saving the latest state value.

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2928]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.5

### Reproduction link

The official example can be reproduced

### Expected behavior

Ability to change the value in the resource to save the latest state value.

### Actual behavior

After inserting a hover image, change the image again, such as rotate, zoom in, move, and refresh the page, then it reverts back to the original state, without saving the latest state value.

The value in the resource, which has not been changed, is resaved.
![image](https://github.com/user-attachments/assets/b44ee0b3-84a7-4873-bf4d-b49a528abf8f)

**Comment by jikkai** [comment]
Known issue, will be fixed soon.

**Comment by siam-ese** [comment]
Please provide a reproduction.
