### ISSUE TITLE
[Bug] If you enter a number into a cell, set the formatting and font size, and then modify the value of the cell again, the format will be lost.

### ISSUE THREAD

**Issue by aaxxww** [dream-num/univer#2934]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

https://univer.ai/zh-CN/examples/sheets
1.给某个单元格输入数字
2.给这个单元格设置格式[财务数值]，修改字体大小
3.点击其他单元格后重新点击此单元格，修改数值

### 预期行为

修改后的值应该带有格式

### 实际行为

![1722915492929](https://github.com/user-attachments/assets/a047a166-2936-49fa-95c8-971e5ddddb77)
没有格式

### 运行环境

Firefox

**Comment by jikkai** [comment]
Duplicate of https://github.com/dream-num/univer/issues/2207

It seems to be caused by the problem #2207. I will close this issue for now. Please follow the updates on #2207.
