### ISSUE TITLE
[Bug] Filtering Other Columns data disapear

### ISSUE THREAD

**Issue by Aminoragit** [dream-num/univer#2936]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

online example version

### Reproduction link

https://univer.ai/examples/sheets

### Expected behavior

Same as Excel After Filtering, do not disapear other columns data 

### Actual behavior

There is a problem that the style of another column is released when you apply the filter to the column in row 1 and actually filter it. See Image
![image](https://github.com/user-attachments/assets/3b87d3b2-5635-44cf-87ba-25efd3b2eafa)

**Comment by ybzky** [comment]
https://github.com/dream-num/univer/pull/2980 fixed
