### ISSUE TITLE
[Bug] mobile sheet bar container does not display normally because of scrollbar 

### ISSUE THREAD

**Issue by universeroc** [dream-num/univer#2969]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

![image](https://github.com/user-attachments/assets/9ecb95f3-662e-4dbe-8fc4-42338b1ce00d)

### Actual behavior

![image](https://github.com/user-attachments/assets/e55bc97a-be46-42a7-841e-f45e01b6a35a)

**Comment by wzhudev** [comment]
Have you tried to open this feature in the dev tool? 

![image](https://github.com/user-attachments/assets/65c4492a-5d23-41be-844d-f797523bf282)

Your PR seems impropriate because it would make the sheetbar unscrollable.

**Comment by universeroc** [comment]
> Have you tried to open this feature in the dev tool? Since the demo is for mobile, you should toggle it open.
> 
> ![image](https://private-user-images.githubusercontent.com/12122021/356069019-65c4492a-5d23-41be-844d-f797523bf282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY3NTgsIm5iZiI6MTcyMzE2NjQ1OCwicGF0aCI6Ii8xMjEyMjAyMS8zNTYwNjkwMTktNjVjNDQ5MmEtNWQyMy00MWJlLTg0NGQtZjc5NzUyM2JmMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGM5OGU4MTk2OTlhYjA1NzdjZDkyZDMyMTcxOGJkZTEzZmQ3MGY2MjZlYzdkM2U2ODZiMzVkODhiMTFiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z6OplntmNr1BiBeToXy6yDNtC-CKBIaJ5XanUvxocU)
> 
> Your PR seems impropriate because it would make the sheetbar unscrollable.

Yes, I did, all the same. :)

**Comment by universeroc** [comment]
> Have you tried to open this feature in the dev tool? Since the demo is for mobile, you should toggle it open.
> 
> ![image](https://private-user-images.githubusercontent.com/12122021/356069019-65c4492a-5d23-41be-844d-f797523bf282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY3NTgsIm5iZiI6MTcyMzE2NjQ1OCwicGF0aCI6Ii8xMjEyMjAyMS8zNTYwNjkwMTktNjVjNDQ5MmEtNWQyMy00MWJlLTg0NGQtZjc5NzUyM2JmMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGM5OGU4MTk2OTlhYjA1NzdjZDkyZDMyMTcxOGJkZTEzZmQ3MGY2MjZlYzdkM2U2ODZiMzVkODhiMTFiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z6OplntmNr1BiBeToXy6yDNtC-CKBIaJ5XanUvxocU)
> 
> Your PR seems impropriate because it would make the sheetbar unscrollable.

Yes, my PR just remove the `overflow-x` attribute to make the main content to show normally because I don't think a horizonal scrollbar is a good design for users not only on desktop but also on mobile.

So do you have a better solution to solve it? :)

**Comment by wzhudev** [comment]
> > Have you tried to open this feature in the dev tool? Since the demo is for mobile, you should toggle it open.
> > ![image](https://private-user-images.githubusercontent.com/12122021/356069019-65c4492a-5d23-41be-844d-f797523bf282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY3NTgsIm5iZiI6MTcyMzE2NjQ1OCwicGF0aCI6Ii8xMjEyMjAyMS8zNTYwNjkwMTktNjVjNDQ5MmEtNWQyMy00MWJlLTg0NGQtZjc5NzUyM2JmMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGM5OGU4MTk2OTlhYjA1NzdjZDkyZDMyMTcxOGJkZTEzZmQ3MGY2MjZlYzdkM2U2ODZiMzVkODhiMTFiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z6OplntmNr1BiBeToXy6yDNtC-CKBIaJ5XanUvxocU)
> > Your PR seems impropriate because it would make the sheetbar unscrollable.
> 
> Yes, I did, all the same. :)

Please provide detailed information of how to reproduce that.

**Comment by wzhudev** [comment]
> > Have you tried to open this feature in the dev tool? Since the demo is for mobile, you should toggle it open.
> > ![image](https://private-user-images.githubusercontent.com/12122021/356069019-65c4492a-5d23-41be-844d-f797523bf282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY3NTgsIm5iZiI6MTcyMzE2NjQ1OCwicGF0aCI6Ii8xMjEyMjAyMS8zNTYwNjkwMTktNjVjNDQ5MmEtNWQyMy00MWJlLTg0NGQtZjc5NzUyM2JmMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGM5OGU4MTk2OTlhYjA1NzdjZDkyZDMyMTcxOGJkZTEzZmQ3MGY2MjZlYzdkM2U2ODZiMzVkODhiMTFiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z6OplntmNr1BiBeToXy6yDNtC-CKBIaJ5XanUvxocU)
> > Your PR seems impropriate because it would make the sheetbar unscrollable.
> 
> Yes, my PR just remove the `overflow-x` attribute to make the main content to show normally because I don't think a horizonal scrollbar is a good design for users not only on desktop but also on mobile.
> 
> So do you have a better solution to solve it? :)

It is your personal favor. I don't see why this is necessary to change the code. You can overrite it with CSS in your project.

**Comment by universeroc** [comment]
> ### Reproduction link
> https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

Reproduction link
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

**Comment by universeroc** [comment]
> > > Have you tried to open this feature in the dev tool? Since the demo is for mobile, you should toggle it open.
> > > ![image](https://private-user-images.githubusercontent.com/12122021/356069019-65c4492a-5d23-41be-844d-f797523bf282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjY3NTgsIm5iZiI6MTcyMzE2NjQ1OCwicGF0aCI6Ii8xMjEyMjAyMS8zNTYwNjkwMTktNjVjNDQ5MmEtNWQyMy00MWJlLTg0NGQtZjc5NzUyM2JmMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGM5OGU4MTk2OTlhYjA1NzdjZDkyZDMyMTcxOGJkZTEzZmQ3MGY2MjZlYzdkM2U2ODZiMzVkODhiMTFiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Z6OplntmNr1BiBeToXy6yDNtC-CKBIaJ5XanUvxocU)
> > > Your PR seems impropriate because it would make the sheetbar unscrollable.
> > 
> > 
> > Yes, my PR just remove the `overflow-x` attribute to make the main content to show normally because I don't think a horizonal scrollbar is a good design for users not only on desktop but also on mobile.
> > So do you have a better solution to solve it? :)
> 
> It is your personal flavor. I don't see why this is necessary to change the code. You can overrite it with CSS in your project, or write a plugin that provides UI you want.
OK, it's ok I'll solve it in my way.
