### ISSUE TITLE
[Bug] when using UniverSheetsNumfmtPlugin ,there is  no need to format when the cell value is null

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2971]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.5

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts

### Expected behavior

when the cell value is null ,there is no content in cell

### Actual behavior

when the cell value is null ,there is a formatted content in cell

**Comment by jikkai** [comment]
你可以用中文详细描述一下遇到的问题吗？

**Comment by Picktarget** [comment]
在使用了UniverSheetsNumfmtPlugin 数字格式化插件后，单元格的值为null的情况下，会根据style的n属性，自动格式化为相关的数值形式。在excel中即使设置了单元格格式，在cell为空的情况下，并不会格式化

**Comment by Picktarget** [comment]
<img width="440" alt="image" src="https://github.com/user-attachments/assets/6712ee03-c28d-409e-8786-37b4bacee6d0">
![image](https://github.com/user-attachments/assets/da9675e8-9476-4230-a108-f80e637d1f96)

**Comment by Picktarget** [comment]
![WeChatce713547a1d7730e47c9b43358730bef](https://github.com/user-attachments/assets/28955bb2-76e3-4b65-b818-f799debb42fb)

**Comment by Picktarget** [comment]
![image](https://github.com/user-attachments/assets/97b22b28-3d8a-49b0-bc17-ba9414c16722)

**Comment by Picktarget** [comment]
<img width="263" alt="image" src="https://github.com/user-attachments/assets/540043e9-fbcf-45ff-adf9-91111dc86e37">

**Comment by Picktarget** [comment]
此外 如果单元格是数字类的格式化 会出现 空字符串会变为0 null会被转为Nan ，如果是general格式会将v为null时转为null字符串
<img width="409" alt="image" src="https://github.com/user-attachments/assets/6a926e15-f172-4c5d-9622-9eb9498702f2">

**Comment by Picktarget** [comment]
@Gggpound  此外 在使用了数字格式化插件后 const range = activeSheet.getRange(0, 0, 2, 2);
range.setValue(null); 也会显示null字符串

**Comment by Gggpound** [comment]
如何复现？

**Comment by Gggpound** [comment]
这里数据异常了，如果 cell.t 为 2 的话，v 不应该是个 null. 怎么产生这种数据的？有具体路径么

**Comment by Picktarget** [comment]
@Gggpound 不太理解您所说的 具体路径？我提供的复现链接不能使用吗？另外cell.t 为 2时，单元格确实没有内容 ，这种情况 我要给它默认一个0？ 还是如何处理呢？

**Comment by jikkai** [comment]
The reproduction link you provided indeed does not contain any code that can reproduce the issue. 
However, based on your description, this problem has been confirmed and we are currently addressing it.

**Comment by Picktarget** [comment]
那在此感谢 官方了 因为 网络问题 我fork失败了
