### ISSUE TITLE
[Bug] After changing style, the cell type will be covered by the type of value

### ISSUE THREAD

**Issue by super-xman** [dream-num/univer#2973]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.5

### Reproduction link

before:
![before](https://github.com/user-attachments/assets/e3bbee00-2c48-42c8-8064-24dc6fdfa97a)
after:
![after](https://github.com/user-attachments/assets/a6c31c23-b18e-4a57-9e04-bc79d22f463f)

### Expected behavior

keep the cell data type

### Actual behavior

change the string type to number type

**Comment by jikkai** [comment]
This behavior is consistent with Excel, it's not a bug.

**Comment by super-xman** [comment]
Change excel cell style will not update data type.

**Comment by jikkai** [comment]
This is NOT the default behavior of Excel, you may have set the number format.

**Comment by super-xman** [comment]
Wps excel has the same performance. I'm sure the cell data is string, number cell has different format.
