### ISSUE TITLE
Advice on data validation

### ISSUE THREAD

**Issue by skk-97** [dream-num/univer#2974]
### 初始清单

- [x] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

数据验证，多个下拉候选值无法快速定位。

### 解决方案

![1](https://github.com/user-attachments/assets/38d8e1ac-5d89-487d-83d4-ada54035184a)
能否像WPS 中的数据有效性一样，随着用户输入做近似度匹配，能快速定位多个候选值中的其中一个

**Comment by weird94** [comment]
supported on https://github.com/dream-num/univer/pull/3057
