### ISSUE TITLE
[Bug] dataValidation paste crash

### ISSUE THREAD

**Issue by keandfan** [dream-num/univer#2986]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.6

### 复现链接

https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-ttnufu?file=src%2Fassets%2Fdefault-workbook-data.ts

### 预期行为

shortcus keys operation
copy D3 and paste on A3, univer crash
![image](https://github.com/user-attachments/assets/34139516-d16c-4d87-b00d-f1cb0fd5ec88)

### 实际行为

univer crash

### 运行环境

Chrome

### 系统信息

System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm

**Comment by weird94** [comment]
will be fixed on next version
