### ISSUE TITLE
[Bug] After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx is erased when exporting it;

### ISSUE THREAD

**Issue by YanDonkeyBaby** [dream-num/univer#2994]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

lastest

### Reproduction link

https://univer.ai/pro/examples/sheets-exchange
xlsx file:[各省人才需求分布.xlsx](https://github.com/user-attachments/files/16558499/default.xlsx)

### Expected behavior

After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx file will not disappear when exporting it again; including other original xlsx formats, the format of the original file should not be changed when importing and exporting;

### Actual behavior

After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx is erased when exporting it;

**Comment by Dushusir** [comment]
Because the data validation plugin was not installed in the import and export demo plugin, the plugin data was lost. It has been fixed. Please check again. If there are other problems, please resubmit the issue.
