### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'editor')

### ISSUE THREAD

**Issue by dxj0211** [dream-num/univer#2995]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.6

### 复现链接

使用CDN引入
<script src="https://unpkg.com/@univerjs/umd/lib/univer.full.umd.js"></script>
<script src="https://unpkg.com/@univerjs/umd/lib/locale/zh-CN.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@univerjs/umd/lib/univer.css">
var {
  UniverCore,
  UniverDesign,
  UniverEngineRender,
  UniverEngineFormula,
  UniverDocs,
  UniverDocsUi,
  UniverUi,
  UniverSheets,
  UniverSheetsUi,
  UniverSheetsFormula,
  UniverFacade,
  UniverSheetsHyperLink,
  UniverSheetsHyperLinkUi,
  UniverUniscript
} = window

const univer = new UniverCore.Univer({
        theme: UniverDesign.defaultTheme,
        locale: UniverCore.LocaleType.ZH_CN,
        locales: {
          // eslint-disable-next-line no-undef
          [UniverCore.LocaleType.ZH_CN]: UniverUMD['zh-CN']
        }
      })
      this.univer = univer

      // core plugins
      univer.registerPlugin(UniverEngineRender.UniverRenderEnginePlugin)
      univer.registerPlugin(UniverEngineFormula.UniverFormulaEnginePlugin)
      univer.registerPlugin(UniverUi.UniverUIPlugin, {
        container: this.$refs.container
      })

      // doc plugins
      univer.registerPlugin(UniverDocs.UniverDocsPlugin, {
        hasScroll: false
      })
      univer.registerPlugin(UniverDocsUi.UniverDocsUIPlugin)

      // sheet plugins
      univer.registerPlugin(UniverSheets.UniverSheetsPlugin)
      univer.registerPlugin(UniverSheetsUi.UniverSheetsUIPlugin)
      univer.registerPlugin(UniverSheetsFormula.UniverSheetsFormulaPlugin)

      // 浮动图片
      // univer.registerPlugin(UniverDrawing.UniverDrawingPlugin)
      // univer.registerPlugin(UniverDrawingUi.UniverDrawingUIPlugin)
      // univer.registerPlugin(UniverSheetsDrawing.UniverSheetsDrawingPlugin)
      // univer.registerPlugin(UniverSheetsDrawingUi.UniverSheetsDrawingUIPlugin)

      // 超链接
      univer.registerPlugin(UniverSheetsHyperLink.UniverSheetsHyperLinkPlugin)
      univer.registerPlugin(
        UniverSheetsHyperLinkUi.UniverSheetsHyperLinkUIPlugin
      )

      // Uniscript
      univer.registerPlugin(UniverUniscript.UniverUniscriptPlugin)

      // create workbook instance
      this.workbook = univer.createUnit(
        UniverCore.UniverInstanceType.UNIVER_SHEET,
        data
      )
      this.univerAPI = UniverFacade.FUniver.newAPI(univer)

### 预期行为

展示uniscript面板

### 实际行为

<img width="977" alt="1" src="https://github.com/user-attachments/assets/4c9e63cf-0181-4aaa-acd7-2ec8f8195a93">
<img width="1019" alt="2" src="https://github.com/user-attachments/assets/7d25febb-93e2-4622-b479-aa0cf0951279">

### 运行环境

Chrome

**Comment by jikkai** [comment]
The umd package provided by Univer does not include `monaco-editor`, you may need to import it yourself.
