### ISSUE TITLE
[Bug] Multiplication with percentages has errors

### ISSUE THREAD

**Issue by october-rain** [dream-num/univer#3043]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.2.7

### Reproduction link

this bug can reproduce in this template link.

you can simply reproduce it, just add a percent number in A1, add a integer number in B1, use Formula =A1*B1 in C1

### Expected behavior

i excepted to get a correct number.

### Actual behavior

but i got a error

![image](https://github.com/user-attachments/assets/c1cc46b1-ecb3-455d-b840-07ecbcb41285)

**Comment by jikkai** [comment]
@Gggpound The manually entered `0.5%` will not be recognized as a numerical format.
