### ISSUE TITLE
[Bug] setEditable(false) but still can edit the excel

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#3047]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.7

### Reproduction link

[https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-rx3zx9?file=src%2FApp.vue,src%2Fcomponents%2FUniverSheet.vue](https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-rx3zx9?file=src%2FApp.vue,src%2Fcomponents%2FUniverSheet.vue)

### Expected behavior

it should block the edit permission like the website demo

### Actual behavior

I referenced the following website to use this code, but I can still edit the entire workbook. I'm not sure if I misunderstood something, or if there's an issue with the code somewhere?

[https://univer.ai/zh-CN/guides/sheet/features/permission](https://univer.ai/zh-CN/guides/sheet/features/permission)

```javascript
import { FUniver } from "@univerjs/facade";
const univerAPI = FUniver.newAPI(univer);
univerAPI.getActiveWorkbook().setEditable(false);
```

**Comment by ybzky** [comment]
It is not effective now because the result returned by the asynchronous request is reset. We have fixed this problem and will release it in the next one or two versions. You can add a timer to use it now.
