### ISSUE TITLE
[Bug] import Excel from url show getUnitId is null error

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#3048]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.7

### Reproduction link

[https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-s3zq22?file=src%2FApp.vue,src%2Fcomponents%2FUniverSheet.vue](https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-s3zq22?file=src%2FApp.vue,src%2Fcomponents%2FUniverSheet.vue)

### Expected behavior

There shouldn't be a getUnitId error.

### Actual behavior

After importing the Excel file using a URL and displaying it on the screen with `importXLSXToSnapshot`, it does display successfully. 

However, it seems like there's an asynchronous mechanism that triggers a `Cannot read properties of null (reading 'getUnitId') error`. I haven't called this `getUnitId`, and I'm not sure where it's being used, but the error keeps appearing. Although it doesn't affect functionality, it's quite bothersome.

<img width="556" alt="截圖 2024-08-14 11 03 01" src="https://github.com/user-attachments/assets/d6e2b7e9-a1ef-474c-a62b-ee2a1beec17a">

**Comment by hexf00** [comment]
@mukiwu  The error is not related to import/export but rather due to improper initialization and destruction ref #2767
