### ISSUE TITLE
[Bug] How to get inserted floating image data

### ISSUE THREAD

**Issue by dxj0211** [dream-num/univer#3049]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.6

### 复现链接

<img width="1031" alt="1" src="https://github.com/user-attachments/assets/73e7e003-3eb0-4974-a249-2fe4e1e46747">

### 预期行为

可以在workbook.value.save()中获取到图片相关数据

### 实际行为

未查询到图片相关数据

**Comment by jikkai** [comment]
`univerAPI.getActiveWorkbook().getSnapshot()`

**Comment by dxj0211** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dream-num/univer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月14日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dream-num/univer] [Bug] How to get inserted floating image data (Issue #3049)





 
univerAPI.getActiveWorkbook().getSnapshot()
