### ISSUE TITLE
[Bug] When the column width of the excel file is narrow and the following cells are empty, the copied cells become merged, but there is no actual merge.

### ISSUE THREAD

**Issue by maotong06** [dream-num/univer#3051]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.7

### 复现链接

![image](https://github.com/user-attachments/assets/0715e35a-4f21-4ff5-9bc5-40bbc4d1a731)
![image](https://github.com/user-attachments/assets/b50b759e-b5aa-4467-9598-df1a9bebfefd)

### 预期行为

希望正确处理单元格数据

### 实际行为

自动合并和不该合并的单元格

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Comment by maotong06** [comment]
> We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

这就直接给我直接关了？这么明显的问题，自己找个excel试一下就出来了。粘贴到官网的 examples  https://univer.ai/examples/sheets 就能复现。还非得让我写个demo出来？

**Comment by jikkai** [comment]
希望这篇文章能解答你的疑惑 https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by maotong06** [comment]
抱歉我没说清楚。
我用的程序是office 2016，必须从2016的文件中复制，wps是没问题的，office365网页版也没问题。
[工作簿1.xlsx](https://github.com/user-attachments/files/16610708/1.xlsx)
1. 用office 2016打开此文件，复制 A1:E1 单元格。
2. 在官方示例网站中，任选一个单元格。粘贴。
3. 拖拽列宽，可以发现单元格被合并了

![image](https://github.com/user-attachments/assets/6a8bb645-b751-4736-8f49-2fc5284da0be)

**Comment by maotong06** [comment]
windows10系统

**Comment by maotong06** [comment]
> 希望这篇文章能解答你的疑惑 https://antfu.me/posts/why-reproductions-are-required-zh
> 
> 此外你的 case 我们验证过了，从 Excel copy 出来的 data 就是 `colspan=2`，因此这不是一个 bug：
> 
> <img alt="1f265807-6941-4f6e-a74a-d61d563b26a3" width="568" src="https://private-user-images.githubusercontent.com/14025786/357713165-9212f345-dd47-4547-8f4d-0a54d311a14f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzIwNjgsIm5iZiI6MTcyMzYzMTc2OCwicGF0aCI6Ii8xNDAyNTc4Ni8zNTc3MTMxNjUtOTIxMmYzNDUtZGQ0Ny00NTQ3LThmNGQtMGE1NGQzMTFhMTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMzYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Njg1YzhhYjRmZGU0YWFhMjE5Mjk0ODRjZDNmYWJkMzVmNGFlYTZmMzJhMDI0MjIwNmZlNjQ3MjMwMzc4YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QG15AHRnnfpzURhH1Zsn6Jq2PYj_LJ_YfQPILGIjz-I">

抱歉我没说清楚。
我用的程序是office 2016，必须从2016的文件中复制，wps是没问题的，office365网页版也没问题。
[工作簿1.xlsx](https://github.com/user-attachments/files/16610708/1.xlsx)
1. 用office 2016打开此文件，复制 A1:E1 单元格。
2. 在官方示例网站中，任选一个单元格。粘贴。
3. 拖拽列宽，可以发现单元格被合并了

![image](https://github.com/user-attachments/assets/6a8bb645-b751-4736-8f49-2fc5284da0be)
