### ISSUE TITLE
[Bug] The backend server is deployed offline and cannot be used normally.

### ISSUE THREAD

**Issue by mingpen** [dream-num/univer#3063]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

最新版本

### 复现链接

macOS上 参考后端服务离线部署
https://univer.ai/zh-CN/guides/sheet/server/docker#%E7%A6%BB%E7%BA%BF%E9%83%A8%E7%BD%B2

启动内置的演示程序，访问 http://localhost:3010

下面是录屏
https://github.com/user-attachments/assets/ce7fc67f-b1cf-4c3a-bf70-521dae8e0e76

### 预期行为

能够正常协作编辑

### 实际行为

不能协助编辑，编辑A1单元格后，再点击B2后，内容显示丢失
参考录屏

### 运行环境

Chrome

**Comment by jikkai** [comment]
The information you provided is insufficient，please at least provide information from the browser console and docker logs.
https://univer.ai/guides/sheet/server/docker#%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5%E6%9C%8D%E5%8A%A1%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99
