### ISSUE TITLE
[Bug] After importing Excel, inserting col and then exporting, the newly inserted col will disappear.

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#3065]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.7

### 复现链接

[https://excel.goodlinker.io:3010/?unit=UdYkerjeTXOBdbwOBiuYbg&type=2&subunit=uni1](https://excel.goodlinker.io:3010/?unit=UdYkerjeTXOBdbwOBiuYbg&type=2&subunit=uni1)

### 预期行为

當 col 或 row 不足時，手動插入 col / row 再匯出 Excel，應該要能顯示我新插入的 row / col

### 实际行为

我先导入了一份 excel 文件，然后手动插入新的 col 塞入值，接着另存导出 Excel 后，发现新插入的字段都不会出现

這是我匯入的 Excel 檔案
https://muki.tw/demo/univer-93698052.xlsx

我手動插入了 col : BA ~ BL
![截圖 2024-08-15 10 37 53](https://github.com/user-attachments/assets/58d7d7ad-8ea0-412d-88f9-1af2c319e49f)

匯出之後在本機打開，插入的 col 沒有出現
<img width="848" alt="截圖 2024-08-15 10 38 19" src="https://github.com/user-attachments/assets/9b03f599-d1fd-4c3e-9e42-73e72e21d92b">

### 运行环境

Chrome

**Comment by Dushusir** [comment]
Will be fixed in the next version
