### ISSUE TITLE
[Feature] Prohibit or Disable the initialization of the selected cell state

### ISSUE THREAD

**Issue by rainjay** [dream-num/univer#3067]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![image](https://github.com/user-attachments/assets/91090c36-ab97-4b63-8cfe-205e6381d9da)

the disableAutoFocus config not work

### Solution

no selected cell after init

**Comment by jikkai** [comment]
The feature of `disableAutoFocus` is not to cancel the default selection of cells, in fact, deselecting is not allowed in Excel, so currently Univer will not provide this feature.

**Comment by rainjay** [comment]
> The feature of `disableAutoFocus` is not to cancel the default selection of cells, in fact, deselecting is not allowed in Excel, so currently Univer will not provide this feature.

But the disableAutoFocus doesn't work well, I've fixed the problem with `document.activeElement?.blur()` and lifecyclehook.
