### ISSUE TITLE
[Bug] IF, AND Formula causing memory leaks.

### ISSUE THREAD

**Issue by wang2lang** [dream-num/univer#3068]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.7

### Reproduction link

https://univer.ai/pro/examples/sheets-exchange

上传文件：
[CBAM+Communication+template+for+installations_en_240224.xlsx](https://github.com/user-attachments/files/16621151/CBAM%2BCommunication%2Btemplate%2Bfor%2Binstallations_en_240224.xlsx)

### Expected behavior

Rendering after uploading and parsing the file does not cause the browser to hang.

### Actual behavior

Rendering after uploading and parsing the file cause the browser to hang.

### System information

Chrome, Mac

**Comment by Dushusir** [comment]
Already fixed, please test again.
This issue will be closed. If you still find problems, feel free to reopen this issue.
