### ISSUE TITLE
[Feature] Provide the ability to use lifecycle callback hooks

### ISSUE THREAD

**Issue by rainjay** [dream-num/univer#3073]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I need to call the FUniver API to perform some operations, but the issue is that all methods of the univerAPI must wait until the univer rendering is complete to take effect, and currently, there is no lifecycle function to inform me when the rendering is finished.

### Solution

// maybe some hooks like this:
univerAPI.on('ready' =>  {
  // call univerAPI.fns
})

**Comment by jikkai** [comment]
```
const lifecycleService = univer.__getInjector().get(LifecycleService)

lifecycleService.lifecycle$.subscribe((lifecycle) => {
    console.log(lifecycle, LifecycleStages)
})

```
