### ISSUE TITLE
Cells with protection ranges set can also be automatically filled.

### ISSUE THREAD

**Issue by yang-xiao-xue** [dream-num/univer#3076]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

线上环境

### 复现链接

无

### 预期行为

设置了保护范围,设置了不允许编辑,双击去改动的时候确实也提示了不能编辑,但是拖动鼠标又下角的加号不应该改变被保护的单元格的值

### 实际行为

设置了保护范围,设置了不允许编辑,双击去改动的时候确实也提示了不能编辑,但是拖动鼠标又下角的加号就能改变单元格的值
![微信图片_20240815164022](https://github.com/user-attachments/assets/19d8a2e3-1865-4e0c-840d-5a62fa921548)

### 运行环境

Chrome

### 系统信息

window10

**Comment by jikkai** [comment]
It seems that permission verification was not conducted before the auto-fill. @yuhongz

**Comment by ybzky** [comment]
> ### 在您提交此问题之前，您是否检查了以下内容？
> * [x]  这真的是个问题吗？
> * [x]  我已经在 Github Issues 中搜索过了，但没有找到类似的问题。
> 
> ### 受影响的包和版本
> 线上环境
> 
> ### 复现链接
> 无
> 
> ### 预期行为
> 设置了保护范围,设置了不允许编辑,双击去改动的时候确实也提示了不能编辑,但是拖动鼠标又下角的加号不应该改变被保护的单元格的值
> 
> ### 实际行为
> 设置了保护范围,设置了不允许编辑,双击去改动的时候确实也提示了不能编辑,但是拖动鼠标又下角的加号就能改变单元格的值 ![微信图片_20240815164022](https://private-user-images.githubusercontent.com/75985936/358169291-19d8a2e3-1865-4e0c-840d-5a62fa921548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTQyNDgsIm5iZiI6MTcyMzcxMzk0OCwicGF0aCI6Ii83NTk4NTkzNi8zNTgxNjkyOTEtMTlkOGEyZTMtMTg2NS00ZTBjLTg0MGQtNWE2MmZhOTIxNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMTBhMjYwZWJhNTI4NzUzNjg4NWM0NzAzMWFjYTk2YTYyMmY1YjBkNWUzM2UyOWNlYjUyOTg2NjRiMzA4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cZd7FE5CUf2761jkbTzT9VW9zQcvBPvkU2QVSNSG3Oo)
> 
> ### 运行环境
> Chrome
> 
> ### 系统信息
> window10

这个怎么复现的，能提供一个复现demo吗，我这里看是好着的

**Comment by ybzky** [comment]
https://github.com/dream-num/univer/pull/3081 fixed
