### ISSUE TITLE
Data validation rules hope to be superimposed

### ISSUE THREAD

**Issue by yang-xiao-xue** [dream-num/univer#3080]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

目前是发现一个单元格只能设置一条数据验证规则,设置了多条验证规则只会保留最后一条

### 解决方案

希望验证规则能叠加,一个单元格可以设置多条验证规则

**Comment by weird94** [comment]
目前的规范是一个cell只会存在一个校验规则（如google、excel），如果你存在多个校验规则的需求，可以使用自定义公式的规则来实现
