### ISSUE TITLE
[Bug] build quasar mode electorn  RangeError: Maximum call stack size exceeded  Exception in PromiseRejectCallback:

### ISSUE THREAD

**Issue by Arc-zlz** [dream-num/univer#3085]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.7

### Reproduction link

[[
RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:]()](https://github.com/Arc-zlz/error_univerjs)

### Expected behavior

![image](https://github.com/user-attachments/assets/9123faec-b724-4b0f-95e2-4b57be46f00c)

### Actual behavior

![image](https://github.com/user-attachments/assets/e70ceb44-9296-478a-a17c-2280681a8570)

### System information

npm run build:e error RangeError: Maximum call stack size exceeded Exception in PromiseRejectCallback:
npm run dev:e  success

**Comment by Arc-zlz** [comment]
https://stackblitz.com/~/github.com/Arc-zlz/error_univerjs

**Comment by Arc-zlz** [comment]
delete "@univerjs/core": "^0.2.7",
    "@univerjs/design": "^0.2.7",
    "@univerjs/docs": "^0.2.7",
    "@univerjs/docs-ui": "^0.2.7",
    "@univerjs/engine-formula": "^0.2.7",
    "@univerjs/engine-numfmt": "^0.2.7",
    "@univerjs/engine-render": "^0.2.7",
    "@univerjs/facade": "^0.2.7",
    "@univerjs/rpc": "^0.2.7",
    "@univerjs/sheets": "^0.2.7",
    "@univerjs/sheets-formula": "^0.2.7",
    "@univerjs/sheets-ui": "^0.2.7",
    "@univerjs/ui": "^0.2.7",
    build success

**Comment by jikkai** [comment]
Everything is normal, please check your own development environment.

<img width="585" alt="image" src="https://github.com/user-attachments/assets/9df56e27-760a-4228-a3af-21d2c2d2c0ac">

**Comment by Arc-zlz** [comment]
> 一切正常，请检查您自己的开发环境。
> 
> <img alt="image" width="585" src="https://private-user-images.githubusercontent.com/14025786/358454798-9df56e27-760a-4228-a3af-21d2c2d2c0ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTAyMjcsIm5iZiI6MTcyMzc4OTkyNywicGF0aCI6Ii8xNDAyNTc4Ni8zNTg0NTQ3OTgtOWRmNTZlMjctNzYwYS00MjI4LWEzYWYtMjFkMmMyZDJjMGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExODEzYTkxN2VhNzgxMGMzZWRkMjcxMDFiMDEyOTRhMmE2ZWIxNTRiM2U2MGFkY2IzNDExNGE5ZGE4YzlmZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pm9NReSzZthtyzhIVVxLgPc-DsZRgFXvniX4WtZzvok">

**Comment by Arc-zlz** [comment]
please try  "npm run build:e" electron mode  ,not "npm run dev" spa mode

**Comment by Arc-zlz** [comment]
> 一切正常，请检查您自己的开发环境。
> 
> <img alt="图像" width="585" src="https://private-user-images.githubusercontent.com/14025786/358454798-9df56e27-760a-4228-a3af-21d2c2d2c0ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTA4NTYsIm5iZiI6MTcyMzc5MDU1NiwicGF0aCI6Ii8xNDAyNTc4Ni8zNTg0NTQ3OTgtOWRmNTZlMjctNzYwYS00MjI4LWEzYWYtMjFkMmMyZDJjMGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMmQ3NjViOGE0ZjM2NzNjMWYwZmZjN2JhMTEyM2NlZTVhMTdlNTU5MTBkYjYzZDY0ZmViZTFkZGJjMjc3NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BCWHFeknYETEhArKd46edTPEftDKzuLTcol0XglQV4">

please try "npm run build:e" electron mode ,not "npm run dev" spa mode

**Comment by jikkai** [comment]
https://quasar.dev/quasar-cli-vite/developing-electron-apps/configuring-electron/#dependencies-optimization
