### ISSUE TITLE
[Bug] Import Excel, freezes after scrolling

### ISSUE THREAD

**Issue by zhanghui6666** [dream-num/univer#3089]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

[电镀日产量报表_1723597532980.xlsx](https://github.com/user-attachments/files/16633112/_1723597532980.xlsx)

### Expected behavior

正常滚动

### Actual behavior

我在后端生成了excel并转换为base64，然后在前端再将base64转换为excel的file文件，调用了importXLSXToSnapshot后成功渲染了，但是在滚动后就卡死了，这是什么情况
I generated an Excel file on the backend and converted it to base64. Then, I converted the base64 file to an Excel file on the frontend and successfully rendered it by calling importXLSXoSnapshot. However, it froze after scrolling. What is the situation

**Comment by lumixraku** [comment]
a little confused, I updated your file to univer space, it rendered very smooth.
How to reproduce this problem?
<img width="832" alt="image" src="https://github.com/user-attachments/assets/d89b9ef5-cc73-4dd6-baa5-e508498ac328">
