### ISSUE TITLE
[Bug] How to get the script data in the monaco editor instance in Unscript and execute this script during initialization

### ISSUE THREAD

**Issue by dxj0211** [dream-num/univer#3090]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.6

### 复现链接

无法获取Unscript中monaco editor实例数据

### 预期行为

设计页面获取Unscript中monaco editor实例数据并保存，详情页获取到脚本内容并执行

### 实际行为

未找到获取monaco editor实例的方法及脚本执行方法

**Comment by jikkai** [comment]
https://github.com/dream-num/univer/tree/dev/packages/uniscript#get-the-editor-instance
