### ISSUE TITLE
[Bug] copy examples to new directory and run dev

### ISSUE THREAD

**Issue by guinanlin** [dream-num/univer#311]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1, copy the directory from examples to dty.

2, update the script 

3. run yarn dty:test

4. run yarn dev:test
![image](https://github.com/dream-num/univer/assets/44794953/1a485391-1af9-46ba-9bd9-4bd9b8bdf7cd)

### 预期行为

if run  yarn dty:sheet , shoulw pop up ports.

`frappe@e8811978c502:~/frappe-bench/apps/qifudengta/sites/univer$ yarn dty:sheet
yarn run v1.22.19
warning univer@0.0.0-NOT-VALID: The engine "pnpm" appears to be invalid.
$ turbo dty:demo --filter ./dty/univer-sheet-ts
• Packages in scope: 
• Running dty:demo in 0 packages
• Remote caching disabled

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    103ms 

Done in 0.25s.
frappe@e8811978c502:~/frappe-bench/apps/qifudengta/sites/univer$ yarn dev:sheet
yarn run v1.22.19
warning univer@0.0.0-NOT-VALID: The engine "pnpm" appears to be invalid.
$ turbo dev:demo --filter ./examples/univer-sheet-ts
• Packages in scope: univer-sheet-ts
• Running dev:demo in 1 packages
• Remote caching disabled
univer-sheet-ts:dev:demo: cache bypass, force executing ede1aecb7a1e780e
univer-sheet-ts:dev:demo: 
univer-sheet-ts:dev:demo: > univer-sheet-ts@0.0.1 dev:demo /home/frappe/frappe-bench/apps/qifudengta/sites/univer/examples/univer-sheet-ts
univer-sheet-ts:dev:demo: > node ./esbuild.config.mjs --watch
univer-sheet-ts:dev:demo: 
univer-sheet-ts:dev:demo: Local server: http://localhost:3002
`

### 实际行为

cannot popup ports.

### 运行环境

Chrome

### 操作系统

Linux

### 构建工具

esbuild

**Comment by jikkai** [comment]
We do not use `yarn` as package manager, we recommend using `pnpm`
