### ISSUE TITLE
[Bug] Add custom formula for data validation, advanced settings cannot be edited normally

### ISSUE THREAD

**Issue by luckyguanxin** [dream-num/univer#3111]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

最新版

### 复现链接

https://github.com/user-attachments/assets/9b6a3ea3-b17c-414b-b7f9-b484f7ed3356

### 预期行为

高级设置正常编辑

### 实际行为

无法编辑高级设置

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
