### ISSUE TITLE
[Bug] 公式填充生成公式ID后再次回显问题

### ISSUE THREAD

**Issue by TaylerLi** [dream-num/univer#3113]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

sheets-formula

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts
1.初始化了一个公式填充的数据
2.手动修改A1单元格的公式，比如改成：B1+1+1
3.再次点击获取数据按钮，查看celldata对象，复制后替换原来的celldata,运行后发现后面的公式不见了

### 预期行为

在修改了填充公式的第一个公式后，应该进行判断，是否其他公式ID没有对应的公式了

### 实际行为

数据经过存储后再次回显，实际公式ID没法找到对应的公式

### 运行环境

Chrome

**Comment by Dushusir** [comment]
we will handle it as soon as possible

**Comment by Dushusir** [comment]
We will check this out when we have time.
