### ISSUE TITLE
[Bug] Registered custom menu disappear in right Context Menu 

### ISSUE THREAD

**Issue by Ka1evi** [dream-num/univer#3120]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.8

### Reproduction link

before update:
![univer@0.2.5](https://github.com/user-attachments/assets/ecfced06-82b8-4e54-871a-1a99c7bf495b)

after update:
![univer@0.2.8](https://github.com/user-attachments/assets/f460f22c-8ebc-498c-b209-ebae8aed5e41)

### Expected behavior

custom menu should show in context menu

### Actual behavior

custom menu disappear in context menu

### System information

  System:
    OS: macOS 12.7.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 156.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/Library/pnpm/node
    npm: 8.19.4 - ~/Library/pnpm/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.6

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by Ka1evi** [comment]
> Please provide the minimal reproduction.
[custom-menu](https://codesandbox.io/p/github/awesome-univer/custom-menu/csb-df8g8w/draft/wonderful-shannon?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm01v5g1r00053p6i0cmab8li%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm01v5g1q00023p6iktw1rljm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm01v5g1q00033p6iggirngdy%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm01v5g1q00043p6ijpce4cm0%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm01v5g1q00023p6iktw1rljm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm01v5g1q00013p6i7ymwlhk8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm01v5g1q00023p6iktw1rljm%2522%252C%2522activeTabId%2522%253A%2522cm01v5g1q00013p6i7ymwlhk8%2522%257D%252C%2522cm01v5g1q00043p6ijpce4cm0%2522%253A%257B%2522id%2522%253A%2522cm01v5g1q00043p6ijpce4cm0%2522%252C%2522activeTabId%2522%253A%2522cm01v5gdy000c3p6i7b1ewsve%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522cm01v5gdy000c3p6i7b1ewsve%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm01v5g1q00033p6iggirngdy%2522%253A%257B%2522id%2522%253A%2522cm01v5g1q00033p6iggirngdy%2522%252C%2522activeTabId%2522%253A%2522cm01v5qm400153p6iego1hitc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm01v5qm400153p6iego1hitc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
