### ISSUE TITLE
[Feature] Hope to support rank ranking function

### ISSUE THREAD

**Issue by lzjpp** [dream-num/univer#3123]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

之前luckysheet是支持的，univer暂不支持rank排名函数，希望迭代加上

### Solution

‌‌RANK函数是‌Excel中用于对数值进行排名的函数，它可以根据指定的数值区域和排序方式（升序或降序）返回一个数值在区域内的排名。‌ RANK函数的基本语法是RANK(number, ref, [order])，其中number是要排名的数值，ref是数值区域，[order]是排序方式，0或省略表示降序，1表示升序。
RANK函数的基本用法
‌基本排名‌：通过指定要排名的数值和数值区域，RANK函数可以快速计算出某个数值在给定区域内的排名。
‌排序方式‌：通过设置[order]参数，可以选择升序或降序排名。默认情况下，不输入[order]参数或输入0时，RANK函数将按照降序进行排名；输入1时，RANK函数将按照升序进行排名。
‌处理重复值‌：当区域内的数值相同时，RANK函数会给它们相同的排名，并且跳过后续的排名。例如，如果有两个相同的数值排在第一位，那么下一个不同的数值将被排在第三位，而不是第二位。

- [x] RANK
- [ ] RANK.AVG
- [ ] RANK.EQ

**Comment by jikkai** [comment]
Determine if it's necessary to prioritize implementing the `RANK` function. @wpxp123456

**Comment by zhaolixin7** [comment]
rank 1、删除引用值后预期结果显示#ref
2、缺少括号可以计算出结果
[2024_8_21 17_13_23 commands.json](https://github.com/user-attachments/files/16689340/2024_8_21.17_13_23.commands.json)
[2024_8_21 17_13_23 video.webm](https://github.com/user-attachments/assets/15633649-d27d-44f7-b7c8-b99a194623cb)
