### ISSUE TITLE
[Bug] The element coordinates are calculated incorrectly when inserting a suspended layer, causing the rendering of third-party components to be offset.

### ISSUE THREAD

**Issue by hxguo** [dream-num/univer#3127]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.8

### 复现链接

在使用悬浮图层（SheetCanvasFloatDomManagerService的addFloatDomToPosition插入的图层）时，最终展现的插入组件和悬浮图层存在偏移，如下图示：
![image](https://github.com/user-attachments/assets/b608704d-a3a8-45d6-88a1-4543c6d22559)
另外悬浮图层的编辑按钮位置与悬浮图层的相对位置有点奇怪，期望能恢复到最初的在悬浮图层的右上角位置。
![image](https://github.com/user-attachments/assets/be671370-9e5e-44d4-a74b-62ec597b9ded)

### 预期行为

悬浮图层插入的元素应当与悬浮图层的位置对齐。
悬浮图层编辑按钮位置应当在悬浮图层的合理位置。

### 实际行为

悬浮图层插入的元素组件位置与悬浮图层的位置有严重的偏移，应当是坐标计算错误。
悬浮图层编辑按钮的位置不合理，期望能改为之前版本的位置。

### 运行环境

Chrome

### 系统信息

 System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 13.40 GB / 31.77 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22000.120

**Comment by weird94** [comment]
Hi, thank you for you submission, this issue will be fixed on version 0.2.9
