### ISSUE TITLE
[Bug] Function format is not strict

### ISSUE THREAD

**Issue by RainDlc** [dream-num/univer#3136]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.5

### 复现链接

=SUM((1)

### 预期行为

应该报错，因为公式多了一个"("

### 实际行为

计算结果 1

### 运行环境

Chrome

### 系统信息

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 146.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.local/state/fnm_multishells/1000_1724163825227/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/1000_1724163825227/bin/yarn
    npm: 10.7.0 - ~/.local/state/fnm_multishells/1000_1724163825227/bin/npm
    pnpm: 9.3.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.5

**Comment by zhaolixin7** [comment]
fixed   https://github.com/dream-num/univer/pull/3174
