### ISSUE TITLE
[Feature] Disabling menu in column header

### ISSUE THREAD

**Issue by bc4s** [dream-num/univer#3145]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I would like to have the option to remove the arrow shown in the image, disabling the ability to open the column header menu through the arrow.
![Snímka obrazovky 2024-08-21 123103](https://github.com/user-attachments/assets/85086cde-71bc-4d92-8514-38e264d72377)

### Solution

An option in the configuration to disable the menu in the column header

**Comment by jikkai** [comment]
You can actually achieve this using the `contextMenu` configuration option in our `UniverUIPlugin`. Setting `contextMenu` to `false` disables all context menus, including the one triggered by the column header arrow. We have fixed a bug where the arrow was still visible even when the context menu was disabled this way.

We're curious to understand your use case a bit better: Are there scenarios where you'd want to hide only the arrow without disabling the context menu entirely? Knowing more about your specific needs would help us explore potential solutions.

**Comment by bc4s** [comment]
The fixed bug will solve our issue. Thank you
