### ISSUE TITLE
[Feature] Error: [redi]: Expect "required" dependency items for id "IAuthzIoIoService" but get 2

### ISSUE THREAD

**Issue by qp91abc1234** [dream-num/univer#3155]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

只按指南中协同编辑操作，会出问题，引出了《依赖注入在 Univer 的实践 》，然而这篇文章协同插件注入CollaborativeUndoRedoService 不知道咋弄

### 解决方案

建议完善一下文档 & 给一个可以运行的 demo

**Comment by jikkai** [comment]
I don't quite understand your specific request, could you provide more details?

**Comment by qp91abc1234** [comment]
![微信图片_20240822164504](https://github.com/user-attachments/assets/df2d3ac4-9609-4169-b9e5-54ca8e4fde86)
this one，how to use dependencies，give me a demo pls！3gu~

**Comment by jikkai** [comment]
So it sounds like you just want to inquire about how to use the built-in DI system in Univer. It is recommended to refer to the redi documentation at https://redi.wendell.fun/. You can also find the answers you want in the source code of Univer.

**Comment by qp91abc1234** [comment]
the question is about Collaborative Editing, i follow the official document (https://univer.ai/guides/sheet/features/collaboration)，but it appear below question
![微信图片_20240822171158](https://github.com/user-attachments/assets/6b3567b4-46ff-41d4-bb84-1a943fc3e038)
I hope your team could optimize the official document or provide a demo, thanks

**Comment by jikkai** [comment]
If you want the problem to be solved, please provide the minimum reproduction first.

**Comment by qp91abc1234** [comment]
[sheets-vue3-mini-demo.zip](https://github.com/user-attachments/files/16721224/sheets-vue3-mini-demo.zip)

the minimum reproduction use version 0.2.8, base on [vue3 demo](https://univer.ai/zh-CN/playground?title=Vue+3), follow this [guide](https://univer.ai/zh-CN/guides/sheet/features/collaboration), finally appear the above question
