### ISSUE TITLE
[Bug] sheet.operation.set-cell-edit-visible cannot prevent editing

### ISSUE THREAD

**Issue by AnHeYi** [dream-num/univer#3160]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.8

### 复现链接

我打算在进入编辑的时候就阻止进入，虽然我知道可以使用权限控制，但是在一些特殊的情况，可能不能进入编辑，我需要立即消失聚焦

```
univerAPI.value.onBeforeCommandExecute((command) => {
    const { id, type, params } = command
  
    if (id === 'sheet.operation.set-cell-edit-visible') {
  
      command.params.visible && univerAPI.value.executeCommand('sheet.operation.set-cell-edit-visible', { eventType: DeviceInputEventType.PointerUp, visible: false })
    
    }
  })
```

### 预期行为

不进入编辑状态

### 实际行为

进入编辑状态

### 运行环境

Chrome

**Comment by AnHeYi** [comment]
> Could you explain the special situation and why permission control doesn't meet your needs? Please provide more infomation or demo

eg: 单元格可能是一个图标的事件，可以打开一个dialog。

**Comment by jikkai** [comment]
You can throw an Error in `onBeforeCommandExecute` to prevent the event from executing.

**Comment by AnHeYi** [comment]
> You can throw an Error in `onBeforeCommandExecute` to prevent the event from executing.

我写了一个demo，这样是可以阻止鼠标的点击，但是无法阻止 键盘的输入。
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

从demo 中可以看到，如果先使用键盘输入后，在其他的位置点击时候，input的聚焦是无法消失的。

**Comment by AnHeYi** [comment]
```
const univerAPI = FUniver.newAPI(univer)

univerAPI.onBeforeCommandExecute(command => {
 if (command.id === 'sheet.operation.set-cell-edit-visible') {
  if ((command.params as { visible: boolean }).visible) {
    univerAPI.executeCommand('sheet.operation.set-cell-edit-visible', { eventType: DeviceInputEventType.PointerUp, visible: false })
    throw new Error('禁止编辑')
  }
 }
})
```

如果我这样操作，鼠标事件可以阻止，但是无法阻止键盘事件的输入，并且移动到其他单元格聚焦事件不会消失。

**Comment by jikkai** [comment]
For these cases, you should prevent the execution of each corresponding command, not just one.

**Comment by AnHeYi** [comment]
> For these cases, you should prevent the execution of each corresponding command, not just one.

ok

**Comment by lindanni** [comment]
<img width="369" alt="1728888186987" src="https://github.com/user-attachments/assets/7404953b-8de7-448c-8eb2-258f7bdaeb6e">
如果通过throw new Error('禁止编辑')阻止命令执行，控制台点击一下单元格就会爆红，这个有什么办法可以不爆红吗

**Comment by wssnail** [comment]
I also encountered the same problem, is there any way to not use throw error and still prevent the command from executing

**Comment by utyfua** [comment]
@lindanni @wssnail to prevent showing the error in console throw [`CustomCommandExecutionError`](https://github.com/dream-num/univer/blob/4ae5482fed3aff976ae9afabdbe6d216136b0f9f/packages/core/src/common/error.ts#L17) instead of plain `Error` [[ref](https://github.com/dream-num/univer/blob/4ae5482fed3aff976ae9afabdbe6d216136b0f9f/packages/core/src/services/command/command.service.ts#L440)]
