### ISSUE TITLE
[Feature] How to synchronize with other clients when users choose to change their selection for collaborative operations using the Facade API. Or in other words, how to implement collaborative cursor using Facade API

### ISSUE THREAD

**Issue by gk-1213** [dream-num/univer#3179]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

how to implement collaborative cursor using Facade API

### Solution

What are the parameters of the collaborative cursor

**Comment by jikkai** [comment]
At present, collaborative features can only be directly implemented through the Univer's collaboration plugins. No facade API is provided for implementing collaboration.

**Comment by gk-1213** [comment]
What are the collaborative cursor parameters that Univer can parse

**Comment by gk-1213** [comment]
> 目前协作功能只能通过Univer的协作插件直接实现，没有提供实现协作游标的外观API。
Does Univer have built-in collaborative cursor parameters

**Comment by gk-1213** [comment]
> At present, collaborative features can only be directly implemented through the Univer's collaboration plugins. No facade API is provided for implementing collaborative cursor.

Does Univer have built-in collaborative cursor parameters
