### ISSUE TITLE
[Feature] Need an  API to display a client's selection in other clients

### ISSUE THREAD

**Issue by gk-1213** [dream-num/univer#3181]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

how to change client's selection in other clients，in  API Reference

### Solution

need an  API to display a client's selection in other clients

**Comment by jikkai** [comment]
Generally, we recommend using Univer's out-of-the-box collaboration services & plugins: https://univer.ai/guides/sheet/features/collaboration

If you want to implement collaboration yourself, you can refer to the [websocket-related facadeAPI](https://univer.ai/guides/sheet/facade/general-api#websocket). Apart from this, we currently have no plans to add other specific business interfaces
