### ISSUE TITLE
[Bug] Collaborative Editing not working

### ISSUE THREAD

**Issue by qp91abc1234** [dream-num/univer#3182]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.8

### Reproduction link

[sheets-vue3-mini-demo.zip](https://github.com/user-attachments/files/16744644/sheets-vue3-mini-demo.zip)

the minimum reproduction use version 0.2.8, base on [vue3 demo](https://univer.ai/zh-CN/playground?title=Vue+3), follow this [guide](https://univer.ai/zh-CN/guides/sheet/features/collaboration), finally appear the below question

### Expected behavior

I hope your team could optimize the official document or provide a demo, thanks

### Actual behavior

![微信图片_20240822171158](https://github.com/user-attachments/assets/6b3567b4-46ff-41d4-bb84-1a943fc3e038)

### System information

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 8.84 GB / 15.91 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    pnpm: 9.7.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.1566

**Comment by qp91abc1234** [comment]
@jikkai I have provide the minimal reproduction on Reproduction link（[sheets-vue3-mini-demo.zip](https://github.com/user-attachments/files/16744644/sheets-vue3-mini-demo.zip)），what other info you need？

**Comment by hexf00** [comment]
@qp91abc1234  Please check if you have missed the `override` configuration item. Refer to https://univer.ai/guides/sheet/features/collaboration#register . 
```diff
const univer = new Univer({
+  override: [
+    [IAuthzIoService, null]
+    [IUndoRedoService, null],
+  ],
});
```

If you have other questions, you can try to check it against the [start-kit demo](https://github.com/dream-num/univer-pro-sheet-start-kit).

**Comment by qp91abc1234** [comment]
@hexf00 ，wow，thanks~
