### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xzhly** [dream-num/univer#3184]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.9

### 复现链接

https://stackblitz.com/edit/stackblitz-starters-ev8hmc?file=src%2Fmain.ts

### 预期行为

这里我按照文档把这两个变量覆盖掉了

### 实际行为

![image](https://github.com/user-attachments/assets/cb0ee0cd-e37c-45cc-be29-22b82be8e275)
但是主题并没有按照预期变化

### 运行环境

Chrome

**Comment by jikkai** [comment]
https://stackblitz.com/edit/stackblitz-starters-k1lzya?file=src%2Fmain.ts
