### ISSUE TITLE
Toolbar configuration multi-line display, no need to hide the display

### ISSUE THREAD

**Issue by enjoyaday** [dream-num/univer#3197]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

工具栏配置多行展示，不需要隐藏显示

### 解决方案

能够通过参数配置工具栏行数

**Comment by jikkai** [comment]
We have no plans to support this feature.
