### ISSUE TITLE
[Feature] cdn method, it is recommended to add a core version.

### ISSUE THREAD

**Issue by 888go** [dream-num/univer#3213]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

现在cdn把所有插件都打包了,  
大部分人有可能是冲着univer核心功能来的.  甚至连多语言都未必用得上. 
我测试过, 如果就核心打包后, gzip压缩下才1.1m.  少了2/3体积. 
,  
.
功能很重要, 用户体验也很重要.  但是还是有人在意体积太大的. 

### 解决方案

建议增加核心的cdn包

**Comment by jikkai** [comment]
We have offered a corresponding UMD bundle for each plugin from the outset. All you need to do is just replace the package name.

https://unpkg.com/browse/@univerjs/core@0.2.9/lib/umd/index.js

**Comment by 888go** [comment]
> 我们从一开始就为每个插件提供了相应的 UMD 捆绑包。您需要做的就是替换包名称。
> 
> https://unpkg.com/browse/@univerjs/core@0.2.9/lib/umd/index.js

牛哇.  谢谢大佬,  
也建议官方文档能加一些这方面的,  也照顾一下用jquery和layui的同志们.

**Comment by 888go** [comment]
> 我们从一开始就为每个插件提供了相应的 UMD 捆绑包。您需要做的就是替换包名称。
> 
> https://unpkg.com/browse/@univerjs/core@0.2.9/lib/umd/index.js



> 我们从一开始就为每个插件提供了相应的 UMD 捆绑包。您需要做的就是替换包名称。
> 
> https://unpkg.com/browse/@univerjs/core@0.2.9/lib/umd/index.js

大佬, 有没办法提供一个核心版本的例子,  折腾一天,  搞不定啊...  
UMD这个, 文档也很简略. 折腾一天,  搞不定

**Comment by 888go** [comment]
jquery这种方式, 应该挺多人用的才是啊, 比如一些后端开发的,  layui在国内还是挺多人用的. 
主要是文档的例子, 打包好的, 实在太大了, 15M....
