### ISSUE TITLE
[Bug] Formula calculation is very slow when there are many formulas in a cell.

### ISSUE THREAD

**Issue by Just-null** [dream-num/univer#3221]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.2.9

### Reproduction link

在线demo地址：https://stackblitz.com/edit/vitejs-vite-3ptcpe?file=src%2Fassets%2Fsheet_data.ts

### Expected behavior

单元格中涉及到公式计算的时候，希望能够在尽可能短的时间内完成计算的逻辑

### Actual behavior

单元格中有大量公式的时候，计算的时间很长，但是并不是每一次都很长，有些时候快，有些时候很慢

### System information

System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v14.21.3/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Chrome: 127.0.6533.122
    Safari: 17.6

**Comment by Dushusir** [comment]
Try using Web Worker to improve computing performance, which can solve this problem. Refer to here, https://stackblitz.com/~/github.com/Dushusir/vitejs-vite-mjzk1j

However, when Web Worker is not enabled, a large number of renderings are triggered during formula calculations. This problem will be investigated later.

**Comment by Dushusir** [comment]
npm run build packaging issue has been fixed

**Comment by Dushusir** [comment]
@DR-Univer  依赖解析耗时比较久，这里嵌套循环是否有优化空间
![企业微信截图_17252762746093](https://github.com/user-attachments/assets/3f1fb73a-bcbc-484a-a2d1-b63795b0f2df)

**Comment by Dushusir** [comment]
Fixed by https://github.com/dream-num/univer/pull/3359
