### ISSUE TITLE
[Feature] Can I combine multiple instructions into one event and undo them all at once?

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3223]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

我可以把多个指令合并成一次事件， 在执行撤销的时候一次撤销掉吗 
假设我 发出了三个指令但是我只想记录成一次事件

### Solution

有这样的方法 或者我怎么做可以模拟

**Comment by jikkai** [comment]
https://univer.ai/zh-CN/guides/sheet/advanced/custom-command#undo--redo
