### ISSUE TITLE
[Bug] Cut And Paste Protected Data

### ISSUE THREAD

**Issue by ImSlaym** [dream-num/univer#3238]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

@0.2.9

### Reproduction link

https://stackblitz.com/~/github.com/ImSlaym/sheets-vite-demo

### Expected behavior

Since it is "edit protected" it shouldnt be allowed to remove the cell value of protected cell with a cut and paste

### Actual behavior

It is possible to remove the cell value with a cut and paste

**Comment by ybzky** [comment]
In our permission system, copying and cutting have additional point controls. When the copy permission is true, readable areas can be copied.
