### ISSUE TITLE
[Bug] hover on time selector ，errors show on console

### ISSUE THREAD

**Issue by keandfan** [dream-num/univer#3239]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

^0.2.8

### 复现链接

https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-ttnufu?file=src%2Fcomponents%2FUniverSheet.vue

### 预期行为

无事发生

### 实际行为

![image](https://github.com/user-attachments/assets/1f6bc389-65a9-425c-a736-2f801b195156)
报错

**Comment by weird94** [comment]
请更新到最新版本，0.2.12。
