### ISSUE TITLE
[Bug] Data validation rules from SHEET_DATA_VALIDATION_PLUGIN are not working correctly when initializing WorkBook

### ISSUE THREAD

**Issue by Just-null** [dream-num/univer#3250]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.9

### 复现链接

https://stackblitz.com/~/github.com/Dushusir/vitejs-vite-mjzk1j?file=src%2FApp.vue

### 预期行为

在初始化WorkBook时候，我在resource中添加SHEET_DATA_VALIDATION_PLUGIN的校验规则，ranges中的单元格应该需要按照设置的规则初始化校验的逻辑

### 实际行为

在初始化WorkBook时候，我在resource中添加SHEET_DATA_VALIDATION_PLUGIN的校验规则，但是没有正确的工作，只有第一个单元格生效，后面的单元格不生效
<img width="849" alt="image" src="https://github.com/user-attachments/assets/90f0d511-e45c-459a-834a-c2e3d45aa42b">

**Comment by Dushusir** [comment]
Please confirm that the snapshot after setting data validation can display data validation normally

https://stackblitz.com/~/github.com/Dushusir/vitejs-vite-mjzk1j?file=src/assets/snapshot.ts

**Comment by Just-null** [comment]
Where exactly is the issue?

**Comment by Just-null** [comment]
> 请确认设置数据验证后的快照可以正常显示数据验证
> 
> https://stackblitz.com/~/github.com/Dushusir/vitejs-vite-mjzk1j?file=src/assets/snapshot.ts

I made a comparison and found that when a cell only has the f attribute, meaning the cell's data is calculated through a formula and doesn't have the v attribute during initialization, the snapshot for data validation doesn't work. Is this a bug or is it designed to work this way? Logically, shouldn't the data validation logic be applied after the formula execution?

**Comment by Dushusir** [comment]
Please test again with the new version. If there is no problem, this issue will be closed.
