### ISSUE TITLE
[Feature] How to set member names in collaboration ？

### ISSUE THREAD

**Issue by qp91abc1234** [dream-num/univer#3273]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![1725243940067](https://github.com/user-attachments/assets/a25791c2-09b8-40fd-a784-3c9c6a4578af)
how to modify member name from anonymous to custom name ?

### Solution

hope custom member name

**Comment by zsq1234** [comment]
You can try our Saas product “space.univer.ai”, if you want to identify member to yourself service user like our Saas product, you can use USIP protocol: https://www.univer.ai/guides/sheet/server/usip
