### ISSUE TITLE
[Bug] After setting the permissions and saving them, and then loading the data, the gray background of this permission protection will cover the words. Remove the permission protection, and then add the regional permission protection to see the words covered by the gray background.

### ISSUE THREAD

**Issue by BugExpert** [dream-num/univer#3274]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.11

### Reproduction link

[Bug] 设置权限保存后，之后加载数据，这个权限保护灰色背景会把字给盖住，移除权限保护，再加区域权限保护才可以看到被灰色背景盖住的字

### Expected behavior

应该保存之后加载默认可以看到灰色背景上的文字

### Actual behavior

目前系统会用灰色背景盖住单元格字

**Comment by BugExpert** [comment]
Uploading 001.mp4…

**Comment by BugExpert** [comment]
https://github.com/user-attachments/assets/0c3f6ce5-4063-439d-a37f-e6f67725a20f

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by BugExpert** [comment]
> 请提供最少的复制品。

[demo.zip](https://github.com/user-attachments/files/16833148/demo.zip)

**Comment by BugExpert** [comment]
[demo.zip](https://github.com/user-attachments/files/16833517/demo.zip)
该版本只能一部分显示一部分不显示

**Comment by ybzky** [comment]
> [demo.zip](https://github.com/user-attachments/files/16833517/demo.zip) 该版本只能一部分显示一部分不显示

已复现 渲染缓存没有清掉 下个版本会修复

**Comment by jikkai** [comment]
Duplicate of #3293
