### ISSUE TITLE
[Bug] Floating image movement and zoom events cannot be continuously blocked during the execution of onBeforeCommandExecute. They only take effect for the first time, and subsequent movement and zoom events cannot be blocked.

### ISSUE THREAD

**Issue by BugExpert** [dream-num/univer#3283]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.11

### Reproduction link

[Bug] 浮动图片移动、放大缩小事件无法阻止

### Expected behavior

可以每次阻止浮动图片移动、放大缩小等

### Actual behavior

在事件执行前onBeforeCommandExecute阻止浮动图片移动放大缩小只在第一次可以生效。

**Comment by BugExpert** [comment]
> 请提供最小复制量。

[demo.zip](https://github.com/user-attachments/files/16842244/demo.zip)
测试拖动图片在事件onBeforeCommandExecute执行前阻止，只能在第一次阻止图片拖动，后续可以随意拖动图片，已提供相关demo，安装依赖即可看到效果。

**Comment by weird94** [comment]
Will support disable transform by set `allowTransform` to `false`. Please follow this pr https://github.com/dream-num/univer/pull/3342
For example
```ts
worksheet.addFloatDomToPosition({
  componentKey: 'demo',
  allowTransform: false,
  ...otherOptions.
})
```
