### ISSUE TITLE
[Feature] The declared custom attribute will not be copied when copied.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3284]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

range.setValue({
  v: 'Hello, Univer',
  custom: {
      key: 'value',
  },
});
我声明的custom 属性在复制的时候不会复制过去

### 解决方案

希望可以有一个入口去管理我可以复制哪些字段

**Comment by jikkai** [comment]
Univer does not process custom fields further, as these are considered business-specific. Users are responsible for managing their own business logic related to these fields.

Regarding the issue you mentioned about custom fields not being copied, please submit a new issue with a minimal reproduction.
