### ISSUE TITLE
[Bug] The custom attribute of the cell will be reset in some cases, which is not as expected

### ISSUE THREAD

**Issue by LukerChen** [dream-num/univer#3294]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.4~0.2.11

### 复现链接

https://github.com/user-attachments/assets/76cf482c-b22b-4c78-882d-c3b1f6ed80c6

vue2

### 预期行为

custom无论如何，在单元格已确定的情况下，都不应该发生改变。

### 实际行为

点键盘上的删除或右键清除内容，单元格custom会丢失
从任何地方复制的内容粘贴到单元格也会丢失单元格原来的custom
如果是数字，拖动右下角的+扩展复制内容，后面单元格也会丢失custom

### 运行环境

Chrome

### 系统信息

vue2

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by jikkai** [comment]
This is the expected behavior, not a bug.
