### ISSUE TITLE
[Bug] The custom field was not copied when copying.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3295]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

[Uploading test-copy-custom1.zip…]()

### Expected behavior

期望能复制过去custom字段

### Actual behavior

实际复制不过去

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by 840251442** [comment]
我上面的视频不能说明问题吗

**Comment by jikkai** [comment]
To help us resolve this quickly, please share your code snippet. Also, where is the video you mentioned? :)

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
