### ISSUE TITLE
[Bug] Added CustomMenu, when registering plugin engine, LocaleService cannot be loaded.

### ISSUE THREAD

**Issue by Gocgo** [dream-num/univer#3297]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.11

### 复现链接

https://github.com/Gocgo/univer-demo.git

### 预期行为

升级到0.2.11版本后，发现自定义ui 注册引擎的时候不再使用wendellhu/redi，都合并到了univer/core中，但是umi项目还是无法加载LocaleService，报错信息参考前期问题链接：[https://github.com/dream-num/univer/issues/2511](url)，前期提供了迂回的解决方案This is a known issue. We are not sure what Umi has done that caused the TypeScript decorators to not execute as expected. The provided link (https://stackblitz.com/edit/vitejs-vite-exfdw3?file=src%2Fpages%2Fplugins%2FDataSourcePlugin.tsx) is a workaround for this problem.升级之后univer/core中没有setDependencies方法，无法使用之前的方案。
请问是否可以再提供迂回的解决方案，万分感谢。

### 实际行为

升级到0.2.11版本后，发现自定义ui 注册引擎的时候不再使用wendellhu/redi，都合并到了univer/core中，但是umi项目还是无法加载LocaleService，报错信息参考前期问题链接：[https://github.com/dream-num/univer/issues/2511](url)，前期提供了迂回的解决方案This is a known issue. We are not sure what Umi has done that caused the TypeScript decorators to not execute as expected. The provided link (https://stackblitz.com/edit/vitejs-vite-exfdw3?file=src%2Fpages%2Fplugins%2FDataSourcePlugin.tsx) is a workaround for this problem.升级之后univer/core中没有setDependencies方法，无法使用之前的方案。

### 运行环境

Chrome

**Comment by jikkai** [comment]
The workaround for Umi remains unchanged. However, please note that `setDependencies` has been migrated from `wendellhu/redi` to `@univerjs/core`. You can now import and utilize it directly from `@univerjs/core`.
