### ISSUE TITLE
[WIP] RFC: Univer Architecture Optimization

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#33]
Focus on transforming the core. After the structure is stable, plug-ins will be involved

Architecture related tasks
- [ ] core: Circular dependencies
  - [ ] The `worksheet` `workbook` should be split into model and api, the former only includes snapshot and get related, the latter is set modification @eiji-th
  - [ ]  undo in CommandManager @eiji-th
  - [ ] `Styles` module changed to worksheet. When transferring, the modification of the worksheet does not depend on the workbook, and the two are decoupled @eiji-th
  - [ ] `Action` `Apply` @Dushusir 
- [ ] ui-plugin-sheets: Circular dependencies @tonytonychopper123
- [ ] Using DI: sheets-plugin-numfmt @eiji-th
- [ ] Using DI: sheets-plugin-find @tonytonychopper123
- [ ] Move @wendellhu/redi into core package @wzhudev
- [ ] Add a dependency layer in core package @wzhudev
- [ ] Check for typos, like genname @eiji-th
- [x] Remove unneeded modules like `Server` @Dushusir
- [x] `Interface` `Enum` `Types` `Const` These directories are merged into the `Types` directory @Dushusir
- [ ] Don't put Univer in Basics @wzhudev
- [ ] Univer and Context are also a problem of holding each other, transform it into an injector on Univer @wzhudev
- [ ] [Optional] Remove index.ts, remove the introduction of `./index`
- [ ] [Optional] Remove static methods and propertoes

**Comment by wzhudev** [comment]
I am going to merge this issue to #32.
