### ISSUE TITLE
[Bug] Copying and pasting 2024-09-02 into a cell will display NaN, but not 2024-09-08 and 2024-09-03.

### ISSUE THREAD

**Issue by IQEQSQ** [dream-num/univer#3301]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.11

### 复现链接

试不出来，但我这边却是必现

### 预期行为

单元格显示2024-09-03

### 实际行为

单元格显示为NaN或者43393

### 运行环境

Electron

### 系统信息

无

**Comment by IQEQSQ** [comment]
![image](https://github.com/user-attachments/assets/5578a933-a149-4d7c-b0af-0a266ee362f8)

**Comment by IQEQSQ** [comment]
即使偶尔可以，修改一下日期又不行了

**Comment by IQEQSQ** [comment]
必现

**Comment by jikkai** [comment]
Please provide the minimal reproduction, this is necessary.

**Comment by IQEQSQ** [comment]
0.2.11 必现啊，按照操作来就是了。issue的 demo升级后也必现啊

**Comment by IQEQSQ** [comment]
你看聊天记录啊

**Comment by IQEQSQ** [comment]
这个是个 bug啊，别改标签

**Comment by jikkai** [comment]
<img width="1895" alt="image" src="https://github.com/user-attachments/assets/aca6bbfe-3eaa-417a-a2a1-975013999a12">

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts

我们按照你所说的步骤无法复现你提到的问题，请你遵守社区的规范提供最小复现。

**Comment by IQEQSQ** [comment]
我们发现问题在哪了，没有univer.registerPlugin(UniverSheetsNumfmtPlugin);
建议你们官方的默认安装文档加上这个，不然会踩坑

**Comment by jikkai** [comment]
https://univer.ai/zh-CN/guides/sheet/features/numfmt
