### ISSUE TITLE
[Bug] Border issue after merging cells

### ISSUE THREAD

**Issue by dxj0211** [dream-num/univer#3306]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.11

### 复现链接

通过自定义逻辑合并单元格后，单元格边框渲染有问题。如何在执行自定义合并单元格后，给单元格设置边框
  univerAPI.value.executeCommand('sheet.command.add-worksheet-merge', {
    subUnitId: sheetId,
    unitId: 'univerSheetId',
    selections: [...data]
  })

### 预期行为

![success](https://github.com/user-attachments/assets/821a4c4e-bfa6-4861-836c-e13f6003cc96)

### 实际行为

![error](https://github.com/user-attachments/assets/3cc761cd-8181-4ce8-816c-dadd42703860)

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
