### ISSUE TITLE
[Feature] More flexible combinations of permissions

### ISSUE THREAD

**Issue by wang2lang** [dream-num/univer#3318]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

In practice, we often encounter the need for a read-only workbook. The core of this read-only requirement is that the cell values cannot be edited. However, for ease of reading, it should be possible to adjust the column width and row height. 

Sometimes, when a color legend has been predefined, it might even be necessary to allow changes to the cell's background color for marking purposes, which requires more flexible permission combinations. 

**The ability to edit cell values and the ability to adjust column width, row height, and cell styles are two different levels of operations**, and it would be ideal to support more flexible combinations of permissions.

The most common requirement at present is to support the non-editable cell values while allowing adjustments to row height and column width. 

It would be great if this could be implemented soon. Thank you!

**Comment by Gggpound** [comment]
Currently, the WorkbookEditablePermission is used to expose the ability to set the workbook as readable. For more granular control over editing values or styles, you can utilize the WorksheetSetCellStylePermission and WorksheetSetCellValuePermission points. To control row height and column width, you can directly use the WorksheetSetColumnStylePermission and WorksheetSetRowStylePermission. For more available points, please refer to 
(https://univer.ai/zh-CN/guides/sheet/features/core/permission#worksheet-%E5%B7%A5%E4%BD%9C%E8%A1%A8)[https://univer.ai/zh-CN/guides/sheet/features/core/permission#worksheet-%E5%B7%A5%E4%BD%9C%E8%A1%A8]
