### ISSUE TITLE
[Bug] [data-validation] When changing cell values ​​through drop-down, cell custom fields are overwritten

### ISSUE THREAD

**Issue by OuYangJie167** [dream-num/univer#3346]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.11

### 复现链接

https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-zqnkcp?file=src%2FApp.vue

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/7b6ad41d-c703-4b9c-a2d7-7f245c80f23c">

选择下拉更改值后，点击查看结果按钮查看结果

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/8ba58807-c37f-4f6b-b1fa-d1b89a8f54cd">

### 预期行为

单元格的custom不应该被覆盖 

### 实际行为

通过下拉更改值后，单元格的custom属性被赋值为 __link_url：''"

### 运行环境

Chrome

**Comment by OuYangJie167** [comment]
@Dushusir 这是个大问题嘞

**Comment by hexf00** [comment]
fixed in #3436
