### ISSUE TITLE
[Bug] If a cell with a formula has been set and another CV value is entered, the formula will not be cleared.

### ISSUE THREAD

**Issue by caijiamin** [dream-num/univer#3347]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

^0.2.11

### Reproduction link

![3af0c1d937905552c09f216e82de85c](https://github.com/user-attachments/assets/7f856a50-4c4b-4659-8fc0-ab188e138809)

### Expected behavior

1、步骤一：单元格1，输入公式=SUM(1,2)；
2、步骤二：单元格2，输入字符串“cccc”；

### Actual behavior

3、步骤三：将单元格2的“cccc",复制粘贴到单元格1，单元格1的值改变了，公式还在。

**Comment by wpxp123456** [comment]
https://github.com/dream-num/univer/pull/3257 @caijiamin 最新版本已经修复了
