### ISSUE TITLE
[Bug] The font size is inconsistent with the actual font size of the browser, and the fontFamily is inconsistent with the actual display

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3354]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

demo如下
[font-sizeAndFont-family.zip](https://github.com/user-attachments/files/16906780/font-sizeAndFont-family.zip)
![6271725619845_ pic](https://github.com/user-attachments/assets/8abe9630-c332-473d-afd9-01ffc56ec189)

### Expected behavior

期望字体与字号都应该与浏览器展示一致

### Actual behavior

实际这几种字体都不一致。包括字号

**Comment by jikkai** [comment]
This is not a bug. The font size unit used is Excel's pt (points), not px (pixels).
