### ISSUE TITLE
[Bug] univerAPI.getPermission().setPermissionDialogVisible(false) After clicking the cell, the console reports an error

### ISSUE THREAD

**Issue by caijiamin** [dream-num/univer#3362]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

^0.2.11

### Reproduction link

univerAPI.getPermission().setPermissionDialogVisible(false)

### Expected behavior

没有权限不弹提示窗口，不需要报错

### Actual behavior

设置没有权限不弹提示窗口，控制台会报错
![image](https://github.com/user-attachments/assets/78c3117a-2d46-4b91-911a-6c911be2af63)

**Comment by ybzky** [comment]
下个版本会处理掉这个问题
