### ISSUE TITLE
[Bug] The first problem is that after the table column width is copied in, it is different from the actual display size of the excel width, and cannot be fully displayed. The second problem is that when the first column is not enough, the merged excel is pasted in and the merged cells are not correct.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3366]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

[copyexcel-issus.zip](https://github.com/user-attachments/files/16917000/copyexcel-issus.zip)
![6291725695552_ pic](https://github.com/user-attachments/assets/7174e510-0efc-453a-a3cc-4832403c1825)
[issue.xlsx](https://github.com/user-attachments/files/16917001/issue.xlsx)
excel 文件就是用来测试的
测试的时候可以把univer的列设置成20列去测试第二个问题

### Expected behavior

第一个问题期望 （excel1）粘贴过来内容可以完全展示
第二个问题期望 （excel2）粘贴过来的合并单元格不会乱

### Actual behavior

第一个问题期望 （excel1）粘贴过来内容宽度不等。
第二个问题期望 （excel2）粘贴过来的合并单元格不准。

**Comment by 840251442** [comment]
当列足够的时候 粘贴出来的合并单元格就不会出错

**Comment by ybzky** [comment]
Please upgrade to the latest version
