### ISSUE TITLE
[Bug] IStyleBase In the IStyleBase, the 'ul' property is of type ITextDecoration, but in the JSON data, it defaults to 'false'.

### ISSUE THREAD

**Issue by Minuscu1e** [dream-num/univer#3367]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.211

### Reproduction link

After I set the value in a certain cell to have an underline, the corresponding value for 'ul' in the 'styles' changed from 'false' to an empty object '{}'. Upon reviewing the source code, I found that it is defined as ITextDecoration. Why does the value 'false' appear? According to the design, it should be 'undefined'.

### Expected behavior

Data should always be of a consistent type.

### Actual behavior

The value of 'ul' should be either 'undefined' or of type 'ITextDecoration'.

**Comment by Jocs** [comment]
> the corresponding value for 'ul' in the 'styles' changed from 'false' to an empty object '{}'.

Can you show me a screenshot of the value for `ul` in the `styles` that is `false`?

**Comment by Jocs** [comment]
>  in the JSON data

Where does this JSON data come from? Did you build it yourself?

**Comment by Minuscu1e** [comment]
Sorry, I cannot reproduce it now. I will contact you after reproducing it

**Comment by jikkai** [comment]
We will temporarily close this issue. Feel free to reopen it at any time when you can provide a reproduction :)
