### ISSUE TITLE
[Bug] Horizontal scroll freeze/hang on filtering large data If the number of rows in the filter is low

### ISSUE THREAD

**Issue by viditrastogi11** [dream-num/univer#3369]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.12

### Description:

I have added two Univer plugins: @univerjs/sheets-filter, and @univerjs/sheets-filter-ui
I have registered the plugins src/main.ts
Run the application
Added a lot of data, ~5000 rows
I use filter on one of the columns
I scroll horizontally after filtering

https://www.loom.com/share/a06414f223744521ae5da8f20e2a3375

### Expected behavior

Scrolling should remain smooth and seamless.

### Actual behavior

If the number of rows in the filter is high, the horizontal scroll is smooth.
If the number of rows in the filter is low, the horizontal scroll lags a bit.

**Comment by lumixraku** [comment]
Hi~, I checked StackBlitz demo, but there is no data.  And the video did not finish uploading.

<img width="1834" alt="image" src="https://github.com/user-attachments/assets/6bd09138-63ff-48b9-8726-bec2964c9dfc">

**Comment by viditrastogi11** [comment]
https://www.loom.com/share/a06414f223744521ae5da8f20e2a3375?sid=ce915c0b-4eb5-4ea5-b9c4-7d6aff5e5ac4

**Comment by viditrastogi11** [comment]
@lumixraku hey added data to [stackblitz](https://stackblitz.com/~/github.com/viditrastogi11/sheets-vite-demo?file=src/main.ts)

**Comment by viditrastogi11** [comment]
@lumixraku You guys are awesome, keep rocking! 🙌

**Comment by lwzhang** [comment]
Has this problem been solved? I'm still having this issue with version 0.10.4.
