### ISSUE TITLE
[Bug] cell editor overflows

### ISSUE THREAD

**Issue by jerry-f** [dream-num/univer#3374]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

所以版本均有这个问题，包括最新的0.2.12

### 复现链接

![image](https://github.com/user-attachments/assets/d7917f4b-7265-4caa-bee3-ad1ec6dd2cfd)

### 预期行为

这个可编辑区域应该是在sheet 工作区中，但是它现在却溢出了工作区，但是溢出工作的部分是看不到的，这个我通过修改样式后的才能看到溢出的内容，实际上这个可编辑区域应该在工作区域内

### 实际行为

![image](https://github.com/user-attachments/assets/19993a6b-13a5-4783-b30f-14b7037de7f1)

### 运行环境

Chrome

### 系统信息

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.8.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.42)
    Internet Explorer: 11.0.22621.3527

**Comment by Jocs** [comment]
@weird94 It should be that the editor expands the width and height beyond the work area(sheet) when editing, and this problem needs to be considered when refactoring

**Comment by jerry-f** [comment]
这个问题应该没有修复， 最新版本在v0.4.1 中我看到虽然将编辑器限制在工作区内了，但是实际的编辑区还是跟之前一样， 导致了可编辑区域都看不完整。见图

![image](https://github.com/user-attachments/assets/3202205a-34b2-4480-a86a-69abadffcbba)

**Comment by jikkai** [comment]
If you believe the issue still exists, the minimum reproduction plz.
