### ISSUE TITLE
[Bug]   How to reset permissions after reinitializing with univerAPI.disposeUnit?

### ISSUE THREAD

**Issue by mietl** [dream-num/univer#3388]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.12

### Reproduction link

https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-ludshv?file=src%2Fcomponents%2FUniverSheet.vue

Minimum reproduction, when initializing, do not set permissions  Include permissions after reinitialization

### Expected behavior

After reinitialization, permissions should be applied according to the new work book. 

### Actual behavior

permissionPoint does not exist!  

<img width="898" alt="image" src="https://github.com/user-attachments/assets/e93da67a-09bd-43b3-be2d-3d438c5062eb"> 

He will receive an error. He is still using the previous permission. I don't know how to reset the permission.

Others have also encountered it  https://github.com/dream-num/univer/issues/2046#issuecomment-2178431256 

### System information

 System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M2
    Memory: 113.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.9.0 - ~/Library/pnpm/pnpm
    bun: 1.1.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 18.0

**Comment by ybzky** [comment]
The next version will fix

**Comment by mietl** [comment]
> The next version will fix

This issue still exists.

**Comment by jikkai** [comment]
> > The next version will fix
> 
> This issue still exists.

If you believe the issue still exists, please provide a reprodution link.
