### ISSUE TITLE
Bug Report: Excel Border Issue and Text Alignment Problem After Download

### ISSUE THREAD

**Issue by rainxw** [dream-num/univer#3391]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.12

### Reproduction link

https://univer.ai/pro/examples/sheets-exchange
[20240910-163006.zip](https://github.com/user-attachments/files/16942522/20240910-163006.zip)

### Expected behavior

border OK
Text Alignment OK

### Actual behavior

border Fail
Text Alignment Fail

### System information

detail info please see --[20240910-163006.zip](https://github.com/user-attachments/files/16942522/20240910-163006.zip)

**Comment by lumixraku** [comment]
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/f49c5222-ed34-49b0-9faa-e6d949a5729d">
