### ISSUE TITLE
[Bug] Clear Range Data Validation Error umd@0.2.12

### ISSUE THREAD

**Issue by keremduran** [dream-num/univer#3399]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

umd@0.2.12

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-p42rqq?file=index.html

### Expected behavior

activeSheet.getRange(0, 0, 1, 1).setDataValidation(null) should clear validation without error if the validation plugin is registered.

### Actual behavior

activeSheet.getRange(0, 0, 1, 1).setDataValidation(null) errors out: "sheets.command.clear-range-data-validation" is not registered.

Reproduction: In the provided link, enter a value that's not 10, validation kicks in. Click Clear Validation button at the top, see error at the console.

**Comment by hexf00** [comment]
ref: https://univer.ai/guides/sheet/features/data-validation/introduction
