### ISSUE TITLE
[Feature] Added whether cells can be edited

### ISSUE THREAD

**Issue by Mmh-1997** [dream-num/univer#3407]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

In the actual development process, we need to set the cell to whether it can be edited, so that users can operate in the cells that can be edited, such as the header text users can not modify.

**Comment by ybzky** [comment]
There are already permission functions that can meet this requirement.
