### ISSUE TITLE
[Bug] When pasting long column data from Excel into a table, only the column width of the first column will automatically take effect, but not the subsequent ones.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3409]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.12

### 复现链接

官方的customMenu demo 就可以复现

### 预期行为

应该所有的列都可以读取复制的宽度

### 实际行为

只有第一列读取了

**Comment by 840251442** [comment]
还有就是复制过来的宽度会短一些 希望把这个问题也给修复了

**Comment by ybzky** [comment]
The problem is not reproduced in the latest version of the code and the official website demo. Please provide a specific reproduction demo.

**Comment by 840251442** [comment]
https://univer.ai/playground?title=Custom+Menu 这个地址的例子都是稳定复现的 随便从excel 粘贴长内容 到后面的列

**Comment by 840251442** [comment]
你不要从第一列开始粘贴 从第二列开始稳定复现的

**Comment by 840251442** [comment]
[issue.xlsx](https://github.com/user-attachments/files/16989384/issue.xlsx)
你可以把表格里面的第二列直接粘贴到 https://univer.ai/playground?title=Custom+Menu 官方地址的第二列
