### ISSUE TITLE
[Bug] sheets-ui/src/controllers/clipboard/utils.ts getSetCellValueMutations When this method is executed, if there is a custom field in the original value, it will be removed by this method after pasting.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3411]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.12

### Reproduction link

上面的文件路径这个方法

### Expected behavior

期望custom 字段如果存在不应该被移除

### Actual behavior

会被这个方法过滤掉

**Comment by 840251442** [comment]
<img width="941" alt="image" src="https://github.com/user-attachments/assets/bc2dcb6d-5fcd-482a-bdbe-edaf7d863819">
我通过 debugger 找到了这个方法的这个地方 就只拷贝了v 相关的 custom相关的 根本没有拷贝。我不懂我该怎样去提供这个复现的步骤，这是一个必现的问题 。

**Comment by jikkai** [comment]
To help us understand and diagnose the issue, please provide a minimal reproduction. Without clear steps to reproduce the problem in a specific environment, it's difficult for us to pinpoint the cause.

Once you have a minimal reproduction ready, please feel free to reopen this issue. We'll be happy to investigate further.
