### ISSUE TITLE
[Bug] 删除表格内容后cellData数据仍然存在

### ISSUE THREAD

**Issue by Xzhly** [dream-num/univer#3424]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.2.9

### 复现链接

<img width="959" alt="image" src="https://github.com/user-attachments/assets/fef6c672-0c93-40d9-ac44-bf0fc0aae05e">

### 预期行为

删除后cellData不存在已经删除的数据信息

### 实际行为

<img width="1886" alt="image" src="https://github.com/user-attachments/assets/73641be2-1f74-472a-8113-81d95a44a89e">

**Comment by Xzhly** [comment]
https://stackblitz.com/edit/stackblitz-starters-pqsnnk?file=src%2Fmain.ts

**Comment by jikkai** [comment]
Unable to reproduce the issue you mentioned:

<img width="499" alt="image" src="https://github.com/user-attachments/assets/2e64332b-3a5b-4085-b096-491d82c8f090">

**Comment by Xzhly** [comment]
你提供的图片删除输入的数据后第0行0列的数据中仍然存在一个空对象，这会导致获取getDiscreteRanges等操作时会获取到已经没有数据的range

**Comment by Dushusir** [comment]
> getDiscreteRanges

After deleting the table content, the cell is an empty object, which is the expected effect.
getDiscreteRanges is used to obtain the dirty range. If an empty object exists, it may mean a deletion action, which needs to be marked.
If you think getDiscreteRanges has a bug, you can provide a detailed reproduction process for getDiscreteRanges.

**Comment by Xzhly** [comment]
我需要使用到getDiscreteRanges获取cellData中离散数据的range，但是不希望里面存在脏数据，有没有其他的解决办法呢？api文档有点不完善，无法进行搜索

**Comment by Dushusir** [comment]
> 我需要使用到getDiscreteRanges获取cellData中离散数据的range，但是不希望里面存在脏数据，有没有其他的解决办法呢？api文档有点不完善，无法进行搜索

After getting the [cellData](https://univer.ai/typedoc/@univerjs/core/interfaces/IWorksheetData#cellData) in IWorkbookData, you can process the data yourself.

**Comment by Xzhly** [comment]
好的，谢谢
