### ISSUE TITLE
[Bug] Use setValue to set a custom field before manual input in the cell, and the custom field is overwritten after manual input.

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3432]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.12

### 复现链接

![BUG](https://github.com/user-attachments/assets/2e700cb4-4c05-47ef-8d1f-01783794c362)

### 预期行为

![B1](https://github.com/user-attachments/assets/5214f11d-b799-4e7b-995c-c83c9295286d)

### 实际行为

在单元格手动输入之前使用setValue设置了一个自定义字段,在手动输入之后自定义字段被覆盖掉了,有什么办法能保留这个字段吗

### 运行环境

Chrome

**Comment by hexf00** [comment]
Please provide the minimal reproduction.

**Comment by 335060087** [comment]
activeSheet.value.getRange(...startCoordinates,1,1).setValue({v:'', custom: {flag: 'start',},})//setValue设置自定义字段flag
![image](https://github.com/user-attachments/assets/c764474a-d4ab-4dc1-9b80-92e969076c98)
//手动编辑输入值之后flag字段丢失
![image](https://github.com/user-attachments/assets/02d21d94-fafd-4f27-8fde-ed57a900c9d6)

**Comment by jikkai** [comment]
The `custom` field is reserved for your application's specific needs. Setting a valid object to this field will completely overwrite its existing value. To preserve existing data, manage merging or modifications within your own logic, as Univer does not handle application-specific data manipulation.

| oldValue | newValue | result |
| --- | --- | --- |
| `{ a: 1 }` | `{}` | `{}` |
| `{ a: 1 }` | `undefined` | `{ a: 1 }` |
```

**Comment by 335060087** [comment]
手动进入编辑保存的自定义字段丢失了这不算一个bug吗？

**Comment by jikkai** [comment]
So you need provide the minimal reproduction.
