### ISSUE TITLE
[Feature] Excel Cell with rich text of multiple lines, what's the text wrapping symbol, \n or \r\n, how to use it

### ISSUE THREAD

**Issue by xuequanyang** [dream-num/univer#3439]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

Excel Cell with rich text of multiple lines,what's the text wrapping symbol，\n or \r\n，how to use it?
here is my code,but it just show the first line of rich text
"cellData": {
    "0": {
        "0": {
            "v": null,
            "s": "22-_string226",
            "p": {
                "id": "0_0",
                "body": {
                    "dataStream": "资产名称\r\n（同U列，仅便于参看）\r\n",
                    "textRuns": [
                        {
                            "st": 0,
                            "ed": 5,
                            "ts": {
                                "fs": 11,
                                "bg": null,
                                "cl": {
                                    "rgb": "#0070c0"
                                }
                            }
                        },
                        {
                            "st": 6,
                            "ed": 18,
                            "ts": {
                                "fs": 11,
                                "bg": null,
                                "cl": {
                                    "rgb": "#0070c0"
                                }
                            }
                        }
                    ],
                    "paragraphs": [
                        {
                            "startIndex": 5,
                            "paragraphStyle": {
                                "indentFirstLine": 20,
                                "spaceAbove": 20
                            }
                        },
                        {
                            "startIndex": 19,
                            "paragraphStyle": {
                                "indentFirstLine": 20,
                                "spaceAbove": 20
                            }
                        }
                    ],
                    "sectionBreaks": [
                        {
                            "startIndex": 20,
                            "columnSeparatorType": 1,
                            "sectionType": 0
                        }
                    ]
                },
                "documentStyle": {
                    "pageSize": {
                        "width": 300,
                        "height": 100
                    },
                    "marginTop": 0,
                    "marginBottom": 0,
                    "marginRight": 2,
                    "marginLeft": 2
                }
            }
        }
    }
}
![image](https://github.com/user-attachments/assets/1c21b6c9-57e2-4850-989b-9f7ff1478759)

**Comment by hexf00** [comment]
In `dataStream`, the concept of paragraphs is used instead of line breaks.
- `\r` indicates the start of a new paragraph. I understand this is the line break you are looking for.
- The ending `\r\n` is mandatory; otherwise, you will encounter an error.

**Comment by Jocs** [comment]
@hexf00 That is true. One more point. 
`\n` also means section break, but in cell's rich text, there is no concept of section break(only in Doc), so in cell rich text, `\n` only appears at the end of `dataStream`.

**Comment by Jocs** [comment]
> "dataStream": "资产名称\r\n（同U列，仅便于参看）\r\n",

As comment above, there should be no `\n` in the middle of dataSteam.
