### ISSUE TITLE
[Bug] After setting the right border and merging cells, the right border of the merged cells disappears.

### ISSUE THREAD

**Issue by APythonMonster** [dream-num/univer#3452]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.12

### 复现链接

![demo](https://github.com/user-attachments/assets/ae462f6e-a942-4c38-bc0f-6222febce432)
步骤：添加单元格右边框，合并单元格，右边框消失

### 预期行为

合并后的单元格保留右边框

### 实际行为

合并后的单元格右边框消失

### 运行环境

Chrome

**Comment by jikkai** [comment]
Duplicate of #2509
