### ISSUE TITLE
[Feature] Please support the normal distribution function, which is often used in scientific statistics and is also NORM.S.DIST in stocks.

### ISSUE THREAD

**Issue by IQEQSQ** [dream-num/univer#3455]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

如题，求求了！
js计算 cdf累计正态函数是这个
function erf(x) {
  // 误差函数的数值逼近
  let sign = 1;
  if (x < 0) {
    sign = -1;
  }
  x = Math.abs(x);

  let a1 =  0.254829592;
  let a2 = -0.284496736;
  let a3 =  1.421413741;
  let a4 = -1.453152027;
  let a5 =  1.061405429;
  let p  =  0.3275911;

  let t = 1.0 / (1.0 + p * x);
  let y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * Math.exp(-x * x);

  return sign * y;
}

function normalCDF(x, mean = 0, stdDev = 1) {
  // 正态分布的CDF
  let z = (x - mean) / stdDev;
  let cdf = 0.5 * (1.0 + erf(z / Math.sqrt(2)));
  return cdf;
}

// 示例：计算正态分布CDF
let x = 1.0; // 你想要计算的值
let mean = 0; // 均值
let stdDev = 1; // 标准差

let cdf = normalCDF(x, mean, stdDev);
console.log(`The CDF of ${x} in a normal distribution with mean ${mean} and stdDev ${stdDev} is ${cdf}`);

**Comment by wpxp123456** [comment]
NORM.DIST?

**Comment by jikkai** [comment]
`ERF` is currently supported, and other formulas are under development.

You can find a list of supported functions here: https://univer.ai/guides/sheet/features/core/formula#%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E7%9A%84%E5%85%AC%E5

For faster implementation, let us know the required Excel formulas (not JavaScript functions).

**Comment by IQEQSQ** [comment]
> NORM.DIST?

是的

**Comment by IQEQSQ** [comment]
> `ERF` is currently supported, and other formulas are under development.
> 
> You can find a list of supported functions here: https://univer.ai/guides/sheet/features/core/formula#%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E7%9A%84%E5%85%AC%E5
> 
> For faster implementation, let us know the required Excel formulas (not JavaScript functions).

标题里面有了

**Comment by IQEQSQ** [comment]
> > `ERF` is currently supported, and other formulas are under development.
> > You can find a list of supported functions here: https://univer.ai/guides/sheet/features/core/formula#%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E7%9A%84%E5%85%AC%E5
> > For faster implementation, let us know the required Excel formulas (not JavaScript functions).
> 
> 标题里面有了

不是 erf，是 norm.s.dist，就是求累计正则分布数值

**Comment by IQEQSQ** [comment]
> `ERF` is currently supported, and other formulas are under development.
> 
> You can find a list of supported functions here: https://univer.ai/guides/sheet/features/core/formula#%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E7%9A%84%E5%85%AC%E5
> 
> For faster implementation, let us know the required Excel formulas (not JavaScript functions).

你的正在开发中的也没有啊

**Comment by jikkai** [comment]
I'm not sure what prompted your previous comment, but I can confirm that `NORM.DIST` and `NORM.S.DIST` are currently under development. We are progressively implementing a wide range of Excel functions. While we generally follow our own roadmap, we do adjust priorities based on user needs.

While we appreciate your input, please remember that GitHub Issues are designed for tracking bugs and feature requests, not for back-and-forth conversations. Using them as such can make it difficult to manage and track important information. Please aim to provide all necessary details in a single, comprehensive comment. Otherwise, we will consider it abuse of the issues.

**Comment by wpxp123456** [comment]
@IQEQSQ https://github.com/dream-num/univer/pull/3463
