### ISSUE TITLE
[Bug] 无论怎么搞，都不能正确显示表格内容

### ISSUE THREAD

**Issue by IQEQSQ** [dream-num/univer#3460]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.11

### 复现链接

无法在复现链接复现，我是在我的表格里操作了几下，然后就出现了这个问题，下面这两个表格都无法显示正确的内容，检查了下没有空格，还手敲了几下，都不行
<img width="258" alt="Screenshot 2024-09-15 at 16 55 26" src="https://github.com/user-attachments/assets/3cceacdd-08cc-420a-b06b-fdebe0e7d644">
<img width="305" alt="Screenshot 2024-09-15 at 16 55 51" src="https://github.com/user-attachments/assets/492f8125-4330-4340-8e82-2b56282102af">

<img width="292" alt="Screenshot 2024-09-15 at 16 55 40" src="https://github.com/user-attachments/assets/37501cb1-aa95-4f01-8f45-461e48d5e380">

另外，再多反馈给问题，默认表格宽度无法很好地显示小数，比如你打=100/3，会显示很多个 3，我搞了半天才知道，浪费了很多时间。小数这一块能参考 excel的吗，让人知道右边或者左边还有内容

### 预期行为

正确显示 22

### 实际行为

没有任何内容显示，重新加载网页才可以正常显示

### 运行环境

Chrome

**Comment by hexf00** [comment]
The current latest version is 0.2.14, please upgrade to 0.2.12 or the latest version
