### ISSUE TITLE
[Feature] Quickly find the coordinates of a specified cell

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3461]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

请问现在有方法快速查找到单元格的坐标吗,比如根据custom字段快速查找到单元格的坐标

**Comment by jikkai** [comment]
Developers should implement this functionality themselves using the facade API. The source code for "find-replace" can serve as a useful reference.
