### ISSUE TITLE
[Feature] Add a method to range that can return the range identifier of the diagonal

### ISSUE THREAD

**Issue by lichkingzz** [dream-num/univer#3466]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

可以返回 A4:D5，这样和sheet上的范围对应上
![ca38c13ab2a3c10d5a93be58aa9fb7b](https://github.com/user-attachments/assets/3a3fe420-1daf-4bf4-aa42-377d945e00b1)

**Comment by jikkai** [comment]
Please upgrade to the latest version.
