### ISSUE TITLE
[Bug] Setting the right or bottom border after merging cells is invalid

### ISSUE THREAD

**Issue by lindanni** [dream-num/univer#3475]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.14

### Reproduction link

Setting the right or bottom border after merging cells is invalid
<img width="800" alt="1726663280854" src="https://github.com/user-attachments/assets/2ec253b6-ec92-45ce-8ffb-76acd4368797">

### Expected behavior

After merging cells, set the right or top border to render

### Actual behavior

After merging cells, the set right or top border is invalid and not rendered

**Comment by lumixraku** [comment]
when set left border for merged cells.
<img width="973" alt="image" src="https://github.com/user-attachments/assets/1aad33c6-8778-41f0-b9a6-144c3bc482a1">



when set right / bottom border for merged cells
<img width="968" alt="image" src="https://github.com/user-attachments/assets/409d445b-a301-4566-aa5a-a48d5b3b61c2">
