### ISSUE TITLE
[Feature] I hope that the border of the selected box can be thickened, which is the same as the thickness when selecting many boxes.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3477]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

我想修改 选中的单元格的边框颜色 加粗 或者 换成深的或者亮的颜色 该怎么处理

**Comment by jikkai** [comment]
You can execute any command you want through the facade API, here are some reference links:

https://univer.ai/guides/sheet/facade/general-api#execute-commands
https://univer.ai/guides/sheet/tutorials/find-the-command-id
https://univer.ai/typedoc/@univerjs/sheets/variables/SetBorderBasicCommand
