### ISSUE TITLE
[Feature] Control the edit button of the drop-down box

### ISSUE THREAD

**Issue by sun995046205** [dream-num/univer#3478]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![image](https://github.com/user-attachments/assets/8a2cfcf3-952a-4b47-9053-cb95d926021a)
下拉框的值可以任意改动，需要有个编辑按钮的权限控制，希望尽快处理一下
![微信图片_20240919093146](https://github.com/user-attachments/assets/3981141a-9d25-4858-bf1e-0565e8016b73)

**Comment by weird94** [comment]
以下写法将在0.2.16生效。
```typescript
 univer.registerPlugin(UniverSheetsDataValidationPlugin, {
        showEditOnDropdown: false,
 });
```

**Comment by sun995046205** [comment]
固德固德
