### ISSUE TITLE
[Bug] After the cells are merged, you can also individually select the lower-left cell

### ISSUE THREAD

**Issue by lindanni** [dream-num/univer#3480]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.14

### Reproduction link

After the cells are merged, you can also individually select the lower-left cell
<img width="470" alt="1726714520176" src="https://github.com/user-attachments/assets/a294e8a8-4eb4-4f2e-aa44-aacb9a4d826c">

### Expected behavior

After the cells are merged, click on the merged cell and the entire merged range should be selected

### Actual behavior

After merging the cells, you can individually select the lower-left cell in the merge range

**Comment by ybzky** [comment]
下个版本会修复 https://github.com/dream-num/univer/pull/3443
