### ISSUE TITLE
[Feature] What I want is for the line to change when the grid is selected, not to set a wide line for the cell. For example, when dragging multiple cells, the line is thick. When you let go, the line becomes thin.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3482]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

我希望的是选中格子选中态的线变框 不是给单元格设置宽的线。 比如在拖拽多个单元格的时候那个线是粗的 当松手之后线变成了细的

**Comment by 840251442** [comment]
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/0be01afc-3018-4601-9c31-b33ff6088b56">

**Comment by jikkai** [comment]
We do not have plans to support this feature at this time.
