### ISSUE TITLE
[Bug] For two grids, first merge the cells, then cancel the cells, and then report an error when merging the cells. When canceling, click and report the following error.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3483]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.12

### 复现链接

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/31262288-0486-45f4-a75b-3046ebc72b13">

### 预期行为

应该是正常可以 合并 取消 在合并

### 实际行为

合并。取消 在合并失败

**Comment by jikkai** [comment]
Please follow our community rules and provide a minimal reproduction link.

**Comment by 840251442** [comment]
fUniverRef.current.onCommandExecuted((command) => {
        console.log(command, command.id);
    });
    setTimeout(() => {
        fUniverRef.current.executeCommand('sheet.operation.set-selections', {
            "unitId": "workbook-01",
            "subUnitId": "sheet-01",
            "selections": [
                {
                    "range": {
                        "startRow": 3,
                        "startColumn": 10,
                        "endRow": 4,
                        "endColumn": 11,
                        "rangeType": 0,
                        "unitId": "workbook-01",
                        "sheetId": "sheet-01"
                    },
                    "style": null,
                    "primary": {
                        "startRow": 3,
                        "startColumn": 10,
                        "endRow": 4,
                        "endColumn": 11,
                        "actualRow": 3,
                        "actualColumn": 10,
                        "isMerged": true,
                        "isMergedMainCell": true
                    }
                }
            ]
        })
        fUniverRef.current.executeCommand('sheet.command.add-worksheet-merge',{
            "selections": [
                {
                    "startRow": 3,
                    "startColumn": 10,
                    "endRow": 4,
                    "endColumn": 11,
                    "rangeType": 0,
                    "unitId": "workbook-01",
                    "sheetId": "sheet-01"
                }
            ],
            "unitId": "workbook-01",
            "subUnitId": "sheet-01"
        })
        fUniverRef.current.executeCommand('sheet.command.add-worksheet-merge-all', {
            "label": "sheet.command.add-worksheet-merge-all",
            "id": "sheet.command.add-worksheet-merge-all"
        })
        setTimeout(() => {
            fUniverRef.current.executeCommand('sheet.mutation.remove-worksheet-merge', {
                "unitId": "workbook-01",
                "subUnitId": "sheet-01",
                "ranges": [
                    {
                        "startRow": 3,
                        "startColumn": 10,
                        "endRow": 4,
                        "endColumn": 11,
                        "rangeType": 0,
                        "unitId": "workbook-01",
                        "sheetId": "sheet-01"
                    }
                ],
                "trigger": "sheet.command.remove-worksheet-merge"
            }, 2)
            fUniverRef.current.executeCommand("sheet.mutation.set-range-values", {
                "unitId": "workbook-01",
                "subUnitId": "sheet-01",
                "cellValue": {},
                "trigger": "sheet.command.remove-worksheet-merge"
            }, 2)
            fUniverRef.current.executeCommand("formula.mutation.set-array-formula-data", {
                "arrayFormulaRange": {},
                "arrayFormulaCellData": {}
            }, 2)
            fUniverRef.current.executeCommand("formula.mutation.set-formula-data", {
                "formulaData": {
                    "workbook-01": {
                        "sheet-01": {}
                    }
                }
            }, 2)
            fUniverRef.current.executeCommand("sheet.command.remove-worksheet-merge", {
                "label": "sheet.command.remove-worksheet-merge",
                "id": "sheet.command.remove-worksheet-merge",
                value: undefined
            }, 2);
            fUniverRef.current.executeCommand("formula.mutation.set-formula-calculation-start", {
                "dirtyRanges": [],
                "dirtyNameMap": {},
                "dirtyDefinedNameMap": {},
                "dirtyUnitFeatureMap": {},
                "dirtyUnitOtherFormulaMap": {},
                "forceCalculation": false
            }, 0)
            fUniverRef.current.executeCommand("sheet.command.add-worksheet-merge-all", {
                "label": "sheet.command.add-worksheet-merge-all",
                "id": "sheet.command.add-worksheet-merge-all"
            }, 2)
        }, 100)
    }, 100)

这个bug 用命令复现不出来感觉跟点击事件有关系 你可以按照 我上面提供的操作流程 去手动点击合并单元格 和 取消单元格 在点击合并单元格

**Comment by 840251442** [comment]
这个bug 用指令复现不出来感觉跟点击事件有关系 你可以按照 我上面提供的指令操作流程 手动点击 合并单元格 和 取消单元格 在点击合并单元格

**Comment by jikkai** [comment]
We were unable to reproduce the issue following the steps you provided. Please provide a reproduction link and more detailed reproduction steps so we can further investigate. You can also consider upgrading to the latest version to confirm whether this issue still exists.

**Comment by 840251442** [comment]
我直接使用命令是复现不了这个问题，但是 我手动行为操作这个问题一定会出现，对于这个问题 我真不知道我应该怎么用code 去描述。我可以通过录用视频的方式去描述这个问题吗

**Comment by jikkai** [comment]
Providing a live reproduction link or a repository link helps us ensure that your build tools aren't causing the issue and eliminates potential environmental factors. Clear reproduction steps are crucial for understanding the specific problem you're facing. Please include all the necessary information to help us reproduce the issue, ideally providing every possible means to recreate the problem you're encountering.

---

提供一个在线复现链接或仓库链接可以帮助我们确保你的构建工具不是问题所在，并消除可能的环境因素。清晰的复现步骤对于理解你面临的特定问题至关重要。请包含所有必要信息以帮助我们复现问题，理想情况下可以提供所有可能的方式来构筑你所遇到的问题。

**Comment by 840251442** [comment]
Uploading 632_1726795448.mp4…
你可以看一下我视频里的操作

**Comment by 840251442** [comment]
[Uploading merge-video.mp4.zip…]()

**Comment by 840251442** [comment]
上面这个视频应该可以说明这个问题

**Comment by jikkai** [comment]
You have not uploaded any content.

**Comment by 840251442** [comment]
我上面有传一个 zip 文件里面是我压缩的操作视频
[Uploading merge-video.mp4.zip…]()

**Comment by 840251442** [comment]
好像是我网络问题导致传输失败了 sorry 我在传一次
[merge-video.mp4.zip](https://github.com/user-attachments/files/17069256/merge-video.mp4.zip)

**Comment by jikkai** [comment]
This issue does not exist in 0.2.14, but we have found an additional bug where the selection is lost after deselecting. We are trying to fix it, please pay attention to updates for `0.2.15` or `0.2.16`.

**Comment by 840251442** [comment]
0.2.15 或者 0.2.16 什么时候会更新 ，有时间点吗。我看我之前反馈有的问题被关闭了。但是没看到最新的版本
