### ISSUE TITLE
[Bug] Custom is lost during copying cells

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3487]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.11

### 复现链接

https://github.com/840251442/sheets-vite-demo/tree/840251442/patch-25281

### 预期行为

预期第二个单元格应该把第一个单元格的custom 复制过去

### 实际行为

实际只复制了v 没复制custom

**Comment by jikkai** [comment]
1. Please note that the `selections` field is no longer available.
2. The issue with copy-pasting within `custom` will be fixed in an upcoming release.

BTW, You can add further information to closed issues and reopen them. Please avoid submitting duplicate issues.

**Comment by 840251442** [comment]
好的 我后面会按照reopen 这种去重新打开重复的问题。我另一个没法通过code 去复现的问题 通过视频这种去描述可以吗
