### ISSUE TITLE
[Bug] When there are two merged cells and a border is set, one side will disappear.

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3490]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.14

### 复现链接

https://github.com/840251442/sheets-vite-demo/tree/840251442/patch-87669

### 预期行为

两个线都应该正常展示

### 实际行为

现在有一个线只展示了一半

**Comment by ybzky** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/3a5bc94a-92ff-4b82-b70f-1156e72c81ed">
在这个函数里 把合并单元格的边框线设置为null了 @Dushusir 帮忙看看之前为什么要这么做

**Comment by Dushusir** [comment]
![image](https://github.com/user-attachments/assets/59f35bfa-4466-4c23-a737-5cf58379c5e5)
The data is correct, but the render cache ignores the top border of the merged cell @lumixraku

**Comment by lumixraku** [comment]
same as https://github.com/dream-num/univer/issues/2509
