### ISSUE TITLE
[Feature]How to import files without using background service?

### ISSUE THREAD

**Issue by lanfaboy** [dream-num/univer#3499]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

打开或编辑一个 Excel 文件的 URL 地址 提示Error: [redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".
at DependencyNotFoundError2.RediErro

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/features/import-export

Import/export must be implemented using the services provided by Univer. This error indicates that the plugin package and facade API are not being used correctly, as outlined in the documentation. Please review the documentation carefully and ensure proper implementation. If the issue persists, provide sufficient information for us to assist you further.
