### ISSUE TITLE
[Bug] DOC adding image error and I can not get pictuer data 

### ISSUE THREAD

**Issue by DKSwang** [dream-num/univer#3500]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.14

### Reproduction link

Adding images smoothly without errors and able to capture data

### Expected behavior

Adding images smoothly without errors and able to capture data

### Actual behavior

Adding images smoothly without errors and able to capture data

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
