### ISSUE TITLE
[Bug] When multiple people collaborate, using backspace to delete multiple rows of data will cause errors when the operation is synchronized to other users.

### ISSUE THREAD

**Issue by LiuYuLu** [dream-num/univer#3529]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

bug发生的原因是ws 消息体过大，导致ws服务端无法处理，希望能够在command指令能给出大小，屏蔽过大的操作。

<img width="1341" alt="image" src="https://github.com/user-attachments/assets/eef12bae-7131-4dd5-8578-b8a4a059c1e3">

### 预期行为

ws 可正常工作

### 实际行为

ws 无法正常工作

**Comment by jikkai** [comment]
If you choose to implement collaboration features using WebSockets independently, please note that Univer will not preprocess user data. You will need to implement any necessary data handling within your own implementation.

Should you encounter issues when utilizing Univer's collaborative services, kindly provide us with sufficient details about the problem you are experiencing to enable us to provide appropriate support.
