### ISSUE TITLE
[Bug] sheet.insertRows/insertRowsAfter is not a function

### ISSUE THREAD

**Issue by lichencc** [dream-num/univer#3550]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

https://codesandbox.io/p/devbox/rt9vcq

### Expected behavior

The API can be used normally. I'm not sure if there's a problem with the UMD citation, but the official website Playground also has this issue.

### Actual behavior

is not a function

**Comment by jikkai** [comment]
Please provide an accessible minimization reproduction.

**Comment by lichencc** [comment]
> Please provide an accessible minimization reproduction.

@jikkai  https://codesandbox.io/p/devbox/rt9vcq

**Comment by lichencc** [comment]
> Please provide an accessible minimization reproduction.

it's a public sandbox now

**Comment by jikkai** [comment]
Please use the latest version.

<img width="680" alt="image" src="https://github.com/user-attachments/assets/0a25331c-b15b-493c-9b1f-25d2c81a7605">

**Comment by lichencc** [comment]
> Please use the latest version.
> 
> <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/14025786/370189273-0a25331c-b15b-493c-9b1f-25d2c81a7605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjUwNjksIm5iZiI6MTcyNzE2NDc2OSwicGF0aCI6Ii8xNDAyNTc4Ni8zNzAxODkyNzMtMGEyNTMzMWMtYjE1Yi00OTNjLTliMWYtMjVkMmM4MWE3NjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4M2MwYzRmYjBjNWRmYWQwZmE4OWU0MGQxYmQ2MWRmODg0ZTRiYTZjMDg3NWU4MDZkMmFjNjY2ZDc0YjU4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-3HKmmxzNqDYm0U4NWuA87MYIQhS7AZdkczqQALuYRI">

Thanks a lot~~~ I copied this version from https://univer.ai/zh-CN/playground?title=UMD, the officail Univer website. And there is a spelling error about `div id=app`.  Could you please update the examples in the official website playground when you have time
