### ISSUE TITLE
[Bug] Scrollbar Jumps on Drag Start

### ISSUE THREAD

**Issue by yuwenhao12** [dream-num/univer#3554]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

You can repeat this question in the official online DEMO

### 预期行为

The same behavior as a scroll bar in a traditional document flow

### 实际行为

When I click on the scroll bar, the position of the scroll bar changes in an unexpected forced position

### 运行环境

Chrome

**Comment by jikkai** [comment]
你可以用中文详细描述遇到的问题，并提供一切必要的信息

**Comment by yuwenhao12** [comment]
当我拖拽滚动条时，滚动条会异常偏移，表现为当我点击滚动条最左侧，滚动条会瞬移到我鼠标的右侧大概50px位置
![gitIssue](https://github.com/user-attachments/assets/48e41f65-28bd-4f18-b43a-55993100745b)
