### ISSUE TITLE
[Bug] after reinitializing with univerAPI.disposeUnit missing column header and has `permissionPoint does not exist` error

### ISSUE THREAD

**Issue by zwight** [dream-num/univer#3555]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-dkkrow

### Expected behavior

After reinitialization with univerAPI.disposeUnit, column header is display normally and no error `permissionPoint does not exist` will occur

### Actual behavior

when import hyperlink plugin，after reinitialization with univerAPI.disposeUnit，column header missing and focus cell has error `permissionPoint does not exist` in console

![image](https://github.com/user-attachments/assets/e92691ba-3b54-4149-be37-eb104e02e280)

**Comment by mietl** [comment]
I am not interested in solving this problem now, but rather the issue of editing permissions from one table to another. However, I do not know how to refresh permissions.

Implementing batchAllowed in IAuthzIoService does not trigger a re-call.

**Comment by mietl** [comment]
@ybzky

**Comment by ybzky** [comment]
Permission related issues have been fixed and will be released in the next version

**Comment by lumixraku** [comment]
Way to reproduce this issue:
first
univerAPI.disposeUnit('workbook-01')
then
univerAPI.createUniverSheet()

**Comment by mietl** [comment]
> Permission related issues have been fixed and will be released in the next version

This issue still exists.
