### ISSUE TITLE
[Bug] createUniverSheet(snapshot) did not perform as expected

### ISSUE THREAD

**Issue by wang2lang** [dream-num/univer#3557]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-sw3ee3?file=src%2Fmain.ts

### Expected behavior

The background color can be consistently removed and the system reset to its original state with each operation.

### Actual behavior

The system failed to reset to its original condition after the second run.

**Comment by lumixraku** [comment]
You mean the header is not rendering correct? 
<img width="639" alt="image" src="https://github.com/user-attachments/assets/4ff907c9-cef6-4ac2-a7c8-cf789bf0f10b">

**Comment by jikkai** [comment]
https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-xskccx?file=src%2Fmain.ts


Reference: https://github.com/dream-num/univer/issues/2767
