### ISSUE TITLE
[Bug] Cell editor position display problem

### ISSUE THREAD

**Issue by jerry-f** [dream-num/univer#3579]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

所有版本，包括最新的0.2.15

### 复现链接

当在小的单元格编辑之后，内容较少没有问题，能正常编辑， 当在另一个单元格内容很多的时候，编辑，将单元格设置自动换行，并且内容很多，此时，编辑完之后在到其他单元格编辑，这时就出现了问题， 在新的单元格上看不到编辑的内容，实际上时编辑了的。

https://github.com/user-attachments/assets/0c9e98bf-1cfd-4772-b96c-ab25aa1cf888

### 预期行为

在任何单元格上都能查看到编辑的内容。

### 实际行为

在内容多的单元格编辑之后，转移到小单元格， 编辑时，不能查看到编辑的光标，也看不到任何编辑的内容。

### 系统信息

  System:
    OS: Windows 11 10.0.22631
    CPU: xxx
    Memory: 6.38 GB / 29.74 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: chromedriver.exe
chromedriver_win32.zip
LICENSE.chromedriver
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

**Comment by hexf00** [comment]
> Could you please provide more specific steps and the correct video or a link to reproduce the issue?
> 
> 你能重新描述一下具体步骤以及提供正确的视频或者复现链接吗？

可以复现，先粘贴一个长文本，然后编辑上一个单元格

**Comment by jerry-f** [comment]
是可以复现的， 浮现的步骤： "先粘贴一个长文本，然后再编辑一个默认的小单元格"
我再试试看能不能上传正确的视频， 好像还是不行~

![image](https://github.com/user-attachments/assets/f0e9a4d3-12e6-4ec5-8b51-76a643509928)


https://github.com/user-attachments/assets/259448f4-7fe3-43df-9e26-dafdc6d7782e
