### ISSUE TITLE
[Bug] with vue3  error, could not resolve react

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3581]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

na

### Reproduction link

na

### Expected behavior

na

### Actual behavior

➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/docs-ui/lib/es/index.js:6:84:
      6 │ import { createIdentifier as zn, Inject as T, Injector as Be, Optional as Gn } from "@wendellhu/redi";
        ╵                                                                                     ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/docs/lib/es/index.js:6:45:
      6 │ import { Inject as ee, Injector as hn } from "@wendellhu/redi";
        ╵                                              ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/sheets/lib/es/index.js:5:85:
      5 │ import { createIdentifier as bo, Inject as te, Injector as kn, Optional as Xs } from "@wendellhu/redi";
        ╵                                                                                      ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/core/lib/es/index.js:4:193:
      4 │ ...able as ts, filter as Fn, merge as zs, timer as Gr, BehaviorSubject as te, map as jr, distinctUntilChanged as Vr, skip as Xs, of as Ze, combineLatest as Kr } from "rxjs";
        ╵                                                                                                                                                                       ~~~~~~  

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/sheets-formula/lib/es/index.js:5:84:
      5 │ import { Inject as F, Injector as De, createIdentifier as Wt, Optional as Si } from "@wendellhu/redi";
        ╵                                                                                     ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/docs-ui/lib/es/index.js:9:121:
      9 │ import { takeUntil as se, Observable as B, combineLatest as To, fromEvent as bt, BehaviorSubject as Mt, map as bo } from "rxjs";
        ╵                                                                                                                          ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/ui/lib/es/index.js:9:216:
      9 │ ...t as we, fromEvent as Qo, switchMap as Jo, BehaviorSubject as Q1, filter as Ko, map as Hr, startWith as ea, combineLatest as ta, distinctUntilChanged as na } from "rxjs";
        ╵                                                                                                                                                                       ~~~~~~  

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/engine-formula/lib/es/index.js:5:85:
      5 │ import { Inject as ce, createIdentifier as rt, Injector as Xt, Optional as Ti } from "@wendellhu/redi";
        ╵                                                                                      ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/docs/lib/es/index.js:7:55:
      7 │ import { BehaviorSubject as ne, takeUntil as bt } from "rxjs";
        ╵                                                        ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs/operators"

    node_modules/@univerjs/core/lib/es/index.js:5:73:
      5 │ import { filter as Yr, debounceTime as zr, first as Xr, map as qr } from "rxjs/operators";
        ╵                                                                          ~~~~~~~~~~~~~~~~

  You can mark the path "rxjs/operators" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/sheets/lib/es/index.js:8:116:
      8 │ import { shareReplay as sr, takeUntil as eo, switchMap as hn, of as mn, Subject as je, BehaviorSubject as wt } from "rxjs";
        ╵                                                                                                                     ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi/react-bindings"

    node_modules/@univerjs/docs-ui/lib/es/index.js:10:58:
      10 │ import { useDependency as z, connectInjector as Mo } from "@wendellhu/redi/react-bindings";
         ╵                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi/react-bindings" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi/react-bindings"

    node_modules/@univerjs/ui/lib/es/index.js:10:99:
      10 │ import { useDependency as ie, useInjector as ra, connectInjector as g1, useObservable as st } from "@wendellhu/redi/react-bindings";
         ╵                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi/react-bindings" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "dayjs"

    node_modules/@univerjs/design/lib/es/index.js:4:15:
      4 │ import Kr from "dayjs";
        ╵                ~~~~~~~

  You can mark the path "dayjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi/react-bindings"

    node_modules/@univerjs/sheets-formula/lib/es/index.js:12:59:
      12 │ import { useDependency as se, connectInjector as no } from "@wendellhu/redi/react-bindings";
         ╵                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi/react-bindings" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/engine-formula/lib/es/index.js:6:30:
      6 │ import { Subject as xt } from "rxjs";
        ╵                               ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/core/lib/es/index.js:6:69:
      6 │ import { createIdentifier as zt, Inject as ie, Injector as we } from "@wendellhu/redi";
        ╵                                                                      ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@univerjs/engine-numfmt"

    node_modules/@univerjs/sheets/lib/es/index.js:9:42:
      9 │ import { DEFAULT_TEXT_FORMAT as Uo } from "@univerjs/engine-numfmt";
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@univerjs/engine-numfmt" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react"

    node_modules/@univerjs/docs-ui/lib/es/index.js:11:52:
      11 │ import xo, { useState as on, useEffect as rn } from "react";
         ╵                                                     ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react"

    node_modules/@univerjs/ui/lib/es/index.js:11:19:
      11 │ import * as K from "react";
         ╵                    ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/sheets-formula/lib/es/index.js:13:156:
      13 │ import { Subject as _e, combineLatestWith as ao, map as Je, switchMap as io, of as Jn, Observable as ro, merge as ea, filter as dn, bufferTime as oo } from "rxjs";
         ╵                                                                                                                                                             ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react"

    node_modules/@univerjs/design/lib/es/index.js:6:19:
      6 │ import * as f from "react";
        ╵                    ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs/operators"

    node_modules/@univerjs/sheets/lib/es/index.js:10:57:
      10 │ import { takeUntil as to, filter as no, map as rr } from "rxjs/operators";
         ╵                                                          ~~~~~~~~~~~~~~~~

  You can mark the path "rxjs/operators" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:8:100:
      8 │ import { Inject as H, Injector as vt, createIdentifier as nn, Quantity as Xl, Optional as bh } from "@wendellhu/redi";
        ╵                                                                                                     ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/ui/lib/es/index.js:13:85:
      13 │ import { Inject as ke, createIdentifier as Ve, Optional as zt, Injector as s1 } from "@wendellhu/redi";
         ╵                                                                                      ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react"

    node_modules/@univerjs/sheets-formula/lib/es/index.js:14:104:
      14 │ import uo, { forwardRef as dt, useRef as Ua, createElement as pt, useState as W, useEffect as gt } from "react";
         ╵                                                                                                         ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react-dom"

    node_modules/@univerjs/design/lib/es/index.js:8:87:
      8 │ import Gn, { createPortal as Af, unstable_batchedUpdates as fg, flushSync as jl } from "react-dom";
        ╵                                                                                        ~~~~~~~~~~~

  You can mark the path "react-dom" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/engine-render/lib/es/index.js:5:98:
      5 │ import { Inject as ln, isClassDependencyItem as F6, Injector as Gr, createIdentifier as k0 } from "@wendellhu/redi";
        ╵                                                                                                   ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:9:284:
      9 │ ...Tt, distinctUntilChanged as Gs, Subject as lt, Observable as tt, combineLatestWith as jn, filter as wh, Subscription as Hn, merge as Wt, throttleTime as bp } from "rxjs"; 
        ╵                                                                                                                                                                       ~~~~~~  

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs/operators"

    node_modules/@univerjs/ui/lib/es/index.js:16:26:
      16 │ import { map as Tr } from "rxjs/operators";
         ╵                           ~~~~~~~~~~~~~~~~

  You can mark the path "rxjs/operators" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi"

    node_modules/@univerjs/rpc/lib/es/index.js:5:66:
      5 │ import { createIdentifier as O, Inject as g, Injector as C } from "@wendellhu/redi";
        ╵                                                                   ~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/engine-render/lib/es/index.js:6:172:
      6 │ ...BehaviorSubject as d1, startWith as C6, distinctUntilChanged as E6, Subject as Ke, Observable as jr, shareReplay as S6, Subscription as k6, fromEvent as A1 } from "rxjs"; 
        ╵                                                                                                                                                                       ~~~~~~  

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@univerjs/engine-numfmt"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:11:15:
      11 │ import fn from "@univerjs/engine-numfmt";
         ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@univerjs/engine-numfmt" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react-dom"

    node_modules/@univerjs/ui/lib/es/index.js:17:39:
      17 │ import Rn, { createPortal as Vr } from "react-dom";
         ╵                                        ~~~~~~~~~~~

  You can mark the path "react-dom" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs/operators"

    node_modules/@univerjs/rpc/lib/es/index.js:6:57:
      6 │ import { takeUntil as f, filter as ee, take as te } from "rxjs/operators";
        ╵                                                          ~~~~~~~~~~~~~~~~

  You can mark the path "rxjs/operators" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@wendellhu/redi/react-bindings"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:13:58:
      13 │ import { useDependency as j, connectInjector as Zo } from "@wendellhu/redi/react-bindings";
         ╵                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@wendellhu/redi/react-bindings" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs"

    node_modules/@univerjs/rpc/lib/es/index.js:7:125:
      7 │ import { isObservable as se, of as ne, BehaviorSubject as re, firstValueFrom as ie, Observable as $, shareReplay as A } from "rxjs";
        ╵                                                                                                                              ~~~~~~

  You can mark the path "rxjs" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "rxjs/operators"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:14:29:
      14 │ import { filter as Ah } from "rxjs/operators";
         ╵                              ~~~~~~~~~~~~~~~~

  You can mark the path "rxjs/operators" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "react"

    node_modules/@univerjs/sheets-ui/lib/es/index.js:17:162:
      17 │ import Bs, { useState as de, useEffect as Se, forwardRef as ht, useRef as Zl, createElement as at, useCallback as kn, useLayoutEffect as Jp, useMemo as $p } from "react";
         ╵                                                                                                                                                                   ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

### System information

vue3 error,  demo error too
https://github.com/awesome-univer/sheets-vue3-demo

**Comment by hexf00** [comment]
> npm install # npm version >= 7  or pnpm install

Please read README and official website documents for troubleshooting

> If you are using npm, make sure you are using npm@7 or higher. This is because npm@3 ~ npm@6 will not correctly install peerDependencies[1](https://univer.ai/guides/sheet/getting-started/installation#user-content-fn-1).
> If you are using pnpm, make sure you are using pnpm@8 or higher. If you are using pnpm@6 ~ pnpm@7, you can try configuring auto-install-peers=true [2](https://univer.ai/guides/sheet/getting-started/installation#user-content-fn-2) to resolve dependency installation issues.
> If you are using yarn, you need to manually install the missing peerDependencies[3](https://univer.ai/guides/sheet/getting-started/installation#user-content-fn-3), but don't worry, the installation commands below already include these dependencies.

https://univer.ai/guides/sheet/getting-started/installation#installation
