### ISSUE TITLE
[Feature]  multi-grid sheets

### ISSUE THREAD

**Issue by fadi123go** [dream-num/univer#3587]
### Initial checklist

- [X] I have searched the Github Issues for similar issues, but did not find anything.
- [ ] Is this really a problem?

### Problem

This is a major feature suggestion but sheets should support more than one grid.  Each grid should support its own filtering, freeze and sorting operations . This is similar to [rows.com](url) . Grids would grow manually with plus signs next to last row and last column and they could be resized to fit the table you are creating and when printing you  could select which grid would be included in the print. 

Currently all spreadsheet apps follow the excel model, one endless grid that can be used unfortunately for only one table. My idea is that grids should complement each other in terms of information . One grid could provide a profile of the subject the other could grow endlessly while the the third could provide analytics. Each grid should have its apparent  name and a distinct one-word-name that should be unique per workbook, in case you decide to move a grid across the workbook. The one-word-name should be used in formulas.  And you should be able to roll up grids or change their order per sheet.

Also you may have to introduce a more relative cell reference, next to the current method of course , such as B-first, B-last , and B @row. Last in particular would be very useful for multi-grid design since users would continually add more rows to grids. For analytics in the third grid, for example, you will have to put something like :  thirdgrid.B4=sum(secondgrid.B3:secondgrid.B-last) for calculating sum, and for average it would be : thridgrid.B6=average(secondgrid.B3:secondgrid.B-last) , and so on.

For compatibility with excel format one grid would be exported as one sheet and you could choose more than one grid to be exported as a workbook. Since you are a startup you should really consider such a major feature.

**Comment by jikkai** [comment]
Thank you for the suggestion. However, please note that Univer is primarily an office suite SDK and, as such, doesn't typically offer fully productized features like this. While Univer supports multiple instances and offers powerful extensibility, allowing you to override existing components and services to implement functionality similar to row.com (as we've demonstrated in previous feasibility studies), it would require a significant development effort.

We don't currently have the resources to provide a more streamlined implementation for developers. Therefore, we'll add this issue to our backlog. We always welcome new ideas and encourage you to submit a pull request if you're interested in contributing a solution.

**Comment by fadi123go** [comment]
Thanks. Sheet instances are different from multi-grid sheets .Perhaps in the future you may find the resources to apply this idea.
