### ISSUE TITLE
[Bug] The export api will report an error when exporting large files.

### ISSUE THREAD

**Issue by zkzk4635** [dream-num/univer#3590]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

[QMS&QCP Documents of SP- QAQC Dept. Rev-0.xlsx](https://github.com/user-attachments/files/17143763/QMS.QCP.Documents.of.SP-.QAQC.Dept.Rev-0.xlsx)
When I import this file and then export it, an error occurs.

### 预期行为

export success

### 实际行为

![image](https://github.com/user-attachments/assets/e5fe5434-ccf3-4ef9-9224-5a34cc12988e)

### 运行环境

Chrome

**Comment by jikkai** [comment]
This is a limitation of the free version, not a bug.
