### ISSUE TITLE
[Bug] App freezes due to high frequency changes

### ISSUE THREAD

**Issue by NadaaFarook** [dream-num/univer#3591]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.12

### Reproduction link

-

### Expected behavior

I should be able to edit text no matter what is going on in the BG. Also the focused cell should not lose focus

### Actual behavior

Hey, so I have a sheet that changes numerical data every second. And based on the data, the cells change bg color. Due to the very frequent bg change, the cells are uneditable. Any workaround this ?
Also, if i have a cell focused to edit, on the bg change, the app loses the focused cell

**Comment by jikkai** [comment]
Please provide a minimal reproduction.

**Comment by NadaaFarook** [comment]
Reproduction might not be possible but attached a loom for the exact issue demonstration

https://www.loom.com/share/ee1809754b014048b87abb050af6ae92

**Comment by jikkai** [comment]
Not sure if this is enough info to find the problem. Perhaps you could take a look, @Jocs ?

**Comment by NadaaFarook** [comment]
any update on this @Jocs

**Comment by Jocs** [comment]
@weird94

**Comment by weird94** [comment]
This issue will be fixed on next version, please follow our weekly update, thanks.
