### ISSUE TITLE
[Feature] I want to remove all the default formulas and add my own formulas. How do I clear them?

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3594]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

我想把默认的公式都给去掉 然后加入自己的公式 ，我该怎么去处清除他们

**Comment by jikkai** [comment]
https://univer.ai/typedoc/@univerjs/engine-formula/interfaces/IFunctionService#unregisterexecutors

**Comment by 840251442** [comment]
![image](https://github.com/user-attachments/assets/eeb0df77-4123-4bfe-b9e2-e188c8140ef3)
我已经做了清除的逻辑为什么他们还可以被搜索出来

**Comment by jikkai** [comment]
https://univer.ai/typedoc/@univerjs/engine-formula/interfaces/IFunctionService#unregisterdescriptions

I believe some independent exploration would be beneficial.

**Comment by 840251442** [comment]
https://univer.ai/typedoc/@univerjs/sheets-formula/functions/IDescriptionService  上面的服务使用了没生效 我用了下面的实现了。 我还有个问题 大概新版本是多久发一次 一周吗

**Comment by 840251442** [comment]
this._IDescriptionService.unregisterDescriptions(Array.from(keys));
            this._IFunctionService.unregisterExecutors
我通过他们是取消了描述，但是自身函数的计算逻辑好像还没有移除掉。我还需要处理哪个地方
