### ISSUE TITLE
Commonly used formulas

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#363]
List of all formulas referenced from Luckysheet
1. The latest excel formula list to be updated
2. Deadline for discussion

- [ ] SUMIF
- [ ] TAN
- [ ] TANH
- [ ] CEILING
- [ ] ATAN
- [ ] ASINH
- [ ] ABS
- [ ] ACOS
- [ ] ACOSH
- [ ] MULTINOMIAL
- [ ] ATANH
- [ ] ATAN2
- [ ] COUNTBLANK
- [ ] COSH
- [ ] INT
- [ ] ISEVEN
- [ ] ISODD
- [ ] LCM
- [ ] LN
- [ ] LOG
- [ ] LOG10
- [ ] MOD
- [ ] MROUND
- [ ] ODD
- [ ] SUMSQ
- [ ] COMBIN
- [ ] SUM
- [ ] SUBTOTAL
- [ ] ASIN
- [ ] COUNTIF
- [ ] RADIANS
- [ ] RAND
- [ ] COUNTUNIQUE
- [ ] DEGREES
- [ ] ERFC
- [ ] EVEN
- [ ] EXP
- [ ] FACT
- [ ] FACTDOUBLE
- [ ] PI
- [ ] FLOOR
- [ ] GCD
- [ ] RANDBETWEEN
- [ ] ROUND
- [ ] ROUNDDOWN
- [ ] ROUNDUP
- [ ] SERIESSUM
- [ ] SIGN
- [ ] SIN
- [ ] SINH
- [ ] SQRT
- [ ] SQRTPI
- [ ] GAMMALN
- [ ] COS
- [ ] TRUNC
- [ ] QUOTIENT
- [ ] POWER
- [ ] SUMIFS
- [ ] GET_TARGET
- [ ] GET_AIRTABLE_DATA
- [ ] ASK_AI
- [ ] COUNTIFS
- [ ] PRODUCT
- [ ] HARMEAN
- [ ] HYPGEOMDIST
- [ ] INTERCEPT
- [ ] KURT
- [ ] LARGE
- [ ] STDEVA
- [ ] STDEVP
- [ ] GEOMEAN
- [ ] RANK_EQ
- [ ] RANK_AVG
- [ ] PERCENTRANK_EXC
- [ ] PERCENTRANK_INC
- [ ] FORECAST
- [ ] FISHERINV
- [ ] FISHER
- [ ] MODE_SNGL
- [ ] WEIBULL_DIST
- [ ] COUNT
- [ ] COUNTA
- [ ] AVEDEV
- [ ] AVERAGE
- [ ] AVERAGEA
- [ ] BINOM_DIST
- [ ] BINOM_INV
- [ ] CONFIDENCE_NORM
- [ ] CORREL
- [ ] COVARIANCE_P
- [ ] COVARIANCE_S
- [ ] DEVSQ
- [ ] EXPON_DIST
- [ ] AVERAGEIF
- [ ] AVERAGEIFS
- [ ] PERMUT
- [ ] TRIMMEAN
- [ ] PERCENTILE_EXC
- [ ] PERCENTILE_INC
- [ ] PEARSON
- [ ] NORM_S_INV
- [ ] NORM_S_DIST
- [ ] NORM_INV
- [ ] NORM_DIST
- [ ] NEGBINOM_DIST
- [ ] MINA
- [ ] MIN
- [ ] MEDIAN
- [ ] MAXA
- [ ] MAX
- [ ] LOGNORM_INV
- [ ] LOGNORM_DIST
- [ ] Z_TEST
- [ ] PROB
- [ ] QUARTILE_EXC
- [ ] QUARTILE_INC
- [ ] POISSON_DIST
- [ ] RSQ
- [ ] T_DIST
- [ ] T_DIST_2T
- [ ] T_DIST_RT
- [ ] T_INV
- [ ] T_INV_2T
- [ ] T_TEST
- [ ] F_DIST
- [ ] F_DIST_RT
- [ ] VAR_P
- [ ] VAR_S
- [ ] VARA
- [ ] VARPA
- [ ] STEYX
- [ ] STANDARDIZE
- [ ] SMALL
- [ ] SLOPE
- [ ] SKEW
- [ ] SKEW_P
- [ ] VLOOKUP
- [ ] HLOOKUP
- [ ] LOOKUP
- [ ] ADDRESS
- [ ] INDIRECT
- [ ] ROW
- [ ] ROWS
- [ ] COLUMN
- [ ] COLUMNS
- [ ] OFFSET
- [ ] MATCH
- [ ] INDEX
- [ ] GETPIVOTDATA
- [ ] CHOOSE
- [ ] HYPERLINK
- [ ] TIME
- [ ] TIMEVALUE
- [ ] EOMONTH
- [ ] EDATE
- [ ] SECOND
- [ ] MINUTE
- [ ] HOUR
- [ ] NOW
- [ ] NETWORKDAYS
- [ ] NETWORKDAYS_INTL
- [ ] ISOWEEKNUM
- [ ] WEEKNUM
- [ ] WEEKDAY
- [ ] DAY
- [ ] DAYS
- [ ] DAYS360
- [ ] DATE
- [ ] DATEVALUE
- [ ] DATEDIF
- [ ] WORKDAY
- [ ] WORKDAY_INTL
- [ ] YEAR
- [ ] YEARFRAC
- [ ] TODAY
- [ ] MONTH
- [ ] EFFECT
- [ ] DOLLAR
- [ ] DOLLARDE
- [ ] DOLLARFR
- [ ] DB
- [ ] DDB
- [ ] RATE
- [ ] CUMPRINC
- [ ] COUPNUM
- [ ] SYD
- [ ] TBILLEQ
- [ ] TBILLYIELD
- [ ] TBILLPRICE
- [ ] PV
- [ ] ACCRINT
- [ ] ACCRINTM
- [ ] COUPDAYBS
- [ ] COUPDAYS
- [ ] COUPDAYSNC
- [ ] COUPNCD
- [ ] COUPPCD
- [ ] FV
- [ ] FVSCHEDULE
- [ ] YIELD
- [ ] YIELDDISC
- [ ] NOMINAL
- [ ] XIRR
- [ ] MIRR
- [ ] IRR
- [ ] NPV
- [ ] XNPV
- [ ] CUMIPMT
- [ ] PMT
- [ ] IPMT
- [ ] PPMT
- [ ] INTRATE
- [ ] PRICE
- [ ] PRICEDISC
- [ ] PRICEMAT
- [ ] RECEIVED
- [ ] DISC
- [ ] NPER
- [ ] SLN
- [ ] DURATION
- [ ] MDURATION
- [ ] BIN2DEC
- [ ] BIN2HEX
- [ ] BIN2OCT
- [ ] DEC2BIN
- [ ] DEC2HEX
- [ ] DEC2OCT
- [ ] HEX2BIN
- [ ] HEX2DEC
- [ ] HEX2OCT
- [ ] OCT2BIN
- [ ] OCT2DEC
- [ ] OCT2HEX
- [ ] COMPLEX
- [ ] IMREAL
- [ ] IMAGINARY
- [ ] IMCONJUGATE
- [ ] IMABS
- [ ] DELTA
- [ ] IMSUM
- [ ] IMSUB
- [ ] IMPRODUCT
- [ ] IMDIV
- [ ] NOT
- [ ] TRUE
- [ ] FALSE
- [ ] AND
- [ ] IFERROR
- [ ] IF
- [ ] OR
- [ ] NE
- [ ] EQ
- [ ] GT
- [ ] GTE
- [ ] LT
- [ ] LTE
- [ ] ADD
- [ ] MINUS
- [ ] MULTIPLY
- [ ] DIVIDE
- [ ] CONCAT
- [ ] UNARY_PERCENT
- [ ] CONCATENATE
- [ ] CODE
- [ ] CHAR
- [ ] ARABIC
- [ ] ROMAN
- [ ] REGEXEXTRACT
- [ ] REGEXMATCH
- [ ] REGEXREPLACE
- [ ] T
- [ ] FIXED
- [ ] FIND
- [ ] FINDB
- [ ] JOIN
- [ ] LEFT
- [ ] RIGHT
- [ ] MID
- [ ] LEN
- [ ] LENB
- [ ] LOWER
- [ ] UPPER
- [ ] EXACT
- [ ] REPLACE
- [ ] REPT
- [ ] SEARCH
- [ ] SUBSTITUTE
- [ ] CLEAN
- [ ] TEXT
- [ ] TRIM
- [ ] VALUE
- [ ] PROPER
- [ ] CONVERT
- [ ] SUMX2MY2
- [ ] SUMX2PY2
- [ ] SUMXMY2
- [ ] TRANSPOSE
- [ ] TREND
- [ ] FREQUENCY
- [ ] GROWTH
- [ ] LINEST
- [ ] LOGEST
- [ ] MDETERM
- [ ] MINVERSE
- [ ] MMULT
- [ ] SUMPRODUCT
- [ ] ISFORMULA
- [ ] CELL
- [ ] NA
- [ ] ERROR_TYPE
- [ ] ISBLANK
- [ ] ISERR
- [ ] ISERROR
- [ ] ISLOGICAL
- [ ] ISNA
- [ ] ISNONTEXT
- [ ] ISNUMBER
- [ ] ISREF
- [ ] ISTEXT
- [ ] TYPE
- [ ] N
- [ ] TO_DATE
- [ ] TO_PURE_NUMBER
- [ ] TO_TEXT
- [ ] TO_DOLLARS
- [ ] TO_PERCENT
- [ ] DGET
- [ ] DMAX
- [ ] DMIN
- [ ] DAVERAGE
- [ ] DCOUNT
- [ ] DCOUNTA
- [ ] DPRODUCT
- [ ] DSTDEV
- [ ] DSTDEVP
- [ ] DSUM
- [ ] DVAR
- [ ] DVARP
- [ ] AGE_BY_IDCARD
- [ ] SEX_BY_IDCARD
- [ ] BIRTHDAY_BY_IDCARD
- [ ] PROVINCE_BY_IDCARD
- [ ] CITY_BY_IDCARD
- [ ] STAR_BY_IDCARD
- [ ] ANIMAL_BY_IDCARD
- [ ] ISIDCARD
- [ ] DM_TEXT_CUTWORD
- [ ] DM_TEXT_TFIDF
- [ ] DM_TEXT_TEXTRANK
- [ ] DATA_CN_STOCK_CLOSE
- [ ] DATA_CN_STOCK_OPEN
- [ ] DATA_CN_STOCK_MAX
- [ ] DATA_CN_STOCK_MIN
- [ ] DATA_CN_STOCK_VOLUMN
- [ ] DATA_CN_STOCK_AMOUNT
- [ ] ISDATE
- [ ] LINESPLINES
- [ ] AREASPLINES
- [ ] COLUMNSPLINES
- [ ] STACKCOLUMNSPLINES
- [ ] BARSPLINES
- [ ] STACKBARSPLINES
- [ ] DISCRETESPLINES
- [ ] TRISTATESPLINES
- [ ] PIESPLINES
- [ ] BOXSPLINES
- [ ] BULLETSPLINES
- [ ] COMPOSESPLINES
- [ ] SORT
- [ ] FILTER
- [ ] UNIQUE
- [ ] RANDARRAY
- [ ] SEQUENCE
- [ ] EVALUATE
- [ ] REMOTE

**Comment by Dushusir** [comment]
Split into other issues 
https://github.com/dream-num/univer/issues/1779
https://github.com/dream-num/univer/issues/908

**Comment by Matt-Jensen** [comment]
> Split into other issues #1779 #908

It looks like some common functions listed here (ie `ROUND`, `ROUNDUP`, `ROUNDDOWN`) are no longer [covered in open issues](https://github.com/dream-num/univer/issues?q=is%3Aissue+label%3Ascope%3Aformula+label%3A%22feature+request%22+is%3Aopen).
