### ISSUE TITLE
[Bug] When umd is packaged and the date format is entered, NaN is displayed.

### ISSUE THREAD

**Issue by CJ66** [dream-num/univer#3635]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

https://univer.ai/zh-CN/guides/sheet/features/core/sheet-api

### 预期行为

正常显示日期内容

### 实际行为

显示NaN

### 运行环境

Chrome

**Comment by jikkai** [comment]
To help us understand and diagnose the issue, please provide a minimal reproduction. Without clear steps to reproduce the problem in a specific environment, it's difficult for us to pinpoint the cause.

Once you have a minimal reproduction ready, please feel free to reopen this issue. We'll be happy to investigate further.

**Comment by jikkai** [comment]
You have only provided a 404 page, and you haven't even provided steps for us to reproduce the issue.
