### ISSUE TITLE
[Bug] When pressing and holding the scroll up and down or sliding left and right, the scroll position will disappear

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#3640]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

[https://llqiwmrpoygithub-dvdl--5173--e60eb5c9.local.webcontainer.io/](https://llqiwmrpoygithub-dvdl--5173--e60eb5c9.local.webcontainer.io/)

瀏覽器：Arc 1.60.0

### 预期行为

當游標按住捲軸移動時，捲軸應該會被壓在游標下面，而且會很順暢地滾動

### 实际行为

游標按住捲軸移動時，捲軸的位置會跑掉，移動時位置也會跑掉

https://github.com/user-attachments/assets/ec9c1255-4bfb-40a6-a2a5-69737233c0b7

### 运行环境

其他 (请在复现步骤中说明)

**Comment by hexf00** [comment]
fixed on #3556
