### ISSUE TITLE
[Bug] The date formula may not be refreshed.

### ISSUE THREAD

**Issue by tjwangcan** [dream-num/univer#3641]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.15

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### 预期行为

每次进入页面时, 日期公式要自动计算成当前日期

### 实际行为

![微信图片_20240930110552](https://github.com/user-attachments/assets/b572b3ca-9170-40ac-80dc-b903bb0192f0)
**日期公式会存在有不刷新的情况. 9/26写的公式, 今天打开,发现还是显示9/26 (页面总共有336个公式)**, 需要重新修改才会刷新

**Comment by hexf00** [comment]
The issue cannot be reproduced through the link you submitted. Please submit a valid reproduction, otherwise the issue will be closed.

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
