### ISSUE TITLE
[Feature] "Force re-render" API

### ISSUE THREAD

**Issue by dima-jabali** [dream-num/univer#3643]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Hi, there!
I'm creating a custom UI surrounding Univer's Spreadsheet. I need to make sure the main view is re-rendered because some new data has appeared, but that data is not tracked by Univer. Every attempt to get it to re-render fails 🫠... been at it for a long time, tried several stuff, including calling some specific commands, and manually calling "makeDirty()", but the MainView is never completely re-rendered 🙃.

It is not the first time I find myself in need of this, so I thought of making this issue 🙏 .

Any idea how that could be achieved? I'd be very happy to make such change, if you'd like 🙏!

**Comment by semmywong** [comment]
+1

**Comment by jikkai** [comment]
After our discussion, we currently do not plan to provide a "force re-render" API. 

First, we recommend handling local data changes through the command system or the facade API, as outlined in our documentation.
Second, the functionality of "force re-render" can essentially be achieved using "dispose + create", which is already a straightforward solution.
Lastly, based on our observations of similar APIs in Luckysheet, such APIs tend to be overused in practice, potentially leading to performance issues.

For these reasons, we believe it is unnecessary to introduce a dedicated API at this time. However, we will continue to monitor user feedback and appreciate your understanding and support!
