### ISSUE TITLE
[Feature] I hope to be able to block the input of an = sign to convert an ordinary text into a formula (because I don’t need my own formula function)

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3648]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

我希望可以屏蔽掉输入一个=号就可以把一个普通文本转化成公式

**Comment by jikkai** [comment]
A configuration option could be provided to allow users to customize the symbol that triggers formulas. @Dushusir 
Such as 
```
{
  formulaTrigger: boolean | '=' | string
}
```

**Comment by Dushusir** [comment]
> A configuration option could be provided to allow users to customize the symbol that triggers formulas. @Dushusir Such as
> 
> ```
> {
>   formulaTriggerSymbol: boolean | '=' | string
> }
> ```

The `=` sign has a special meaning, so adding the configuration may be a bit difficult.

For the need to display formulas, there is currently a solution that adds a single quote `'` before the string, that is, input `'=SUM(1)`

In addition, for cells with `text format`, the formula should not be calculated when input. We are discussing solutions internally.

In addition, you can consider not registering the formula, but there are also problems at present. Pay attention to this issue https://github.com/dream-num/univer/issues/3742
