### ISSUE TITLE
[Bug] When the handler function of a custom command is triggered, there is no clicked or selected table information in the callback.

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3649]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

na

### 复现链接

na

### 预期行为

在handler中，如何获取右键选择的行信息或者单元格信息
export const reportButtonOperation: ICommand = {
id: 'report',
type: CommandType.OPERATION,
handler: async (accessor: IAccessor) => {
    // console.log(accessor.get(DocSelectionManagerService))
    // console.log(accessor.get(DocSelectionManagerService).getDocRanges())
    // console.log(accessor.get(DocSelectionManagerService).getActiveTextRange())
     // console.log(accessor.get(DocSelectionManagerService).getTextRanges())
    // console.log(accessor.get(DocSelectionManagerService).getSelectionInfo())
    return true
  }
}
![image](https://github.com/user-attachments/assets/fe4c3991-e590-4714-be27-f0d626adc499)

### 实际行为

na

### 运行环境

Chrome

### 系统信息

na

**Comment by hexf00** [comment]
Read the following documents to understand the selection content

https://univer.ai/guides/sheet/features/core/range-selection#get-active-selection

https://univer.ai/typedoc/@univerjs/facade/classes/FSelection#getactiverange

**Comment by hexf00** [comment]
For discussion, please go to https://github.com/dream-num/univer/discussions/3646
