### ISSUE TITLE
[Bug] yarn add @univerjs/sheets-pivot @univerjs/sheets-pivot-ui error

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3650]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

na

### 复现链接

yarn add @univerjs/sheets-pivot @univerjs/sheets-pivot-ui error 
尝试过各种镜像源 ，do都不行
![image](https://github.com/user-attachments/assets/4a0d5a48-c8c6-4e7c-946c-3a332ec108d0)

### 预期行为

na

### 实际行为

na

### 运行环境

Chrome

### 系统信息

.

**Comment by hexf00** [comment]
Thanks for your feedback. We found that there is an error in the description of pivot document and have corrected it. Pivot belongs to @univerjs-pro. In addition, it is not recommended to use yarn, but other package managers.

```bash
    pnpm add @univerjs-pro/engine-pivot @univerjs-pro/sheets-pivot @univerjs-pro/sheets-pivot-ui
```
