### ISSUE TITLE
[Bug] Why is 401 displayed on the create document interface after the usip service is enabled

### ISSUE THREAD

**Issue by xieruiliang** [dream-num/univer#3656]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

latest

### 复现链接

After the node language service is started with usip-example, the code of the front-end project dream-num/univer-pro-sheet-start-kit does not change after the configuration of the.env file is changed according to the document. Why does the interface create document project display 401?

### 预期行为

Just trying to change the collaborative user avatar and name

### 实际行为

But any interface 401

### 运行环境

Chrome

**Comment by jikkai** [comment]
So, what changes did you make? Please provide more details.

**Comment by hexf00** [comment]
Please read https://univer.ai/guides/sheet/server/usip#required-interfaces to make sure you implement the `Credential verify` interface correctly.

**Comment by xieruiliang** [comment]
I didn't make any changes. I just followed the documentation to modify the .env file configuration and then started the Node service you provided below. After opening the front-end project, I created a 401 error for the API endpoint in the documentation.

**Comment by hexf00** [comment]
> I didn't make any changes. I just followed the documentation to modify the .env file configuration and then started the Node service you provided below. After opening the front-end project, I created a 401 error for the API endpoint in the documentation.

After enabling USIP, you cannot do nothing. You need to implement the necessary interfaces required by the USIP list, otherwise users will get a 401 error due to lack of legal identity.

**Comment by hexf00** [comment]
@xieruiliang I have updated the [nodejs usip integration example](https://github.com/dream-num/usip-example/pull/5/files) and the [UI demo](https://github.com/dream-num/univer-pro-sheet-start-kit). After correctly configuring the USIP server-side settings, clicking the `USIP: Switch to Alice(Owner)` button in the UI will simulate the Owner user. If these changes help you understand how USIP works, please let me know. Feel free to share any additional context if you have other questions.
