### ISSUE TITLE
[Feature] Get table data based on unitID and render the table

### ISSUE THREAD

**Issue by frontendLorin** [dream-num/univer#3667]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

有个文件列表，需要在点击不同文件时，根据文件对应的unitID获取表格数据并进行表格渲染

**Comment by jikkai** [comment]
Using the facade API seems like a viable approach. If you believe the existing API won't meet your needs, please provide more details about your specific requirements.
