### ISSUE TITLE
[Bug] 单元格文本格式或者常规格式输入0开头0都会被省略掉

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3675]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.3.0

### 复现链接

官网链接即可复现

### 预期行为

文本:01--->01

### 实际行为

文本:01--->1

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please confirm that your cell type is set to [`CellValueType.FORCE_STRING`](https://univer.ai/typedoc/@univerjs/core/enumerations/CellValueType). If you still cannot input a string of numbers starting with `0` when the cell type is set to `CellValueType.FORCE_STRING`, you should provide the minimal reproduction.

**Comment by liuniuxs** [comment]
如果设置了强文本类型，但是我的数据中包含字符串,025,011这种数据，会强制弹出提示“以文本形式存储的数字”，实际中数据可能会有abcd,汉字，025等形式；
而且如果单元格初始化时包含公式，即使设置了强文本类型也会失效。
![Image_20241012094509](https://github.com/user-attachments/assets/4d5c1170-f96f-46ad-818b-0ccb0ce7d1f8)
![Image_20241012094539](https://github.com/user-attachments/assets/13723d44-d48c-42fb-9d0f-5f48b246bd68)

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by wpxp123456** [comment]
@liuniuxs 上面公式那个case 你要用强转类型 就是t设为4 f不要给值 公式字符串给到v值，或者后面设置单元格为文本格式，输入公式不会就算 显示的是文本字符串  一样的道理代码给数据的话 f不要给值  给v值
