### ISSUE TITLE
[Bug] After upgrading to 0.3.0, the custom extended Canvas function is unavailable

### ISSUE THREAD

**Issue by yujianbohz** [dream-num/univer#3690]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.3.0

### 复现链接

复现步骤：
1.下载官方示例代码：https://univer.ai/zh-CN/playground?title=Render%20Extension
2.升级到0.3.0
   2.1 调整初始化结构
      UniverDocsUIPlugin must be registered after UniverUIPlugin
      UniverRenderEnginePlugin should be registered before most plugins
3.官方示例定义拓展Canvas: 
 https://codesandbox.io/p/devbox/condescending-babbage-vkfl8h?file=%2Fmain-extension.ts%3A4%2C1&utm_medium=sandpack
3. 注册拓展Canvas插件 ： univerAPI.registerSheetRowHeaderExtension(unitId, new RowHeaderCustomExtension())
4. 页面报错：
![image](https://github.com/user-attachments/assets/224002d3-c698-469f-b620-ee5a038f1c90)

这是一个官方示例，版本号为0.2.1, 在示例代码中升级到0.3.0即可复现。

### 预期行为

在单元格中正常渲染emoji表情：🍎', '🍌', '🍒', '🍓', '🍅', '🍆', '🍇', '🍈', '🍉', '🍊

### 实际行为

报错，内容如下：
![image](https://github.com/user-attachments/assets/224002d3-c698-469f-b620-ee5a038f1c90)

**Comment by Dushusir** [comment]
Updated https://github.com/awesome-univer/sheets-render-extension-demo

Please try again
