### ISSUE TITLE
[Bug] Disabling writing resources in the cell configuration json does not take effect. The echo cannot be disabled. Just remove the resources.

### ISSUE THREAD

**Issue by zpx-haha** [dream-num/univer#3694]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.3.0

### 复现链接

//  json
export const DEFAULT_WORKBOOK_DATA = {
    id: 'workbook-01',
    locale: LocaleType.ZH_CN,
    name: 'universheet',
    sheetOrder: ['sheet-01', 'sheet-02', 'sheet-03'],
    appVersion: '0.3.0',
    sheets: {
        'sheet-01': {
            type: SheetTypes.GRID,
            id: 'sheet-01',
            cellData: {
                '0': {
                    '0': {
                        v: 'Hello World',
                    },
                },
            },
            name: 'sheet1',
            tabColor: 'red',
            hidden: BooleanNumber.FALSE,
            rowCount: 1000,
            columnCount: 20,
            zoomRatio: 1,
            scrollTop: 200,
            scrollLeft: 100,
            defaultColumnWidth: 93,
            defaultRowHeight: 27,
            status: 1,
            showGridlines: 1,
            hideRow: [],
            hideColumn: [],
            rowHeader: {
                width: 46,
                hidden: BooleanNumber.FALSE,
            },
            columnHeader: {
                height: 20,
                hidden: BooleanNumber.FALSE,
            },
            selections: ['A2'],
            rightToLeft: BooleanNumber.FALSE,
            pluginMeta: {},
        },
        'sheet-02': {
            type: SheetTypes.GRID,
            id: 'sheet-02',
            name: 'sheet2',
            cellData: {},
        },
        'sheet-03': {
            type: SheetTypes.GRID,
            id: 'sheet-03',
            name: 'sheet3',
            cellData: {},
        },
    },
    resources:[
        {name:"SHEET_RANGE_PROTECTION_PLUGIN",data:"{\"sheet-01\":[{\"permissionId\":\"3xtfxG1\",\"name\":\"sheet1\",\"unitType\":3,\"unitId\":\"workbook-01\",\"subUnitId\":\"sheet-01\",\"ranges\":[{\"startRow\":0,\"startColumn\":0,\"endRow\":0,\"endColumn\":0}],\"id\":\"rule1\"}]}"},
        {name:"SHEET_WORKSHEET_PROTECTION_PLUGIN",data:"{}"},
        {name:"SHEET_WORKSHEET_PROTECTION_POINT_PLUGIN",data:"{}"},
        {name:"SHEET_DEFINED_NAME_PLUGIN",data:""},
        {name:"SHEET_DATA_VALIDATION_PLUGIN",data:"{}"},
        {name:"SHEET_AuthzIoMockService_PLUGIN",data:"{}"}
    ]
    // resources:[
    //     {name:"SHEET_RANGE_PROTECTION_PLUGIN",data:"{\"sheet-01\":[{\"permissionId\":\"3xtfxG1\",\"name\":\"sheet1\",\"unitType\":3,\"unitId\":\"workbook-01\",\"subUnitId\":\"sheet-01\",\"ranges\":[{\"startRow\":0,\"startColumn\":0,\"endRow\":0,\"endColumn\":0}],\"id\":\"rule1\"}]}"},
    //     {name:"SHEET_WORKSHEET_PROTECTION_PLUGIN",data:"{}"},
    //     {name:"SHEET_WORKSHEET_PROTECTION_POINT_PLUGIN",data:"{}"},
    //     {name:"SHEET_DEFINED_NAME_PLUGIN",data:""},
    //     {name:"SHEET_DATA_VALIDATION_PLUGIN",data:"{}"},
    //     {name:"SHEET_AuthzIoMockService_PLUGIN",data:"{}"}
    // ]
};
// 禁用方法
getAuthority(){
      const univerRef = this.$refs.univerRef.univer
const accessor = univerRef.__getInjector();
      
      const permissionService = accessor.get(IPermissionService);
      const commandService = accessor.get(ICommandService);
      const sheetSelectionManagerService = accessor.get(SheetsSelectionsService);
      const univerInstanceService = accessor.get(IUniverInstanceService);
      const target = getSheetCommandTarget(univerInstanceService);
      if (!target) {
        return;
      }
      const { unitId, subUnitId } = target;
      const ranges = sheetSelectionManagerService.getCurrentSelections().map(selection => selection.range);
commandService.executeCommand(AddRangeProtectionMutation.id, {
        unitId,
        subUnitId,
        rules: [{
          permissionId: "3xtfxG1",
          name: "sheet1",
          unitType: 3,
          unitId,
          subUnitId,
          ranges,
          id: 'rule1'
        }],
      });
      permissionService.updatePermissionPoint(new RangeProtectionPermissionEditPoint(unitId, subUnitId, "3xtfxG1").id, false)
    },

### 预期行为

本应该回显禁用的内容 并且不会影响禁用

### 实际行为

![ebae823dbbbfc8a9eae163a09c48986](https://github.com/user-attachments/assets/4d40bc66-2857-49e9-a8d4-a7cedb6a581a)

**Comment by jikkai** [comment]
请提供一个可以运行的 demo，在线的或者 GitHub 仓库都可以

**Comment by ybzky** [comment]
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/41b43593-27b2-4018-9172-c1ca5b103ff6">
你这里写死了，这两个id每次新增的时候都要新增一个新的唯一ID, 我看你的snapshot里面已经有一个该id的保护了 所以报错了；至于init的时候snapshot中的保护没显示 这是另外的bug 已经修复 下个版本会发布
