### ISSUE TITLE
[Bug] When destroying the workbook and then creating it again, column titles are lost.

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#3701]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.3.0

### 复现链接
https://gitee.com/wang134246/univer-dome/blob/master/index.html

### 预期行为

创建工作簿

### 实际行为

![image](https://github.com/user-attachments/assets/d4830c67-dcc5-4170-ab01-cdcb1c47e175)
出现报错，并且列标题丢失。

**Comment by ybzky** [comment]
麻烦提供一个在线demo或者git仓库

**Comment by jikkai** [comment]
```diff
    function test() {
      //销毁工作簿
      univerAPI.disposeUnit(univerAPI.getActiveWorkbook().getId());
      //创建工作簿
+      setTimeout(() => {
        univer.createUnit(UniverCore.UniverInstanceType.UNIVER_SHEET, {});
+      }, 500)
    }
```

**Comment by wyl10000** [comment]
错误不显示了，但是列标题还是丢失。

**Comment by lumixraku** [comment]
header is missing is fixed in https://github.com/dream-num/univer/pull/3598
