### ISSUE TITLE
[Bug] Cannot find "HoverManagerService" registered by any injector

### ISSUE THREAD

**Issue by wangchongwei** [dream-num/univer#3703]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

no

### Expected behavior

it should be work

### Actual behavior

const univerAPI = FUniver.newAPI(univer);
univerAPI.getSheetHooks().onCellPointerMove((cell) => {
      console.log('cell =>', cell);
    })

**Comment by wangchongwei** [comment]
BTW, how can i know which cell changed? and get the cell info

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by wangchongwei** [comment]
import '@univerjs/design/lib/index.css';
import './index.css';
import '@univerjs/sheets-filter-ui/lib/index.css';
import { FUniver } from "@univerjs/facade";
import { Univer, LocaleType, UniverInstanceType } from '@univerjs/core';
import { defaultTheme } from '@univerjs/design';
import { UniverDocsPlugin } from '@univerjs/docs';
import { UniverDocsUIPlugin } from '@univerjs/docs-ui';
import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRenderEnginePlugin } from '@univerjs/engine-render';
import { UniverSheetsPlugin } from '@univerjs/sheets';
import { UniverSheetsFormulaPlugin } from '@univerjs/sheets-formula';
import { UniverSheetsUIPlugin } from '@univerjs/sheets-ui';
import { UniverUIPlugin } from '@univerjs/ui';
import { UniverSheetsFilterPlugin } from '@univerjs/sheets-filter';
import { UniverSheetsFilterUIPlugin } from '@univerjs/sheets-filter-ui';
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import { zhCN, enUS } from 'univer:locales'

// eslint-disable-next-line react/display-name
const UniverSheet = forwardRef(({ data }, ref) => {
  const univerRef = useRef(null);
  const workbookRef = useRef(null);
  const containerRef = useRef(null);
  

  useImperativeHandle(ref, () => ({
    getData,
  }));

  /**
   * Initialize univer instance and workbook instance
   * @param data {IWorkbookData} document see https://univer.work/api/core/interfaces/IWorkbookData.html
   */
  const init = (data = {}) => {
    if (!containerRef.current) {
      throw Error('container not initialized');
    }
    const univer = new Univer({
      theme: defaultTheme,
      locale: LocaleType.ZH_CN,
      locales: {
        [LocaleType.ZH_CN]: zhCN,
        [LocaleType.EN_US]: enUS,
      },
    });
    univerRef.current = univer;

    // core plugins
    univer.registerPlugin(UniverRenderEnginePlugin);
    univer.registerPlugin(UniverFormulaEnginePlugin);
    univer.registerPlugin(UniverUIPlugin, {
      container: containerRef.current,
    });

    // doc plugins
    univer.registerPlugin(UniverDocsPlugin, {
      hasScroll: false,
    });
    univer.registerPlugin(UniverDocsUIPlugin);

    // sheet plugins
    univer.registerPlugin(UniverSheetsPlugin);
    univer.registerPlugin(UniverSheetsUIPlugin);
    univer.registerPlugin(UniverSheetsFormulaPlugin);
    
    univer.registerPlugin(UniverSheetsFilterPlugin);
    univer.registerPlugin(UniverSheetsFilterUIPlugin);

    const univerAPI = FUniver.newAPI(univer);

    const dispose = univerAPI.onCommandExecuted((command) => {
      if(command.id === 'sheet.operation.set-cell-edit-visible' && !command.params.visible){
        console.log('Cell edit invisible', command.params, command);
      }
    });

    // this code will show error: Cannot find "HoverManagerService" registered by any injector
    univerAPI.getSheetHooks().onCellPointerMove((cell) => {
      console.log('cell =>', cell);
    })

  console.log('dispose =>', dispose);

    // create workbook instance
    workbookRef.current = univer.createUnit(UniverInstanceType.UNIVER_SHEET, data);
  };

  /**
   * Destroy univer instance and workbook instance
   */
  const destroyUniver = () => {
    // univerRef.current?.dispose();
    univerRef.current = null;
    workbookRef.current = null;
  };

  /**
   * Get workbook data
   */
  const getData = () => {
    console.log('getData start ->', new Date().valueOf());
    if (!workbookRef.current) {
      throw new Error('Workbook is not initialized');
    }
    const data = workbookRef.current.save();
    console.log('getData end=>', new Date().valueOf());
    return data;
  };

  useEffect(() => {
    init(data);
    return () => {
      destroyUniver();
    };
  }, [data]);

  return <div ref={containerRef} className="univer-container" />;
});

export default UniverSheet;

**Comment by wangchongwei** [comment]
```
import '@univerjs/design/lib/index.css';
import './index.css';
import '@univerjs/sheets-filter-ui/lib/index.css';
import { FUniver } from "@univerjs/facade";
import { Univer, LocaleType, UniverInstanceType } from '@univerjs/core';
import { defaultTheme } from '@univerjs/design';
import { UniverDocsPlugin } from '@univerjs/docs';
import { UniverDocsUIPlugin } from '@univerjs/docs-ui';
import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRenderEnginePlugin } from '@univerjs/engine-render';
import { UniverSheetsPlugin } from '@univerjs/sheets';
import { UniverSheetsFormulaPlugin } from '@univerjs/sheets-formula';
import { UniverSheetsUIPlugin } from '@univerjs/sheets-ui';
import { UniverUIPlugin } from '@univerjs/ui';
import { UniverSheetsFilterPlugin } from '@univerjs/sheets-filter';
import { UniverSheetsFilterUIPlugin } from '@univerjs/sheets-filter-ui';
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import { zhCN, enUS } from 'univer:locales'

// eslint-disable-next-line react/display-name
const UniverSheet = forwardRef(({ data }, ref) => {
  const univerRef = useRef(null);
  const workbookRef = useRef(null);
  const containerRef = useRef(null);
  

  useImperativeHandle(ref, () => ({
    getData,
  }));

  /**
   * Initialize univer instance and workbook instance
   * @param data {IWorkbookData} document see https://univer.work/api/core/interfaces/IWorkbookData.html
   */
  const init = (data = {}) => {
    if (!containerRef.current) {
      throw Error('container not initialized');
    }
    const univer = new Univer({
      theme: defaultTheme,
      locale: LocaleType.ZH_CN,
      locales: {
        [LocaleType.ZH_CN]: zhCN,
        [LocaleType.EN_US]: enUS,
      },
    });
    univerRef.current = univer;

    // core plugins
    univer.registerPlugin(UniverRenderEnginePlugin);
    univer.registerPlugin(UniverFormulaEnginePlugin);
    univer.registerPlugin(UniverUIPlugin, {
      container: containerRef.current,
    });

    // doc plugins
    univer.registerPlugin(UniverDocsPlugin, {
      hasScroll: false,
    });
    univer.registerPlugin(UniverDocsUIPlugin);

    // sheet plugins
    univer.registerPlugin(UniverSheetsPlugin);
    univer.registerPlugin(UniverSheetsUIPlugin);
    univer.registerPlugin(UniverSheetsFormulaPlugin);
    
    univer.registerPlugin(UniverSheetsFilterPlugin);
    univer.registerPlugin(UniverSheetsFilterUIPlugin);

    const univerAPI = FUniver.newAPI(univer);

    const dispose = univerAPI.onCommandExecuted((command) => {
      if(command.id === 'sheet.operation.set-cell-edit-visible' && !command.params.visible){
        console.log('Cell edit invisible', command.params, command);
      }
    });

    // this code will show error: Cannot find "HoverManagerService" registered by any injector
    univerAPI.getSheetHooks().onCellPointerMove((cell) => {
      console.log('cell =>', cell);
    })

  console.log('dispose =>', dispose);

    // create workbook instance
    workbookRef.current = univer.createUnit(UniverInstanceType.UNIVER_SHEET, data);
  };

  /**
   * Destroy univer instance and workbook instance
   */
  const destroyUniver = () => {
    // univerRef.current?.dispose();
    univerRef.current = null;
    workbookRef.current = null;
  };

  /**
   * Get workbook data
   */
  const getData = () => {
    console.log('getData start ->', new Date().valueOf());
    if (!workbookRef.current) {
      throw new Error('Workbook is not initialized');
    }
    const data = workbookRef.current.save();
    console.log('getData end=>', new Date().valueOf());
    return data;
  };

  useEffect(() => {
    init(data);
    return () => {
      destroyUniver();
    };
  }, [data]);

  return <div ref={containerRef} className="univer-container" />;
});

export default UniverSheet;

```

**Comment by jikkai** [comment]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/7a468be6-fc75-4797-96d1-2b9258d284c5">

Pasting code snippets makes it difficult for us to reproduce and debug the issue. A minimal reproducible example, like a link or a GitHub repository, would be much more helpful. We'll temporarily close this issue. Feel free to reopen it when you have a working demo.
