### ISSUE TITLE
[Bug] Page refresh inside the modal

### ISSUE THREAD

**Issue by tMathaiou** [dream-num/univer#3711]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.3.0 Latest

### Reproduction link

Just clicking any of those buttons my whole app refreshes, it only happens inside a modal it might have something to do with event bubbling.
![image](https://github.com/user-attachments/assets/fbcf90c1-4f8e-4714-a336-c126d6026191)

### Expected behavior

Those buttons work as expected

### Actual behavior

The application gets refreshed

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by tMathaiou** [comment]
So I found the problem. I was wrapping everything in a form tag and for some reason when I was clicking the button the form action was firing refreshing the whole app
