### ISSUE TITLE
[Bug] Custom menu, callback function gets range error, sheet.getSelection is not a function

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3723]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

na

### 复现链接

![image](https://github.com/user-attachments/assets/89d8ea7e-15b4-4a7f-a8ff-b0bb46196ca2)
![image](https://github.com/user-attachments/assets/40fa2564-f999-44ab-985a-b2c6b1fecfe5)

### 预期行为

na

### 实际行为

na

### 系统信息

na

**Comment by 13701138894** [comment]
https://github.com/13701138894/sheets-vue3-demo.git
![image](https://github.com/user-attachments/assets/9b6c5ad4-bfb2-4ab1-9b28-f8818b0ed715)
  右键选择自定义的按钮，报错代码在 src\components\plugin\commands\operations\single-button.operation.ts

**Comment by jikkai** [comment]
The facade API is not intended for plugin development. Please use the command system provided by the plugin.

**Comment by 13701138894** [comment]
I want to retrieve the selected row or cell in the plugin environment. What should I do? Do you have a demo? I couldn't find it in the documentation. Thank you
