### ISSUE TITLE
[Bug] homepage playground function unavailable

### ISSUE THREAD

**Issue by jiatingyu** [dream-num/univer#373]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

netest

### Steps to reproduce

playground function unavailable

### Expected behavior

fix  fast cdn

### Actual behavior

css、js file not found

**Comment by Dushusir** [comment]
Thanks for your feedback, please check the latest Playground link
