### ISSUE TITLE
[Bug] After removing the numfmt plugin, it fails. After entering the time type, the cell information is rewritten as NaN.

### ISSUE THREAD

**Issue by xzc-repository** [dream-num/univer#3741]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

无

### Reproduction link

例如输入2024-10

### Expected behavior

2024-10

### Actual behavior

NaN

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
