### ISSUE TITLE
[Bug] The formula plug-in UniverSheetsFormulaPlugin is not introduced or after the introduction notExecuteFormula is set to true, an error is reported

### ISSUE THREAD

**Issue by xzc-repository** [dream-num/univer#3742]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

无

### Reproduction link

公式插件UniverSheetsFormulaPlugin不引入或者引入后notExecuteFormula设置为true后，报错

### Expected behavior

正常使用其他univer功能，不使用公式的功能

### Actual behavior

整个univer报错，无法使用

**Comment by xzc-repository** [comment]
升级到0.4.0以后，sheet可以正常使用，但是输入=SUM()类似的公式还是会执行，不会识别为字符串

**Comment by Dushusir** [comment]
Data validation and conditional formatting rely on the formula module and cannot be removed for now.
It is recommended to use a forced string to prevent the triggering of formula calculation, such as `'=SUM(1)`.

**Comment by wow-222** [comment]
I have the same question, and also don't need to triggering of formula calculation @Dushusir

**Comment by EricYang1017** [comment]
> 我有同样的问题，也不需要触发公式计算

请问你怎么解决的
