### ISSUE TITLE
[Bug] Ribbon 'Others' tab flickering due to ResizeObserver

### ISSUE THREAD

**Issue by rahulnayanegali** [dream-num/univer#3744]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.3.0

### Reproduction link

Goto: http://localhost:3002/sheets/
Click on Other button which is next to Start at the top centre.

Short Recording of the issue: https://github.com/user-attachments/assets/88d57ed7-77a2-4f41-8461-50fe5e0575dd

### Expected behavior

The navbar should not flicker and it should render once.

### Actual behavior

Entire navbar keeps flickering infinitely without stopping. After debugging it is happening due to the fake navbar mounted to observe the screen width change and the width is changing in decimal level often. So this is causing the navbarIds state to be set continuously.

**Comment by rahulnayanegali** [comment]
I have fixed this issue in my forked repo and I will raise a PR if approved.

Commit: https://github.com/rahulnayanegali/univer/commit/7b49b97ef429a3171f38760e94739803666b4dd6

**Comment by jikkai** [comment]
LGTM. I've reviewed your commit and confirmed that it fixes the issue. Feel free to submit a pull request. Thank you for your contribution!
