### ISSUE TITLE
[Bug] When reloading data, the rowHeader of the worksheet is hidden

### ISSUE THREAD

**Issue by hibehero** [dream-num/univer#3755]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.3.0

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts:L51

### 预期行为

![image](https://github.com/user-attachments/assets/4a49864a-99f1-44b9-b3be-0f432c62664d)

### 实际行为

![image](https://github.com/user-attachments/assets/24de7ead-a5ab-45a5-82a1-e42cde135bf9)

### 运行环境

Chrome

**Comment by jikkai** [comment]
It has been fixed, please wait for the release of the next version.

**Comment by hibehero** [comment]
@jikkai  麻烦问下 下个版本是啥时候
