### ISSUE TITLE
[Bug] After adding a filter to the non-editable area, I used the sorting function on the filter and found that the data in the non-editable area was also involved in sorting.

### ISSUE THREAD

**Issue by xiaouu565** [dream-num/univer#3763]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

问题描述：在不可编辑区域添加筛选后,使用了筛选上的排序功能,发现不可编辑区域的数据也被参与了排序

复现链接： [https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo]
![排序后](https://github.com/user-attachments/assets/f12a6bbf-b66b-4167-964d-13bc67963801)

### 预期行为

预期效果为： 不可编辑区域不参与排序,仅排序可编辑区域的数据。  或筛选追加在了不可编辑区域,提示排序功能不可用

### 实际行为

实际效果为： 不可编辑区域的数据也参与了排序

### 运行环境

Chrome

**Comment by jikkai** [comment]
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.
