### ISSUE TITLE
[Bug] After using universalAPI.disposeUnit() and then using universalAPI.createUniverSheet() to create a table, the format brush function cannot be used normally.

### ISSUE THREAD

**Issue by lim-kim930** [dream-num/univer#3765]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.3.0

### 复现链接

https://stackblitz.com/edit/awesome-univer-sheets-vite-demo-s9kgjq?file=src%2Fmain.ts
![image](https://github.com/user-attachments/assets/7f7a4400-13ff-40cc-ab84-b9ae59ca2462)

### 预期行为

univerAPI.createUniverSheet()后，格式刷功能正常使用

### 实际行为

univerAPI.createUniverSheet()后，格式刷功能无法使用，点击到单元格并不生效

### 运行环境

Edge: Chromium (129.0.2792.79)
Internet Explorer: 11.0.19041.3636

### 系统信息

OS: Windows 10 10.0.19045
CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2690 v4@ 2.60GHz
Memory: 708.54 MB / 7.99 GB

**Comment by jikkai** [comment]
Reference: https://github.com/dream-num/univer/issues/2767
