### ISSUE TITLE
I used the non-editable permissions on the sheet page and only released the cell style editing permissions, but I found that after setting, the cells can be dragged and moved. [Bug]

### ISSUE THREAD

**Issue by xiaouu565** [dream-num/univer#3784]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

使用了sheet页的不可编辑权限，仅放开了单元格样式编辑权限，但发现设置后，单元格可被拖拽和移动。
复现链接： https://github.com/xiaouu565/sheets-vite-demo/tree/xiaouu565/patch-66537

![da8fc65daf4b583f7f36d3977b21e32](https://github.com/user-attachments/assets/483effdc-8209-4e47-b55c-5be4120257b6)

### 预期行为

设置sheet页所有点位不可编辑时，仅放开单元格可编辑样式权限，单元格应只可编辑样式，不可拖拽

### 实际行为

单元格可编辑样式也可以拖拽，还可以右键菜单控制向上向下移动

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please confirm whether you are using the latest version and provide the minimum reproduction.

**Comment by ybzky** [comment]
提供的仓库中并没有看到设置权限相关的代码 请提供更具体demo

**Comment by jikkai** [comment]
Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.
