### ISSUE TITLE
[Feature] How to detect that rows or columns are hidden?

### ISSUE THREAD

**Issue by wangchongwei** [dream-num/univer#3789]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

了解到可以使用api隐藏行或者列，但是在表格中，隐藏某行或者某列时，无法感知。
调用save获取到的数据中，没有字段能标识该行或该列是被隐藏的。

目前有策略能感知隐藏行列的动作吗？还是后续会支持？

**Comment by jikkai** [comment]
https://univer.ai/typedoc/@univerjs/core/interfaces/IColumnData#properties
https://univer.ai/typedoc/@univerjs/core/interfaces/IRowData#properties
