### ISSUE TITLE
[Bug] Memory overflow error reported after updating version 0.4.1

### ISSUE THREAD

**Issue by Mmh-1997** [dream-num/univer#3797]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.1

### Reproduction link

（1）初始加载报内存溢出的错：
![image](https://github.com/user-attachments/assets/07c084d6-1083-4ddd-8cf2-2d0848746771)
（2）单元格输入中文报错
![image](https://github.com/user-attachments/assets/b724e42c-6434-4341-b6ca-3aa4981b8429)
（3）单元格输入英文和数字正常
![image](https://github.com/user-attachments/assets/4c89915d-fb61-4186-9cee-0d44913597f5)
（4）中文样式问题：
![image](https://github.com/user-attachments/assets/3ce37c82-3838-4db0-b2d2-34682af3dc1f)

### Expected behavior

正常

### Actual behavior

报错

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by Mmh-1997** [comment]
复现的案例就是按照官网的安装操作，并未使用其他进阶功能，只安装了核心功能，安装了

 sheets-formula 两个插件：sheets-formula 和 sheets-formula-ui。
 sheets-data-validation 两个插件：sheets-data-validation 和 sheets-data-validation-ui

页面就报错了，如果不能复现的话周一我再次提交我的代码到issue上，谢谢开发者的回复。

**Comment by Mmh-1997** [comment]
> Please provide the minimal reproduction.

<template>
  <div ref="container" class="univer-container" />
</template>

<script setup lang="ts">
import { Univer, UniverInstanceType, Workbook, LocaleType, IWorkbookData } from "@univerjs/core";
import { defaultTheme } from "@univerjs/design";
import { UniverDocsPlugin } from "@univerjs/docs";
import { UniverDocsUIPlugin } from "@univerjs/docs-ui";
import { UniverFormulaEnginePlugin } from "@univerjs/engine-formula";
import { UniverRenderEnginePlugin } from "@univerjs/engine-render";
import { UniverSheetsPlugin } from "@univerjs/sheets";

import { UniverSheetsFormulaPlugin } from "@univerjs/sheets-formula";
import { UniverSheetsUIPlugin } from "@univerjs/sheets-ui";
import { UniverSheetsFormulaUIPlugin } from "@univerjs/sheets-formula-ui";

import { UniverUIPlugin } from "@univerjs/ui";
import { onBeforeUnmount, onMounted, ref, toRaw } from "vue";

/**
 * 
 * The ability to import locales from virtual modules and automatically import styles is provided by Univer Plugins. For more details, please refer to: https://univer.ai/guides/sheet/advanced/univer-plugins.
 * If you encounter issues while using the plugin or have difficulty understanding how to use it, please disable Univer Plugins and manually import the language packs and styles.
 * 
 * 【从虚拟模块导入语言包】以及【自动导入样式】是由 Univer Plugins 提供的能力，详情参考：https://univer.ai/zh-CN/guides/sheet/advanced/univer-plugins
 * 如果您在使用该插件的时候出现了问题，或者无法理解如何使用，请禁用 Univer Plugins，并手动导入语言包和样式
 */ 
import { zhCN, enUS } from 'univer:locales'

const { data } = defineProps({
  // workbook data
  data: {
    type: Object,
    default: () => ({}),
  },
});

const univerRef = ref<Univer | null>(null);
const workbook = ref<Workbook | null>(null);
const container = ref<HTMLElement | null>(null);

onMounted(() => {
  init(data);
});

onBeforeUnmount(() => {
  destroyUniver();
});

/**
 * Initialize univer instance and workbook instance
 * @param data {IWorkbookData} document see https://univer.ai/typedoc/@univerjs/core/interfaces/IWorkbookData
 */
const init = (data = {}) => {
  const univer = new Univer({
    theme: defaultTheme,
    locale: LocaleType.EN_US,
    locales: {
      [LocaleType.ZH_CN]: zhCN,
      [LocaleType.EN_US]: enUS,
    },
  });
  /**
   * If you set the univer instance to a ref, you need to use toRaw to get the original object
   * 
   * 如果你将 univer 实例设置到 ref 中，使用时则需要使用 toRaw 获取原始对象
   */
  univerRef.value = univer;

  // core plugins
  univer.registerPlugin(UniverRenderEnginePlugin);
  univer.registerPlugin(UniverFormulaEnginePlugin);
  univer.registerPlugin(UniverUIPlugin, {
    container: container.value!,
  });

  // doc plugins
  univer.registerPlugin(UniverDocsPlugin, {
    hasScroll: false,
  });
  univer.registerPlugin(UniverDocsUIPlugin);

  // sheet plugins
  univer.registerPlugin(UniverSheetsPlugin);
  
  univer.registerPlugin(UniverSheetsUIPlugin);
  univer.registerPlugin(UniverSheetsFormulaPlugin);
  univer.registerPlugin(UniverSheetsFormulaUIPlugin);

  // create workbook instance
  workbook.value = univer.createUnit<IWorkbookData, Workbook>(UniverInstanceType.UNIVER_SHEET, data)
};

/**
 * Destroy univer instance and workbook instance
 */
const destroyUniver = () => {
  toRaw(univerRef.value)?.dispose();
  univerRef.value = null;
  workbook.value = null;
};

/**
 * Get workbook data
 */
const getData = () => {
  if (!workbook.value) {
    throw new Error('Workbook is not initialized');
  }
  return workbook.value.save();
};

defineExpose({
  getData,
  destroyUniver
});
</script>


<style scoped>
.univer-container {
  width: 100%;
  height: 100%;
  overflow: hidden;
}

/* Also hide the menubar */
:global(.univer-menubar) {
  display: none;
}
</style>

![image](https://github.com/user-attachments/assets/478624b8-d43f-4396-9b63-ce7946293887)

**Comment by jikkai** [comment]
You have not provided the required reproduction, so we will temporarily close this issue. When you are ready with a runnable online demo or GitHub repository according to community guidelines, feel free to reopen it at any time.
