### ISSUE TITLE
[Bug] index.js:1670 [redi]: You are loading scripts of redi more than once! This may cause undesired behavior in your application. Maybe your dependencies added redi as its dependency and bundled redi to its dist files. Or you import different versions of redi.

### ISSUE THREAD

**Issue by shiguoqian** [dream-num/univer#3814]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.3.0

### Reproduction link

package.json dependencies:
"dependencies": {
    "@antv/x6": "^1.24.4",
    "@riophae/vue-treeselect": "0.4.0",
    "@univerjs-pro/engine-pivot": "^0.3.0",
    "@univerjs-pro/exchange-client": "^0.3.0",
    "@univerjs-pro/facade": "^0.3.0",
    "@univerjs-pro/sheets-exchange-client": "^0.3.0",
    "@univerjs-pro/sheets-pivot": "^0.3.0",
    "@univerjs-pro/sheets-pivot-ui": "^0.3.0",
    "@univerjs-pro/sheets-print": "^0.3.0",
    "@univerjs/core": "^0.3.0",
    "@univerjs/data-validation": "^0.3.0",
    "@univerjs/design": "^0.3.0",
    "@univerjs/docs": "^0.3.0",
    "@univerjs/docs-ui": "^0.3.0",
    "@univerjs/drawing": "^0.3.0",
    "@univerjs/drawing-ui": "^0.3.0",
    "@univerjs/engine-formula": "^0.3.0",
    "@univerjs/engine-render": "^0.3.0",
    "@univerjs/find-replace": "^0.3.0",
    "@univerjs/sheets": "^0.3.0",
    "@univerjs/sheets-conditional-formatting": "^0.3.0",
    "@univerjs/sheets-conditional-formatting-ui": "^0.3.0",
    "@univerjs/sheets-crosshair-highlight": "^0.3.0",
    "@univerjs/sheets-data-validation": "^0.3.0",
    "@univerjs/sheets-drawing": "^0.3.0",
    "@univerjs/sheets-drawing-ui": "^0.3.0",
    "@univerjs/sheets-filter": "^0.3.0",
    "@univerjs/sheets-filter-ui": "^0.3.0",
    "@univerjs/sheets-find-replace": "^0.3.0",
    "@univerjs/sheets-formula": "^0.3.0",
    "@univerjs/sheets-hyper-link": "^0.3.0",
    "@univerjs/sheets-hyper-link-ui": "^0.3.0",
    "@univerjs/sheets-numfmt": "^0.3.0",
    "@univerjs/sheets-sort": "^0.3.0",
    "@univerjs/sheets-sort-ui": "^0.3.0",
    "@univerjs/sheets-thread-comment": "^0.3.0",
    "@univerjs/sheets-thread-comment-base": "^0.3.0",
    "@univerjs/sheets-ui": "^0.3.0",
    "@univerjs/thread-comment": "^0.3.0",
    "@univerjs/thread-comment-ui": "^0.3.0",
    "@univerjs/ui": "^0.3.0",
    "ant-design-vue": "^1.7.1",
    "axios": "^0.21.4",
    "clipboard": "2.0.6",
    "codemirror": "^5.45.0",
    "core-js": "3.8.1",
    "echarts": "4.9.0",
    "echarts-stat": "^1.1.1",
    "element-ui": "2.15.8",
    "exceljs": "^4.2.1",
    "file-saver": "2.0.4",
    "FileSaver": "^0.10.0",
    "fuse.js": "6.4.3",
    "highlight.js": "9.18.5",
    "jquery": "^3.2.1",
    "js-beautify": "1.13.0",
    "js-cookie": "2.2.1",
    "jsencrypt": "3.0.0-rc.1",
    "jsonlint": "^1.6.3",
    "less": "^3.12.2",
    "less-loader": "^7.0.1",
    "luckyexcel": "^1.0.1",
    "node-sass": "^8.0.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "quill": "1.3.7",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "rxjs": "^7.8.1",
    "sass-loader": "^10.5.2",
    "screenfull": "5.0.2",
    "sortablejs": "1.10.2",
    "spark-md5": "^3.0.1",
    "sql-formatter": "^2.3.3",
    "v-charts": "^1.19.0",
    "vue": "2.6.12",
    "vue-count-to": "1.0.13",
    "vue-cropper": "0.5.5",
    "vue-pdf": "^4.2.0",
    "vue-quill-editor": "3.0.6",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.24.3",
    "vuex": "3.6.0",
    "vxe-table": "^2.9.25",
    "xe-utils": "^2.7.14",
    "xlsx": "^0.17.3"
  }

### Expected behavior

no error

### Actual behavior

when i import "@univerjs-pro/facade",report error:
index.js:1670 [redi]: You are loading scripts of redi more than once! This may cause undesired behavior in your application.
Maybe your dependencies added redi as its dependency and bundled redi to its dist files. Or you import different versions of redi.

**Comment by jikkai** [comment]
The provided information isn't enough to understand the issue. Please provide a minimal reproduction.

**Comment by shiguoqian** [comment]
The issue disappeared after all univer plug-ins were upgraded to 0.4.1.
close it
