### ISSUE TITLE
[Bug] umd introduced, version 3.0, perspective registration error reported

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3815]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

na

### 复现链接

demo: https://github.com/13701138894/sheets-vue3-demo.git 
  src\components\UniverSheet.vue
![image](https://github.com/user-attachments/assets/2269ce12-8e5c-4fba-8a1d-e0d1dce5d24f)
![image](https://github.com/user-attachments/assets/c7e98d1c-27a3-4f62-bce8-63f51feb88d3)

![image](https://github.com/user-attachments/assets/e5b3a942-b6eb-4886-9e2c-08f267d6d4a3)

### 预期行为

/

### 实际行为

注册就报错，注销就没事儿
  univer.registerPlugin(UniverEnginePivot.UniverSheetsPivotTablePlugin)
  univer.registerPlugin(UniverSheetsPivotUi.UniverSheetsPivotTableUIPlugin)

### 系统信息

/

**Comment by jikkai** [comment]
`UniverSheetsPivotTablePlugin` is not found under `UniverEnginePivot`. Please check your code for errors.
