### ISSUE TITLE
[Bug] Merge cell, initialize render border error

### ISSUE THREAD

**Issue by LaFee-Helei** [dream-num/univer#3820]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.0/0.4.1

### Reproduction link

https://stackblitz.com/edit/awesome-univer-custom-menu-bq8wyd?file=src%2Fmain.ts

### Expected behavior

Cells merge normally render borders normally。
![image](https://github.com/user-attachments/assets/59edf457-bb98-42f8-8a08-0e621f9a5f5e)

### Actual behavior

![image](https://github.com/user-attachments/assets/599ca05f-2813-433c-9d6a-21c2efd120f5)

**Comment by jikkai** [comment]
The initialization data is incorrect; each cell within a merged range, including merged cells, must have a `bd` value.
