### ISSUE TITLE
[Bug] umd introduces perspective view of version 0.3.0, registration error is reported

### ISSUE THREAD

**Issue by 13701138894** [dream-num/univer#3824]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

na

### 复现链接

https://github.com/13701138894/sheets-vue3-demo
src\components\UniverSheet.vue
![image](https://github.com/user-attachments/assets/51f5bb1e-9a34-4dea-ac87-cc9891dd8a7e)
![image](https://github.com/user-attachments/assets/34bf9fc9-d957-4e9a-b5c9-c099ca51cbac)
![image](https://github.com/user-attachments/assets/4f7cb444-d711-422a-915d-b2d525682d8a)
![image](https://github.com/user-attachments/assets/cc1217ae-46dc-41f8-a4ef-03ea1b63db5f)

### 预期行为

/

### 实际行为

![image](https://github.com/user-attachments/assets/9e09e0e3-52ad-4cc5-9815-2bafa08e9b72)

### 系统信息

/

**Comment by jikkai** [comment]
You have missed the `@univerjs-pro/license` plugin.
