### ISSUE TITLE
[Bug] Version 4.1 cannot be used in vue3 template

### ISSUE THREAD

**Issue by suqiufang** [dream-num/univer#3831]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

4.1

### Reproduction link

https://github.com/awesome-univer/sheets-vite-demo/tree/c47814f1e2f3ef69acab85a7ffaf47cca0e16e24

### Expected behavior

4.1版本在vue3项目中使用，希望可以挂载到非根节点上

### Actual behavior

4.1版本在vue3项目中使用，只能挂载到根节点上渲染，导致无法渲染其他内容

**Comment by hexf00** [comment]
Our Vue3 example works fine, perhaps you can refer to it. https://univer.ai/playground?title=Vue+3

**Comment by hexf00** [comment]
I have reviewed your code, and the way you're using Vue and Univer is incorrect. You should initialize Univer after the DOM is ready.
Please ensure your code has the following structure:
```js
import { onMounted } from "vue";

onMounted(() => {
    // Initialize Univer
})
```
