### ISSUE TITLE
[Feature] It is expected to add a filtering function to the drop-down menu options.

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3839]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

数据验证下拉菜单，下拉框中期望添加搜索筛选功能
![drop](https://github.com/user-attachments/assets/071b9fe7-29b5-45e2-bc4c-97d1c4c0bdbb)

**Comment by weird94** [comment]
在单元格输入即可筛选
