### ISSUE TITLE
[Feature] Can you provide a way to get all cells disabled?

### ISSUE THREAD

**Issue by Mmh-1997** [dream-num/univer#3844]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

Can you provide a way to get all cells disabled? Because if the user keeps stacking the selected cells to disable to form a large array, if there is no way to get all the cells disabled, I can only add this data in the cache again, which will have a problem, when the user refreshes the page, the cache information will not exist.

**Comment by jikkai** [comment]
https://univer.ai/en-US/guides/sheet/features/core/permission

**Comment by Mmh-1997** [comment]
大佬，请问获取所有禁用过的单元格方法是哪一个呢，英文翻译可能有点问题

**Comment by Mmh-1997** [comment]
大佬，请问获取所有禁用过的单元格方法是哪一个呢，英文翻译可能有点问题
