### ISSUE TITLE
[Bug] White screen error after selecting date format during data verification

### ISSUE THREAD

**Issue by Mmh-1997** [dream-num/univer#3857]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

在官网的工具中https://univer.ai/playground?title=Custom+Function，安装了数据验证功能，然后在单元格中使用日期格式。
![image](https://github.com/user-attachments/assets/85734ffd-0d0d-4958-a40c-a47f5513ccdf)

### 预期行为

能显示日期框，并进行选择

### 实际行为

双击定义了日期的数据验证单元格，白屏，且报错。

### 运行环境

Chrome

**Comment by Mmh-1997** [comment]
![image](https://github.com/user-attachments/assets/a38a232e-9ad2-4b1d-a40e-f174ede2bab4)

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by weird94** [comment]
@jikkai dayjs 打包问题 帮忙看下
