### ISSUE TITLE
[Bug] When the row and column titles are hidden, I want to hide these two lines as well.

### ISSUE THREAD

**Issue by vijftienster** [dream-num/univer#3868]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![8df8cd4c43460a2359b103b5edc6e27](https://github.com/user-attachments/assets/b60cb30b-890e-4ee4-8c8d-93ecaa582a7e)

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
