### ISSUE TITLE
[bug]运行npm run dev:sheet报错

### ISSUE THREAD

**Issue by INSIinc** [dream-num/univer#39]
运行npm run dev:sheet报错Uncaught SyntaxError: The requested module '/@fs/F:/univer/packages/core/src/DI/Decorators.ts?t=1689907140611' does not provide an export named 'AsyncDependencyItem'

**Comment by wzhudev** [comment]
请运行 npm run start:sheet

**Comment by Nicksxs** [comment]
用这个 `npm run start:sheet` 启动报错，找不到 main.css
<img width="1510" alt="image" src="https://github.com/dream-num/univer/assets/7351669/e43a5cc5-c8d4-4279-bfa6-963795c82ec5">

**Comment by wangpeng022** [comment]
我那天下载下来也是，一样一样的，还以为本地环境有问题呢

**Comment by wzhudev** [comment]
最近我们的 dev 分支在经历一次比较大的重构，可以先切换到 [wzhudev/refactor-di-arch](https://github.com/dream-num/univer/tree/wzhudev/refactor-di-arch) 分支把项目跑起来

**Comment by iamyunsin** [comment]
I executed the `pnpm run clean` command before executing `pnpm run start:sheet` just fine!

**Comment by wzhudev** [comment]
Closing this issue since the command was removed and README.md was updated.
