### ISSUE TITLE
[Bug] Cell text is blocked in 360 Speed ​​Browser

### ISSUE THREAD

**Issue by Mmh-1997** [dream-num/univer#3900]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

复现链接：https://github.com/Mmh-1997/sheets-vue3-demo-main
问题1：单元格文字底部对齐时，文字在单元格中是朝上的。
![image](https://github.com/user-attachments/assets/aee101d9-b963-4f71-ba7e-b14791c7e9e3)
问题2：单元格文字顶部对齐时，文字上部分被遮挡。
![image](https://github.com/user-attachments/assets/b4328877-9366-4524-8999-5bbd55a3eb86)

问题3：新建规则中文字被遮挡。
![image](https://github.com/user-attachments/assets/907635a6-5eca-4ae5-a089-035a38d936f0)

问题4：新建下拉选择规则时，文字被遮挡。
![image](https://github.com/user-attachments/assets/87d69065-814e-46ad-8c31-d30018dab5ac)

浏览器：
![image](https://github.com/user-attachments/assets/3deae1e2-f95e-4df6-b306-004551cc279c)

### 预期行为

1、文字不应该出现被遮挡的情况；
2、垂直方向的对齐方式应该正常显示

### 实际行为

文字被遮挡，垂直方向设置没有按照预期属性显示

### 运行环境

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
Please confirm if this issue still persists after updating your browser.

**Comment by Mmh-1997** [comment]
> Please confirm if this issue still persists after updating your browser.

Yes, the browser is up to date and still alive.

**Comment by jikkai** [comment]
The provided version number is not the latest, plz confirm.

**Comment by jikkai** [comment]
While a browser's current status isn't our primary concern, the screenshot you provided indicates a significantly outdated version. Could you please double-check that?

**Comment by Mmh-1997** [comment]
> While a browser's current status isn't our primary concern, the screenshot you provided indicates a significantly outdated version. Could you please double-check that?

![image](https://github.com/user-attachments/assets/a2408d26-8bd0-4b09-afa2-3108b67c2f8a)
Because of this problem in my local project, I downloaded the case from the official website and there was a corresponding problem with using the 360 Superspeed browser, similarly, there was no style problem in Google Chrome. I've tested this so many times.

**Comment by jikkai** [comment]
Since we haven't received any new replies for over a week, we're temporarily closing this issue.  If you can provide more helpful information, please feel free to reopen it at any time.
