### ISSUE TITLE
[Bug] When adding data validation to a cell with a custom formula condition, the expected result is not achieved when the formula is set to “=Cell1=Cell2”.

### ISSUE THREAD

**Issue by Just-null** [dream-num/univer#3902]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

4.0.1

### 复现链接

官方的在线示例中可以复现

### 预期行为

需要判断两个单元格的值是否相等，在其中一个单元格添加数据验证规则，条件类型为自定义公式，公式“=单元格1=单元格2”，即使单元格1和单元格2的值是相等的，也会提示违反了验证规则
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/e70c7fc8-a050-4175-aa7f-a03b9263bec6">

### 实际行为

当添加自定义公式“=单元格1=单元格2”时候，如果单元格1的值和单元格2的值相同，应该是验证通过的状态

### 运行环境

Chrome

**Comment by Dushusir** [comment]
Will be fixed in the next version.
