### ISSUE TITLE
[Bug] The official website's import and export demo imported a table containing the sum calculation formula, and then clicked export. The saved excel calculation formula did not take effect and displayed 0.

### ISSUE THREAD

**Issue by huijuanhu** [dream-num/univer#3910]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1 0.4.2

### 复现链接

[官网的导入导出demo](https://univer.ai/pro/examples/sheets-exchange)，导入了一个表格包含求和计算公式，然后再点击导出，保存的excel打开计算公式不生效了，显示0。本地项目也会百分百复现

https://github.com/user-attachments/assets/4301c306-8d4c-44c0-bdc3-3e962bacea34

[工作簿1.xlsx](https://github.com/user-attachments/files/17586040/1.xlsx)

### 预期行为

导出的表格公式应该现实正常

### 实际行为

导出的表格打开后公式显示异常，都为0

### 运行环境

Chrome

### 系统信息

  System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M2
    Memory: 120.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/Documents/appsoft/node-v18.18.2-darwin-arm64/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 10.9.0 - ~/Documents/appsoft/node-v18.18.2-darwin-arm64/bin/npm
  Browsers:
    Chrome: 130.0.6723.91
    Safari: 16.4

**Comment by Dushusir** [comment]
@vanijin Please help check first

**Comment by vanijin** [comment]
公式值目前只在打开univer文件时候进行计算，导出时候值均为0。非只读状态下excel会重新计算，所以没问题，而wps不会主动计算就导致看到都是0。 这个问题目前没有计划解决。

**Comment by vanijin** [comment]
closed because it hasn't been updated for too long

**Comment by vanijin** [comment]
Adding one, this is because the calculation results were not included when saving the data, and it may be considered to recalculate on the server in the future.
