### ISSUE TITLE
[Bug] Copy and paste the contents of a cell, and the content before and after ‘<’ or ‘>’ is missing

### ISSUE THREAD

**Issue by hello-yajing** [dream-num/univer#3918]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

UMD method introduces dependencies into the project, and the local development environment works normally. There are exceptions when deploying to testing and production environments.（UMD方式引入到项目中，本地开发环境正常。部署到测试及生产环境有异常）
1. 复制单元格的内容，粘贴后 内容里 ‘’<‘’+字母 和 字母+‘>’的内容会被当做html标签而丢失。
2. 还会出现复制了内容，但粘贴的结果依然是前一次的内容，以及内容粘贴到另一个单元格后字体颜色变为蓝色。
![4ef5a9f1856431efa2a0f4a6886db64](https://github.com/user-attachments/assets/2fac0f12-9c71-477d-b173-f56a555c295b)
![4ef5a9f1856431efa2a0f4a6886db64](https://github.com/user-attachments/assets/a20525a8-e7d6-4d53-9627-2bcf24b64207)

### 预期行为

复制粘贴后内容不变。

### 实际行为

问题一：粘贴结果是前一次复制的
1. 第一次复制'a<>b', 粘贴出的是正确的还是'a<>b'
2. 第二次复制‘<a’，粘贴的结果是上一次的‘a<>b’
![4ef5a9f1856431efa2a0f4a6886db64](https://github.com/user-attachments/assets/f1547412-6fa9-40ea-9bfe-1477b3a2f9b0)
问题二：小于号后面不能有字母，否则内容会丢失。
1. 复制'<a>123<123>asf<123>321<sadf'， 粘贴结果：‘123<123>asf<123>321’
![4ef5a9f1856431efa2a0f4a6886db64](https://github.com/user-attachments/assets/5153bf70-29d4-44e6-8fdc-211f2b071ddc)

### 运行环境

Chrome

**Comment by hello-yajing** [comment]
<img width="535" alt="9503bc99ba866e89a5d395b383a13ce" src="https://github.com/user-attachments/assets/b73a1f22-9a3c-4b0f-8382-aaed8e15f068">

**Comment by ybzky** [comment]
I don't quite understand the description, please provide a reproducible demo or a reproducible video

**Comment by hello-yajing** [comment]
> I don't quite understand the description, please provide a reproducible demo or a reproducible video

![丢失](https://github.com/user-attachments/assets/a7ad23dc-f254-479f-83e5-186cf00be982)
![空行](https://github.com/user-attachments/assets/21b08b69-25e2-48a1-b59d-25f433a5e191)
