### ISSUE TITLE
[Bug] Setting the cell to read-only will disable viewing after reloading the data.

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#3944]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

https://gitee.com/wang134246/univer-dome/blob/master/index.html

### Expected behavior

禁止编辑，可以查看。

### Actual behavior

禁止编辑，禁止查看

### System information

.

**Comment by ybzky** [comment]
这里在初始化表格的时候，如果发现resouce上面存储了权限信息，会将权限所有点位置为false，然后去拉取对应点位的值，拉取到再重新赋值，你这里缺少了拉取点位的动作。我们的sdk不提供点位的存储，这里需要你自己去某个地方找到对应的权限id相关联的点位值，然后重新设置进去

**Comment by wyl10000** [comment]
> 这里在初始化表格的时候，如果发现resouce上面存储了权限信息，会将权限所有点位置为false，然后去拉取对应点位的值，拉取到再重新赋值，你这里缺少了拉取点位的动作。我们的sdk不提供点位的存储，这里需要你自己去某个地方找到对应的权限id相关联的点位值，然后重新设置进去

这个有相关的例子吗？

**Comment by wyl10000** [comment]
我需要将res.permissionId保存下来吗？然后通过permissionService.updatePermissionPoint(new RangeProtectionPermissionViewPoint(unitId, subUnitId, res.permissionId).id, true);重新设置为true吗？

**Comment by ybzky** [comment]
> 我需要将res.permissionId保存下来吗？然后通过permissionService.updatePermissionPoint(new RangeProtectionPermissionViewPoint(unitId, subUnitId, res.permissionId).id, true);重新设置为true吗？

是的，你可以将这些点位的值存储在你自己的服务端中，然后每次打开表格的时候再重新初始化正确的点位值

**Comment by wyl10000** [comment]
> > 我需要将res.permissionId保存下来吗？然后通过permissionService.updatePermissionPoint(new RangeProtectionPermissionViewPoint(unitId, subUnitId, res.permissionId).id, true);重新设置为true吗？
> 
> 是的，你可以将这些点位的值存储在你自己的服务端中，然后每次打开表格的时候再重新初始化正确的点位值

好的，谢谢。已经解决该问题
