### ISSUE TITLE
[Bug]    Clearing the content will remove the formula togethe

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3950]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

![clear](https://github.com/user-attachments/assets/2ddecdba-d941-415a-9160-0625c8fbbd78)

### Expected behavior

Clearing the content will remove the formula together, in theory, clearing the content is only clearing the content will not remove the formula, clearing all will remove the formula

### Actual behavior

clearing the content is only clearing the content will not remove the formula, clearing all will remove the formula

**Comment by Dushusir** [comment]
This function is similar to Excel. When clearing the content, the formula will be deleted at the same time.
