### ISSUE TITLE
[Bug] Cell value was changed "NaN" when input date format string in the cell(e.g. input 2024/05/05)

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#3970]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.4.1

### Reproduction link

https://univer.ai/zh-CN/playground?title=React

### Expected behavior

input value can work.

### Actual behavior

Cell value was changed "NaN" when input date format string in the cell(e.g. input 2024/05/05)
![241106 144037](https://github.com/user-attachments/assets/b28a6f34-866a-49d6-8c71-50e0919ffa40)

**Comment by jikkai** [comment]
This isn't a bug, but it seems the @univerjs/sheets-numfmt plugin isn't registered.
