### ISSUE TITLE
[Feature] Like editing permissions, designated users can view

### ISSUE THREAD

**Issue by mietlove** [dream-num/univer#3985]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Now it can only be set that others can view it, or others can't view it. I hope to better control the viewing permission.

Is there any way I can expand it?

**Comment by jikkai** [comment]
We do not understand what you need, so we will close this issue for now. Once you have organized a precise description of your requirements, feel free to reopen this issue at any time.

**Comment by mietlove** [comment]
I want to set the viewing permission for the designated user separately.

In the viewState, I have the following options:
- othersCanView: Allows others to view the content.
- noOneElseCanView: Restricts access to the content to only the designated user.

I believe a user with the designatedUserCanView permission is required to access permissions.

I would like to know why the cancel view is not designed in the same way as the edit view.

**Comment by mietlove** [comment]
I can't reopen the issue.
@jikkai

**Comment by mietlove** [comment]
@ybzky You're a good man.

**Comment by ybzky** [comment]
In the next version we will support customization of this component

**Comment by mietlove** [comment]
> In the next version we will support customization of this component

good!

**Comment by ybzky** [comment]
The document provides a custom way
