### ISSUE TITLE
[Bug] The text of the shortcut panel is written incorrectly

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#3993]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

不需要链接

### 预期行为

文本正常

### 实际行为

文本写错了，应该是右移绘图
![c78f29b34552df73673c9e56142da78](https://github.com/user-attachments/assets/65f809c6-1a81-4a0e-918d-8e54714c301d)

**Comment by jikkai** [comment]
PR welcome.
