### ISSUE TITLE
[Bug] Set name for a workbook

### ISSUE THREAD

**Issue by buschhardtt** [dream-num/univer#3999]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

dont know how to provide a demo

### Expected behavior

I would change the name of the workbook

`univerAPI.getActiveWorkbook().setName('test')`

### Actual behavior

Uncaught TypeError: univerAPI.getActiveWorkbook(...).setName is not a function

In the class doc there is a function [setName](https://univer.ai/typedoc/@univerjs/core/classes/Workbook#setname)

**Comment by jikkai** [comment]
We do not provide this facade API. If you need it, you can use command system with `SetWorkbookNameMutation.id`.
