### ISSUE TITLE
[Feature] Remove the protection background grain by configuring

### ISSUE THREAD

**Issue by zhao-bin-zero** [dream-num/univer#4003]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

My requirement is to disable most of the cells in an excel workbook, and only some of the whitelist cells can be edited (they will have their own background color). If there is a gray background, it will be very ugly, so the request can be determined by some configuration whether to add a background.

![8b66b1725d992332f1d0d0814733677](https://github.com/user-attachments/assets/16ff651e-c4cb-4bc6-897b-6b05abf38988)

**Comment by jikkai** [comment]
Perhaps users can be allowed to configure whether to display mask @ybzky.

**Comment by ybzky** [comment]
已完成
