### ISSUE TITLE
[Bug] Paste and paste-related functions in the right-click menu are disabled and cannot be used.

### ISSUE THREAD

**Issue by wdnmdezreal** [dream-num/univer#4007]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.2

### 复现链接

下载官网playground中vue3的模板，在vite.config.js文件defineConfig中添加server: {host: '0.0.0.0',}

### 预期行为

右键菜单粘贴功能正常使用

### 实际行为

运行项目后使用Edge浏览器，在network中访问项目右键菜单中的粘贴被禁用无法使用，而在localhost中能正常使用，这是什么原因。
![1731046559350](https://github.com/user-attachments/assets/ded84479-7ace-4b00-a528-967a5e7f74b4)

### 运行环境

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
Please refer to the documentation.
