### ISSUE TITLE
[Feature] Sometimes it is necessary to load data in batches, but I see that there is no API for data update in the worksheet. Is this function possible?

### ISSUE THREAD

**Issue by percentcola3** [dream-num/univer#4012]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

1. 假如一共有1000条数据，可能每次请求后端时，单次只能请求200条，所以需要多次请求
2. 每次请求结束，都需要往sheet页内增加数据

**Comment by jikkai** [comment]
You can use the facade API under `FWorksheet`.
