### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fengbingchao** [dream-num/univer#4034]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### 预期行为

SUMIFS函数应获取到多个条件的值

### 实际行为

SUMIFS函数只获取到了第一个条件值

### 运行环境

Chrome

**Comment by fengbingchao** [comment]
添加添加*做模糊匹配时结果不准确。

**Comment by jikkai** [comment]
Since you DID NOT provide the correct minimum reproduction link, we will close this issue.
