### ISSUE TITLE
[Bug] According to the IDocumentData interface specification, the image is defined in the drawings and resources fields. Why is the image not rendering?

### ISSUE THREAD

**Issue by ReturnToTheYouth** [dream-num/univer#4080]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.1

### Reproduction link

[template.md](https://github.com/user-attachments/files/17774930/template.md)

### Expected behavior

the image render 

### Actual behavior

the image not render

**Comment by Jocs** [comment]
Can you provide the minimal demo? or the snapshot?

**Comment by ReturnToTheYouth** [comment]
> Can you provide the minimal demo? or the snapshot?
Hello, it has been provided, in the template.md file, download it and you can see my code and snapshot data。

![image](https://github.com/user-attachments/assets/7ab5dc69-1487-4f2d-b6cf-fa7ebfdbc415)

**Comment by jikkai** [comment]
> > Can you provide the minimal demo? or the snapshot?
> > Hello, it has been provided, in the template.md file, download it and you can see my code and snapshot data。
> 
> ![image](https://private-user-images.githubusercontent.com/25609358/387027448-7ab5dc69-1487-4f2d-b6cf-fa7ebfdbc415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTEyNzUsIm5iZiI6MTczMTkxMDk3NSwicGF0aCI6Ii8yNTYwOTM1OC8zODcwMjc0NDgtN2FiNWRjNjktMTQ4Ny00ZjJkLWI2Y2YtZmE3ZWJmZGJjNDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2MjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1OTllMzhjZTFjMDkzZTQyY2RkNmJjNTViMmRhYmY0NDM0YzQxYTA5Y2VmMDRjN2Y1ZGUzZmYxMThmMDMxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0QP0g8AxAo84AuVbGwLYWdj-9jBUfMuiGsFmwNdTYEo)

This is not a runnable reproduction, just a code snippet.

**Comment by jikkai** [comment]
Hey @ReturnToTheYouth , Your lengthy content is still just snippets of code. Please provide a **runnable** reproduction. It can be a stackblitz / codesanbox link, or a GitHub repro.

**Comment by ReturnToTheYouth** [comment]
Hello, the executable code has been uploaded, could you please take a look at it again?
[univer-question.zip](https://github.com/user-attachments/files/17808488/univer-question.zip)
 And codesandbox link: https://codesandbox.io/p/devbox/4v3jtm?file=%2Fsrc%2FApp.vue%3A29%2C2

**Comment by Jocs** [comment]
@ReturnToTheYouth The data format is wrong, I don't see a `\b` placeholder in the dataStream field to represent the image in your `DEFAULT_DOCUMENT_DATA_CN` file, and there is no customBlocks field in the body yet.

**Comment by ReturnToTheYouth** [comment]
Hello, can you give an example? Similar to the mockData in the examples directory in your project

**Comment by ReturnToTheYouth** [comment]
Hello, I directly use your data to run in my program, and the image is not rendered, please help me take a look? The  codesandbox link：https://codesandbox.io/p/devbox/4v3jtm?file=%2Fsrc%2Fcomponents%2Fdoc%2FuniverDoc.vue%3A22%2C47
