### ISSUE TITLE
[Bug] Copy and paste cell contents are missing and an extra blank line between two lines

### ISSUE THREAD

**Issue by hello-yajing** [dream-num/univer#4090]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.2

### 复现链接

无

### 预期行为

1. 单元格内容包含<或>时，复制粘贴后内容不能缺少。
2. 单元格内容包含换行符时，复制粘贴后两行中间有一行空白行。

### 实际行为

1. 单元格内容包含尖括号内容会丢失
![丢失](https://github.com/user-attachments/assets/995bd6a9-0410-49fd-95b1-a0f20833ba17)

2. 单元格有换行符粘贴后多出空行
![空行](https://github.com/user-attachments/assets/8993a186-7c7f-43a4-8b98-9a55bc2aa71e)

### 运行环境

Chrome

### 系统信息

 System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.19 GB / 15.84 GB
  Binaries:
    Node: 20.11.1 - D:\soft\node\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - D:\soft\node\npm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.22621.3527

**Comment by ybzky** [comment]
按照你提供的场景 再控制台复现不了

**Comment by hello-yajing** [comment]
> 按照你提供的场景 再控制台复现不了
我启动本地项目，通过localhost:5173是正常的，如果通过IP:port访问就能稳定复现。
