### ISSUE TITLE
[Bug] How to save cells styles as an object instead of a id string?

### ISSUE THREAD

**Issue by lily7630** [dream-num/univer#4094]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

^0.4.2

### 复现链接

![5566](https://github.com/user-attachments/assets/daa6c32d-3a9b-486e-a116-737257c9353c)

### 预期行为

我希望通过univerAPI.getActiveWorkbook().save() 保存表格数据时，单元格的样式是对象，像这样 "s":{"ht":2,"bl":1}，现在保存时单元格对象是id，像这样的  "s": "样式id"

### 实际行为

单元格样式是id字符串

### 运行环境

Chrome

**Comment by jikkai** [comment]
The id is designed as the index of the style object. If you need to save it as the style object itself, you'll need to handle that yourself and be responsible for any resulting bugs.

**Comment by lily7630** [comment]
Well, I understand, the default style saved is id, similar to "s": "sg87", so I read your document, I can't find how to match this style id, this style id includes cell color, font alignment, font size and other information, how to match
