### ISSUE TITLE
[Bug] import, crashes after a moment of display, memory overflows

### ISSUE THREAD

**Issue by wiki-sunny** [dream-num/univer#4100]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

官方demo

### 复现链接

https://univer.ai/pro/examples/sheets-exchange
import  
[sample cal.xlsx](https://github.com/user-attachments/files/17808999/sample.cal.xlsx)

### 预期行为

正常显示和编辑

### 实际行为

导入显示片刻后崩溃
![image](https://github.com/user-attachments/assets/67f590da-9666-4538-a9d3-bd78acbe44f4)

### 运行环境

Chrome

**Comment by Gggpound** [comment]
条件格式的渲染缓存太大了，这里后续会进行优化，已经有其他pr在跟进了。

**Comment by CaiJinHao** [comment]
https://univer.ai/pro/examples/sheets-exchange 
Where can I find the source code of this demo. Could you please provide a link address? I have searched everywhere but couldn't find it

**Comment by jikkai** [comment]
> https://univer.ai/pro/examples/sheets-exchange Where can I find the source code of this demo. Could you please provide a link address? I have searched everywhere but couldn't find it

We are in the process of migrating our official examples, which will be completed later.

**Comment by Gggpound** [comment]
[Fixed](https://github.com/dream-num/univer/pull/4164)
