### ISSUE TITLE
[Bug] On mobile devices, a single tap on the table will trigger the virtual keyboard, but logically, it should only be the double-tap on each cell of the table that activates the virtual keyboard.

### ISSUE THREAD

**Issue by zhengshengyue** [dream-num/univer#4106]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.2

### Reproduction link

![单击](https://github.com/user-attachments/assets/9d2c90fb-b777-4e15-b4c6-3a8cb9fd9020)
as you can see,when i open this online excel on the mobile phone,if i touch the sheet,the virtual keyboard will pop up,no matter where i touch this sheet

### Expected behavior

I want to implement it so that the virtual keyboard only appears when the cell is double-tapped quickly.

### Actual behavior

the virtual keyboard appears when the cell is single-tapped.

**Comment by ankyo** [comment]
same issue, too hard to use in mobie device
