### ISSUE TITLE
[Bug] After setting the protection scope, check all protection scopes.

### ISSUE THREAD

**Issue by jay-xon** [dream-num/univer#4109]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.2

### 复现链接

![057cf486205b1f785bdc867df8a2f2d8](https://github.com/user-attachments/assets/d8766a7d-6b06-405e-9205-74bf565df2d6)

### 预期行为

可以查看设置的保护范围。

### 实际行为

无法查看设置的保护范围。

**Comment by ybzky** [comment]
The information of the permission panel needs to be pulled through the request. This needs to be implemented by the user. The SDK will not store the relevant information. For details, please see https://univer.ai/zh-CN/guides/sheet/features/core/permission
