### ISSUE TITLE
[Feature] Can I prevent cell editing through commands?

### ISSUE THREAD

**Issue by lindanni** [dream-num/univer#4114]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

通过命令阻止单元格编辑，包括双击输入跟键盘输入都要阻止，具体是阻止哪些命令的执行？

**Comment by jikkai** [comment]
https://univer.ai/zh-CN/guides/sheet/features/core/general-api#%E7%9B%91%E5%90%AC%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E5%89%8D

**Comment by lindanni** [comment]
是阻止sheet.operation.set-cell-edit-visible 跟 sheet.operation.set-activate-cell-edit命令的执行吗
