### ISSUE TITLE
[Bug] The mergeAcross() method on range is missing a primary argument, and merging cells using univerAPI.executeCommand produces the same error

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#4121]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

![Snipaste_2024-11-22_10-27-22](https://github.com/user-attachments/assets/c6bee053-5f82-4a2c-b6b4-eac24f0919b2)

### Expected behavior

Failed to merge successfull

### Actual behavior

Failed to merge cells

**Comment by jikkai** [comment]
Please provide the minimal reproduction.

**Comment by 335060087** [comment]
Do not close the busy provide reproduction demo

**Comment by jikkai** [comment]
I'm having a little trouble understanding your point. A minimal reproduction would really help us investigate and fix the issue. Could you please provide one within the next week? If we don't receive it by then, we might have to close the issue.

**Comment by simonegiovanelli77** [comment]
> I'm having a little trouble understanding your point. A minimal reproduction would really help us investigate and fix the issue. Could you please provide one within the next week? If we don't receive it by then, we might have to close the issue.

**Comment by 335060087** [comment]
The problem has been solved,One more question, can the merge cell warning box be set to not prompt
![Snipaste_2024-11-24_11-29-37](https://github.com/user-attachments/assets/7012e011-577c-42d6-ae58-46876886727a)
next:alignment What is the format
![Snipaste_2024-11-24_11-34-45](https://github.com/user-attachments/assets/e2363c23-b005-46fa-a5e5-9fe1069fad5d)
