### ISSUE TITLE
[Bug] How to remove the large watermarks introduced in v0.4

### ISSUE THREAD

**Issue by lovasoa** [dream-num/univer#4143]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.5.0

### Reproduction link

![image](https://github.com/user-attachments/assets/eabba280-fde2-43c6-b7f9-110418c6ecb4)

### Expected behavior

Same as v0.4, no watermark

### Actual behavior

v0.5 introduced large watermarks on the spreadsheets. The documentation does not seem to mention how to remove them.

### System information

  System:
    OS: Linux 6.11 Fedora Linux 41 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.73 GB / 15.34 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
  Binaries:
    Node: 22.11.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm

**Comment by jikkai** [comment]
The `@univerjs-pro` packages now require a valid license. Unlicensed usage will produce a watermark.

**Comment by lovasoa** [comment]
Hello and thank you for the clarification !

You should probably update the license then. I was under the impression that the entire project was under Apache-2.0, and https://univerjs/preset-sheets-advanced still indicates an apache license. 

Is there somewhere users can see which project is distributed under which license ?

**Comment by jikkai** [comment]
You're right about `@univerjs/preset-sheets-advanced` being based on Apache-2.0 and we'll open-source it soon. However, it depends on `@univerjs-pro` packages which are not currently open-sourced. We appreciate your understanding. 🫶

**Comment by lovasoa** [comment]
I understand what you want to do, and I am no legal expert, but I don't think you have the right to do that. You cannot list Apache-2.0 as the license in your package.json if your package has dependencies that are not open-sourced. Doing so violates the terms of the Apache-2.0 license.
