### ISSUE TITLE
[Feature] how to change the  order of the top menu item ,or hide it .  with @univer/ presets0.5.0

### ISSUE THREAD

**Issue by percentcola3** [dream-num/univer#4185]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

how to change the  order of the top menu item ,or hide it .  with @univer/ presets0.5.0

**Comment by jikkai** [comment]
![image](https://github.com/user-attachments/assets/8586ad61-98c4-416e-b6d0-c9d804025672)
