### ISSUE TITLE
请问目前支持限制部分单元格为只读状态，部分可编辑吗？

### ISSUE THREAD

**Issue by zwdgit** [dream-num/univer#42]
比如公司会设置一些单据或者工单，模板肯定是不能让用户编辑的，只能编辑可填项，这种需求目前有API可以实现吗？

**Comment by Dushusir** [comment]
目前未实现。未来会支持。

**Comment by F-Monkey** [comment]
之前luckysheet是可以返回false阻止事件发生的，但是所有的函数都是同步的，能不能支持promise语法？

**Comment by yooyea** [comment]
+1

**Comment by jikkai** [comment]
Duplicate of https://github.com/dream-num/univer/issues/1312
