### ISSUE TITLE
[Bug] crash when I use 0.5.1

### ISSUE THREAD

**Issue by percentcola3** [dream-num/univer#4200]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

https://github.com/percentcola3/crashuniver

### Expected behavior

I  submitted  this  issue. https://github.com/dream-num/univer/issues/4188 . And I noticed it has been closed. 
So I use 0.5.1  , but  it crashed when I  initialize   a grid.
 

### Actual behavior

![image](https://github.com/user-attachments/assets/b1f58e8e-9a46-44a2-b6c2-bcda0a449f3a)

### System information

System information
System:
OS: macOS 15.1.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 356.40 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
pnpm: 9.11.0 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
Browsers:
Edge: 131.0.2903.70

**Comment by jikkai** [comment]
Please use rspack@1 or above.
