### ISSUE TITLE
[Feature] Create new sheet with initial data

### ISSUE THREAD

**Issue by siisee11** [dream-num/univer#4207]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Seems like there is no FacadeAPI for creating new sheet with initial sheet data similar to `univerAPI.createUniverSheet(WORKBOOK_DATA);`

There is only 'workbook.create()' API which do not accept data.
Is there a way to create new sheet with `IWorkSheetData`?

**Comment by jikkai** [comment]
Duplicate of #3643
