### ISSUE TITLE
[Feature] Hope to support displaying custom components in cells

### ISSUE THREAD

**Issue by ji-hae** [dream-num/univer#4215]
### 初始清单

- [x] 这真的是个问题吗？
- [x] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

我想到在点击单元格时，工具栏上可以选择单元格样式的选项，如下拉框，日期输入什么的，而且要支持自定义组件的展示

**Comment by jikkai** [comment]
Functions like these are typically provided by "Data Validation" in Excel, and of course, it's the same in Univer.
https://docs.dev.univer.plus/en-US/guides/sheets/features/data-validation
