### ISSUE TITLE
[Bug] Error when i use UniverSheetsConditionalFormattingPreset and UniverPresetSheetsConditionalFormattingZhCN 

### ISSUE THREAD

**Issue by hurricane1998** [dream-num/univer#4217]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.0 and 0.5.1

### Reproduction link

<html>
<head>
  <script src="https://unpkg.com/react/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/rxjs/dist/bundles/rxjs.umd.min.js"></script>
 
  <script src="https://unpkg.com/@univerjs/presets/lib/umd/index.js"></script>
  
  <script src="https://unpkg.com/@univerjs/preset-sheets-core/lib/umd/index.js"></script>
  <script src="https://unpkg.com/@univerjs/preset-sheets-core/lib/umd/locales/zh-CN.js"></script>
  <link rel="stylesheet" href="https://unpkg.com/@univerjs/preset-sheets-core/lib/index.css" />
</head>
<body>
  <div id="app"></div>
 
  <script>
    const { createUniver, LocaleType, Tools, defaultTheme } = UniverPresets
    const { UniverSheetsCorePreset } = UniverPresetSheetsCore
	
    const { univerAPI } = createUniver({
      locale: LocaleType.ZH_CN,
      locales: {
        zhCN: Tools.deepMerge(
          {},
          UniverPresetSheetsCoreZhCN,
          UniverPresetSheetsConditionalFormattingZhCN 
        ),
      },
      theme: defaultTheme,
      presets: [
        UniverSheetsCorePreset(),
		UniverSheetsCorePreset(),
                UniverSheetsConditionalFormattingPreset()
      ],
    });
    univerAPI.createUniverSheet({ name: 'Test Sheet' }); // 创建一个名为 'Test Sheet' 的工作表
  </script>
</body>
</html>

### Expected behavior

Maybe you should expose UniverPresetSheetsConditionalFormattingZhCN and UniverSheetsConditionalFormattingPreset on window like UniverPresetSheetsCore?

### Actual behavior

![image](https://github.com/user-attachments/assets/c256d14e-060e-47d6-9060-2fefa6bb8b3b)

![image](https://github.com/user-attachments/assets/13a5638e-47ad-4222-a895-37920e29943f)

**Comment by jikkai** [comment]
You did not import the conditional formatting package.

**Comment by hurricane1998** [comment]
ok，thank you very much! I will try it tomorrow.
