### ISSUE TITLE
When registering the data validation plug-in, univer.registerPlugin(UniverSheetsDataValidationPlugin); reports an error and cannot register normally.

### ISSUE THREAD

**Issue by pengshiyong15761698056** [dream-num/univer#4220]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.5.1

### 复现链接

[Uploading package.json…]()

### 预期行为

正常注册

### 实际行为

 Cannot find "We" registered by any injector. The stack of dependencies is: "Fe -> F -> k -> We".

### 运行环境

Safari, 其他 (请在复现步骤中说明)

### 系统信息

[](url)

**Comment by jikkai** [comment]
This is not a link that reproduces the issue, so we will close this issue for now. You are welcome to reopen it at any time once you provide a valid reproduction link.

**Comment by jikkai** [comment]
Duplicate of #4221
