### ISSUE TITLE
Data verification cannot register

### ISSUE THREAD

**Issue by pengshiyong15761698056** [dream-num/univer#4222]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.5.1

### 复现链接

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts

### 预期行为

11

### 实际行为

11

### 运行环境

Chrome

**Comment by jikkai** [comment]
Duplicate of #4221
