### ISSUE TITLE
[Bug] [Bug] 0.5.1 Preset package UniverSheetsDrawingReset. FWorksheet calls addFloatDomToPosition and the console displays activeSheet.addFloatDomToPosition is not a function

### ISSUE THREAD

**Issue by zhou-7** [dream-num/univer#4236]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

`<template>
    <div id="test"></div>
</template>

<script setup>
import { onMounted } from "vue";
import Popup from '@/components/Popup.vue'
import { createUniver, defaultTheme, LocaleType } from '@univerjs/presets'
import { zhCN, enUS } from 'univer:locales';
import { UniverSheetsCorePreset } from '@univerjs/presets/preset-sheets-core'
import { UniverSheetsDrawingPreset } from '@univerjs/presets/preset-sheets-drawing'

import '@univerjs/presets/lib/styles/preset-sheets-core.css'
import '@univerjs/presets/lib/styles/preset-sheets-drawing.css'

onMounted(() => {
    const { univerAPI } = createUniver({
        locale: LocaleType.ZH_CN, // 设置univer语言
        locales: {
            [LocaleType.ZH_CN]: zhCN,
            [LocaleType.EN_US]: enUS,
        },
        theme: defaultTheme, // 设置univer主题
        presets: [
            UniverSheetsCorePreset({
                container: 'test', // 挂载容器
            }),
            UniverSheetsDrawingPreset(),
        ],
    })

    // 创建工作簿
    univerAPI.createUniverSheet({ id: "workbook1" });

    // 注册组件
    univerAPI.getComponentManager().register(
        'excelPopup',
        Popup,
        { framework: 'vue3' }
    )

    // 当前工作簿激活的sheet
    const activeSheet = univerAPI.getActiveWorkbook().getActiveSheet()
    // 添加一个浮层
    activeSheet.addFloatDomToPosition({
        componentKey: 'excelPopup',
        initPosition: {
            startX: 100,
            endX: 200,
            startY: 100,
            endY: 200,
        },
        // 这是组件的数据
        data: {
            title: '我是浮层',
        },
    })

})
</script>

<style>
#test {
    padding: 0;
    margin: 0;
    height: 100%;
}
</style>`

### Expected behavior

You can float custom organizations to specified locations

### Actual behavior

在调用 addFloatDomToPosition 时控制台显示 activeSheet.addFloatDomToPosition is not a function
![image](https://github.com/user-attachments/assets/8d78a544-ec82-4ada-9fa5-4ae9d6b202eb)

**Comment by jikkai** [comment]
`addFloatDomToPosition` in `FWorksheet` is provided by `@univerjs/sheets-drawing-ui`. So you should include the missing preset: `@univerjs/presets/preset-sheets-drawing`.

**Comment by zhou-7** [comment]
![image](https://github.com/user-attachments/assets/f5bc66a5-5459-45b2-a69e-5f1421f362b0)
