### ISSUE TITLE
[Bug] XLOOKUP fails if match_model has empty value

### ISSUE THREAD

**Issue by graham2071** [dream-num/univer#4239]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

https://stackblitz.com/~/github.com/graham2071/sheets-vite-demo?file=src/main.ts

### Expected behavior

In Excel and libreoffice, default value is 0 if not present in the formula

### Actual behavior

![image](https://github.com/user-attachments/assets/01d9e35a-a161-4662-9976-33782b18b084)

`=XLOOKUP(1,(B5:B15=H5)*(C5:C15=H6)*(D5:D15=H7),E5:E15)` => is OK
`=XLOOKUP(1,(B5:B15=H5)*(C5:C15=H6)*(D5:D15=H7),E5:E15,,0,-1)` is Ok
`=XLOOKUP(1,(B5:B15=H5)*(C5:C15=H6)*(D5:D15=H7),E5:E15,,,-1)` => #VALUE

Note: example based on https://exceljet.net/formulas/xlookup-with-multiple-criteria

**Comment by jikkai** [comment]
Could you please confirm if this is related to any known issues? @Dushusir

**Comment by Dushusir** [comment]
> Could you please confirm if this is related to any known issues? @Dushusir

There are indeed some problems with the handling of formula default values.
