### ISSUE TITLE
[Bug] After customizing the UI, the button is not displayed after registration.

### ISSUE THREAD

**Issue by wyl10000** [dream-num/univer#4250]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

5.0.1

### 复现链接

https://gitee.com/wang134246/univer-dome.git

### 预期行为

注册成功，显示按钮

### 实际行为

未显示按钮

### 运行环境

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
you haven't even registered the plugin.

**Comment by wyl10000** [comment]
> 您甚至还没有注册插件。

Presets方式如何注册插件啊，我看官网文档没有写呀

**Comment by wyl10000** [comment]
> 您甚至还没有注册插件。

    const { univer,univerAPI } = createUniver({
      locale: LocaleType.ZH_CN,
      locales: {
        zhCN: Tools.deepMerge(
          {},
          UniverPresetSheetsCoreZhCN,
        ),
      },
      theme: defaultTheme,
      presets: [
        UniverSheetsCorePreset(),
      ]
    });
	univer.registerPlugin(UniverSheetsExportMenuPlugin)
	univerAPI.createUniverSheet({ name: 'Test Sheet' });
	
	注册后，还是不显示，能帮忙看看，是那里的问题吗？
