### ISSUE TITLE
[Feature] How to synchronize data to cells that are forbidden to view and edit in a collaborative document

### ISSUE THREAD

**Issue by wssnail** [dream-num/univer#4252]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

- demo：
https://stackblitz.com/edit/awesome-univer-sheets-vue3-demo-tqapzx?file=src%2Fassets%2Fdefault-workbook-data.ts,src%2Fcomponents%2FUniverSheet.vue,package.json,src%2FApp.vue
- questions are as follows：
In the collaboration table, cell B4 is available for X and disabled for Y, and this cell is involved in formula calculation. Then, after X updates and changes the cell content, how to synchronize it in Y? Currently, if you use the command Set Cell Content to set it, an inoperable pop-up window will appear.
![image](https://github.com/user-attachments/assets/b270643c-1a6b-428b-bba8-e47e6a2bd192)

**Comment by jikkai** [comment]
Cells that are disabled in the current client cannot be edited, which is the **intended behavior**. If the collaborative implementation on your side does not mark the cell as disabled, it should be editable. Please verify your implementation accordingly.
