### ISSUE TITLE
[Feature] The method of rendering cells does not provide a padding parameter. I want to use this padding to handle some logic

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#4257]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

或者有类似的api吗

**Comment by jikkai** [comment]
Duplicate of #4255 

GitHub Issues is intended for reporting bugs and submitting product suggestions. If you have usage-related questions, please use GitHub Discussions for inquiries. Kindly avoid misusing the GitHub Issues feature.
