### ISSUE TITLE
[Bug] Find and replace plugins, enter the search content in the input box, and then close the search box can not open the next time

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#4269]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

The official website connection can be reproduced

### Expected behavior

After closing, you can re-open the search box

### Actual behavior

Unable to open the search popup after closing

**Comment by jikkai** [comment]
According to community guidelines, your issue will be closed.
