### ISSUE TITLE
[Feature] How to disable the mouse right-click menu

### ISSUE THREAD

**Issue by 18860852449** [dream-num/univer#4272]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

场景：用户填报数据的时候，禁止用户通过鼠标右击唤起菜单，只能通过我们自定义的按钮调用部分api

**Comment by jikkai** [comment]
GitHub Issues is not intended for resolving "how-to" questions. You can find solutions in the [documentation](https://docs.univer.ai/en-US/guides/sheets/features/core#univerjsui).

**Comment by 18860852449** [comment]
你好，我是需要禁用鼠标右击唤起右键菜单，而文档中是根据 菜单的ID 一个一个的隐藏，而且是隐藏的顶部的菜单项，和我的需求不一致啊。
