### ISSUE TITLE
[Bug] An error occurred after deployment using Docker

### ISSUE THREAD

**Issue by wssnail** [dream-num/univer#4278]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.5.1

### 复现链接

Local environment, temporarily no online reproduction link

### 预期行为

Expect to be able to open http://localhost:3010 locally for document collaboration

### 实际行为

After deployment, accessing http://localhost:3010 proxy to port 8000 service failed
- frontend error
![image](https://github.com/user-attachments/assets/4692a3fc-8f42-4f83-b622-3f3fbcc4385f)
- UI Docker error
![image](https://github.com/user-attachments/assets/7647dbdb-bf91-43be-9cdd-8c2a1b15ab74)

**Comment by jikkai** [comment]
You haven't provided enough information to help. This issue will be closed.  Please reopen it when you have the necessary information to reproduce the problem.
