### ISSUE TITLE
[Bug] Component COMPONENT_DOC_HEADER_FOOTER_PANEL already exists. The footer style is not in effect

### ISSUE THREAD

**Issue by Harpoonhu** [dream-num/univer#4284]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

    "@univerjs/core": "^0.5.1",     "@univerjs/design": "^0.5.1",     "@univerjs/docs": "^0.5.1",     "@univerjs/docs-ui": "^0.5.1",     "@univerjs/engine-formula": "^0.5.1",     "@univerjs/engine-render": "^0.5.1",     "@univerjs/sheets": "^0.5.1",     "@univerjs/sheets-formula": "^0.5.1",     "@univerjs/sheets-formula-ui": "^0.5.1",     "@univerjs/sheets-numfmt": "^0.5.1",     "@univerjs/sheets-numfmt-ui": "^0.5.1",     "@univerjs/sheets-ui": "^0.5.1",     "@univerjs/ui": "^0.5.1",    "react": "^18.3.1",     "react-dom": "^18.3.1",

### Reproduction link

import { LocaleType, Univer, UniverInstanceType } from '@univerjs/core';
import { defaultTheme } from '@univerjs/design';

import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRenderEnginePlugin } from '@univerjs/engine-render';
import { UniverSheetsPlugin } from '@univerjs/sheets';
import { UniverSheetsUIPlugin } from '@univerjs/sheets-ui';
import { UniverUIPlugin } from '@univerjs/ui';
import { UniverDocsPlugin } from '@univerjs/docs';
import { UniverDocsUIPlugin } from '@univerjs/docs-ui';
import DesignZhCN from '@univerjs/design/locale/zh-CN';
import '@univerjs/engine-formula/facade';
import '@univerjs/ui/facade';
import '@univerjs/docs-ui/facade';
import '@univerjs/design/lib/index.css';
import '@univerjs/ui/lib/index.css';
import '@univerjs/docs-ui/lib/index.css';
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
// import { zhCN, enUS } from 'univer:locales';
import { DEFAULT_WORKBOOK_DATA } from './default-workbook-data';
import './index.css';

// eslint-disable-next-line react/display-name
const UniverSheet = forwardRef(({ data = DEFAULT_WORKBOOK_DATA }, ref) => {
  const univerRef = useRef(null);
  const workbookRef = useRef(null);
  const containerRef = useRef(null);

  useImperativeHandle(ref, () => ({
    getData,
  }));

  /**
   * Initialize univer instance and workbook instance
   * @param data {IWorkbookData} document see https://univer.work/api/core/interfaces/IWorkbookData.html
   */
  const init = (data = {}) => {
    if (!containerRef.current) {
      throw Error('container not initialized');
    }
    const univer = new Univer({
      theme: defaultTheme,
      locale: LocaleType.ZH_CN,
      locales: {
        [LocaleType.ZH_CN]: DesignZhCN,
      },
    });
    univerRef.current = univer;

    // core plugins
    univer.registerPlugin(UniverRenderEnginePlugin);
    univer.registerPlugin(UniverFormulaEnginePlugin);
    univer.registerPlugin(UniverUIPlugin, {
      container: containerRef.current,
    });

    // doc plugins
    univer.registerPlugin(UniverDocsPlugin, {
      hasScroll: false,
    });
    univer.registerPlugin(UniverDocsUIPlugin);

    // sheet plugins
    univer.registerPlugin(UniverSheetsPlugin);
    univer.registerPlugin(UniverSheetsUIPlugin);

    // create workbook instance
    workbookRef.current = univer.createUnit(UniverInstanceType.UNIVER_SHEET, data);
  };

  /**
   * Destroy univer instance and workbook instance
   */
  const destroyUniver = () => {
    // univerRef.current?.dispose();
    univerRef.current = null;
    workbookRef.current = null;
  };

  /**
   * Get workbook data
   */
  const getData = () => {
    if (!workbookRef.current) {
      throw new Error('Workbook is not initialized');
    }
    return workbookRef.current.save();
  };

  useEffect(() => {
    init(data);
    return () => {
      destroyUniver();
    };
  }, [data]);

  return <div ref={containerRef} className="univer-container" />;
});

export default UniverSheet;

### Expected behavior

Render properly

### Actual behavior

![image](https://github.com/user-attachments/assets/c1e8ee8e-3ba4-4f69-a237-8ee243435863)
![image](https://github.com/user-attachments/assets/22fb18c6-aea1-4bba-bebb-3df67f8ac83a)

**Comment by Harpoonhu** [comment]
return <div ref={containerRef} className="univer-container" />;

**Comment by Harpoonhu** [comment]
return       <div ref={containerRef} className="univer-container" />;

**Comment by jikkai** [comment]
You forgot to import the sheets-ui stylesheet.
```diff
+ import '@univerjs/sheets-ui/lib/index.css';
```

**Comment by qwewangkang** [comment]
使用@univerjs/presets 要怎么引入'@univerjs/sheets-ui/lib/index.css'？
