### ISSUE TITLE
[Bug] `0.5.1` Can't find variable: Path2D

### ISSUE THREAD

**Issue by okxiaoliang4** [dream-num/univer#4286]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

[repo](https://github.com/okxiaoliang4/univer-server-bug-report)

```shell
bun install
bun run dev
```

It's only throw the `Can't find variable: Path2D` Error on 0.5.1, 0.5.0 is fine.

### Expected behavior

not throw error

### Actual behavior

throw `Can't find variable: Path2D` Error

### System information

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.1 - ~/.nvm/versions/node/v22.4.1/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.4.1/bin/npm
    pnpm: 9.15.0 - ~/Library/pnpm/pnpm
    bun: 1.1.38 - ~/.bun/bin/bun
    Watchman: 2024.11.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.109
    Safari: 18.0

**Comment by jikkai** [comment]
Fixed in https://github.com/dream-num/univer-presets/pull/25
