### ISSUE TITLE
[Feature] 希望函数计算时候考虑一下js浮点数问题，不知道univer有没有，因为在luckysheet中遇见过因为js浮点数导致计算不准的问题

### ISSUE THREAD

**Issue by zhaorui2000** [dream-num/univer#430]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

比如说luckysheet中round方法实现
![cde6396296393b37b9a577d114933c3f](https://github.com/dream-num/univer/assets/49807887/ccf051de-4785-4dce-8b53-d146e78f7d50)
单元格内配置=ROUND(34384.075,2) 计算出来的结果是 34384.07
原因：
![1699600941865_93B032B6-25CC-47d1-87BF-EDBBD9F88A5F](https://github.com/dream-num/univer/assets/49807887/33ea9082-2a98-492e-805a-451179914ec6)
js计算浮点数的问题导致最终结果不准

### 解决方案

使用一些计算相关的库 比如 mathjs 之类的

### 替代方案

不清楚

**Comment by jikkai** [comment]
Thanks for your feedback. We have noticed the problems and we will try our best to avoid its occurrence in Univer.

---

感谢反馈，相关问题我们已经注意到了，Univer 中会尽量避免该问题的发生
