### ISSUE TITLE
[Feature] How to remove copy selection?

### ISSUE THREAD

**Issue by VanessaWang1110** [dream-num/univer#4314]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

hi, it's not an issue or feature, I just want to know how to use API to remove this selection
![image](https://github.com/user-attachments/assets/72663623-fc85-4f77-9267-dc44b7a66e32)

**Comment by jikkai** [comment]
We do not accept any how-to type of questions in GitHub issues, please move to the discussion for consultation.
