### ISSUE TITLE
[Bug] [Univer Sheet] ctrl+c causes unexpected scrolling in non-https environments.

### ISSUE THREAD

**Issue by jnzhsh** [dream-num/univer#4326]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

[SheetBugReproduceExample.zip](https://github.com/user-attachments/files/18174516/SheetBugReproduceExample.zip)
# How To Reproducte
1. npm i
2. npm run dev
3. open browser and select a cell  （dont use localhost）
4. ctrl + c

# Some findings that might be useful
In this case it hits _legacyCopyHtml function ，this function creates a div and focuses on it, which causes a scrolling。

### Expected behavior

no scrolling

### Actual behavior

scrolling

**Comment by ybzky** [comment]
The provided demo cannot be opened

**Comment by jnzhsh** [comment]
[SheetBugReproduceExample.zip](https://github.com/user-attachments/files/18181431/SheetBugReproduceExample.zip)
upload again

**Comment by jikkai** [comment]
This is expected behavior, not a bug.

**Comment by jnzhsh** [comment]
If I don't want this behavior, is there a way to stop it?
