### ISSUE TITLE
[Bug] Printing function introduces error reporting

### ISSUE THREAD

**Issue by 18860852449** [dream-num/univer#4339]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

@univerjs-pro/sheets-print 0.5.1

### 复现链接

暂无

### 预期行为

期望和其他功能一样，根据文档引入后可以直接使用。

### 实际行为

实际情况根据文档引入后报错，主要是这一句：import { UniverSheetsPrintPlugin } from '@univerjs-pro/sheets-print'
![image](https://github.com/user-attachments/assets/39d57fd2-8902-4aec-a397-e5b84661bb0a)

### 运行环境

Chrome

### 系统信息

![image](https://github.com/user-attachments/assets/8c610c17-d2b3-401e-8f5c-6b48baf54b0a)

**Comment by jikkai** [comment]
Reproduction link plz.

**Comment by jikkai** [comment]
Since you have not provided a reproduction link, we will close this issue for now. Once you have prepared the reproduction link, feel free to reopen this issue at any time.
