### ISSUE TITLE
[Bug] After I remove the table protection in the menu item, I can still select table protection and edit in the mouse mail menu and worksheet list right-click menu.

### ISSUE THREAD

**Issue by xiaoshuaikang** [dream-num/univer#4349]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.5.1

### 复现链接

https://gitee.com/wkk001/demo/tree/master/

### 预期行为

当我在菜单项中删除掉表格保护后，在右键菜单以及工作表列表右键菜单也删除表格保护选项

### 实际行为

![issues-image](https://github.com/user-attachments/assets/ff0a445e-fbe1-4d4c-a9e9-c5c5a49aed60)
当我在菜单项中把表格保护移除之后，在鼠标邮件菜单和工作表列表右键菜单仍然可选择表格保护并编辑。

### 运行环境

Chrome

### 系统信息

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 800.15 MB / 15.72 GB
  Binaries:
    Node: 20.13.1 - D:\node\node.EXE
    npm: 10.5.2 - D:\node\npm.CMD
    pnpm: 9.14.2 - D:\node\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.89)
    Internet Explorer: 11.0.22621.3527

**Comment by xiaoshuaikang** [comment]
![issues01](https://github.com/user-attachments/assets/5bb236b0-b222-49f7-a297-1001a928ed07)
这个是配置菜单移除保护按钮

**Comment by ybzky** [comment]
You did not hide all related menus

**Comment by xiaoshuaikang** [comment]
> You did not hide all related menus
How should I hide all relevant menus?

**Comment by xiaoshuaikang** [comment]
> You did not hide all related menus

How should I hide all relevant menus?
