### ISSUE TITLE
[Bug] Row height does not adjust automatically (row height is not automatically adjusted after wrap)

### ISSUE THREAD

**Issue by YaSLiZhe** [dream-num/univer#4351]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.2

### 复现链接

English：
After using the setWrap method in Frange, the row height does not adjust automatically, even though I’ve tried disabling all settings related to height. In rare cases, the table will suddenly adjust the row height some time after the data has finished loading, but most of the time it does not. My expectation is that once the data is loaded, the row height should be stably adjusted right away.
中文：
使用 Frange 中的 setWrap 方法之后，没有自动调整行高，已经尝试关闭所有和高度相关的设置。极少数情况下，表格会在加载完毕后一段时间突然自动调整行高，大部分情况下则不会。我的预期是加载完数据后，行高就能立刻并稳定地自动调整好。

### 预期行为

After using the setWrap method in Frange, the row height adjusts automatically,

### 实际行为

Not adjust

### 运行环境

Chrome

**Comment by jikkai** [comment]
Please provide the minimal reproduction.
