### ISSUE TITLE
[Feature] I want to hide all the menu items and keep only one merge cell. What should I do?

### ISSUE THREAD

**Issue by elevenwangyang** [dream-num/univer#4353]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

![image](https://github.com/user-attachments/assets/7ea9faa6-2cef-4518-8f6e-e4456693f393)

This method is a little too cumbersome, what is the method of batch setting?

**Comment by jikkai** [comment]
We do not accept any how-to type of questions in GitHub issues, please move to the discussion for consultation.
