### ISSUE TITLE
[Feature] How to set the adaptive height

### ISSUE THREAD

**Issue by south936** [dream-num/univer#4357]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

 styles: {
          hyperlink: {
            cl: {
              rgb: '#0000ff'
            },
            ul: {
              s: 1, // 是否展示下划线
              c: 0, // 颜色是否跟随字体颜色。当 `c` 为 1（TRUE） 时 cl 不起作用。默认值为 1
              cl: { // 下划线颜色
                rgb: '#0000ff'
              },
              t: 0 // 下划线类型
            }
          },
          PznCR3: {
            ff: 'Helvetica Neue, Helvetica, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif',
            fs: 10,
            it: 0,
            bl: 0,
            ul: {
              s: 0,
              cl: {
                rgb: 'rgb(0,0,0)'
              }
            },
            td: 0,
            cl: {
              rgb: 'rgb(0,0,0)'
            },
            ia:1,
            ht: 0,
            vt: 0,
            tb: 0,
            pd: {
              t: 0,
              b: 1,
              l: 2,
              r: 2
            }
          }
        },

**Comment by Dushusir** [comment]
Set https://reference.univer.ai/@univerjs/core/interfaces/IRowData in IRowData

If you still have problems, feel free to reopen the issue
