### ISSUE TITLE
[Feature] Bottom right-click menu configuration

### ISSUE THREAD

**Issue by qwewangkang** [dream-num/univer#4362]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

![image](https://github.com/user-attachments/assets/bd7bd102-46f9-474e-bcff-498670995a50)
可以提供一个api去掉这个功能吗？

**Comment by Dushusir** [comment]
You can add custom menu configuration https://docs.univer.ai/en-US/guides/sheets/advanced/custom-ui#customizing-menu-items-hiding-menu-items
