### ISSUE TITLE
[Feature] Provide the Freeze function for configuration

### ISSUE THREAD

**Issue by smallCF** [dream-num/univer#4367]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Expected to provide a freeze function for configuration, which may not be necessary in certain scenarios or allow users to perform freezing operations

**Comment by jikkai** [comment]
Whether through configuration or via the Facade API, we have already provided support for implementing freezing functionality.
