### ISSUE TITLE
[Bug] Using the custom extension command provided by the official documentation, but the expected effect was not achieved

### ISSUE THREAD

**Issue by ForSakuraLove** [dream-num/univer#4373]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

I use the official react writing method and add custom plug-ins, but the desired result was not achieved

GitHub repository address: https://github.com/ForSakuraLove/sheets-react-demo
Use pnpm install and pnpm dev to start the project

The main code is as follows:
```
import { Disposable } from '@univerjs/core'
import { ISheetClipboardService, ISheetClipboardHook } from '@univerjs/sheets-ui'

export class CustomController extends Disposable {
    constructor(
        @ISheetClipboardService private readonly _sheetClipboardService: ISheetClipboardService
    ) {
        super()
        const yourHook: ISheetClipboardHook = {
            id: 'your-hook-id',
            onBeforeCopy: () => {
                alert('Hello!') // In this method, your code will be executed before copying.
            }
            // all hook methods are optional, you can learn it from interface definition.
        }
        // register your hook
        this.disposeWithMe(this._sheetClipboardService.addClipboardHook(yourHook))
    }
}
```
```
import { Plugin, ICommandService, UniverInstanceType, Injector, setDependencies } from '@univerjs/core'
import { CustomController } from './customController'

export class CustomPlugin extends Plugin {
    static override type = UniverInstanceType.UNIVER_UNKNOWN
    static override pluginName = 'MY_PLUGIN_NAME'
    protected _injector: Injector;
    protected _commandService: ICommandService;
    constructor(_injector: any, _commandService: any) {
        super()
        this._injector = _injector
        this._commandService = _commandService
    }
    override onStarting() {
        [[CustomController]].forEach(d => this._injector.add(d))
    }
}
setDependencies(CustomPlugin, [Injector, ICommandService])
```
```
const univer = new Univer({
      theme: defaultTheme,
      locale: LocaleType.ZH_CN,
      locales: {
        [LocaleType.ZH_CN]: Tools.deepMerge(
          SheetsZhCN,
          DocsUIZhCN,
          SheetsUIZhCN,
          UIZhCN,
          DesignZhCN,
        ),
      },
    });

    // core plugins
    // doc plugins
    // sheet plugins
    univer.registerPlugin(CustomPlugin)//custom plugin
```

### Expected behavior

When copying in the Univer table, an alert appears

### Actual behavior

Nothing happened

### System information

System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
    Memory: 2.40 GB / 19.79 GB
  Binaries:
    Node: 18.20.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - D:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.1 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355

**Comment by jikkai** [comment]
I believe the issue lies in the user code rather than a bug. Could you help me take a look? @hexf00

**Comment by hexf00** [comment]
1. Using `ISheetClipboardService` without registering it.
2. `CustomController` has not been instantiated.

```diff
-  override onStarting() {
+  override onReady() {
    console.log('onStarting');
    [[CustomController]].forEach((d) => this._injector.add(d));
+   this._injector.get(CustomController);
  }
```
