### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by lemndo** [dream-num/univer#490]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

可以转成es5吗？旧浏览器不能兼容
need es5 version

### Solution

need es5 version

### Alternatives

need es5 version

**Comment by jikkai** [comment]
We provide ES module-based packages. You can convert the compiled code into es5 or even es3 specifications through packaging tools (Vite, Webpack, Rollup) in integrated products, all of which depends on your work.

---

我们提供了基于 ES module 的包，你可以在集成的产品中自行通过打包工具（Vite、Webpack、Rollup）将编译后的代码转为符合 es5 甚至是 es3 规范的代码，这一切仅取决于你的工作
