### ISSUE TITLE
[Feature] Can not add as library

### ISSUE THREAD

**Issue by coyzeng** [dream-num/univer#506]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

yarn add @univerjs/base-render

YN0001: │ Error: @univerjs/core@workspace:^0.0.1: Workspace not found (@univerjs/core@workspace:^0.0.1)

### Solution

Support use as a library.

### Alternatives

No

**Comment by jikkai** [comment]
We haven't released this package in npm yet.

**Comment by coyzeng** [comment]
Has any plan?

**Comment by jikkai** [comment]
> Has any plan?

Next month, we will release an early preview version.
