### ISSUE TITLE
[Bug] 选中单元后复制粘贴功能报错

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#531]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.0.1-pre-alpha.26

### 复现步骤

1.选中单元古 2快捷键复制 （报错）3快捷键粘贴（报错）

### 预期行为

能正常的拷贝和粘贴

### 实际行为

无法正常的拷贝和粘贴

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Webpack

**Comment by jikkai** [comment]
ref #561

**Comment by jikkai** [comment]
fixed in #561
