### ISSUE TITLE
[Feature] 列表头一行（序号列）样式支持自定义（序号上下左右居中，底色），露出rowTitleCellRenderAfter 钩子函数支持自定义绘制。

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#542]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

列表第一一行（序号列）样式支持自定义（序号上下左右居中，底色），露出rowTitleCellRenderAfter 钩子函数支持自定义绘制。
如图: 
<img width="311" alt="01" src="https://github.com/dream-num/univer/assets/17244342/66e8e0f8-c705-4912-b469-41b2b32f24fc">

### 解决方案

序号支持上下左右对齐，底色可改变， 头部列支持钩子函数rowTitleCellRenderAfter， 进行自定义canvas 绘制自己需要的文案和图标。<img width="231" alt="02" src="https://github.com/dream-num/univer/assets/17244342/98864bed-de0d-4958-b9ac-a56ec10102d4">

### 替代方案

作者是否可以提供一个api 更好更便捷的去进行传入，比如  let arr =  [{content: '详情', handle: 'click', handFun: ()=>{}, x: 100, y: 100}] columnHeadData={ arr };     x和y 代表 和当前单元格的上边距 左边距，handle 代表该content操作类型，handFun: 代表 操作后触发的方法。

**Comment by Dushusir** [comment]
In the future we will discuss the functional design of related requirements

未来我们会讨论相关需求的功能设计

**Comment by Dushusir** [comment]
目前已经实现了渲染扩展API来满足自定义行标题 列标题的功能，详细参考 https://github.com/awesome-univer/sheets-render-extension-demo
