### ISSUE TITLE
[Feature]头部第一行能否进行冻结 固定，这样在上下滚动的时候便于观察数据

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#543]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

目前头部第一行在滚动的时候不固定。
<img width="693" alt="03" src="https://github.com/dream-num/univer/assets/17244342/3bccb85c-cdd0-4756-8173-29bec21ba14b">

### 解决方案

头部第一行或者任意一行可进行冻结固定，这样滚动的时候可以固定在当前视窗内。
<img width="553" alt="04" src="https://github.com/dream-num/univer/assets/17244342/883b6ea1-a64f-48b6-953b-e6af51e3c987">

### 替代方案

无

**Comment by jikkai** [comment]
In this case, Univer's logic is to freeze the top-left of the selected area. So, the outcome of freezing the first row is the same as unfreezing it.
For freezing panes, like selecting the first row, first column, or A1 cell, different products, such as Excel and Google Sheets, has different performance.
We won't consider this as a bug for now, and we won't close this issue temporarily. Feel free to continue discussing any new ideas on this issue.

---

我们目前的原则是对选中区域的左上进行冻结，因此对首行冻结的结果和取消冻结无异。
关于选择首行、首列或者 A1 单元格进行冻结窗格操作的场景，Excel、Google Sheets 等产品都有不同的展现形式。
我们暂时不会将此视为 bug，但也暂时不会关闭这个 issue，有任何新的想法可以在这个 issue 继续讨论

**Comment by wzhudev** [comment]
We have already supported freezing in next latest versions. This issue would be closed.
