### ISSUE TITLE
[Bug] freeze字段， 有值后 表格渲染失败。

### ISSUE THREAD

**Issue by nanguaye** [dream-num/univer#559]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.0.1-pre-alpha.26

### 复现步骤

1.数据中 新增字段 freeze: { startColumn: -1, xSplit: 0, startRow:1,  ySplit: 1 },  PS： 该字段值是我通过，冻结表格第一行后，window.univer._univerInstanceService.getCurrentUniverSheetInstance().getActiveSheet()._snapshot.freeze  方式获取到的。
2.字段初始化好值后，刷新表格 发现表格渲染失败
<img width="673" alt="11" src="https://github.com/dream-num/univer/assets/17244342/5d34b369-72bb-4a5d-97b0-41553fd89767">

### 预期行为

预期表格能正常渲染， 渲染完后 第一节是冻结的状态

### 实际行为

表格无法正常渲染

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Webpack

**Comment by jikkai** [comment]
试了下没有什么问题，请确认下你的数据结构是否正确

```javascript
sheets: {
  'sheet-0010': {
    ...
    name: 'sheet-0010',
    id: 'sheet-0010',
    freeze: {
      xSplit: 0,
      ySplit: 0,
      startRow: -1,
      startColumn: -1,
    },
```

**Comment by nanguaye** [comment]
> 试了下没有什么问题，请确认下你的数据结构是否正确
> 
> ```js
> sheets: {
>   'sheet-0010': {
>     ...
>     name: 'sheet-0010',
>     id: 'sheet-0010',
>     freeze: {
>       xSplit: 0,
>       ySplit: 0,
>       startRow: -1,
>       startColumn: -1,
>     },
> ```

用你提供的数据，表格可以正常渲染，但是 冻结不生效。 我那个数据的话 是通过冻结以后，然后获取到的数据。
