### ISSUE TITLE
[Feature]数据量太大 渲染速度较慢，阻塞页面进程，出现卡死的现象。

### ISSUE THREAD

**Issue by Nice-yang** [dream-num/univer#560]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

导入excel数据量大，数据量大概1w+条， 出现渲染阻塞进程，页面卡死的现象。

### 解决方案

渲染速度提升，不要阻塞进程。

### 替代方案

有更好的也可以

**Comment by DR-Univer** [comment]
@Nice-yang 已经fix了，可以用最新版本看看
