### ISSUE TITLE
Decompose mutating methods from Worksheet Workbook Range RangeList etc and move these methods into base-sheet-plugin

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#61]
移除 `Worksheet` `Workbook` `Range` `RangeList` 上的 mutate 方法，接入新的命令系统

- [x] refactor old Apply & Action to new Command & Mutation
- [x] Remove API methods on the classes above
- [x] Remove callers to these API. Invoke commands instead.

**Comment by Dushusir** [comment]
- [ ] Worksheet @eiji-th 
- [ ] Workbook @Dushusir 
- [ ] Range @tonytonychopper123 
- [ ] RangeList @tonytonychopper123 @Dushusir
