### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zhao-yang857** [dream-num/univer#63]
请问作者  这个现在怎么使用呢，需要下载源码后自己打包，和luckysheet一样？

**Comment by jikkai** [comment]
Thanks for your interest in the project! 
As of now, the project is still in development. You can stay updated on our progress by checking out our [GitHub Projects](https://github.com/dream-num/univer/projects) page. 😄

---

感谢您对项目的关注！
目前为止项目仍在开发中。您可以通过 [GitHub Projects](https://github.com/dream-num/univer/projects) 来了解我们的工作进展。😄
