### ISSUE TITLE
感谢作者开源，请问有稳定1.0版本了吗

### ISSUE THREAD

**Issue by fancyboynet** [dream-num/univer#68]
好像都还是在开发状态？

**Comment by jikkai** [comment]
Thanks for your interest in the project! 
As of now, the project is still in development. You can stay updated on our progress by checking out our [GitHub Projects](https://github.com/dream-num/univer/projects) page. 😄

---

感谢您对项目的关注！
目前为止项目仍在开发中。您可以通过 [GitHub Projects](https://github.com/dream-num/univer/projects) 来了解我们的工作进展。😄
