### ISSUE TITLE
双击单元格进入编辑状态，再拖动行高或者列宽后，选中框的高度或者宽度不会跟着改变[Bug]

### ISSUE THREAD

**Issue by kdevilpf** [dream-num/univer#680]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

2023年12月8日12:40前

### 复现步骤

https://github.com/dream-num/univer/assets/30714247/a5bb0b47-95f1-408f-acad-7ef9f4d1b6dd

### 预期行为

改变【进入编辑状态单元格】的行高或者列宽后，绿色选中框的高度和宽度应该跟随改变后的状态

### 实际行为

改变【进入编辑状态单元格】的行高或者列宽后，绿色选中框的高度和宽度应该跟随改变后的状态，且对应的列标尺或行标尺上出现了颜色不统一的情况
![image](https://github.com/dream-num/univer/assets/30714247/4911522c-7989-44c2-aa45-0da3494e4e8b)

**Comment by DR-Univer** [comment]
@kdevilpf 用最新版本看看，好像这个问题已经没有了

**Comment by kdevilpf** [comment]
好的，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月17日(周日) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dream-num/univer] 双击单元格进入编辑状态，再拖动行高或者列宽后，选中框的高度或者宽度不会跟着改变[Bug] (Issue #680)




 
@kdevilpf 用最新版本看看，好像这个问题已经没有了

**Comment by kdevilpf** [comment]
你好，刚拉取了最新代码，没修复这个bug呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月17日(周日) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dream-num/univer] 双击单元格进入编辑状态，再拖动行高或者列宽后，选中框的高度或者宽度不会跟着改变[Bug] (Issue #680)




 
@kdevilpf 用最新版本看看，好像这个问题已经没有了

**Comment by kdevilpf** [comment]
是【双击】单元格，单元格内有【光标闪动】，再拖动那个单元格对应的行高或者列宽



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月17日(周日) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dream-num/univer] 双击单元格进入编辑状态，再拖动行高或者列宽后，选中框的高度或者宽度不会跟着改变[Bug] (Issue #680)




 
@kdevilpf 用最新版本看看，好像这个问题已经没有了
