### ISSUE TITLE
[Feature]冻结行列设置：frozen 是否可以 支持既冻结首行，又冻结选区列的功能？

### ISSUE THREAD

**Issue by 18893782895** [dream-num/univer#684]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

使用  frozen 冻结行列配置，该值是一个对象：如下
forzen: { 
    type: 'rangeColumn', //row 冻结首行 column冻结首列 rangeColumn 冻结列到选区
    range: {
        row_focus: 1,
        column_focus: 6
    }
};
当使用 type为rangeColumn，只冻结了列到选区。
如果想要将首行即标题行 和 列选区如前6列都冻结，则无法配置。效果如下图：
![image](https://github.com/dream-num/univer/assets/96401262/16849def-f72e-4dae-8c0e-1d1e673effd9)

### Solution

同时支持 既能冻结首行，又能冻结选区列的功能 配置

### Alternatives

无

**Comment by jikkai** [comment]
这个功能在 univer 中已经实现

<img width="816" alt="image" src="https://github.com/dream-num/univer/assets/14025786/9746198e-7e78-4a15-8f1d-7a3f0ffffe45">
