### ISSUE TITLE
[Feature] 清除能力无法清除数字格式

### ISSUE THREAD

**Issue by Eelson** [dream-num/univer#698]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

清除能力无法清除数字格式

### 解决方案

清除能力支持清除数字格式

### 替代方案

无

**Comment by Gggpound** [comment]
这个应该已经处理过了,阿森

**Comment by wzhudev** [comment]
cc @zhaolixin7 Please verify this and close the issue if it had been fixed.
