### ISSUE TITLE
[Bug] freeze column cannot come across merged cells

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#724]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

*

### Steps to reproduce

从右键菜单或者拖拽来设置冻结行列

### Expected behavior

如果穿越了一个合并单元格，要报错并禁止操作

### Actual behavior

冻结行列穿越了合并单元格

**Comment by yuhongz** [comment]
> ### Initial checklist
> * [x]  Is this really a problem?
> * [x]  I have searched the Github Issues for similar issues, but did not find anything.
> 
> ### Affected packages and versions
> 
> ### Steps to reproduce
> 从右键菜单或者拖拽来设置冻结行列
> 
> ### Expected behavior
> 如果穿越了一个合并单元格，要报错并禁止操作
> 
> ### Actual behavior
> 冻结行列穿越了合并单元格
> 
> ### Runtime
> _No response_
> 
> ### OS
> _No response_
> 
> ### Build and bundle tools
> _No response_

Excel 中是可以冻结是可以穿过合并单元格的，并且合并单元格也可以穿越冻结，是否不必要禁止这一点

**Comment by wzhudev** [comment]
> Excel 中是可以冻结是可以穿过合并单元格的，并且合并单元格也可以穿越冻结，是否不必要禁止这一点

cc @DR-Univer What is your opinion?

**Comment by weird94** [comment]
Google sheet无法穿越冻结的，excel和microsoft365是可以的。反之在冻结场景下合并单元格跨域冻结同理

**Comment by wzhudev** [comment]
Closed as expected.
