### ISSUE TITLE
[Feature] 刷新时可以从当前子表打开

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#760]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

active sheet的id体现到url里，刷新的时候 还是定位当前sheet

### 解决方案

active sheet的id体现到url里，后端做按需加载也能用

### 替代方案

手动切换

**Comment by wzhudev** [comment]
Implemented in univer-pro.

**Comment by 1314xulujin** [comment]
Hello, I`ve encounter the same problem you have, follows are my implementions:
`  univerAPI = FUniver.newAPI(univer);
    console.log(workbookRef, univerAPI)

    univerAPI.executeCommand('**sheet.command.set-worksheet-activate**', { unitId: "workbook-01", subUnitId: "E-0qn3prMttDTaHCcML7p" }); `

**Comment by 1314xulujin** [comment]
Hello, I`ve encounter the same problem you have, follows are my implementions:  

```
univerAPI = FUniver.newAPI(univer);
console.log(workbookRef, univerAPI)
univerAPI.executeCommand('sheet.command.set-worksheet-activate', { unitId: "workbook-01", subUnitId: "E-0qn3prMttDTaHCcML7p" });
```

It seems the univer`s guide command "sheet.command.active-sheet" is wrong, when I use it, will occured error: Unhandled Rejection (Error): [CommandService]: command "sheet.command.active-sheet" is not registered.
