### ISSUE TITLE
[Bug] status bar 选中范围同时包含日期、数字 日期当作日期还是转化为数值的策略问题 

### ISSUE THREAD

**Issue by Ella1117** [dream-num/univer#776]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

latest version

### 复现步骤

当选中范围内数据类型包括数字、日期，遵循Excel的做法： 
1. 若第一个（高亮 白底单元格） 为日期，则将下面的数值转化为日期参与计算 ；
2. 若第一个不为日期，不论是数值或文本，不论接下来出现的数值或日期怎么排列，都默认把日期转化为数值进行计算 

### 预期行为

![image](https://github.com/dream-num/univer/assets/146371080/cc109e29-35f6-482f-9108-1f93cc38c0fe)

### 实际行为

![image](https://github.com/dream-num/univer/assets/146371080/acfd837a-ae86-4001-ae86-c3fa2b7bfd7e)

### 运行环境

Chrome

### 操作系统

Windows

### 构建工具

其他 (请在复现步骤中说明)

**Comment by zhaolixin7** [comment]
统计栏包含了所有的格式（货币、时间等），确认下保留日期还是全部
