### ISSUE TITLE
[Bug] row height & column width can be a minus number

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#781]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

The current dev branch

### Steps to reproduce

![image](https://github.com/dream-num/univer/assets/12122021/e63a2859-1a7c-40e5-84b7-9981f1be134e)

I have no idea how to reproduce this bug in a consistent way.

### Expected behavior

.

### Actual behavior

.

**Comment by DR-Univer** [comment]
只要改变行高就会出现？是通过标题的按钮拖动修改么

**Comment by wzhudev** [comment]
> 只要改变行高就会出现？是通过标题的按钮拖动修改么

Yes 有一定的概率会出现
