### ISSUE TITLE
渲染时，部分（靠后）列数据未渲染出来

### ISSUE THREAD

**Issue by yangluoshen** [dream-num/univer#790]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

latest

### 复现步骤

复现条件:
1. 列数大于行数（colCount > rowCount)
2. 大于行数（rowCount)的列，其单元格有内容

以下是我的实验结果（希望对你有帮助）。

当我设置初始化表格为row:100, col:200的时候，编辑操作过程中没有看出问题。
但是刷新之后，最终展示的时候，只展示到100列（也就是展示了一半）。
![image](https://github.com/dream-num/univer/assets/5471004/6d1dd75d-b05d-4658-b747-573a5bff3fcb)
![image](https://github.com/dream-num/univer/assets/5471004/90066ef8-ebb6-40a1-a754-61616410ddba)

**猜测是渲染的时候，univer代码中col和row变量用反了**

于是，我改成初始化表格为 row:200, col:200,  刷新正常
![image](https://github.com/dream-num/univer/assets/5471004/617961b7-bfec-4411-b6c1-36dabaae448e)

为了避免巧合，初始化表格改为 row:150, col:200，刚好停在EU列，也就是150列。
![image](https://github.com/dream-num/univer/assets/5471004/a8b718a0-c42b-45de-8914-c5ac28204417)
![image](https://github.com/dream-num/univer/assets/5471004/2dc4d7e3-4f9c-4f33-8ea0-dc703f83dbed)

### 预期行为

展示（渲染）所有数据

### 实际行为

实际结果中， 大于行数的列数据不展示

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

esbuild

**Comment by DR-Univer** [comment]
@yangluoshen 测试链接给我个

**Comment by zhaolixin7** [comment]
@DR-Univer  
[2023_12_25 20_58_37 video.webm](https://github.com/dream-num/univer/assets/154207126/17ca1f3d-28d1-4307-98e9-a04398f1296f)

[2023_12_25 20_58_37 commands.json](https://github.com/dream-num/univer/files/13766105/2023_12_25.20_58_37.commands.json)

**Comment by DR-Univer** [comment]
> @DR-Univer [2023_12_25 20_58_37 video.webm](https://github.com/dream-num/univer/assets/154207126/17ca1f3d-28d1-4307-98e9-a04398f1296f)
> 
> [2023_12_25 20_58_37 commands.json](https://github.com/dream-num/univer/files/13766105/2023_12_25.20_58_37.commands.json)

Fixed

**Comment by yangluoshen** [comment]
@DR-Univer @zhaolixin7 这个问题好像还没有解决。
刷新一下就会发现部分渲染不出来了
