### ISSUE TITLE
setRangeMerge not working

### ISSUE THREAD

**Issue by Allegro2** [dream-num/univer#8]
I have a problem with the setRangeMerge function. When I try to use it I get the following error:

api.js:3114         
    Uncaught TypeError: Cannot set properties of undefined (setting '9_3')
    at Object.setRangeMerge (api.js:3094:41)
    at UnisciCelle (prova_LuckySheet.html:45:20)
    at HTMLInputElement.onclick (prova_LuckySheet.html:21:98)

This is my code:

<html>
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/css/pluginsCss.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/plugins.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/css/luckysheet.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/assets/iconfont/iconfont.css' />
<script src="https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/js/plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luckysheet@2.1.13/dist/luckysheet.umd.js "></script>

 

```
<title>EasyGrooming</title>

    <input type='button' id='btnUnisci' value='Unisci celle' onclick='UnisciCelle()'>
    <input type='button' id='btnLeggiCella' value='Leggi cella' onclick='LeggiCella()'>
    <div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:600px;height:70%;"></div>
        
 
<script> 
    $(function () 
    {
        //Configuration item
        var options = {
            container: 'luckysheet' //luckysheet is the container id
        };
        luckysheet.create(options);
    });
    
    function UnisciCelle()
    {
        alert("Here I am!");
        luckysheet.cancelFrozen();
        luckysheet.setRangeMerge("all", "D10:E15");
    }
    function LeggiCella()
    {
        luckysheet.setRowHeight({5:50, 6:80});
        luckysheet.setCellValue(3, 4, "puppa");
        luckysheet.setCellFormat(4, 5, "bd", {borderType: "border-right",style: "1", color: "#ff0000"});
        luckysheet.setRangeShow("D10:E15");
        var sVal = luckysheet.getCellValue(0, 0);
        alert("Valore : " + sVal);
    }
    
</script>
  
</html>
```

Can somebody help me?
Many thanks

**Comment by Dushusir** [comment]
I am very sorry for the inconvenience caused to you. For the time being, Luckysheet needs your own custom development.
