### ISSUE TITLE
[Bug选中多行，只删除内容行未消失

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#815]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

选中多行，右键菜单删除选中行

### 预期行为

选中行被删除

### 实际行为

选中行内容消失行未被删除

![image](https://github.com/dream-num/univer/assets/154207126/fe713ac4-a9cf-4652-ba6f-e41c3f013083)

### 运行环境

其他 (请在复现步骤中说明)

### 操作系统

Windows

### 构建工具

其他 (请在复现步骤中说明)

**Comment by Gggpound** [comment]
close #826
