### ISSUE TITLE
[Bug]删除最后一列白屏

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#816]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

选中最后一列，右键删除

### 预期行为

列被删除

### 实际行为

sheet白屏
![image](https://github.com/dream-num/univer/assets/154207126/43adbf41-8532-498d-8e1f-39f6a27deb94)

### 运行环境

其他 (请在复现步骤中说明)

### 操作系统

Windows

### 构建工具

其他 (请在复现步骤中说明)

**Comment by Gggpound** [comment]
close #826
