### ISSUE TITLE
[Bug]渲染问题

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#818]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

取消冻结行列

https://github.com/dream-num/univer/assets/154207126/9006d1a3-cf14-4d44-ac54-14368f1542b3

### 预期行为

正常渲染
![image](https://github.com/dream-num/univer/assets/154207126/014730dd-a526-444c-9af8-edd5adbd8b41)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/d4fbeed7-9e09-424c-9a10-f975d707a7ac)

**Comment by zhaolixin7** [comment]
@DR-Univer 这个case还有问题
[2023_12_25 17_02_52 video.webm](https://github.com/dream-num/univer/assets/154207126/c713404b-efa2-4cc1-b5ad-cdb254e7292d)

**Comment by DR-Univer** [comment]
> @DR-Univer 这个case还有问题 [2023_12_25 17_02_52 video.webm](https://github.com/dream-num/univer/assets/154207126/c713404b-efa2-4cc1-b5ad-cdb254e7292d)
Fixed
