### ISSUE TITLE
[Bug]删除列后undo，内容不对

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#821]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

删除列侯undo

### 预期行为

undo后内容恢复

### 实际行为

丢失2列

https://github.com/dream-num/univer/assets/154207126/88674e7c-78bb-4165-8235-4914bca8030d

**Comment by Gggpound** [comment]
close #826
