### ISSUE TITLE
[Bug]修改列宽行高也跟随改变

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#823]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

修改sheet1、7、8的子表的列宽

### 预期行为

行高不发生改变

### 实际行为

https://github.com/dream-num/univer/assets/154207126/bad1f6bf-954c-4588-b6cd-b59de04ebdd8

**Comment by wzhudev** [comment]
@Jocs Please take a look at this. This seems related to auto row height.
