### ISSUE TITLE
[Bug] 选区问题

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#829]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

问题1、选中合并单元格右下角十字光标拖拽
问题2、选中列拖拽修改列宽

### 预期行为

1、合并单元格不能向内拖拽
2、选区随列宽改变

### 实际行为

1、![image](https://github.com/dream-num/univer/assets/154207126/5cc974a4-b409-4b13-8acb-e7cfde7d15a3)
2、选区跟随列宽改变

https://github.com/dream-num/univer/assets/154207126/0cd71f46-544c-471a-966b-7e8221fd5ae6

**Comment by wzhudev** [comment]
This should be fixed. @zhaolixin7
