### ISSUE TITLE
[Bug]快捷键 Backspace无法删除内容

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#851]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

window，选中内容使用快捷键Backspace删除

### 预期行为

选中内容被删除
![image](https://github.com/dream-num/univer/assets/154207126/2e8f72e4-7957-44cf-827f-ff812a4e6f7c)

### 实际行为

快捷键Backspace无法删除

### 运行环境

其他 (请在复现步骤中说明)

### 操作系统

Windows

**Comment by Jocs** [comment]
目前是和 excel 保持一致，先 close 掉，后面可以随时打开 @zhaolixin7
