### ISSUE TITLE
Provide migration guide to Luckysheet users

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#862]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Univer's data is not compatible with Luckysheet.

### Solution

We should provide an official guideline to help Luckysheet users migrate their data to Univer.

**Comment by Dushusir** [comment]
closed by https://github.com/dream-num/univer.ai/pull/124
