### ISSUE TITLE
导入依赖后启动报错

### ISSUE THREAD

**Issue by Xzhly** [dream-num/univer#875]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

<img width="1563" alt="image" src="https://github.com/dream-num/univer/assets/74232608/f727e7f7-dbe9-42df-8c23-64b8476ec85b">
[univer-demo1.zip](https://github.com/dream-num/univer/files/13764749/univer-demo1.zip)

### 预期行为

...

### 实际行为

<img width="1590" alt="image" src="https://github.com/dream-num/univer/assets/74232608/007db2b7-5cb4-4234-935f-6c5515bac82f">
<img width="1587" alt="image" src="https://github.com/dream-num/univer/assets/74232608/0e6e1c2d-20a9-442a-8e4c-deeb665f690f">

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

其他 (请在复现步骤中说明)

**Comment by jikkai** [comment]
1. Please make your angular project support importing CSS.

2. Please add `"skipLibCheck": true,` to your `tsconfig.json`.

```diff
+ "skipLibCheck": true,
```

**Comment by TONG77777** [comment]
Issue : 我目前用你提供的[univer-demo1.zip](https://github.com/dream-num/univer/files/13765018/univer-demo1.zip)跑ng serve以及在自己的project加了`"skipLibCheck": true`,同样也会抱错 问题如图
![image](https://github.com/dream-num/univer/assets/78796067/f656f47f-43c9-405c-ad40-4a6ce3480400)

**Comment by TONG77777** [comment]
> 1. Please make your angular project support importing CSS.
> 2. Please add `"skipLibCheck": true,` to your `tsconfig.json`.
> 
> ```diff
> + "skipLibCheck": true,
> ```
> 
> [univer-demo1.zip](https://github.com/dream-num/univer/files/13765018/univer-demo1.zip)
Issue : 我目前用你提供的[univer-demo1.zip](https://github.com/dream-num/univer/files/13765018/univer-demo1.zip)跑ng serve以及在自己的project加了`"skipLibCheck": true`,同样也会抱错 问题如图
![image](https://github.com/dream-num/univer/assets/78796067/f656f47f-43c9-405c-ad40-4a6ce3480400)

**Comment by jikkai** [comment]
> > 1. Please make your angular project support importing CSS.
> > 2. Please add `"skipLibCheck": true,` to your `tsconfig.json`.
> > 
> > ```diff
> > + "skipLibCheck": true,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [univer-demo1.zip](https://github.com/dream-num/univer/files/13765018/univer-demo1.zip)
> > Issue : 我目前用你提供的[univer-demo1.zip](https://github.com/dream-num/univer/files/13765018/univer-demo1.zip)跑ng serve以及在自己的project加了`"skipLibCheck": true`,同样也会抱错 问题如图
> > ![image](https://private-user-images.githubusercontent.com/78796067/292947112-f656f47f-43c9-405c-ad40-4a6ce3480400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTAwMzMsIm5iZiI6MTcwMzY0OTczMywicGF0aCI6Ii83ODc5NjA2Ny8yOTI5NDcxMTItZjY1NmY0N2YtNDNjOS00MDVjLWFkNDAtNGE2Y2UzNDgwNDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA0MDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YmRmOGQwZDk2MWI0NDQzODZiYzg4YWI5YTMxMDc3ZTk0N2I1NzdjZjRjZDdkZmZhZTBiZTI4MjI2OTQ0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7qLJVztBxWu5G43qf_VHl4L2vD_ONfqdmyPq5rk89ZI)

Duplicate #897

**Comment by Miki-AG** [comment]
@Xzhly Your example (using 0.1.0-beta.0) works for me, the only issue I see is that formulas don't work. However, version 0.1.3 does not work at all @jikkai.

**Comment by hexf00** [comment]
This is the latest version of the univer and Angular demo, if you are looking for it  https://github.com/awesome-univer/sheets-angular-demo
