### ISSUE TITLE
[Bug] 删除工作表失败，刷新后再次显示已删除的工作表

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#891]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

删除工作表后刷新

### 预期行为

工作表被删除

### 实际行为

刷新后被删除的工作表再次显示

**Comment by Dushusir** [comment]
已由此PR https://github.com/dream-num/univer/pull/850 修复
