### ISSUE TITLE
[Bug] 双击选中单元格，滑动页面，该单元格被固定在页面上

### ISSUE THREAD

**Issue by 1111eleven** [dream-num/univer#893]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

![1703581213291](https://github.com/dream-num/univer/assets/74369139/5c92b009-89fc-4b0b-bef8-f85710613e58)
双击选中一个单元格，滑动页面，该单元格被固定在页面上！！！

### 预期行为

单元格选中的样式不应该跟随屏幕滑动

### 实际行为

单元格选中的样式跟随屏幕滑动

### 运行环境

Chrome

### 操作系统

Windows

### 构建工具

Vite

**Comment by jikkai** [comment]
This is an intentional design to prevent collaboration from affecting user operations.

We have no plans to change this design at this time.

---

这是有意为之的设计，目的是防止协同时影响用户操作。

我们暂时没有计划更改这个设计。
