### ISSUE TITLE
[Feature] 需要直接调用 monaco editor 的 API

### ISSUE THREAD

**Issue by z1070548197** [dream-num/univer#894]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

我们无法获取、和操作monaco editor 

### 解决方案

需要加一个口子让你获取到这个编辑器实例，这样不管是写入内容还是设置只读就可以直接调用 monaco editor 的 API 了

**Comment by wzhudev** [comment]
Closed by #895
