### ISSUE TITLE
[Bug] Can't resolve '@univerjs/design/lib/index.css' ，not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+core@0.1.0-beta.0/node_modules/@univerjs/core/lib/es'

### ISSUE THREAD

**Issue by harity** [dream-num/univer#897]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

v0.1.0

### 复现步骤

启动就报错

### 预期行为

正常启动

### 实际行为

error - ./src/pages/Report/components/EditeReport/components/Sheet/index.tsx:17:0-40
Module not found: Error: Can't resolve '@univerjs/design/lib/index.css' in '/Users/harity/report/src/pages/Report/components/EditeReport/components/Sheet'
error - ./node_modules/.pnpm/@univerjs+core@0.1.0-beta.0/node_modules/@univerjs/core/lib/es/index.js:37:0-85
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+core@0.1.0-beta.0/node_modules/@univerjs/core/lib/es'
error - ./node_modules/.pnpm/@univerjs+docs@0.1.0-beta.0_t37jaibwnrnc6km4ip5ht22dki/node_modules/@univerjs/docs/lib/es/index.js:38:0-102
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+docs@0.1.0-beta.0_t37jaibwnrnc6km4ip5ht22dki/node_modules/@univerjs/docs/lib/es'
error - ./node_modules/.pnpm/@univerjs+engine-formula@0.1.0-beta.0_iabekwx6g3skjb775bmg3ohv7u/node_modules/@univerjs/engine-formula/lib/es/index.js:32:0-86
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+engine-formula@0.1.0-beta.0_iabekwx6g3skjb775bmg3ohv7u/node_modules/@univerjs/engine-formula/lib/es'
error - ./node_modules/.pnpm/@univerjs+engine-render@0.1.0-beta.0_iabekwx6g3skjb775bmg3ohv7u/node_modules/@univerjs/engine-render/lib/es/index.js:1:3656-3736
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+engine-render@0.1.0-beta.0_iabekwx6g3skjb775bmg3ohv7u/node_modules/@univerjs/engine-render/lib/es'
error - ./node_modules/.pnpm/@univerjs+sheets-formula@0.1.0-beta.0_caugfyytmwfdp4tzfxfn6vmkgu/node_modules/@univerjs/sheets-formula/lib/es/index.js:1:2861-2940
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+sheets-formula@0.1.0-beta.0_caugfyytmwfdp4tzfxfn6vmkgu/node_modules/@univerjs/sheets-formula/lib/es'
error - ./node_modules/.pnpm/@univerjs+sheets-formula@0.1.0-beta.0_caugfyytmwfdp4tzfxfn6vmkgu/node_modules/@univerjs/sheets-formula/lib/es/index.js:1:5956-6041
Module not found: Error: Can't resolve '@wendellhu/redi/react-bindings' in '/Users/harity/report/node_modules/.pnpm/@univerjs+sheets-formula@0.1.0-beta.0_caugfyytmwfdp4tzfxfn6vmkgu/node_modules/@univerjs/sheets-formula/lib/es'
error - ./node_modules/.pnpm/@univerjs+sheets-ui@0.1.0-beta.0_425cebaxhwzzdkhuncg6ymsgfe/node_modules/@univerjs/sheets-ui/lib/es/index.js:1:7626-7705
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+sheets-ui@0.1.0-beta.0_425cebaxhwzzdkhuncg6ymsgfe/node_modules/@univerjs/sheets-ui/lib/es'
error - ./node_modules/.pnpm/@univerjs+sheets-ui@0.1.0-beta.0_425cebaxhwzzdkhuncg6ymsgfe/node_modules/@univerjs/sheets-ui/lib/es/index.js:1:8706-8791
Module not found: Error: Can't resolve '@wendellhu/redi/react-bindings' in '/Users/harity/report/node_modules/.pnpm/@univerjs+sheets-ui@0.1.0-beta.0_425cebaxhwzzdkhuncg6ymsgfe/node_modules/@univerjs/sheets-ui/lib/es'
error - ./node_modules/.pnpm/@univerjs+sheets@0.1.0-beta.0_l4oxzwivd52fgzzv7llofw3kqe/node_modules/@univerjs/sheets/lib/es/index.js:34:0-87
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+sheets@0.1.0-beta.0_l4oxzwivd52fgzzv7llofw3kqe/node_modules/@univerjs/sheets/lib/es'
error - ./node_modules/.pnpm/@univerjs+ui@0.1.0-beta.0_fqqrb4dhl3ky3zzz4a3avidpgm/node_modules/@univerjs/ui/lib/es/index.js:54:0-103
Module not found: Error: Can't resolve '@wendellhu/redi' in '/Users/harity/report/node_modules/.pnpm/@univerjs+ui@0.1.0-beta.0_fqqrb4dhl3ky3zzz4a3avidpgm/node_modules/@univerjs/ui/lib/es'
error - ./node_modules/.pnpm/@univerjs+ui@0.1.0-beta.0_fqqrb4dhl3ky3zzz4a3avidpgm/node_modules/@univerjs/ui/lib/es/index.js:57:0-92
Module not found: Error: Can't resolve '@wendellhu/redi/react-bindings' in '/Users/harity/report/node_modules/.pnpm/@univerjs+ui@0.1.0-beta.0_fqqrb4dhl3ky3zzz4a3avidpgm/node_modules/@univerjs/ui/lib/es'

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

Webpack

**Comment by harity** [comment]
import React, { FC, useState, useEffect } from 'react'
import sheetFactory from '@/config/sheets'
import '@univerjs/design/lib/index.css';
import '@univerjs/ui/lib/index.css';
import '@univerjs/sheets-ui/lib/index.css';
import '@univerjs/sheets-formula/lib/index.css';

import { Univer } from '@univerjs/core';
import { defaultTheme } from '@univerjs/design';
import { UniverDocsPlugin } from '@univerjs/docs';
import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRenderEnginePlugin } from '@univerjs/engine-render';
import { UniverSheetsPlugin } from '@univerjs/sheets';
import { UniverSheetsFormulaPlugin } from '@univerjs/sheets-formula';
import { UniverSheetsUIPlugin } from '@univerjs/sheets-ui';
import { UniverUIPlugin } from '@univerjs/ui';

interface propsType {
  [key: string]: any
}
const Sheet: FC<propsType> = () => {

  useEffect(() => {
    // sheetFactory('editor-sheet')()
    const univer = new Univer({
      theme: defaultTheme,
    });

    // 注册 sheets 所必要的基础插件
    univer.registerPlugin(UniverRenderEnginePlugin);
    univer.registerPlugin(UniverFormulaEnginePlugin, {
      notExecuteFormula: true,
    });

    univer.registerPlugin(UniverUIPlugin, {
      container: 'editor-sheet',
      header: true,
      toolbar: true,
      footer: true,
    });

    univer.registerPlugin(UniverDocsPlugin, {
      hasScroll: false,
    });

    univer.registerPlugin(UniverSheetsPlugin, {
      notExecuteFormula: true,
    });
    univer.registerPlugin(UniverSheetsUIPlugin);
    univer.registerPlugin(UniverSheetsFormulaPlugin);

    // 初始化 sheet
    univer.createUniverSheet({});
  }, [])

  return <div id="editor-sheet"></div>
}
export default Sheet

**Comment by jikkai** [comment]
已在 #870 修复
