### ISSUE TITLE
[Bug] 从对话中点击有冻结行列的表格链接，表格显示异常

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#916]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

路径1、从对话中点击有冻结行列的表格链接，
路径2、设置冻结行列后，复制链接再新开一个页面

### 预期行为

![image](https://github.com/dream-num/univer/assets/154207126/d6fce16e-c04a-43fe-b16e-8e792db67266)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/ad3d656f-7ebd-4b01-9ec0-97b30266cd50)

**Comment by weird94** [comment]
this issue is solved on new staging

**Comment by weird94** [comment]
this issue is solved on new staging
