### ISSUE TITLE
动态切换编辑和查看功能

### ISSUE THREAD

**Issue by chunyangyang** [dream-num/univer#934]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

需要可以动态切换表格编辑和查看

### 解决方案

可以在表格插件有个配置

**Comment by jikkai** [comment]
We expect to implement this feature in the first quarter of next year.

**Comment by jikkai** [comment]
https://univer.ai/guides/sheet/features/permission
