### ISSUE TITLE
[Bug] live share跟随者未跟随

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#938]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

晨会文档有冻结行列，开启live share，共享人滑动查看sheet

### 预期行为

其他人跟随滚动

### 实际行为

共享人滚动时，其他人未跟随

**Comment by yuhongz** [comment]
Request more information @zhaolixin7
