### ISSUE TITLE
[Bug] 列拖拽后undo，内容未回到原来位置

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#940]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、选中列拖拽，然后undo

### 预期行为

1、undo后列和内容都恢复

### 实际行为
[2023_12_29 16_20_14 commands.json](https://github.com/dream-num/univer/files/13791992/2023_12_29.16_20_14.commands.json)
[2023_12_29 16_20_14 video.webm](https://github.com/dream-num/univer/assets/154207126/6c269ada-9806-4c19-9c8e-4de61c4fc914)

**Comment by wzhudev** [comment]
Related to recent changes of removing `ObjectArray`. Please take a look at this.

![image](https://github.com/dream-num/univer/assets/12122021/14fea8d9-0b47-4506-a639-8321dcc9be8a)

**Comment by wzhudev** [comment]
![image](https://github.com/dream-num/univer/assets/12122021/2638285c-a692-4131-a3de-a297ec5f5453)

The formula module insert an empty object during moving rows. To you @Dushusir.

**Comment by wzhudev** [comment]
Separated to https://github.com/dream-num/univer/issues/952
