### ISSUE TITLE
[Bug] The top of the cell text is too close to the edge

### ISSUE THREAD

**Issue by Dushusir** [dream-num/univer#951]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.0

### Steps to reproduce

1. start dev
2. insert new sheet
3. input any content

### Expected behavior

excel
![image](https://github.com/dream-num/univer/assets/26371161/054317db-7ca5-49cc-be35-774532bfb837)

### Actual behavior

univer
![image](https://github.com/dream-num/univer/assets/26371161/91bda79c-59de-4596-8fb1-846ae9ee3872)

**Comment by DR-Univer** [comment]
![image](https://github.com/dream-num/univer/assets/68851825/9e3ae3d1-f2ff-4bdd-9e7f-fc8c5d081204)
padding 给大一些就行，要看看旋转的情况
