### ISSUE TITLE
[Bug] 文字旋转设置文字竖排，竖排格式显示错误

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#967]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、选中单元格，文字旋转设置为竖排文字

### 预期行为

Excel
![image](https://github.com/dream-num/univer/assets/154207126/47e35687-7edb-4d85-9e20-a5bff25e8092)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/3a1e2dbd-0555-4223-86a5-b244a6b47d97)

**Comment by Jocs** [comment]
这个目前我们是对齐 word 的中西文混排-竖排，目前是符合预期的
