### ISSUE TITLE
[Bug] 公式拼写错误时（公式等于文本特殊符号），结果应显示为#NAME?

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#971]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、单元格中输入公式=文本、特殊符号，表情符号
2、公式拼写错误时如=sum
3、等于不支持的函数
4、公式等于不存在的单元格如图
![image](https://github.com/dream-num/univer/assets/154207126/605a293a-d35b-40b2-849d-7e7b69265fbc)

### 预期行为

Excel ![image](https://github.com/dream-num/univer/assets/154207126/2b5c69ed-1829-406a-bb12-b217d3247ce3)

### 实际行为

![image](https://github.com/dream-num/univer/assets/154207126/900b29c1-1879-41bc-af5d-29f25b6b8ef0)

**Comment by zhaolixin7** [comment]
@DR-Univer  公式等与不存在的单元格结果显示0，365结果显示#name
![image](https://github.com/dream-num/univer/assets/154207126/d4dadf63-fe94-4dd6-b312-0e0d85436832)

**Comment by DR-Univer** [comment]
> @DR-Univer 公式等于不存在的单元格结果显示0，365结果显示#name ![image](https://private-user-images.githubusercontent.com/154207126/294835232-d4dadf63-fe94-4dd6-b312-0e0d85436832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQ0NjQsIm5iZiI6MTcwNDcyNDE2NCwicGF0aCI6Ii8xNTQyMDcxMjYvMjk0ODM1MjMyLWQ0ZGFkZjYzLWZlOTQtNGRkNi1iMzEyLTBlMGQ4NTQzNjgzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNDI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzE4MjBmODQyN2FhMjhhZjJiNzkzMDE0ODhmN2QxNTMxOGNjMGQwYTVkOWQ4NTI4NmViNzE0MTMyZWFiNTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tys1k6HJw--SNPMkdDzALfzDQuW_AgmAayuSZZezNvk)

搞定了 重新试试
