### ISSUE TITLE
[Bug] 协同方用户名字会消失

### ISSUE THREAD

**Issue by DR-Univer** [dream-num/univer#974]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

![image](https://github.com/dream-num/univer/assets/68851825/f8e77bfe-9601-4c92-9efc-1a7581fafe91)
协同方编辑后，hover的名字会消失

### 预期行为

hover应该一直在，不应该消失

### 实际行为

消失了

### 运行环境

Chrome

### 操作系统

Windows

### 构建工具

Webpack

**Comment by yuhongz** [comment]
编辑方编辑成功后发送当前编辑坐标缺少 subUnitId，导致协同光标丢失，已补上。该 bug 已由开发自测通过
