### ISSUE TITLE
[Bug] 公式计算引用错误时,excel显示#value

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#982]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

case1、1. 公式等于=SUM("A1:A5"）
case2、公式等于=单元格内容“12”/1，且12中间有空格
case3、公式等于=12（换行）/1

### 预期行为

Excel ![image](https://github.com/dream-num/univer/assets/154207126/d2390fc5-f590-4303-8462-1b3063a772cb)

### 实际行为

[2024_1_3 15_54_10 commands.json](https://github.com/dream-num/univer/files/13816687/2024_1_3.15_54_10.commands.json)
[2024_1_3 15_54_10 video.webm](https://github.com/dream-num/univer/assets/154207126/fcbe623a-68ac-4f87-a7a5-efbb5f6bfbef)

**Comment by DR-Univer** [comment]
![image](https://github.com/dream-num/univer/assets/68851825/74675f1b-2678-46c9-852b-da9b37b05baa)
@zhaolixin7 这几个case，office365的报错不都是#value! 了。 咱们要不就follow最新版。

**Comment by zhaolixin7** [comment]
@DR-Univer   公式等于=单元格内容“12”/1，且12中间有换行，结果等于45293（365等于 #value）
![image](https://github.com/dream-num/univer/assets/154207126/c46b4dae-3763-492b-aff4-51e3e26219fe)
