### ISSUE TITLE
[Bug] 选中尾行合并单元格插入行，插入行失败

### ISSUE THREAD

**Issue by zhaolixin7** [dream-num/univer#995]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

前提：合并单元格是多行，多列（如图）
case1、选中A插入行，插入方式选择下移
case2、选中B单元格，插入方式选择右移
case3、选中A插入行，插入方式选择左侧或上方
![image](https://github.com/dream-num/univer/assets/154207126/40ead35d-9071-494c-b84f-b8ef692e7c06)

### 预期行为

case1、2可以插入行，case3格式和单元格一致

### 实际行为

合并单元格被取消，单元格内容消失

[2024_1_4 18_00_59 video.webm](https://github.com/dream-num/univer/assets/154207126/9eb40739-5e1b-416d-af20-d46b4afd3ccc)
[Uploading 2024_1_4 18_00_59 commands.json…]()

**Comment by Gggpound** [comment]
插入行【下移】这个操作，没有扩展行数...我先看看

**Comment by Gggpound** [comment]
<img width="934" alt="_7138e768-21d8-4948-b629-670eb1fa67be" src="https://github.com/dream-num/univer/assets/141617023/964979af-5a59-4261-8b45-d06ca9b89b5f">
这段注释的意图对应的需求点是什么？

**Comment by Dushusir** [comment]
> 中A插入行，插入方式选择下移
> case2、选中B单元格，插入方式选择右移
> case3、选中A插入行，插入方式选择左侧或上方

参照google sheets，最后一行空白的话，不会insert range
